### ISSUE TITLE
kleurcode als er 3 maanden geen verslag is toegevoegd bij maatschappelijkwerk

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1000]
Als er 3 maanden geen verslag is toegevoegd cliënt groen kleuren in overzicht/lijsten

**Comment by dvleeuwen** [comment]
+ in scherm klanten een vinkje toevoegen om alleen de groen gekleurde klanten te tonen

**Comment by jtborger** [comment]
2.2.45

**Comment by dvleeuwen** [comment]
Ha Jan,
komt deze in volgende versie of is ie al live?
Staat nu versie 2.2.45 (huidige), maar ik mis het vinkje nog?

dank!
Daan

---------- Forwarded message ---------
Van: JT Borger <notifications@github.com>
Date: ma 29 jun. 2020 om 10:31
Subject: Re: [deregenboog/ecd] kleurcode als er 3 maanden geen verslag is
toegevoegd bij maatschappelijkwerk (#1000)
To: deregenboog/ecd <ecd@noreply.github.com>
Cc: dvleeuwen <ecd@deregenboog.org>, Author <author@noreply.github.com>


Closed #1000 <https://github.com/deregenboog/ecd/issues/1000>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deregenboog/ecd/issues/1000#event-3491866906>, or
unsubscribe

**Comment by jtborger** [comment]
oh het vinkje... overheen gelezen :)

**Comment by dvleeuwen** [comment]
Omdat er nu teveel gekleurde dossiers zijn lijkt het doel voorbij te schieten.

Op verzoek van Michael termijn aanpassen naar 1 jaar geen verslag (ipv 3 mnd)

**Comment by dvleeuwen** [comment]
afgesloten zie #1235
