### ISSUE TITLE
nieuwe rapportage maatschappelijk werk

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1002]
nieuwe rapportage mw:
gemiddelde doorloop

=tijd tussen intake en afsluitdatum 
(als er geen afsluitdatum is (dus nog open) dan niet meenemen)

uitgesplitst per locatie en totaal

**Comment by dvleeuwen** [comment]
update: ja echt wenselijk

**Comment by jtborger** [comment]
Volgens mij is deze opgelost in #1153
