### ISSUE TITLE
verwijderen werkt niet?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1004]
Hoi Daan/Jan,

Van Emma van Homeservice hoorde ik dat het niet lukt een dubbel aangemaakte klant te verwijderen in de rubriek HS. Ik heb dit even getest en hier zit inderdaad een bug, na het klikken op verwijderen verschijnt het record gewoon weer in de lijst.
NB Het gaat hier dus om klanten = derden, dit staat los van de algemene klantenlijst.
Graag toevoegen aan de werkzaamheden.

Groet,

Josje

Hoi Daan,

Zie https://ecd.deregenboog.org/hs/klanten/?klant_filter%5Bfilter%5D=&klant_filter%5Bid%5D=&klant_filter%5Bnaam%5D=panka&klant_filter%5Bhulpverlener%5D=&klant_filter%5Badres%5D=&klant_filter%5Bstadsdeel%5D=&klant_filter%5BafwijkendFactuuradres%5D=&klant_filter%5Bstatus%5D=

Het 2e dossier met HS-klantnr. 2616 moet verwijderd worden. Ik heb ook een testdossiertje met naam 'test' aangemaakt.

Groet,

Josje

deze ook:

https://ecd.deregenboog.org/hs/klanten/?klant_filter%5Bfilter%5D=&klant_filter%5Bid%5D=&klant_filter%5Bnaam%5D=sham&klant_filter%5Bhulpverlener%5D=&klant_filter%5Badres%5D=&klant_filter%5Bstadsdeel%5D=&klant_filter%5BafwijkendFactuuradres%5D=&klant_filter%5Bstatus%5D=

**Comment by jtborger** [comment]
OK dit moet worden onderzocht, in principe konden klanten nooit verwijderd worden denk ik, maar door wat aanpassingen in het verleden lijkt het alsof het nu wel kan.
echter is dat dus maar half geïmplementeerd. dat zorgt voor de verwarring.
ik heb het nu zo gemaakt dat standaard in de klantenlijst alleen actieve klanten staan. dan verdwijnen ze ook uit de lijst.

**Comment by jtborger** [comment]
2.2.40

**Comment by dvleeuwen** [comment]
Josje:

Hoi Daan,

Er gebeurt nu iets raars... Ik kon geen testdossier meer vinden, dus heb een nieuwe klant aangemaakt (TEST). Deze kan ik na opslaan niet meer terugvinden in de klantenlijst. 
Bij nogmaals proberen blijkt dat je een nieuw aangemaakt klantdossier wel rechtstreeks kunt verwijderen, vanuit het dossierscherm. Maar bewaren lukt dus niet...
LIjkt er dus op alsof dit nog niet helemaal gefixt is.

Groet,

Josje

**Comment by dvleeuwen** [comment]
blijkt met actief/nietactief te maken, sluit m weer
