### ISSUE TITLE
vinkje toestemming woningbouw / eigen woning

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1005]
We kunnen de kamer pas aanbieden aan een huurder als er toestemming is van een woningcorporatie (of als het een eigen huis is). Dit willen we graag in de lijst kunnen zien. 

Bij huuraanbiedingen vinkbox maken "toestemming woningbouw / eigen woning"
Als aangevinkt: deze groen kleuren in de  lijst huuraanbiedingen

**Comment by jtborger** [comment]
er zijn al twee velden: toestemming aangevraagd (datum) en toestemming toegekend (datum)
Ik neem aan dat deze laatste eigenlijk het vinkje is, toch?
Ik kan maken dat wanneer deze is ingevuld, hij groen wordt. dekt dat de lading?

**Comment by dvleeuwen** [comment]
daan vraagt na bij OdP of bovenstaande idd voldoet

**Comment by dvleeuwen** [comment]
-verzoek tot vinkboxje bij eigen woning/toestemming 
Jan merkt terecht op dat er bij huuraanbiedingen al de velden bestaan 'toestemming aangevraagd" en "toestemming toegekend" 
Zijn voorstel is om zodra er bij toestemming toegekend een datum ingevuld is, deze huuraanbiedingen in de lijst groen te kleuren. Dit betekent voor jullie dus dat zodra toestemming binnen is (of er sprake is van een eigen woning!) dit veld ingevuld moet worden. We gaan dan dus niet met een extra vinkboxje werken. Klinkt dit werkbaar voor jullie?

**Comment by dvleeuwen** [comment]
Marit:
lijkt me goed!

**Comment by jtborger** [comment]
2.2.41
