### ISSUE TITLE
kolom toevoegen aan download bij huurders en verhuuders

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1007]
Hoi Daan/Jan,

Graag zou ik aan de downloads Huurders en Verhuurders OdP een kolom Gekoppeld (ja/nee) toegevoegd willen zien. Dit om in 1 x een mailing aan gekoppelde huurders/verhuurders te kunnen uitdraaien.

Groet,

Josje

**Comment by jtborger** [comment]
2.2.47

**Comment by dvleeuwen** [comment]
Josje geeft aan dat deze nog niet goed werkt:

Hoi Daan/Jan,

Onlangs is op mijn verzoek een kolom 'gekoppeld' toegevoegd aan de download Huurders van OdP. Helaas blijkt die kolom vaak niet te kloppen: in veel gevallen waar 'ja' is ingevuld is er toch geen open koppeling. Waar 'nee' staat klopt de kolom wel. 
Ik voeg een bestand bij waarin dit uitgebreid is getest, zie voor toelichting de tab 'info'. Dit mag weer op de lijst dus!

Groet,

Josje

**Comment by dvleeuwen** [comment]
Wellicht handigst als Jan weer een keer live afstemt met Josje, zie mail voor verdere toelichting Josje

**Comment by jtborger** [comment]
Dit gaat mee in de volgende release 2.2.50
