### ISSUE TITLE
rol stagiaires inloop aanpassen 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1008]
willemijn:
bij een afgelopen intervisie kwam er naar voren dat stagiair(e)s wanneer ze de registratie doen de opmerkingen en schorsingen niet kunnen inzien. 
Ze kunnen wel zien dát er een opmerking of schorsing is, maar niet wat deze inhoudt of wat de reden van de schorsing is.
Vooral bij de opmerkingen lijkt het me zeer onhandig dat stagiair(e)s deze niet aan kunnen klikken.
Moeten we dit niet aanpassen?

**Comment by jtborger** [comment]
daar moet dan eerst een beslissing over worden genomen. ik hoor wel wat ik ermee moet.

**Comment by dvleeuwen** [comment]
Die toestemming is er inmiddels, dus graag aanpassen.

**Comment by jtborger** [comment]
2.2.41
Overigens volgens mij konden ze gewoon op het klantdossier kijken en daar alles zien voor zover ik dat heb kunnen nagaan, maar dat terzijde. Nu kan het ook door het aanklikken van de opmerking of schorsing in het registratie scherm
