### ISSUE TITLE
doorklikken van verhuurder naar huuraanbod niet meer mogelijk?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1009]
Josje:

Hoi Daan/Jan,

Nog een OdP-punt: het lukt (sinds kort waarschijnlijk) niet meer om vanuit het verhuurdersdossier een huuraanbieding te openen. Het loep-icoontje is verdwenen. 

----

zie bijvoorbeeld hier: 
https://ecd.deregenboog.org/odp/verhuurders/331/view?redirect=/odp/verhuurders/

er is een huuraanbieding, maar daar kun je via dit scherm dus niet (meer) terecht komen

**Comment by dvleeuwen** [comment]
Hoi Daan/Jan,

Ik kom er net achter dat er vanuit het OdP verhuurdersdossier ook geen huuraanbieding en dus geen koppeling kan worden aangemaakt. Dit hangt wellicht samen met het niet kunnen openen van de koppeling(?), zie recent verzoek.
Kan dit met prioriteit worden hersteld? 

Groet,

**Comment by jtborger** [comment]
2.2.41
