### ISSUE TITLE
Filters toevoegen aan pagina /oek_trainingen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#101]
Kolommen:
 - id (\AppBundle\Form\KlantFilterType)
 - naam (\AppBundle\Form\KlantFilterType)
 - groep (dropdown)
 - start (\AppBundle\Form\AppDateType)
 - eind (\AppBundle\Form\AppDateType)

**Comment by Evertt** [comment]
Gedaan, behalve:

Start- en eind-datum zijn onhandige filters denk ik als je ze strict AppDateType laat zijn, want dan werken ze alleen als je een exacte datum invult. Zouden we ze een andere type kunnen maken zodat de gebruiker alleen een jaartal of alleen een jaar+maand op hoeft te geven en dan alles krijgt wat daar binnen valt?

**Comment by barthuttinga** [comment]
@Evertt Ja klopt, het moet waarschijnlijk een datumbereik worden. Dit geldt voor meer plekken. Wil ik nog even over nadenken en/of overleggen en dan op alle plekken in een keer aanpassen.

**Comment by barthuttinga** [comment]
@Evertt Dat datumbereik waar ik het hierboven over heb zit er inmiddels in. Ik sluit dit ticket.
