### ISSUE TITLE
foutmelding bij doorklikken

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1012]
Josje:
Hoi Daan/Jan,

Het probleem van de foutmelding bij doorklikken van een OdP-dossier naar de klantenlijst blijkt toch nog niet helemaal verholpen te zijn. Het werkt nu wel vanuit het huurdersdossier (zowel bij het OdP-team als bij mij) maar nog niet vanuit het verhuurdersdossier.
Dit graag dus nog aanpassen. Is hopelijk niet ingewikkeld aangezien de oplossing bekend zal zijn. 

Groet,

JOsje

Hoi Daan,

Zie screenshot, dit is als je in het verhuurdersdossier hebt geklikt op Wijzigen. Als je via dit invulscherm naar het basisdossier wilt om daar iets aan te passen klik je op 'hier', vervolgens verschijnt de foutmelding.

Groet,

Josje

https://ecd.deregenboog.org/odp/verhuurders/331/edit?redirect=/odp/verhuurders/

**Comment by jtborger** [comment]
Ik kan het niet 100% testen nu maar ik denk dat het met de volgende release verholpen is.
2.2.41
