### ISSUE TITLE
foutmelding bij toevoegen nieuwe vw'er inloophuizen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1013]
als je hier op '+ nieuwe vrijwilliger' klikt kom je op foutmelding terecht

https://ecd.deregenboog.org/inloop/vrijwilligers/add?vrijwilliger_filter%5Bid%5D=&vrijwilliger_filter%5Bnaam%5D=brian&vrijwilliger_filter%5Bbsn%5D=&vrijwilliger_filter%5Bgeboortedatum%5D=&vrijwilliger_filter%5Bfilter%5D=

**Comment by jtborger** [comment]
2.2.41
