### ISSUE TITLE
beter klikbaar maken bij huurverzoek/huuraanbod 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1015]
-het viel op dat in het overzicht van huuraanbiedingen/verzoeken je precies op het nummer moet klikken ipv op naam of elders in de rij. In de rest van ECD is dit niet zo, en lijkt mij  onhandig... Is dit een bewuste keuze geweest? If not: passen we het aan, zodat je gewoon op de naam kunt klikken om bij het huuraanbod/huurverzoek te komen.  

Marit:
pas graag aan!

**Comment by jtborger** [comment]
2.2.47
