### ISSUE TITLE
aanmaken nieuwe vrijwilliger inlopen levert foutmelding op

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1017]
Zodra je een bestaande vrijwilliger aanklikt, of nieuwe wil toevoegen, kom je op foutmeldingspagina 

https://ecd.deregenboog.org/inloop/vrijwilligers/add?vrijwilliger_filter%5Bid%5D=&vrijwilliger_filter%5Bnaam%5D=klaas&vrijwilliger_filter%5Bbsn%5D=&vrijwilliger_filter%5Bgeboortedatum%5D=&vrijwilliger_filter%5Bfilter%5D=

**Comment by jtborger** [comment]
duplicate of #1013
