### ISSUE TITLE
foutmelding na invoeren reeks

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1018]
Ha Daan, 

Ik probeer net een reeks in te voeren in ecd maar krijg telkens een foutmelding. 

groepsactiviteiten -> activiteiten ->Reeks activiteiten toevoegen

Dan vul ik bv onderstaand in (hopelijk kun je dit lezen). En dan krijg ik vervolgens een foutmelding en dat ik contact moet opnemen met jou. Dus bij deze. Doe ik iets niet goed? Hoor graag van je! 
Mileen

https://ecd.deregenboog.org/ga/activiteitenreeks/add?redirect=/ga/activiteiten/

**Comment by jtborger** [comment]
hoi daan
ik weet niet precies wat zij invoerde, maar bij mij werkte het helemaal niet, en toen ik er naar keek leek het wel alsof het nooit echt goed heeft gewerkt... 
ik heb het voor een groot deel herschreven en volgens mij doet het nu wat het moet doen. althans, dat hoop ik maar ;) anders hoor ik het wel.
2.2.41

**Comment by dvleeuwen** [comment]
Ha Jan,
zou me niets verbazen als het idd nooit echt gewerkt heeft. Volgens mij
heeft deze afdeling tot voor kort ECD minimaal gebruikt/benut. Dus lopen ze
nu pas tegen dit soort dingen aan...


Op vr 20 mrt. 2020 om 12:52 schreef JT Borger <notifications@github.com>:
