### ISSUE TITLE
Foutmelding 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1022]
Josje:

Hoi Daan/Jan,

Bij invoer van inloopvw-gegevens stuitte ik op twee foutmeldingen:

- na het wijzigen van de aanmeldnotitie > dit lukt soms wel, soms niet, ik kom er niet achter waar dat aan ligt. Zie dossier XXX, hier lukt het niet de tekst 'Locatie?' te verwijderen in het veld notitie. Voor zover ik zie lukt wijzigen van andere gegevens (medewerker en locatie) wel.
https://ecd.deregenboog.org/inloop/vrijwilligers/128/view?redirect=/inloop/vrijwilligers/

**Comment by jtborger** [comment]
Als ik het goed begrijp lukte het niet om de aanmeld notitie 'leeg' te halen toch? Dat kon ik reproduceren en heb ik opgelost in 2.2.45
