### ISSUE TITLE
Foutmelding

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1023]
Hoi Daan/Jan,

Bij invoer van inloopvw-gegevens stuitte ik op twee foutmeldingen:

- na het opslaan van een training - overig: zie dossier XXX. De training die links onder Opmerking staat vermeld wilde ik invoeren onder Trainingen, ook hier een foutmelding. Zie  https://ecd.deregenboog.org/inloop/vrijwilligers/54/view?redirect=/inloop/vrijwilligers/  

DvL Bij training gekozen voor overige en dan naam ingetikt ---> foutmelding

**Comment by jtborger** [comment]
Gaat mee in 2.2.45
