### ISSUE TITLE
locatie niet weergegeven in overzicht

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1024]
Josje:

Hoi Daan/Jan,

Nog een ding mbt de inloopvrijwilligers: de locatie die is ingevoerd in het dossier verschijnt niet altijd op de schermlijst. Dit zou te maken kunnen hebben met het wijzigen van de tab Aanmelding. Voorbeeld: dossier XXX
https://ecd.deregenboog.org/inloop/vrijwilligers/123/view?redirect=/inloop/vrijwilligers/  

en

https://ecd.deregenboog.org/inloop/vrijwilligers/?vrijwilliger_filter%5Bfilter%5D=&vrijwilliger_filter%5Bvrijwilliger%5D%5Bid%5D=&vrijwilliger_filter%5Bvrijwilliger%5D%5Bnaam%5D=groot&vrijwilliger_filter%5Baanmelddatum%5D%5Bstart%5D=&vrijwilliger_filter%5Baanmelddatum%5D%5Bend%5D=&vrijwilliger_filter%5Bafsluitdatum%5D%5Bstart%5D=&vrijwilliger_filter%5Bafsluitdatum%5D%5Bend%5D=&vrijwilliger_filter%5Blocatie%5D=&vrijwilliger_filter%5Bvrijwilliger%5D%5Bstadsdeel%5D=

**Comment by dvleeuwen** [comment]
Aanvullend:

Hoi Daan/Jan,

Nog een verzoek mbt de inloopvrijwiligers: kan de locatie uit het tabblad Aanmelding ook worden toegevoegd aan de download? (Zie ook mijn eerdere mail van 23/4, de locatie verschijnt op dit moment niet bij alle vw op de schermlijst).

Dank & groet,

Josje

**Comment by jtborger** [comment]
gaat mee in 2.2.45
