### ISSUE TITLE
einddatum Amoc moet geen verplicht veld zijn bij andere intakelocaties 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1027]
hier komen sinds eind april verschillende mailtjes over, intakers andere locaties kunnen intake niet opslaan doordat eindatum Amoc nu een verplicht veld lijkt te zijn

**Comment by dvleeuwen** [comment]
mail aan Aukje, Willemijn, Janneke:

Ola,zojuist met Jan gesproken: hij kan terugvinden waar dit (=eindatum amoc is verplicht veld ook voor andere locaties) probleem vandaan komt, en gaat het zsm proberen op te lossen. Wat hierbij wel frappant is: het lijkt te maken te hebben met een aanpassing eind februari, maar ik kreeg hier eind april van jullie pas bericht over. Jullie enig idee hoe dit kan, in de tussentijd zijn er toch ook vast wel intakes gedaan? Eigenaardig dat dit toen niet voor problemen gezorgd heeft. Anyways: ik laat het weten zodra Jan het aangepast heeft!
groetDaan

**Comment by jtborger** [comment]
Update: opgelost in 2.2.43
In overleg met Janneke het volgende besloten:
alle 'toegang tot/vanaf' velden zijn niet verplicht.
Toegang tot AMOC moet worden veranderd in toegang tot intakelocatie. Dit wordt soms ook op andere locaties gebruikt dan AMOC.
Ook dan is het niet verplicht.
Maak ik nieuw issue voor aan.
