### ISSUE TITLE
kolom Locatie toevoegen in download inloopvrijwilligers

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1029]
Hoi Daan/Jan,

Nog een verzoek mbt de inloopvrijwiligers: kan de locatie uit het tabblad Aanmelding ook worden toegevoegd aan de download? (Zie ook mijn eerdere mail van 23/4, de locatie verschijnt op dit moment niet bij alle vw op de schermlijst).

Dank & groet,

Josje

**Comment by jtborger** [comment]
opgelost, gaat mee in de volgende update. 
2.2.63 ofzo.
