### ISSUE TITLE
verwijderen "niet rechthebbend uit-NL" bij verblijfstatus/intake

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1030]
De term "niet rechthebbend uit NL" bij intake/verblijfstatus blijkt niet (meer?) gebruikt te worden, en zorgt nu enkel voor verwarring. 
Graag verwijderen. 
(ik kon dit zelf nergens binnen beheer vinden?)

**Comment by jtborger** [comment]
Hij is 'gedeactiveerd'. Kan inderdaad alleen rechtstreeks in de database. Oude intakes die op die status staan zijn gewoon zo zichtbaar maar verschijnt niet meer als nieuwe optie.
