### ISSUE TITLE
IZdossier verdwenen na ontdubbeling

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1033]
Josje heeft in december een ontdubbeling gedaan van dossiers, en kreeg hierbij een foutmelding (zie aanvullende mail).
Nu blijkt dat het IZdossier van mw P daarbij verdwenen is gaat. We hopen dat de intake/verslagen weer boven water gehaald kunnen worden

https://ecd.deregenboog.org/klanten/?klant_filter%5Bfilter%5D=&klant_filter%5Bid%5D=&klant_filter%5Bnaam%5D=prinz&klant_filter%5Bgeslacht%5D=&klant_filter%5Bgeboortedatum%5D=&klant_filter%5Bmedewerker%5D=&klant_filter%5Bstadsdeel%5D=&klant_filter%5Bpostcodegebied%5D=

**Comment by jtborger** [comment]
Kan niet meer terughalen. Wacht op mogelijkheid tot backup via hosting partij.

**Comment by jtborger** [comment]
Helaas hebben ze geen backup (meer). :(
Ben bang dat dit verloren is gegaan...
