### ISSUE TITLE
Naam mederwerker klantdossier tonen in overzicht huurder ODP

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1034]
In het huurdersoverzicht van onder de panne (https://ecd.deregenboog.org/odp/huurders/)
svp een extra kolom met daarin de naam "medewerker" van de huurder. 
Dus de naam die bij het algemene klantdossier als medewerker genoteerd staat

**Comment by jtborger** [comment]
gaat mee in 2.2.45

**Comment by jtborger** [comment]
Met Jullie besproken: gaat zowel om de caseload / coordinator vanuit Odp als Ambulant ondersteuner.

**Comment by jtborger** [comment]
2.2.47

**Comment by dvleeuwen** [comment]
Bij invoer van sommige medewerkers levert dit een foutmelding op. (vb navragen bij Josje)

**Comment by dvleeuwen** [comment]
antwoord Josje:
als je deze namen invoert als medewerker krijg je foutmelding:
Alyssia Theijs, Tessa Zaaijer, Bep Brunt en Maria Hashem.

**Comment by jtborger** [comment]
Ik kan het niet reproduceren:

de bovengenoemde namen kan ik niet invoeren als medewerker, enkel als ambulant ondersteuner. wanneer ik dat doe krijg ik keurig een resultaat te zien.

Of ik snap de vraag niet, of ik kijk niet goed...of ik zie iets over het hoofd?

**Comment by jtborger** [comment]
Gaat erom bij huurder: het wijzigingen van ambulant ondersteuner levert foutmelding op voor Josje. iets met rechten?

**Comment by dvleeuwen** [comment]
Ik leg het voor aan Josje

Op di 25 aug. 2020 om 10:44 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Is opgelost. Er zat een systeembeperking op het ambulant ondersteuner veld die stelde dat deze uniek (eenmaal) moest zijn in de hele tabel...
Ik weet niet waarom dat zo is maar ik heb het gecorrigeerd en het werkt nu zoals het zou moeten.
(direct live)
