### ISSUE TITLE
geen nieuwe klussen meer voor mensen met betalingsachterstand

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1042]
Iris:
- Klanten die een betalingsachterstand hebben, en waar we dus geen nieuwe klus willen/kunnen doen, daar zetten we nu een uitroepteken achter de naam, en in de omschrijving klant "geen nieuwe klus". Jan opperde dat dat anders kan: heel graag! Het liefst dat er dus echt geen nieuwe klus kan worden aangemaakt.

**Comment by jtborger** [comment]
Adhv status = Geen nieuwe klus

**Comment by jtborger** [comment]
Veld toegevoegd 'status'. Deze heeft twee mogelijkheden op dit moment: Nieuwe klussen mogelijk en 'Geen nieuwe klussen'

Als deze laatste, dan kan er geen klus worden toegevoegd.
Ook in het zoekfilter deze optie toegevoegd bij status (actief/nietactief/geen nieuwe klussen)
NB
iemand kan actief zijn en toch geen nieuwe klussen krijgen; dit staat los van elkaar. maar voor het overzichtelijk houden van het scherm heb ik voor het zoeken er een zoekoptievan gemaakt.

2.3.7
