### ISSUE TITLE
huuraanbod toevoegen levert foutmelding op

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1048]
Josje: 
Hoi Daan/Jan,

Het aanmaken van een nieuw huuraanbod bij een OdP verhuurder lukt niet. Dit probleem is al eens eerder opgetreden en toen verholpen, nu krijg ik opnieuw een foutmelding, Ida idem. 
Als voorbeeld zie  https://ecd.deregenboog.org/odp/verhuurders/344/view?redirect=/odp/verhuurders/ 
 
Aangezien het een bug is graag voorrang.

Groet,

Josje

---

Daan:
Ha Josje,
ik probeer het oude ticket hiervan naar boven te halen. Maar kan m nergens vinden. Ben jij zeker dat dit eerder gebeurd (en verholpen) is? En zo ja: kun jij daar correspondentie over terug vinden?

dank!
Daan

**Comment by dvleeuwen** [comment]
= oude issue #1009

**Comment by jtborger** [comment]
Had niks met elkaar te maken maar het zag er hetzelfde uit. dit is per ongeluk geïntroduceerd bij alle toevoegingen en aanpassingen van vorige week.
2.2.48
