### ISSUE TITLE
1malige zoekopdracht veel gekoppelde deelnemers 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1050]
Je mag deze bewaren voor na je vakantie. Ik heb m wel in Github gezet met label hoge prio, enkel zodat we m na je vakantie niet uit het oog verliezen, ok?

Gezocht:Namen van deelnemers die nu gekoppeld zijn, of een open hulpvraag hebben:met 5 of meer koppelingen achter hun naam binnen 1 project.

**Comment by jtborger** [comment]
Hoi Daan, zie mail.
Query: SELECT izk.id, izk.iz_deelnemer_id, k.achternaam, COUNT(izk.iz_deelnemer_id) FROM `iz_koppelingen` AS izk INNER JOIN iz_deelnemers AS izd ON izd.id = izk.iz_deelnemer_id INNER JOIN klanten AS k ON k.id = izd.foreign_key WHERE izk.discr = 'hulpvraag' AND izk.koppeling_einddatum IS NULL GROUP BY iz_deelnemer_id, project_id AND izd.model = 'Klant' HAVING COUNT(iz_deelnemer_id) > 4

**Comment by dvleeuwen** [comment]
deelnemers met een actieve of open koppeling die in het verleden wellicht ook al eerder gekoppeld waren, binnen dezelfde hulpvraag (of hulpvraagsoort?)
waarbij de koppelingen in het verleden er dus meer dan 4 zijn.

**Comment by jtborger** [comment]
SELECT DISTINCT iz_koppelingen.iz_deelnemer_id, k.voornaam, k.achternaam, izhvs.naam AS hulpvraagsoort, COUNT(izk2.id) AS aantalKoppelingen FROM `iz_koppelingen` INNER JOIN iz_koppelingen AS izk2 ON izk2.iz_deelnemer_id = iz_koppelingen.iz_deelnemer_id AND izk2.hulpvraagsoort_id = iz_koppelingen.hulpvraagsoort_id
INNER JOIN iz_deelnemers AS izd ON izd.id = iz_koppelingen.iz_deelnemer_id 
INNER JOIN klanten AS k ON k.id = izd.foreign_key
INNER JOIN iz_hulpvraagsoorten AS izhvs ON izhvs.id = iz_koppelingen.hulpvraagsoort_id
WHERE iz_koppelingen.koppeling_einddatum IS NULL AND iz_koppelingen.discr = 'hulpvraag'
GROUP BY iz_koppelingen.iz_deelnemer_id HAVING COUNT(izk2.id) > 4  
ORDER BY `izk2`.`hulpvraagsoort_id`  DESC

**Comment by jtborger** [comment]
SELECT izk1.iz_deelnemer_id, k.voornaam, k.achternaam, izp.naam, b.numKoppelingen FROM iz_koppelingen AS izk1 
INNER JOIN  (
  SELECT DISTINCT izk2.iz_deelnemer_id, izk2.project_id, COUNT(izk2.id) AS numKoppelingen FROM iz_koppelingen AS izk2 
    WHERE (izk2.einddatum IS NOT NULL OR izk2.koppeling_einddatum IS NOT NULL)
   -- AND izk2.iz_deelnemer_id = 8299
   GROUP BY izk2.iz_deelnemer_id, izk2.project_id
	HAVING COUNT(izk2.id) > 4 ) AS b
ON b.iz_deelnemer_id = izk1.iz_deelnemer_id AND b.project_id = izk1.project_id
INNER JOIN iz_deelnemers AS izd ON izd.id = izk1.iz_deelnemer_id
INNER JOIN klanten AS k ON k.id = izd.foreign_key
INNER JOIN iz_projecten AS izp ON izp.id = izk1.project_id
WHERE 
(izk1.koppeling_einddatum IS NULL AND izk1.einddatum IS NULL)
