### ISSUE TITLE
vrijwilligers onvindbaar in algemene lijst

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1051]
Hoi Daan/Jan,

Het valt de laatste tijd op dat niet alle vw vindbaar zijn in de algemene vw-lijst. Ik heb daarom een steekproefje gedaan om te kijken of daar een patroon in zit, maar kan dat niet ontdekken. Zie bijlage. 
Die vindbaarheid is van belang om (oud)vrijwilligers makkelijk terug te kunnen vinden, o.a. nav afmeldingen voor post, overlijdensberichten etc., we moeten dan controleren of/wanneer het dossier afgesloten is en dat evt. alsnog doen als dit ten onrechte niet is gebeurd.  In onze nieuwe relatiedatabase Xapti (opvolger van Charibase), waar de vrijwilligers ook worden ingevoerd, zijn de projectkenmerken komen te vervallen, waardoor het zoeken in ECD nog vaker via de algemene vw-lijst zal gaan. 
Hopelijk is te achterhalen waar de fout zit. Er is al eerder een verzoek ingediend voor een dienstenblokje in het vw-dossier. Als dit gerealiseerd is worden meteen de eventuele verschillende afdelngsdossiers zichtbaar, dus dan zijn de vw helemaal goed vindbaar.
Alleen verwijderde dossiers hoeven niet meer zichtbaar te zijn.

Dit punt mag dus aan de lijst worden toegevoegd.

Groet,

Josje

---
Aantal vwers wel te vinden binnen tab, maar niet in algemene lijst.
Bijvoorbeeld: 
dossiernummer 15198 (wel vindbaar binnen IZ, niet bij algemene lijst) en 15280 (wel vindbaar bij GA (niet actief!), niet in algemene lijst)
En zo zijn er meerdere (zie bijlage mail Josje voor meer voorbeelden)

**Comment by jtborger** [comment]
Hoi Josje,

Het lijkt erop dat het om VWers gaat die niet in Amsterdam wonen. Wanneer dat zo is, gaat de mapping van postcode naar werkgebied naar leeg. En nu stond er op de algemene VW tab een criterium dat die alleen VWers toont waarbij het werkgebied matcht (en dus niet leeg mag zijn). Dat heb ik aangepast. Bedankt voor het vinden !

**Comment by jtborger** [comment]
gaat mee in 2.2.50
