### ISSUE TITLE
Time out op andere manier vormgeven dan als "project"

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1052]
Na de vakantie overleggen Daan-Jan

**Comment by dvleeuwen** [comment]
"time out" verplaatsen van project naar hulpvraagsoort

inclusief de eigenschappen die het nu heeft (nog even overleg/afstemmen?)

deadline 1 okt

**Comment by dvleeuwen** [comment]
Jan zoekt uit of TimeOut nu nog bijzonder eigenschappen heeft,
zo niet past Daan aan

**Comment by jtborger** [comment]
Wanneer bij een project het vinkje 'heeft koppelingen' niet aangevinkt is, wordt aanbod of vraag binnen dit project niet meegenomen.
Dus een VW-er die in project timeout zit die krijgt wel alle mogelijke matches te zien maar hij verschijnt zelf niet als mogelijke match bij een deelnemer.
en vv.
Dus dat is wat er dan met hulpvraagsoorten zou moeten gebeuren.
Mits en tenzij we bv. toch kiezen om het obv de status aparte van Project te doen
(wat was het idee ook alweer achter het verplaatsen ervan naar hulpvraag/aanbod soort?

**Comment by dvleeuwen** [comment]
Ha Jan,
de matches worden op criteria van hulpvraag/aanbod gemaakt. Dus als Timeout
van Project -> Hulpvraag/aanbod verhuist, zul je in het koppelscherm enkel
TimeOuters aan Timeouters voorgeschoteld krijgen vermoed ik?
Dat is een beetje vreemd, maar geen probleem. In de praktijk zal niemand
een Timeouter actief proberen te koppelen, dus verwacht niet dat we hier
tegenaan lopen. En doordat naar hulpvraag/aanbod gezocht worden ze ook niet
via de andere kant naar boven komen. (wat dus bij projecten wel het geval
zou zijn, als we daar geen aanpassing ingebouwd hadden).

Het idee vd opschoning is vooral het rijtje projecten kloppend te krijgen:
gelijk aan de financiering.
Daarnaast voelt het passender dat Timeout een hulpaanbod/vraag is, ipv een
project (als in: heeft nu tijdelijk geen hulpvraag/aanbod)

Lijkt me dat ik het nu dus gewoon om kan zetten? Tenzij jij nog bezwaren
ziet, of betere oplossing? (timeout geen hulpvraag/aanbod, maar op andere
manier vastleggen?

groet!
Daan

Op ma 7 sep. 2020 om 11:30 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
opgelost
