### ISSUE TITLE
klant lijkt onterecht toegang te hebben tot alle locaties

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1055]
Hi Daan,
I have a problem with the file of XXX. I closed it on the 5th of August because he left for work. However, he was back in 2 days or didn't actually leave. I re-opened the dossier and put Startdatum toegang overigen 06-02-2021 but it still says that he can go everywhere. Can that be fixed? For now i put it by his name.
Thanks in advance!
Kind regards,
Ira

Irina Morozova
Maatschappelijk werker 
De Regenboog Groep
Locatie AMOC
di t/m vrij

Hi Daan,
To try it out I will have to make another intake then. But i think that date should not be a problem since we have an agreement that to Zeeburg and Transformatorweg people can go after 2 weeks and then after 6 months to other places. So we do the same with other clients and it works fine.
I am more curious about Makom in this case. 
Could the reason be that i closed his case with the reason "overige' and not "repatriatie'? 
Met vriendelijke groet,

Irina Morozova

dossier:
https://ecd.deregenboog.org/inloop/klanten/?klant_filter%5Bklant%5D%5Bid%5D=&klant_filter%5Bklant%5D%5Bvoornaam%5D=&klant_filter%5Bklant%5D%5Bachternaam%5D=zabas&klant_filter%5Bklant%5D%5BgeboortedatumRange%5D%5Bstart%5D=&klant_filter%5Bklant%5D%5BgeboortedatumRange%5D%5Bend%5D=&klant_filter%5Bklant%5D%5Bgeslacht%5D=&klant_filter%5Bgebruikersruimte%5D=&klant_filter%5BlaatsteIntakeLocatie%5D=&klant_filter%5BlaatsteIntakeDatum%5D%5Bstart%5D=&klant_filter%5BlaatsteIntakeDatum%5D%5Bend%5D=&klant_filter%5BhuidigeStatus%5D=&klant_filter%5Bfilter%5D=

**Comment by jtborger** [comment]
Ik laat deze even zitten; we hebben na die tijd het hele toegangsgebeuren op de schop genomen. Dit is oud lijkt mij. Mocht er weer iets voorbij komen dan pak ik het dan (eerder) op.
