### ISSUE TITLE
afsluitredenen van trajecten die op niet-actief staan worden toch getoond

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1056]
afsluitredenen die op niet actief staan worden toch getoond in het uitklapmenu bij afsluiten trajecten

https://ecd.deregenboog.org/dagbesteding/admin/trajectafsluitingen/?redirect=/dagbesteding/mijn/trajecten

**Comment by jtborger** [comment]
Dit was niet alleen het geval bij dagbesteding/trajecten maar op heel veel plekken in ECD. Er waren veel items die wel op inactief konden worden gezet, maar toch niet meededen. Heb alles (voor zover ik weet) nagelopen en dit gefixt.
2.2.50
