### ISSUE TITLE
toevoegen kolommen in overzicht scherm

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1057]
In de schermen deelnemers/vrijwilliger/hulpvragen/hulpaanbod/koppelingen + onder mijn IZ
toevoegen kolom "hulpvraagsoort" en "doelgroep"
Bij koppelingen zijn de gegevens van deelnemer leidend (net als nu het geval is bij projecten)

deadline 1 okt ivm wijziging

**Comment by jtborger** [comment]
gaat mee in 2.2. 51
