### ISSUE TITLE
wijziging in management rapportage IZ

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1060]
De onderdelen Team CON/ZOZDIEMEN/WNW mogen eruit

https://ecd.deregenboog.org/iz/rapportages/?rapportage%5Bstartdatum%5D=01-01-2020&rapportage%5Beinddatum%5D=14-09-2020&rapportage%5Brapport%5D=IzBundle%5CReport%5CManagementrapportage&rapportage%5Bshow%5D=

**Comment by jtborger** [comment]
2.3.6
