### ISSUE TITLE
verwijderknop werkt niet in Homeservice, en is er bij sommige dossiers wel/niet 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1062]
Iris:
 Hoi Daan, 

het blijkt dat ik klanten niet kan verwijderen in ECD: kan het wel aanklikken, kan het ook verwijderen, vraagt om bevestiging, maar vervolgens blijft de klant erin staan. Staan twee klanten in met DELETE in hun naam waarbij dat blijft gebeuren..

https://ecd.deregenboog.org/hs/klanten/2616/view?redirect=/hs/klanten/
https://ecd.deregenboog.org/hs/klanten/2619/view?redirect=/hs/klanten/
---

Daarnaast is het mij niet duidelijk waarom sommige dossiers in Homeservice wel een verwijderknop hebben en anderen niet.

**Comment by jtborger** [comment]
Sorry, maar kom er op terug: niet actief betekent bij ons "zonder openstaande klus". De conclusie van Jan klopt dus niet... Als ik een klus aanmaak in een van de "DELETE"-klanten komt die weer gewoon in de actiefmodus, en verwijderen lukt allen als er geen openstaande klus is. 

En nu staat het weer standaard op actief, wat we juist uit hadden gezet, omdat we actieve en niet-actieve klanten willen zien als we een naam intoetsen... 
IRIS

**Comment by jtborger** [comment]
ik heb iris gemaild.

**Comment by jtborger** [comment]
2.3.7
Doorgenomen hoe en wat.
Volgens mij duidelijk.

Er was verwarring over de betekenis van actief/niet actief.
Klanten zijn verwijderbaar wanneer ze geen gelinkte data hebben (klussen, facturen).
Dit zou de lading moeten dekken.
