### ISSUE TITLE
namen lijstje medewerkers in MaatschappelijkWerk is niet meer alfabetisch 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1065]
Hi Daan,

in het scroll down menu waar alle medewerkers staan is het heel moeilijk medewerkers zoeken. Kunnen deze op Alphabet worden gezet? En kan je Arkadi Radolov verwijderen?

Vraag Jan: kunnen wij hierin namen verwijderen? Of moet dat via Leo/TarQ?

**Comment by jtborger** [comment]
gaat mee in 2.2. 51
