### ISSUE TITLE
bij traject toevoegen eigen naam ipv Rolanda als standaard

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1067]
Als er een nieuw traject toegevoegd wordt, staat nu standaard naam van Rolanda ingesteld ipv naam die ingelogt is. Doordat dit over het hoofd gezien wordt komen er veel trajecten onterecht op naam van Rolanda te staan. 

VB:
https://ecd.deregenboog.org/dagbesteding/trajecten/add?deelnemer=591&redirect=/dagbesteding/deelnemers/591/view

**Comment by jtborger** [comment]
is al wel opgelost...
