### ISSUE TITLE
Bij aanmaken Huurovereenkomst alleen Huurverzoek/Huuraanbod met overlap tonen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#107]
Deze is afhankelijk van #106. Bij het aanmaken van een Huurovereenkomst in de dropdown alleen Huurverzoeken/Huuraanbiedingen tonen die overlap hebben (startdatum, einddatum) met het huidige Huuraanbod/Huurverzoek.

**Comment by Evertt** [comment]
@barthuttinga overlap kan op allerlei manieren. Ik gok dat je hier bedoelt dat elke vorm van overlap acceptabel is, klopt dat? Of moet het een specifieke vorm van overlap zijn? Bijvoorbeeld dat de startdatum van het huurverzoek wel vroeger mag zijn dan de startdatum van het huuraanbod, maar niet andersom?

**Comment by barthuttinga** [comment]
@Evertt elke overlap is goed
