### ISSUE TITLE
locaties inloophuizen kloppen niet meer in dit dossier

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1073]
Deze persoon is wel nog vindbaar via MW, maar niet meer via inlopen, lijkt erop dat locaties Inloophuizen bij haar dossier niet meer juist zijn.

https://ecd.deregenboog.org/inloop/intakes/27662/view?redirect=/mw/klanten/5653229/view

**Comment by jtborger** [comment]
Het lijkt erop dat deze klant eerder al bestond bij andere afdelingen voordat deze bij inloop bekend was.
Het was zo, dat een klant enkel een inloop dossier kreeg wanneer deze als nieuwe klant werd aangemaakt, niet wanneer er een intake op een bestaande klant werd aangemaakt.

Dat heb ik aangepast. (na de release moet de laatste intake van de klant even gewijzigd en opgeslagen worden (ook al is er feitelijk niks gewijzigd). Dan 'berekent' hij opnieuw de toegang.
(2.2.53)
