### ISSUE TITLE
Dagbesteding/beheer inactief maken trajectbegeleider lijkt nog niet overal goed te werken

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1077]
Als je via beheer een trajectbegeleider op inactief zet wordt deze naam correct niet meer getoond bij het aanmaken van nieuwe deelnemer. Echter staat hij/zij wel nog in lijstje medewerkers als je een traject wilt wijzigen.

De term "begeleider" mag hier veranderen in "trajectbegeleider"

**Comment by jtborger** [comment]
2.3.6
