### ISSUE TITLE
einddatum voor timeout klus

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1078]
Hoi Daan en Jan, 

wij hebben iets leuks en nieuws bedacht :)

Is het mogelijk om een einddatum te implementeren bij het on hold zetten van een klus? Heeft geen spoed, zou het werk van Jaap wel weer veel makkelijker maken!

Groet Iris

--

mogelijkheid om einddatum in te vullen bij time out, als die datum verstreken is komt klus weer open te staan

**Comment by jtborger** [comment]
evt via einddatum?

**Comment by jtborger** [comment]
2.3.7

Klus kan nu een 'On Hold tot' datum hebben. Dit maakt dat de status on hold komt en na de 'tot' datum weer gewoon wordt.
Via het zoeken van klussen kan je evt de 'On Hold Tot' datum zien in de einddatum (die staat dan tussen haakjes, omdat het dan om de einddatum van on hold tot gaat en niet van de klus zelf).
