### ISSUE TITLE
Selectiecriteria voor IzProjectSelectFilterType geeft niet de juiste lijst met projecten

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1079]
Hometown wordt niet weergegeven in de lijst met te filteren projecten.
Op Dev wel. Zelfde criteria? Raar.

**Comment by jtborger** [comment]
Naw te maken met verschil tussen dev en prod: mysql 5.6 op prod.
Straks met overstappen naar nieuwe server nog eens kijken, downgrade naar 5.6 lokaal heeft wat veel voeten in aarde.
Impact is laag.

**Comment by dvleeuwen** [comment]
lijkt nu te kloppen

**Comment by jtborger** [comment]
Is schijnbaar opgelost :)
