### ISSUE TITLE
Huuraanbod/verzoek blijft open staan na match, en ook na afsluiten dossier?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1080]
Hi Daan en Jan,

Iedereen is zijn caseload aan het lopen en opschonen.
Wij komen er helaas achter dat als mensen gekoppeld worden of als de koppeling afgesloten is dat de huur verzoeken en aanbiedingen blijven bestaan. 

Zie bijv 
https://ecd.deregenboog.org/odp/huurverzoeken/?huurverzoek_filter%5Bfilter%5D=&huurverzoek_filter%5Bid%5D=&huurverzoek_filter%5Bklant%5D%5Bnaam%5D=berggren&huurverzoek_filter%5Bstartdatum%5D%5Bstart%5D=&huurverzoek_filter%5Bstartdatum%5D%5Bend%5D=&huurverzoek_filter%5Bafsluitdatum%5D%5Bstart%5D=&huurverzoek_filter%5Bafsluitdatum%5D%5Bend%5D=&huurverzoek_filter%5Bmedewerker%5D=&huurverzoek_filter%5Bhuurovereenkomst%5D%5BisReservering%5D=1

En zie voor de aanbiedingen
https://ecd.deregenboog.org/odp/huuraanbiedingen/?huuraanbod_filter%5Bfilter%5D=&huuraanbod_filter%5Bid%5D=&huuraanbod_filter%5Bklant%5D%5Bnaam%5D=becker&huuraanbod_filter%5Bklant%5D%5Bstadsdeel%5D=&huuraanbod_filter%5Bstartdatum%5D%5Bstart%5D=&huuraanbod_filter%5Bstartdatum%5D%5Bend%5D=&huuraanbod_filter%5Bafsluitdatum%5D%5Bstart%5D=&huuraanbod_filter%5Bafsluitdatum%5D%5Bend%5D=&huuraanbod_filter%5Bmedewerker%5D=&huuraanbod_filter%5Bhuurovereenkomst%5D%5BisReservering%5D=1

Wij vinken alleen de active aan bovenin en alsnog blijven ze terugkomen.

Willen jullie hier svp naar kijken, op deze manier verliezen wij het overzicht.

Dank!

Hartelijke groet,

Juul Gemmeke 
Projectleider Onder de Pannen

De Regenboog Groep
Bezoekadres: Droogbak 1-D, 1013 GE te Amsterdam

Bereikbaar dinsdag t/m vrijdag
020 531 7600 | 06 14 93 43 58
jgemmeke@deregenboog.org

**Comment by dvleeuwen** [comment]
Ha Juul,
ik zie het.
Dat bij koppeling huurvraag/aanbod open blijft staan is idd bug. Pakt Jan op zodra hij weer een blok "onder de panne" gaat doen. 
Mbt afsluiten van dossier:
moeten jullie dan handmatig huuraanbod/vraag afsluiten, want ik zie in veel gevallen dat dit wel gebeurd is?
Wens is dat dossier alleen gesloten kan worden als er geen open huuraanbod/vraag meer is, correct? 

groet!
Daan

**Comment by dvleeuwen** [comment]
Hoi Daan,

Correct volgens mij, wens is inderdaad dat het dossier alleen afgesloten kan worden als er geen open huuraanbod/vraag meer is. En huuraanbod/vraag sluiten wij handmatig af.

Cindy

**Comment by dvleeuwen** [comment]
op verzoek ivm wijzigingen/uitbreiding vh project hoge prio toegekend

**Comment by jtborger** [comment]
Ik snap de vraag van het afsluiten van dossiers niet helemaal, maar daar moet even een apart issue voor komen denk ik.

Dit ging om actief aanbod/verzoek. Dat is nu gefixt.

Ik had nog wel een vraagje maar krijg Juul niet te pakken.
Hoe ik het nu heb is als volgt:

Een Actief huurverzoek of huuraanbod is er een die nog niet gekoppeld is en ook geen einddatum heeft.

Als dit vinkje UIT staat (standaard) dan zoekt hij dus alleen naar huuraanbod/verzoeken welke nog niet gekoppeld zijn, ongeacht afsluitdatum.
Als het vinkje Actief aan staat, zoekt hij huuraanbod/verzoek dat gekoppeld is en die nog niet zijn afgesloten, of pas in de toekomst worden afgesloten.

Het kan zijn dat het anders moet omdat ik het niet goed begrijp maar dan moet ik even contact hebben met Juul per mail of telefoon.

Gaat mee in 2.2.60
