### ISSUE TITLE
bug mbt schorsingen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1082]
zie dit dossier:
als je via bezoekersregistratie kijkt staat er bij schorsing "geen"
als je in dossier kijkt zie je dat er wel 1 actief is.
https://ecd.deregenboog.org/inloop/klanten/5625601/view?redirect=/inloop/klanten/
Ik vraag nog na of dit enkel bij dit dossier is, of vaker misgaat.

**Comment by dvleeuwen** [comment]
Er lijkt een verband met op welke locatie schorsing aangemaakt is, antwoord Shane:

Hoi Daan,

We zijn het bij meerdere bezoekers tegen gekomen en zowel op mijn account als dat van Jonnie, het lijkt wel alleen te gelden voor schorsingen van andere locaties.

Groet, 
Shane

**Comment by jtborger** [comment]
Ja het is even de vraag wat het gewenste gedrag is: moet schorsing ook getoond worden wanneer niet van die locatie? zo werkt het systeem niet en heeft het voor zover ik kan zien ook nooit gewerkt.

**Comment by dvleeuwen** [comment]
mail aan Shane en collega's:

Ah we zien nu in dit geval (Daud) dat de schorsing enkel geldt voor Princehof (zo staat ie in ECD),
is dat niet de bedoeling. 
Dat verklaart wel waarom je m bij registratie OudWest niet ziet als geschorst, maar bij Princehof weer wel.

Hoor graag terug of dit de juiste verklaring kan zijn, of dat er toch iets mis gaat binnen ECD?

groet!

**Comment by dvleeuwen** [comment]
ik wacht nog steeds op duidelijkheid, haal label hoge prio er voor nu af

**Comment by jtborger** [comment]
Dit is precies de bedoeling: schorsingen alleen zichtbaar op locatie waar die is gegeven.
