### ISSUE TITLE
oude mailadressen bij mails vanuit inloop naar andere afdelingen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1083]
Dit was al eens aangepast, maar vreemd genoeg gaan er nog steeds mails naar de oude adressen:

bdgroot@ moet worden: dagbesteding@
jschmidt@ moet worden: informelezorg@
adbruijn@ mag helemaal weg (de optie inloophuizen dus)

**Comment by jtborger** [comment]
Ik kan echt niks vinden van jschmidt. het enige dat zou kunnen is dat het mailadres informelezorg@ wordt doorgestuurd naar jschmidt?
is 16 oktober de laatste die zij kreeg? 
begroot stond nog wel verkeerd, dat is veranderd.

kan jij vragen of ze wil nagaan of het nog steeds gebeurd? anders is het een raadsel, of vanuit de testomgeving..
maar dat laatste zou niet mogen!

**Comment by dvleeuwen** [comment]
Nee 18 oktober is er ook nog 1 naar Jeannot (Schmidt) gegaan, zie hieronder
voor volledigheid.
En nee: informelezorg@deregenboog is een veel gebruikt mailadres, staat
zeker niet doorgeschakeld richting jeannot

wat een raadsel....


Van: <noreply@deregenboog.org>
Date: zo 18 okt. 2020 om 15:10
Subject: Verzoek
To: <jschmidt@deregenboog.org>, <bdegroot@deregenboog.org>, <
adbruijn@deregenboog.org>, <maatschappelijkwerk@deregenboog.org>


Geachte mevrouw/heer,

Onderstaande mevrouw/heer heeft aangegeven graag van jullie dienstenaanbod
gebruik te willen maken. Wil je alsjeblieft contact opnemen met haar/hem om
een afspraak te maken? Als het je niet lukt om contact te krijgen kun je
mij (de intaker) via de mail laten weten op welke wijze ik kan helpen om
jullie met elkaar in contact te brengen. Mijn mailadres staat hieronder in
de gegevens vermeld.

Met vriendelijke groet,

Jaber Hamidoun


Klant
--------------------
Voornaam: Valerie X

Op ma 9 nov. 2020 om 10:51 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
OK. dat is nu twee weken geleden.
Het zou kunnen hoor dat het toch niet direct aangepast is/was.

Zou je eens kunnen vragen hoe het nu is? of de komende week?

anders snap ik er echt geen sikkepit van.

Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op ma 9 nov. 2020 om 11:06 schreef dvleeuwen <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Kunnen we het zelf mogelijk testen dmv een "testbezoeker" aan te
maken/intaken? (en weer verwijderen)

Op ma 9 nov. 2020 om 11:08 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Ja kan wel. Ik zal het even doen.

**Comment by jtborger** [comment]
heb dat nu gedaan. kijk maar even of mensen een mail krijgen om contact op te nemen voor client Test5 :)
