### ISSUE TITLE
overleg met Juul ivm aanpassingen OdP

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1084]
Jan belt Juul om verder te overleggen:

Ha Daan,
Ik wil even iets aan jou voorleggen.
Pas als het helemaal rond is en staat wordt het live gezet  en op extranet en naar buiten en intern gecommuniceerd etc. Maar ik wilde alvast even bij jou checken op wat voor termijn jij denkt dat dit te realiseren valt in ECD ;)
Wij krijgen een andere structuur voor onder de pannen.Wij worden team tijdelijk wonen met een aantal verschillende producten/projecten die eronder komen te vallen:

- Onder de Pannen Amsterdam
- Onder de Pannen Jong Volwassenen
- OdP Haarlem
- Odp Amstelland
- Odp Zaanstad
- TOD
- Parentshouse
- ABRI!

Wat ik zou willen weten of het mogelijk is om de naam Onder de Pannen in de titel te wijzigen naar Tijdelijk Wonen.En of er binnen elke huurder / verhuurder mogelijk gemaakt kan worden om bovengenoemde keuzes beschikbaar te maken. Moeten meerder opties mogelijk zijn bijv.  drie uitvouwvelden met bovenstaande opties. Waar we dan ook op kunnen selecteren in huur aanbieding en verzoek. En Rapportages moeten kunnen uitdraaien.Dezelfde optie zou dan ook binnen de koppeling moeten komen, alleen is hier maar één uitvouwveld voor nodig.
Heel verhaal maar zou jij mij een indicatie kunnen geven hoelang zoiets zou gaan duren?Gezien wij de pilot binnen nu en een maand gaan starten voor twee projecten en na drie maanden moeten evalueren zou het fijn zijn als het iig nog wel dit jaar zou kunnen 
Benieuwd wat jij denkt!
Hartelijke groet,

Juul

**Comment by jtborger** [comment]
Verhuurder en verzoek krijgt het volgende:
Time Being = ABRI
Parentshouse = Parentshouse
AHAM * = ABRI

Rest doet Juul zelf

**Comment by jtborger** [comment]
Huurder/Huurverzoek wordt standaard OdP Amsterdam
Behalve gekoppelden: die krijgen project van huuraanbieding

**Comment by jtborger** [comment]
2.2.58
