### ISSUE TITLE
dossier onvindbaar binnen IZ

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1089]
Dit dossier is vindbaar via algemene klantentab, maar onvindbaar binnen IZ
https://ecd.deregenboog.org/klanten/?klant_filter%5Bfilter%5D=&klant_filter%5Bid%5D=5651829&klant_filter%5Bnaam%5D=&klant_filter%5Bgeslacht%5D=&klant_filter%5Bgeboortedatum%5D=&klant_filter%5Bmedewerker%5D=&klant_filter%5Bstadsdeel%5D=&klant_filter%5Bpostcodegebied%5D=

Was eerst afgesloten, maar ook na heropening onzichtbaar binnen IZ

**Comment by jtborger** [comment]
Ja, het rare is dat ik hem nu gewoon kan vinden. Even overleg?
