### ISSUE TITLE
Gezinsverbanden dossiers koppelen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1093]
overleg Els + Jan 

Ha Els,zojuist weer even met Jan overlegd over het punt van dossiers koppelen (partners - kinderen).Hij wil hier graag even met jou over doorspreken. Hierbij breng ik jullie in contact, moeten jullie samen wel uitkomen ;)
groet & succes
Daan

Ten tweede: de gezinnen. Ik begrijp dat deze vraag niet in een poep en scheet is opgelost, maar aangezien we steeds meer gezinnenwerk doen zou een koppeling tussen partners en optie + kind heel erg fijn zijn. Nu zijn het stuk voor stuk losse dossiers, terwijl we het gezin als geheel begeleiden.Zou jij deze vragen bij de ECD pro's willen neerleggen?
Dankjewel alvast!
Met vriendelijke groet,Els van Koeverden

**Comment by dvleeuwen** [comment]
aanvullende info Els:
graag zo simpel mogelijk: enkel partners aan elkaar kunnen koppelen (dus 2 dossiers)
waarbij dan zichtbaar is als je in dossier A werkt dat B daar aan gekoppeld is, en je ook direct door kunt klikken naar B

**Comment by jtborger** [comment]
komt mee in 2.2.67.
Partner kan worden toegevoegd en verwijderd.
In principe door alle gebruikers vooralsnog. En daarbij voor alle modules; overal waar de basis klant info wordt gebruikt zit dit in.

**Comment by jtborger** [comment]
v2.3.0
