### ISSUE TITLE
dossier zijn soms niet meer klikbaar

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1096]
mail aan Daphine en Josje die hier veel last van hebben

Hi,
ik heb Jan gesproken: hij vermoedt dat het probleem bij Chrome (onze browser) zit en niet bij ECD.
Willen jullie dit eens proberen:
Rechts van je browserbalk zie je 3 stipjes, klik daarop en kies voor instellingen. 
Je komt dan in nieuw scherm waar je "cache" intikt in zoekbalk. Kies dan voor de onderste optie "Browsegegevens wissen"  
Vervolgens klik je enkel de onderste vd 3 bullets aan, en periode: alles.

Jan is benieuwd of jullie na deze actie het probleem nog steeds hebben.
If so: mocht het zich vandaag (vrijdag) voordoen kun je hem bellen (06-42719707), dan kan hij direct meekijken/meedenken.

groet!
Daan

**Comment by jtborger** [comment]
In de volgende release heb ik een aanpassing gedaan in de timing waarin de rijen van het zoekresultaat klikbaar gemaakt worden. Het kan zijn dat dit het verhelpt.
Even in de gaten houden.
.59

**Comment by dvleeuwen** [comment]
Helaas nog niet (geheel?) verholpen. Ik heropen issue, verschillende collega's hebben we vandaag nog last van.

**Comment by jtborger** [comment]
is de cache verwijderd bij iedereen?

Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op ma 7 dec. 2020 om 13:05 schreef dvleeuwen <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Lijkt bij (bijna?) iedereen verholpen. Ik sluit topic voor nu.
