### ISSUE TITLE
locatie wordt niet meegenomen in managementrapportage MW 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1097]
Bij managementrapportage staat locatie New West Inn op 0 bij mw contacten (periode 1-1-2020 - 4-12-2020)

terwijl er wel degelijk MW contacten geweest zijn op die locatie, zie dit dossier bijvoorbeeld:
https://ecd.deregenboog.org/mw/klanten/5654111/view?redirect=/mw/klanten/

**Comment by jtborger** [comment]
Er zijn twee locaties met dezelfde naam; 1 daarvan is twee weken open geweest.
Bij het opbouwen van de rapportage schrijft hij op 'locatienaam'. De eerste (met contacten) wordt overschreven door de tweede, zonder contacten.
Oplossing is om de tweede Nieuw West Inn te hernoemen naar 'Nieuw West Inn - tijdelijke locatie' of zoiets?

**Comment by jtborger** [comment]
is aangepast in database
