### ISSUE TITLE
Controller/view voor index huurovereenkomsten maken

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#110]
Lijst van huurovereenkomsten tonen met id + naam huurder, id + naam verhuurder, startdatum overeenkomst, einddatum overeenkomst, medewerker die de overeenkomst afsloot. Alles filterbaar en sorteerbaar.

**Comment by Evertt** [comment]
@barthuttinga ik heb dit ticket bijna af, maar ik loop ergens een beetje vertraging op.

Het filteren op de naam van de huurder en de naam van de verhuurder werkt niet zomaar. Want omdat ik ze allebei moet opnemen in de query moet ik ze allebei een alias geven: "odpHuurderKlant" en "odpVerhuurderKlant". Maar de KlantFilter gaat er op regel 43 vanuit dat de klant in de query gewoon "klant" wordt genoemd.

Dus ik wil het hele filter systeem een beetje aanpassen zodat je aliassen door kunt geven. Alleen wil ik even met jou overleggen of je dat oké vindt. Of wil jij het doen? Of wil jij het sowieso op een heel andere manier aanpakken?

**Comment by barthuttinga** [comment]
@Evertt  Je hebt gelijk, ik heb het aangepast in commit 24f4e7bb1657ac067c9b13e90378a7f0e9c27353
