### ISSUE TITLE
vrijwilligers tab aanmaken bij CLIP

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1100]
Exact zoals de vrijwilligers tab bij inlopen is, zo wil CLIP m ook.
(net als MW, zie #1091)

**Comment by dvleeuwen** [comment]
Hi allen,voor jullie staat ECD verzoek open om vrijwilligersmodule te bouwen. Het verzoek is ingediend met de vraag "zelfde als nu bij inloophuizen". Programmeur Jan merkte echter vanochtend terecht op dat bij de inloophuizen ook aangegeven wordt op welke locatie de VW werkt. Zijn vraag is nu of dat voor jullie ook handig is, of dat die mogelijkheid er uit moet?
Ik verwacht dat CLIP en VILLA slechts 1 locatie hebben/gebruiken, dus niet nodig, correct?Mike: hoe is dat bij jouw sport vw'ers? Is het voor die module handig om verschillende locaties te kunnen registreren afhankelijk waar de vw'er actief is?
Hoor m graag terug, dan kan Jan weer verder.
dank & groet!Daan

**Comment by dvleeuwen** [comment]
15jan:
Besten,

 

Ik denk dat voor de Clippers toch wel geldt dat ze op verschillende plekken werken. Ik zal bij hen navragen hoe dit voor hen handig is...
Wordt vervolgd!
Hartelijke groeten van Dini

22jan:
Ha Dini,
had jij hier nog antwoord op?

groet!
Daan

**Comment by dvleeuwen** [comment]
Na overleg Sander + Dini, dit is toch echt nodig voor de organisatie, dus komt weer met prio op lijst.

**Comment by jtborger** [comment]
gaat mee met 2.3.3
