### ISSUE TITLE
nieuwe module ECD met vw registratie: Villa

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1102]
nieuwe module met vrijwilligersregistratie gelijk aan inlopen. "Villa"
ik mail de gegevens van medewerkers die hier toegang tot moeten krijgen.
Jan maakt nieuwe role aan via Tarq zodra module er is.

**Comment by dvleeuwen** [comment]
Hi allen,voor jullie staat ECD verzoek open om vrijwilligersmodule te bouwen. Het verzoek is ingediend met de vraag "zelfde als nu bij inloophuizen". Programmeur Jan merkte echter vanochtend terecht op dat bij de inloophuizen ook aangegeven wordt op welke locatie de VW werkt. Zijn vraag is nu of dat voor jullie ook handig is, of dat die mogelijkheid er uit moet?
Ik verwacht dat CLIP en VILLA slechts 1 locatie hebben/gebruiken, dus niet nodig, correct?Mike: hoe is dat bij jouw sport vw'ers? Is het voor die module handig om verschillende locaties te kunnen registreren afhankelijk waar de vw'er actief is?
Hoor m graag terug, dan kan Jan weer verder.
dank & groet!Daan

**Comment by dvleeuwen** [comment]
Ha Eva,dank voor snelle reactie!Laten we locaties voor jullie achterwege.
groet!Daan

**Comment by jtborger** [comment]
gaat mee met 2.3.4
