### ISSUE TITLE
(te) lange lijst aanmelding bij mw dossier

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1104]
Zie bijvoorbeeld onderstaande 2 dossiers, komen steeds nieuwe aanmeldingen bij, dit is niet de bedoeling + onoverzichtelijk?

https://ecd.deregenboog.org/mw/klanten/5629257/view?redirect=/mw/klanten/
https://ecd.deregenboog.org/mw/klanten/5622257/view?redirect=/mw/klanten/

**Comment by dvleeuwen** [comment]
navragen Jan: wat is dit precies? 
Wordt niet gebruikt, mag weg?

**Comment by jtborger** [comment]
Nalopen waarom er zoveel aanmeldingen zijn op sommige dossiers.

**Comment by jtborger** [comment]
tijdelijk even verbergen?

**Comment by jtborger** [comment]
OK, het kwam doordat bij elk verslag er een nieuwe aanmelding werd aangemaakt.
aangepast en haal alle dubbelen eruit.
2.3.5
