### ISSUE TITLE
niet alle vw'ers worden juist weergegeven als je op locatie filtert

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1105]
https://ecd.deregenboog.org/inloop/vrijwilligers/?vrijwilliger_filter%5Bfilter%5D=&vrijwilliger_filter%5Bvrijwilliger%5D%5Bid%5D=&vrijwilliger_filter%5Bvrijwilliger%5D%5Bnaam%5D=kimo&vrijwilliger_filter%5Baanmelddatum%5D%5Bstart%5D=&vrijwilliger_filter%5Baanmelddatum%5D%5Bend%5D=&vrijwilliger_filter%5Bafsluitdatum%5D%5Bstart%5D=&vrijwilliger_filter%5Bafsluitdatum%5D%5Bend%5D=&vrijwilliger_filter%5Blocatie%5D=&vrijwilliger_filter%5Bvrijwilliger%5D%5Bstadsdeel%5D=

en

https://ecd.deregenboog.org/inloop/vrijwilligers/163/view?redirect=/inloop/vrijwilligers/

worden niet getoond als je op Kloof filtert

(zie ook issue #1024 & #1029)

**Comment by jtborger** [comment]
opgelost, gaat mee in volgende update (2.2.63)
