### ISSUE TITLE
in klantdossier MW naast "medewerker" ook "maatschappelijk werker"

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1108]
Nieuw veld, in te vullen door maatschappelijk werker (namenlijst MW)
Dit ook zichtbaar maken als klant in algemene klantenlijst gezocht wordt.

**Comment by dvleeuwen** [comment]
kolom "mederwerker" kan hier vervangen worden door nieuwe kolom "maatschappelijk werker"
https://ecd.deregenboog.org/mw/klanten/

**Comment by jtborger** [comment]
Gaat mee met 2.3.3
Ik heb het nu als volgt gemaakt;
Elke klant heeft nu een veld 'Maatschappelijk werker', want een MW klant = Inloopklant = algemene klant. (deze heeft geen module specifieke velden).
De maatschappelijk werker is te zien in de zgn. 'klant basis' weergave, die in elke module standaard wordt opgeroepen wanneer de NAW etc wordt weergegeven. Daar is dus ook de MW-er te zien die is toegekend aan die klant.

Iedereen die een klant mag wijzigingen, kan daarbij het maatschappelijk werker veld aanpassen. De selectielijst is de algemene lijst met medewerkers. Er is geen vinkje 'deze medewerker is een maathscppalijk werker'. Ik zou evt een lijst kunnen maken van medewerkers die ooit een MW verslag hebben gemaakt. Maar die lijst is ook al behoorlijk lang (zie de klantenlijst filter maatschappelijk werk. Als je die nu uitklapt zie je de medewerkers op basis van 'heeft ooit een MW verslag geschreven'.

In de MW klantenlijst zie je in de kolom 'Maatschappelijk werker' de geselecteerde maatschappelijk werker, of (zoals het was) de laatste drie medewerkers die een verslag hebben gemaakt. 
Als je filtert op die kolom filtert hij enkel op het veld Maatschappelijk werker, en dus niet meer op verslag medewerker (omdat dit een soort overgangsperiode is, lijkt me).

Moet er voor bestaande MW klanten een maatschappelijk werker worden ingevuld en zo ja, op basis waarvan zou dat moeten? Medewerker laatste verslag? medewerker laatste intake?

Ik hoor het wel.
2.3.3.

**Comment by dvleeuwen** [comment]
update na overleg MW:
vanaf heten dit veld niet meer automatisch aan laten passen op basis van laatste verslag, dus enkel nog invoerbaar/veranderbaar door medewerker zelf.
svp wel alle data zo laten staan zoals het nu is

**Comment by dvleeuwen** [comment]
dit blijkt al zo gebouwd te zijn, ik sluit issue
