### ISSUE TITLE
nieuwe rapportage bij MW: AMW

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1110]
nieuwe rapportage op dezelfde wijze als rapportage "economisch daklozen"
Titel: AMW
Locaties:
Princehof inloop
Princehof gebruikersruimte
Blaka Watra inloop
Blaka Watra gebruikersruimte
Amoc inloop
Amoc Gebruikersruimte
Zeeburg
Spreekbuis
Makom
De Kloof
Oud West
Nachtopvang DRG
Nachtopvang Schuitenhuisstraat
T6 Nachtopvang
T6 Inloop

**Comment by jtborger** [comment]
2.3.3b

**Comment by dvleeuwen** [comment]
Lijstje locaties lijkt niet te kloppen?

**Comment by jtborger** [comment]
helder. 1109 door de war gehaald met deze rapportage...
