### ISSUE TITLE
Emoji's worden niet goed opgeslagen

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1112]
Collatie moet naar utf8mb4 voor alle tabellen en kolommen.

**Comment by dvleeuwen** [comment]
inmiddels geen foutmelding meer, maar tekst wordt nog altijd afgebroken na een emoji uit geplakte tekst

**Comment by jtborger** [comment]
kan je een voorbeeldtekst meesturen om te testen?

Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op vr 12 feb. 2021 om 09:48 schreef dvleeuwen <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Zie hier een voorbeeld, geknipt uit whatsapp:

[14:34, 20-04-2021] Daan: klinkt als een hele mooie coachende rol in deze!
[14:34, 20-04-2021] : 👍
[14:34, 20-04-2021] Daan: ik zal X komende maand ook even een belletje geven voor korte evaluatie vh contact, uiteraard hoor je dan terugkoppeling van mij

Als je dit in verslagen plakt verdwijnt de laatste regel.

**Comment by dvleeuwen** [comment]
Ontvangt nu weer een foutmelding bij opslaan verslag met smiley erin

**Comment by dvleeuwen** [comment]
Ha Jan top, dank!

Ik zie dat de emoji's er nu in komen als vage codes (dit is een smiley: ðŸ˜ ) 
Maar dat is verder geen enkel probleem; verslagen kunnen in elk geval gewoon opgeslagen worden, daar was het om te doen.

Dank!
Daan


Op wo 14 dec. 2022 om 23:21 schreef Jan Borger <[jborger@deregenboog.org](mailto:jborger@deregenboog.org)>:
Hoi daan

ik had het emoji probleem opgelost, of in elk geval werkend genoeg om voor een tijdelijke oplossing door te gaan, en ik wilde dat releasen, maar er ging eea mis dus ik heb de release teruggedraaid.

ik heb de aanpassing die nodig is nu live gepatcht zonder release, dan kunnen jullie iig door. Dus volgens mij zou het verslagen deel bij IZ nu ook weer werken met emojies

**Comment by dvleeuwen** [comment]
zelfde probleem/verzoek nu van tijdelijk wonen.
Zij kunnen verslagen (geknipt uit whatsapp) met sommige emoticons niet opslaan bij hun klanten 

voorbeeld waar het mis gaat:
[15:34, 23-01-2023] Mevr Sayad: Gdm Nezet ,het is goed gekomen voor de woning kan me inschrijven.krijg als het goed is vrijdag de sleutel.!☺️
[16:34, 23-01-2023] Nezet Fares: Dat is goed nieuws! Gefeliciteerd!
[16:36, 23-01-2023] Mevr Sayad: Dankjewel voor je ondersteuning 🤗
[16:36, 23-01-2023] Mevr Sayad: Thank you!
[16:37, 23-01-2023] Mevr Sayad: En ik wil jullie wel als achtergrond voor zoeken naar woning voor onbepaaldetijd

**Comment by dvleeuwen** [comment]
in het veld noties bij aanmelding deelnemer kunnen (bepaalde?) emoticons een foutmelding opleveren als je tekst wilt opslaan. 
Tekst wordt dan wel opgeslagen, maar er verschijnt dan "rode balk met er is een fout opgetreden in beeld"
bijvoorbeeld bij gebruik van deze: 🙂

**Comment by jtborger** [comment]
utf8 ding. is volgens mij overal opgelost.
