### ISSUE TITLE
foutmelding bij toevoegen training

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1113]
Hoi Daan/Jan,

Het lukt niet meer een training toe te voegen of te verwijderen in een inloopvw-dossier. Zie als voorbeeld: https://ecd.deregenboog.org/inloop/vrijwilligers/121/view#trainingen
Graag toevoegen aan de lijst.

Groet,

Josje

**Comment by jtborger** [comment]
gaat mee met 2.3.3

**Comment by dvleeuwen** [comment]
Hoi Daan/Jan,

Het toevoegen van een training in het inloopvw dossier zou volgens GitHub opgelost moeten zijn, maar geeft helaas nog steeds een foutmelding (opslaan lukt niet).
Dus graag opnieuw op de lijst.

Groet,

Josje

**Comment by jtborger** [comment]
Vreemd, ik heb het gezien. Het heeft wel gewerkt maar blijkbaar heb ik het later weer stukgemaakt.
Het gaat mee in de volgende release 2.3.6.
