### ISSUE TITLE
Wachtlijstoverzicht MW maken

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1115]
De tab intakes vanuit Inloophuizen kopiëren naar Maatschappelijk Werk
Hernoemen naar Wachtlijsten
En bij locaties enkel Wachtlijst T6 en Wachtlijst Economisch Daklozen beschikbaar maken
(ik heb die 2 locaties aangemaakt, maar vooralsnog met startdatum 1 maart)

**Comment by jtborger** [comment]
gaat mee me 2.3.3

**Comment by dvleeuwen** [comment]
ombouwen zodat locaties beginnend "wachtlijst" automatisch toegevoegd worden aan wachtlijst

**Comment by jtborger** [comment]
Heb het nu zo gedaan dat je bij locaties (onder inloop beheer) kunt aangeven of een locatie een wachtlijst heeft.
Zo ja, dan komt ie in het overzicht.
2.3.5
