### ISSUE TITLE
info wijzigen maatschappelijkwerk veld verwijderen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1118]
Het scherm MW binnen MW mag verdwijnen.

halverwege links in scherm

Maatschappelijk werk
Info wijzigen

https://ecd.deregenboog.org/mw/klanten/5656173/info?redirect=/mw/klanten/5656173/view

**Comment by dvleeuwen** [comment]
Ha Jan,vervelend, maar nu blijkt dat de velden waarvan Michael ons vroeg te verwijderen (zie issue #1118) door sommige medewerkers toch gebruikt werden :(Kun jij vinden terugvinden of sommige velden wellicht ook in de intake stonden? En dat daardoor verwarring is ontstaan?En mocht het nodig zijn: is deze oude info terug te halen? Hoeft voorlopig nog geen actie op, nog even bezig met uitzoeken wie wat nu precies mist. Maar wel fijn om te weten of, indien nodig, de info nog teruggehaald kan worden?
kunnen het verder vrijdag bespreken
dank!Daan

**Comment by jtborger** [comment]
Hoe verder?

**Comment by dvleeuwen** [comment]
=#1125?

**Comment by jtborger** [comment]
klopt
