### ISSUE TITLE
fout bij rapportage mw

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1119]
Hoi Daan,

De rapportage 'Repatriëring per land van herkomst' doet ook raar. Over heel 2020 zegt ie 1 naar Moldavie, 1 naar Nederland, 1 naar Italie en 1 naar Roemnië :) Ook als je heel 2019 erbij neemt blijft dat de eindstand.

Kan Jan daar een blik op werpen?

Dank alvast!

**Comment by jtborger** [comment]
2.3.5
