### ISSUE TITLE
ZRM toevoegen bij invoer klanten Tijdelijk Wonen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1120]
He Daan,

Wij hebben het volgende ECD verzoek voor Tijdelijk Wonen.

Graag aan de dossier van de huurders de ZRM registratie mogelijkheid toevoegen. 
Wij dienen vanaf heden deze bij iedereen af te nemen en te registreren.

Kan je een bepaalde tijdsindicatie geven wanneer zoiets gerealiseerd kan worden?

Dank!

Hartelijke groet,

Juul Gemmeke 
Projectmanager Tijdelijk Wonen

De Regenboog Groep
Bezoekadres: Droogbak 1-D, 1013 GE te Amsterdam

Bereikbaar dinsdag t/m vrijdag

**Comment by jtborger** [comment]
Gaat mee in 2.3.6
