### ISSUE TITLE
foutmelding bij verslag toevoegen inloop

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1122]
Ha Jan,van Willemijn Los kreeg ik bericht dat ze geen verslagen meer kan toevoegen aan inloopdossiers.Ik wilde het even nakijken, en zie nu dat ik het ook niet kan. Zodra ik op "verslag toevoegen" klik kom ik op foutmeldingpagina. Zie bijvoorbeeld hier (willekeurig voorbeeld)https://ecd.deregenboog.org/inloop/klanten/5630852/view?redirect=/inloop/klanten/#verslagen 
Ik zet m ook in Github
groet!Daan

**Comment by jtborger** [comment]
voor zover ik weet is dit gefixt in 2.3.6. Vergeten dit issue te sluiten.
