### ISSUE TITLE
Aanpassing info MW dossier

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1125]
Zoals besproken met Michael en Janneke:

Info kopje verplaatsen naar tabblad; beschikbare velden zichtbaar maken. Van daaruit bespreken in team hoe te gebruiken: wat mist er, wat kan er weg.

**Comment by jtborger** [comment]
- inloop: schorsingne, registraties en opmerkingen allemaal naar tabblad. note to self: intakes ook?

**Comment by jtborger** [comment]
Casemanager kan weg
Trajectbegeleider = intern, alleen verwijzing.
Trajecthouder wordt Hulpverlener extern

**Comment by jtborger** [comment]
Registarties, opmerkingen en schorsingen:
zo houden, dus links, daarmee conform aan inloop.
Evt: 
registraties naar rechts halen (maar waarom?) en evt laatste intake?
Vragen tzt.
2.3.7

**Comment by dvleeuwen** [comment]
Klopt het dat dit zelfde is als #1118, en dat die dus ook dicht mag?

groet
Daan

Op vr 26 mrt. 2021 om 11:09 schreef JT Borger ***@***.***>:

**Comment by dvleeuwen** [comment]
nog kleine aanpassing: verzoek om tab verslagen weer naar voren (links) te verschuiven, deze tab hebben ze bijna altijd nodig als ze  een dossier openen. 
dus "verslagen" svp vooraan ipv "dossier/informatie"

**Comment by jtborger** [comment]
2.3.8
