### ISSUE TITLE
Download van klantenlijst kunnen maken

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#113]
Zie commits bij ticket #105 voor een voorbeeld

**Comment by Evertt** [comment]
@barthuttinga deze kan volgens mij gesloten worden.

**Comment by barthuttinga** [comment]
@Evertt Met branch refactor/160-oek-bundle uitgecheckt krijg ik wel een foutmelding. Jij ook?

**Comment by Evertt** [comment]
Dat klopt, daar had jij issue #166 over gemaakt en die heb ik gefixt in een aparte branch en die heb jij gemerged met PR #174
