### ISSUE TITLE
tabs verwijderen onder trajecten

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1132]
onder trajecten staan nu tabs die hier eigenlijk niet (meer) horen:
als je in et traject van een klant zit mogen de tabs contactpersonen/verslagen/documenten verwijderd worden
https://ecd.deregenboog.org/dagbesteding/trajecten/1156/view?redirect=/dagbesteding/trajecten/

mocht daar info instaan graag verplaatsen naar dezelfde tabs in persoonlijk dossier:
https://ecd.deregenboog.org/dagbesteding/deelnemers/1101/view?redirect=/dagbesteding/trajecten/1156/view

**Comment by dvleeuwen** [comment]
ook "rapportages" weg bij trajecten ---> deelnemer

**Comment by jtborger** [comment]
werkdoelen mag ook naar deelnemersdossier

**Comment by jtborger** [comment]
Werkdoelen migreren naar verslagen deelnemers en daarna weghalen.
