### ISSUE TITLE
afgesloten VWdossiers zijn niet meer te vinden

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1133]
Sommige afgesloten IZ vw dossiers zijn niet meer terug te vinden onder IZ, wel in algemene bak vw, maar foutmelding als je hen opnieuw wilt aanmaken bij IZ

heeft misschien te maken met als ze geen hulpaanbod gehad hebben?

**Comment by jtborger** [comment]
Het enige dat ik vinden kan is dat er uitgesloten wordt op basis van afsluitreden 'foutieve invoer'. Zowel op dossier als op hulpvraag/aanbod niveau.
Kom er dus niet helemaal uit hoe nu verder. Kan het hier niet reproduceren los van bovenstaande. 
Wat ik heb gedaan is dat wanneer je nu een VW-er wilt toevoegen welke is afgesloten met foutieve invoer, je deze persoon wel vindt in de lijst met bestaande Vwers waarna je het dossier opnieuw kunt openen. 
2.3.8

**Comment by jtborger** [comment]
NB voor deelnemers idem dito.
