### ISSUE TITLE
medewerkers inlopen kunnen geen verslagen meer invoeren

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1134]
Hey Daan!

Raf hier.

Ik kan als dagco geen verslagen schrijven in het ECD. Het vakje opmerkingen is niet beschikbaar... wat maakt dat er waardevolle informatie voor de maatschappelijk werkers ontbreekt. Mijn collega dagco's kunnen dit ook niet.

ik hoor het !

-- 
Vriendelijke groet,

Rafael Hermans
Dagcoördinator inloophuis de Kloof

**Comment by jtborger** [comment]
2.3.8
