### ISSUE TITLE
trainingen toevoegen via beheer inloophuizen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1136]
Mogelijk maken om trainingen voor de vw'ers inloophuizen zelf te regelen/aanpassen via beheer.

+ zorgen dat Lieke en Josje toegang tot beheer inloophuizen hebben (vrijdag even over bellen)

**Comment by jtborger** [comment]
Even kijken naar rollen Josje en Lieke.

**Comment by jtborger** [comment]
mee met 2.3.13
