### ISSUE TITLE
de knoppen vrijwilligers en beheer weg halen voor vrijwilligers CLIP

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1138]
wat betreft CLIP rechten: gewone clippers zien nog wel beheer en vrijwilligers maar kunnen er niet op klikken.
clip beheer kan er wel bij.

zou jij daar een issue voor kunnen maken dan vergeet ik niet dat ik dat visuele aspect nog moet fixen.

thanks

**Comment by dvleeuwen** [comment]
Nu kunnen alle CLIPers bij de algemene vrijwilligerslijst, dit moet alleen toegankelijk zijn voor CLIP_Beheer

**Comment by jtborger** [comment]
gaat mee met 2.3.34
