### ISSUE TITLE
pop up na schorsing

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1145]
Ha ECD, ( Daan, Jan) 

Willemijn, Jeroen en ik hebben naar het schorsingsbeleid gekeken en realiseerde ons dat vaak het terugkomgesprek wat na een schorsing van twee weken met een bezoekers moet plaatsvinden niet gebeurd. 

Een pop-up in het ECD zou daar enorm mee helpen. Dus een pop-up bij iedereen die zich weer meldt na een schorsing van twee weken of langer met een herinnering voor een terugkomgesprek.  
Iets al: 

Schorsing verlopen. Terugkeergesprek nodig.   

Die popup moet natuurlijk weggeklikt kunnen worden. 

Dank ! 

(zie ook aanvullende mails) 
-de knop "gezien" bij schorsingen mag weg/aangepast worden

**Comment by dvleeuwen** [comment]
schorsing gezien vinkje verandert in "terugkomgesprek heeft plaatsgevonden".pop-up blijft verschijnen bij registratie, tot dit vinkje aan gevinkt is.

**Comment by jtborger** [comment]
2.3.7
