### ISSUE TITLE
nieuwe IZ rapportage: hulpvraagsoort x doelgroep per stadsdeel  

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1147]
nieuwe rapportage hulpvraagsoort x doelgroep per stadsdeel.

weergave van nieuw gemaakte koppelingen in de geselecteerde periode.

Wens: bruikbaar in augustus.

**Comment by jtborger** [comment]
per stadsdeel 1 tabel.

**Comment by dvleeuwen** [comment]
vervolgvraag:

naast de huidige tabellen is nu de wens om ook tabellen te laten zien van de beginstand. Dus zelfde format hulpvraagsoort x doelgroep per stadsdeel, maar naast nieuw gestart (zoals nu gemaakt is) extra tabellen met de data van beginstand per stadsdeel.

**Comment by jtborger** [comment]
Ik heb dee nu gemaakt, is gereleased 2.3.16
kijk maar of het zo klopt ik heb geen tijd gehad om de cijfers inhoudelijk na te lopen maar heb gebruik gemaakt van bestaande mechanismes voor nieuw en beginstand, waarvan ik uit ga dat ze kloppen.
