### ISSUE TITLE
aanpassing in Managementrapportage: "locatie zonder zorg" aantal MWcontacten

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1152]
Uit MGMT rapportage contacten met MW: locatie zonder zorg opsplitsten: mensen met >=5 contacten en mensen tm 4 contacten. Evt in andere nieuwe rapportage

**Comment by dvleeuwen** [comment]
Janneke geeft aan dat dit prio heeft

**Comment by jtborger** [comment]
2.3.32
