### ISSUE TITLE
rapportages MW

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1153]
Document Janneke MW rapportages bekijken en terugkoppelen zie mail 21 mei

**Comment by dvleeuwen** [comment]
Janneke kijkt wat er nog uptodate is

**Comment by dvleeuwen** [comment]
laatste update van Janneke (okt 2022) opnieuw gemaild --> Jan

**Comment by jtborger** [comment]
[220503 ECD-rapportage MW.docx](https://github.com/deregenboog/ecd/files/12104216/220503.ECD-rapportage.MW.docx)

**Comment by jtborger** [comment]
Deze is deels opgeleverd. Wacht nu op feedback

**Comment by jtborger** [comment]
Besproken met Tessa ea. 
Deze kan dicht.
