### ISSUE TITLE
Openingstijden inlopen niet meer invullen in ECD

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1161]
oude vraag Janneke:
Die openingsdagen hebben denk ik nut, omdat de gemiddelden per dag gerapporteerd worden. En dan moet je weten of je het aantal unieke bezoekers door 5 of door 7 moet delen. Liever zou ik het zo hebben dat het ECD zelf merkt als er geregistreerd is, en het aantal unieke bezoekers deelt door het aantal dagen dat er is geregistreerd. Dan heb je meteen ondervangen dat de gemiddelden zakken als het systeem een keer plat ligt. Wat denk je daarvan?

----
navragen bij Jan

**Comment by jtborger** [comment]
is opgelost met automatisch afsluiten
