### ISSUE TITLE
medewerker invulveld bij aanmaken nieuwe deelnemer IZ 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1174]
als je een nieuwe deelnemer aanmaakt bij IZ staat er nu 2x een veld "mederwerker" en een hier onlogisch veld "klant*" "maatschappelijk werker"

**Comment by barthuttinga** [comment]
@jtborger Deze sluit ik, want ik kan hem niet reproduceren. Je mag hem heropenen als er toch nog iets mee moet.

**Comment by dvleeuwen** [comment]
Ha Bart,
ik stuur Jan een screenshot, en heropen dit issue

**Comment by dvleeuwen** [comment]
screenshot in inbox Jan,
begeleidende tekst:

Ha Jan,
#1174 was door Bart gesloten op dat hij het niet kon reproduceren. Ik heb zijn mail niet, dus even via jou: svp bijlage
Hier wordt dus 2x om medewerker gevraagd, en 1x om maatschappelijke werker, wat niet thuishoort onder IZ lijkt me?
zou volgens mij 1x medewerker moeten zijn en niets met MW

**Comment by dvleeuwen** [comment]
![aanmaken iz klant](https://github.com/deregenboog/ecd/assets/45566999/f798eed5-70e0-43c1-9e91-f58aa15316d9)

ik zie nu dat ik hier ook bijlage kan uploaden
