### ISSUE TITLE
verdwenen vw'er bij IZ

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1176]
Bij deze vw'er is in meest recente koppeling de vrijwilliger "verdwenen", waardoor geen verslagen meer kunnen worden toegevoegd of bekeken.
https://ecd.deregenboog.org/iz/klanten/11092/view?redirect=/iz/klanten/#koppelingen

Het gaat om deze vw'er, nog te vinden in algemene bak, niet binnen IZ.
https://ecd.deregenboog.org/vrijwilligers/?vrijwilliger_filter%5Bfilter%5D=&vrijwilliger_filter%5Bid%5D=&vrijwilliger_filter%5Bnaam%5D=coxon&vrijwilliger_filter%5Bgeslacht%5D=&vrijwilliger_filter%5Bgeboortedatum%5D=&vrijwilliger_filter%5Bmedewerker%5D=&vrijwilliger_filter%5Bstadsdeel%5D=&vrijwilliger_filter%5Bpostcodegebied%5D=#koppelingen

**Comment by jtborger** [comment]
Opgelost
Er zitten in heel ECD her en der afsluitredenen. Foutieve invoer is een bijzondere variant, want die heeft standaard als 'feature' dat iets dat zo wordt afgesloten, wordt uitgesloten van verdere weergave.
Dus eenmaal foutief, is moeilijk weer terug te vinden.
Ik heb de betreffende vrijwilliger weer geopend.
