### ISSUE TITLE
rapportages tijdelijk wonen niet meer beschikbaar

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1177]
Er valt geen rapport te selecteren

**Comment by jtborger** [comment]
2.3.30

**Comment by dvleeuwen** [comment]
Koppelingen werken helaas nog steeds niet in de rapportage:
https://ecd.deregenboog.org/tw/rapportages/?rapportage%5Bstartdatum%5D=01-01-2021&rapportage%5Beinddatum%5D=30-11-2021&rapportage%5Brapport%5D=TwBundle%5CReport%5CKoppelingen&rapportage%5Bshow%5D=

Ik heropen Github

groet!
Daan

Op do 18 nov. 2021 om 16:19 schreef JT Borger ***@***.***>:

**Comment by dvleeuwen** [comment]
Juul meldt:

Koppelingen werken helaas nog steeds niet in rapportage:

https://ecd.deregenboog.org/tw/rapportages/?rapportage%5Bstartdatum%5D=01-01-2021&rapportage%5Beinddatum%5D=30-11-2021&rapportage%5Brapport%5D=TwBundle%5CReport%5CKoppelingen&rapportage%5Bshow%5D=

**Comment by jtborger** [comment]
Met excuses, blijkbaar dubbel iets over het hoofd gezien
Nu werkt ie echt ;)
