### ISSUE TITLE
ontdubbelen in MW rapportages

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1178]
Hoi Daan,

Met de rapportage van het AMW (onder Maatschappelijk Werk/rapportages) is hetzelfde loos als laatst met die van het economisch daklozen team: hij ontdubbelt het totaal aantal cliënten niet. Zou jij aan Jan willen vragen of hij dit euvel snel kan verhelpen? Het is bijna tijd voor de jaarcijfers.

Dank alvast!
Met vriendelijke groet,

Janneke van Loo, manager Inloophuizen & Hulpverlening

Tel: 020-5317600 / 06-52482869

**Comment by jtborger** [comment]
opgelost 2.3.31
