### ISSUE TITLE
Rapportage 'agressie incidenten per locatie'

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1182]
Inloop

**Comment by jtborger** [comment]
Wordt later opgepakt, kijken er eens tnog even naar. (Zie mail 4-1)

**Comment by dvleeuwen** [comment]
Els:
Wat betreft de incidentenrapportage: daar zijn Janneke en ik ook nog niet niet aan toegekomen. Wordt begin januari en dan maken we even een duidelijk overzicht van wensen en ideeën, is dat ok? Dan kan Jan zn werk denk ik het beste even wachten tot we weten wat we precies willen.

**Comment by dvleeuwen** [comment]
Bij het veld schorsing toevoegen:
3 nieuwe vinkboxjes:
-politie gebeld
-ambulance gebeld
-crisisdienst gebeld

Tevens naam automatisch invullen als medewerker wie ingelogd is bij het aanmaken van nieuwe schorsing. 

+ een nieuwe tab naast schorsingen: "incidenten"
met daarin ook naam mederweker, open veld toelichting
en de 3 vinkjes: 
-politie gebeld
-ambulance gebeld
-crisisdienst gebeld

Er moet uiteindelijk uitgedraaid kunnen worden op bovenstaande vinkjes (schorsing + incidenten)

Overleg deze week met Jan of bovenstaande duidelijk/logisch is.

**Comment by jtborger** [comment]
zo maken dat bij invoeren schorsing de nieuwe boxjes erbij bouwen maar zo dat het als incident wordt opgeslagen.

**Comment by dvleeuwen** [comment]
gedaan!

**Comment by dvleeuwen** [comment]
aanvullend verzoek Janneke en Anniek:
incidenten moet er voor alle afdelingen komen, net zoals bij inlopen (dus gekoppeld aan deelnemers dossier)

Verzoek om dan een management rapportage te maken met overzicht vd verschillende afdelingen

Rapportage onder inloophuizen mag blijven bestaan, zodat op die wijze de verschillende locatie bekeken kunnen worden

Wel belangrijk: moet ook nog uit rapportage duidelijk worden hoeveel incidenten het in totaal zijn. 
(1 incident kan natuurlijk politie+crisisdienst+ambulance hebben, of geen van allen) Nu zie je in rapport enkel die cijfers terug, maar niet aantal unieke rapportages

heel graag klaar in september

**Comment by dvleeuwen** [comment]
Ha,
wij bespraken eerder het verzoek om in alle modules een incidentenregistratie te bouwen. De wens was om dit in september klaar te hebben.
Jan geeft aan dat dit helaas niet gaat lukken. 
Mijn vraag aan jullie: hoe erg is dat? Was september een harde eis van gemeente? Gaan er dingen echt mis als dit in september klaar is?

groet!
Daan

**Comment by dvleeuwen** [comment]
Janneke mondeling:
voor nu is het goed, Iso is tevreden, nadruk ligt op inlopen. Sluit issue voor nu.
