### ISSUE TITLE
foute data bij opmerkingen 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1187]
Van: Jessica Hoogenboom

Hoi Daan,

Er is iets raars aan de hand met de data van de opmerkingen in het ECD.
Zo staat er een opmerking bij  https://ecd.deregenboog.org/inloop/klanten/5628083/view?redirect=/inloop/klanten/#opmerkingen
d.d. 27-12-2021 (vandaag dus) die ik een paar weken geleden heb geplaatst (op 14-10-2021). Ook de opmerkingen eronder zijn duidelijk ouder (maar staan nu ook op 27-12-2021). Best belangrijk, want het gaat om zijn toegang tot de inloophuizen.
Ook bij https://ecd.deregenboog.org/inloop/klanten/5631487/view?redirect=/inloop/klanten/#opmerkingenzie ik een opmerking van Katarzyna  d.d. 27-12-2021 (vandaag) die niet klopt; die opmerking is ook ergens in oktober geplaatst. De bovenste opmerking van vandaag ('nav causistiek heeft per 1 dec toegang tot inloophuizen') klopt wel, die hebben we er vandaag ingezet (om verwarring te voorkomen).  
Zou jij kunnen kijken wat hier mis gaat? En of de juiste data teruggezet kunnen worden?

Groet & dank!

Jessica Hoogenboom
Locatiehoofd Inloophuis De Kloof

Update:
ook als je vandaag (4-1-2022) kijkt naar deze opmerkingen krijgen opmerkingen van afgelopen dagen allen de datum van vandaag

**Comment by jtborger** [comment]
Blijkbaar werd de 'datum gewijzigd' getoond in plaats van 'datum aangemaakt'. Dit heb ik aangepast.
2.3.35
