### ISSUE TITLE
kleurcode 3 maanden geen verslag

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1188]
Is het mogelijk dat dossiers een kleurtje krijgen als er langer dan drie maanden geleden geen contactmoment is aangemaakt? Dat zou erg handig zijn.

Hoor wel of dit lukt,
--
Met vriendelijke groet,

Evelien Mol

=3 maanden geleden laatste verslag toegevoegd

**Comment by jtborger** [comment]
Gaat mee met 2.3.36
