### ISSUE TITLE
overzetten locaties verslagen MW

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1207]
Robin heeft zelf nieuwe locaties aangemaakt.
er moeten nu oude verslagen omgezet worden, verzoek aan Jan:

Hoi Daan bij deze de locaties gekoppeld aan de medewerkers. Van deze medewerkers kunnen alle verslagen per 01-01-2022 naar de STED Stadsdeel locatie.

Naam		Locatie
Alyssia Theijs	STED West
Daya Elzenga	STED Centrum
Evelien Mol	STED Nieuw-West (behalve die staan op STED NWI)
Gisella Stacie	STED Nieuw-West (behalve die staan op STED NWI)
Grégoire Asmus	STED West
Gulsen Sahin	STED Zuid-Oost (behalve die staan op STED NWI)
Henny Tichelaar	STED Amstelland
Khadija Addi	STED Zuid
Madelon de Jong	STED Zuid-Oost
Maria Hashem	STED Nieuw-West (behalve die staan op STED NWI)
Nick Coenen	STED Zuid-Oost
Sander Sebti	STED Nieuw-West
Sharon Cohen	STED Amstelland
Sigria Boersma	STED Amstelland
Tessa Zaaijer	STED Oost
Yemi Schneider	STED Noord

In de rapportage voor economisch daklozen zouden de volgende locaties terug moeten komen:
STED Amstelland
STED Centrum
STED Noord
STED Oost
STED Zuid-Oost
STED Zuid
STED West
STED Nieuw West
STED NWI

**Comment by jtborger** [comment]
done
