### ISSUE TITLE
Oekranie opvang

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1223]
Nieuwe TAB onder Inloophuizen:
"Oekraïne"
met daaronder TAB "registratie" en "klanten"

Wens is dat klanten van Oekraine in een andere bak komen dan klanten inloophuizen, moeten dus niet zichtbaar zijn in lijst/registratie inloop. 

Intake vergelijkbaar met intake klanten inloophuizen, paar wijzigingen:
-"intakelocatie" vervangen door "woonlocatie"
-veld toevoegen "kamernummer"
-Inkomen: -loon - leefgeld -overig
-Bij verwachtingen: "verwachting dienstenaabod" verwijderen, "toekomstplan" geen verplicht veld meer
-Ondersteuning: 1. ongewijzigd 2. vervangen door: "wil je hulp bij het zoeken naar werken" 3. verwijderen 4.ongewijzigd
GEEN mails meer sturen naar afdelingen achter de schermen hierbij

verwijderen uit intake: "toegang inloophuis", "verslaving", "woonsituatie", "doelgroep" "ZRM" "medeweker" (onder ZRM)

In klantenlijst:
kolom toevoegen kamernummer, 
downloadfunctie

Mogelijkheid om dossier te sluiten, met volgende redenen:
-terugkeer Oekraine
-gastgezin
-zelfstandige woning
-vetrokken zonder bericht
-overige

Wel verslagen mogelijkheid, geen "opmerkingen" veld

Rapportagemogelijkheid
hoeveel bewoners per locatie
hoeveel uitstroom
m/v

**Comment by jtborger** [comment]
Eerste release gehad. Nieuwe punten in nieuwe issues en van daaruit verder.

**Comment by dvleeuwen** [comment]
Werkt helaas toch nog niet, wel als je iets intypt wat hij herkent, dan kun je op volged scherm + voeg nieuwe bezoeker toe kiezen. Maar als je iets intypt wat hij niet herkent blijf je in het eerste scherm hangen

**Comment by jtborger** [comment]
Sorry. Slordigheid, te snel geweest gister. - hou me ten goede maar volgens mij is het nu wel echt opgelost ;)
