### ISSUE TITLE
foutmelding bij inactief maken vwdossier HS

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1224]
Ha Daan,
Als ik een vrijwilliger op inactief wil zetten in ECD Homeservice krijg ik een foutmelding.
-
Ai dat is vreemd, en vervelend.
In het screenshot lijkt het dat het probleem in het datumveld vd uitschrijving te zitten, maar ook als dat gewoon ingevuld is en je op opslaan drukt gaat het alsnog mis begrijp ik?
-
Ja klopt, ik kan datum gewoon invullen. Ook wat verschillende data in verleden geprobeerd maar hij blijft de foutmelding geven.

**Comment by jtborger** [comment]
Gaat mee met 2.4.1
