### ISSUE TITLE
laatste bezoek langer dan half jaar geleden: uit registratielijst

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1225]
Als een bezoeker zich bij registratie meldt en laatste bezoek is meer dan 6maanden geleden: uit registratielijst, naar klantenlijst. Eerst nieuwe intake voor weer welkom.

correspondentie:
Maar je wilt wel een pop up bij registratie?
Iets van: "let op half jaar niet geweest, nieuwe intake nodig voor toegang"
Als we de persoon werkelijk uit de registratielijst halen vermoed ik veel gedoe en onduidelijkheid bij de portier aan de deur? Want dan is ie niet terug te vinden, een popup lijkt me dan het meest werkbaar?
mee eens, of zie jij het anders?
groet!
Daan

Ha Daan, 
Hij moet er juist uit. 
Pop ups worden vaak niet gelezen.  Dus alleen als iemand een half jaar helemaal niet geweest is. 
Groetjes !

**Comment by jtborger** [comment]
is opgelost met #1504
