### ISSUE TITLE
fout met cijfers Homeservice?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1231]
Dag Daan,

Vraagje, ik heb voor de Homeservice halfjaar evaluatie cijfers gedraaid in ECD, zie printscreen. Volgens mij geeft ECD te weinig mensen weer en pakt hij alleen de op dit moment actieve dienstverleners en vrijwilligers. Ik mis de mensen in de eerste 6 maand die weer gestopt zijn en niet meer op actief staan.  

Sander

**Comment by jtborger** [comment]
Voor zover ik zien kan neemt hij alleen dienstverleners en vrijwilligers mee die uren geregistreerd hebben in de rapportageperiode.

Voor zover ik zien kan wordt er verder niet gefilterd. Maar ik kan me vergissen. Wat heel handig is bij dit soort meldingen: Hoeveel zouden het er moeten zijn, bv. zichtbaar op een overzicht met bepaalde filterinstellingen, en hoeveel komen er uit de rapportage. Dan kan ik beter en gerichter zoeken. Want nu is het een gevoel en dat is voor mij lastig te controleren, zeker hier in mijn development database met oude en incomplete data...
:)

**Comment by dvleeuwen** [comment]
14 juli
Ha Sander,
zie hieronder reactie van Jan.
Heb jij wat aanvullende info, zodat hij gerichter kan kijken naar dit issue?

dank
Daan

[@Jan Borger](mailto:jborger@deregenboog.org) 
voor volledigheid hierbij nog in bijlage het oorspronkelijke screenshot vd melding

27juli
Ha Sander,
ik zag nog geen antwoord op onderstaande. Kun jij hier nog wat extra info bij geven, of hoeven we er verder niets mee?

dank & groet
Daan

**Comment by dvleeuwen** [comment]
geen reactie op bovenstaande, sluiten af voor nu
