### ISSUE TITLE
niet mogelijke bezoeker in te voeren onder Oekraine

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1234]
Niet mogelijke nieuwe bezoeker in te voeren, komt steeds weer terug in het scherm waar hij zoekt of iemand al bekend is in ecd

--
Het lukt mij nog steeds niet om een nieuwe bezoeker toe te voegen. 
Als ik op een geboortedatum zoek dan vindt ie wel bezoekers. Terwijl er nog geen mensen zijn toegevoegd. Maar als ik dan een nieuwe wil toevoegen omdat dit niet degene is die ik zoek is er geen mogelijkheid?! 
Als ik dan TEST OEKRAÏNE wil invoeren zegt ie deze zoekopdracht levert geen resultaten op. en dan weer maak nieuwe bezoeker aan.
Kortom :) ik ga in rondjes.

Kunnen jullie helpen?! 
Bianca

**Comment by jtborger** [comment]
Opgelost in 2.4.3a
Sorry dat dit niet meteen werkte.
