### ISSUE TITLE
aanpassingen verslag toevoegen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1236]
"Contactsoort" mag er helemaal uit,
hiervoor in de plaats: aantal contactmomenten 

Nog afstemmen waar we dit aantal contactmomenten terug zien: ipv aantal verslagen in rapportage? Met Janneke en Yahya overleggen
(opvallend in overzicht staat bij iedereen bij aantalverslagen 1, deze kolom kan weg uit beginscherm)

**Comment by dvleeuwen** [comment]
"contactduur" mag ook weg

**Comment by jtborger** [comment]
oude data bewaren. rapportages checken.
