### ISSUE TITLE
toekenning project binnen MW

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1237]
Op basis van medewerker, toekennen aan een bepaald project binnen MW

Annie/Yahya leveren lijst aan met namen medewerkers + projecten.
Het moet een handmatig aanpasbaar veld zijn.
Als iemand overstapt naar ander project/maatschappelijkwerker: afsluiten en heropenen? 
Geschiedenis moet terug te vinden zijn onder "dossierinformatie" (dus datum aanmelding/afsluiting en welk project)

**Comment by barthuttinga** [comment]
Project <=> Medewerker = many-to-many
Bij aanmelden moet project gekozen worden.

**Comment by barthuttinga** [comment]
@jtborger PR voor dit ticket staat klaar
