### ISSUE TITLE
TBC melding van inkoopklanten bij IZ?

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1242]
Nagaan of je in IZ / deelnemer bekijken inderdaad een TBC check popup krijgt zoals Daan had bij een deelnemer.

**Comment by dvleeuwen** [comment]
dit blijkt te gebeuren zodra je iets in basisgevens van deze persoon wijzigt.

**Comment by barthuttinga** [comment]
@jtborger @dvleeuwen Deze lijkt me niet meer relevant, aangezien alle mbt TBC eruit mag (#1697). Ik sluit dit issue.
