### ISSUE TITLE
foutmelding bij wijzigen intake

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1245]
ik heb even ingelogd als Olga, en het blijkt inderdaad: zodra zij een intake wil wijzigen komt ze op foutmeldingspagina. Zit iets mis met rechten dus denk ik, want als ik zelf ingelogd ben werkt het wel.
Kun jij uitvinden wat hier aangepast moet worden zodat Olga en collega's ook intakes kunnen aanpassen?

**Comment by jtborger** [comment]
Overgenomen vanuit Inloop. Daar is de regel dat je alleen eigen intakes mag wijzigen. Tevens mogen intakes niet ouder dan een week zijn. Deze regels er uitgehaald voor Oekraïne.
gaat mee met 2.4.4.
