### ISSUE TITLE
mogelijk maken van delen verslagen tussen tijdelijk wonen en MW

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1248]
Op vergelijkbare wijze als nu tussen MW en inloophuizen is: keuze met welke afdeling verslagen gedeeld worden

**Comment by jtborger** [comment]
Het zou fijn zijn als we hier al over kunnen nadenken woensdag.

**Comment by dvleeuwen** [comment]
alles van TW zichtbaar voor MW
MW optie geven tot delen verslag met TW (zelfde als met inloop)
