### ISSUE TITLE
Onder "dossierinformatie" info mbt repatriëring 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1249]
Toevoegen onder kopje dossierinformatie:
datum repatriëring
kosten repatriëring 

mensen kunnen meerdere keren gerepatrieerd worden, dus meerdere keren registreren moet mogelijk zijn

**Comment by dvleeuwen** [comment]
extra vinkje "zachte landing"
terug te zien in rapportage repatriering

**Comment by jtborger** [comment]
deze 'afsluit gegevens' moeten wel zichtbaar zijn ook al is het dossier afgesloten
