### ISSUE TITLE
vinkje voor gezinnen bij MW

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1250]
verzoek Annie, vinkje voor gezinnen (vergelijkbaar als bij IZ, bij intake)
nu vullen ze steeds in bij de naam, wat vervuiling van dat veld is
moet ook mogelijk zijn op gezinnen te filteren (is bij IZ niet het geval volgens mij?)

**Comment by jtborger** [comment]
zie #1168
