### ISSUE TITLE
als je op dezevw'er klikt: deze pagina werkt niet

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1251]
https://ecd.deregenboog.org/iz/vrijwilligers/?iz_vrijwilliger_filter%5Bfilter%5D=&iz_vrijwilliger_filter%5Bvrijwilliger%5D%5Bid%5D=&iz_vrijwilliger_filter%5Bvrijwilliger%5D%5Bvoornaam%5D=sally&iz_vrijwilliger_filter%5Bvrijwilliger%5D%5Bachternaam%5D=&iz_vrijwilliger_filter%5Bvrijwilliger%5D%5BgeboortedatumRange%5D%5Bstart%5D=&iz_vrijwilliger_filter%5Bvrijwilliger%5D%5BgeboortedatumRange%5D%5Bend%5D=&iz_vrijwilliger_filter%5BaanmeldingMedewerker%5D=&iz_vrijwilliger_filter%5BintakeMedewerker%5D=&iz_vrijwilliger_filter%5Bactief%5D=nu&iz_vrijwilliger_filter%5Bproject%5D=&iz_vrijwilliger_filter%5BhulpaanbodMedewerker%5D=&iz_vrijwilliger_filter%5Bhulpvraagsoort%5D=&iz_vrijwilliger_filter%5Bdoelgroep%5D=&iz_vrijwilliger_filter%5Bvrijwilliger%5D%5Bstadsdeel%5D=&iz_vrijwilliger_filter%5BafsluitDatum%5D%5Bstart%5D=&iz_vrijwilliger_filter%5BafsluitDatum%5D%5Bend%5D=

**Comment by jtborger** [comment]
Was afgesloten met als afsluitreden 'foutieve invoer' welke wordt uitgesloten van de query.
dat moet niet mogen.
ga nieuw issue aanmaken.
