### ISSUE TITLE
hoe krijgen we Mileen in rijtjes mederwerkers

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1254]
We willen hier in veld linksboven "medewerker" Mileen van maken, maar ze kan niet geselecteerd worden, terwijl ze toegevoegd is als trajectcoach bij beheer?
https://ecd.deregenboog.org/dagbesteding/deelnemers/968/view#trajecten

Mogelijk sowieso kijken naar de verschillende termen, mensen hebben nu 2x veld "medewerker" met verschillende naam, moet bovenste niet trajectcoach worden?

**Comment by jtborger** [comment]
Het is nu zo dat trajectcoaches die zonder medewerkerkoppeling worden ingevoerd, enkel met naam, niet werken.
Navragen bij bas, zo nodig oplossen. Mileen is opgelost.
