### ISSUE TITLE
Overzicht koppelingen: kolom reserveringen eruit, kolom aanmelddatum klant.

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1260]

**Comment by jtborger** [comment]
Ik heb nu ook het vinkje om reserveringen ook te laten zien eruit gehaald. Standaard worden reserveringen niet getoond.
Moet dat vinkje er weer bij of kan dat eruit blijven?

**Comment by jtborger** [comment]
2.4.6

**Comment by dvleeuwen** [comment]
> Ik heb nu ook het vinkje om reserveringen ook te laten zien eruit gehaald. Standaard worden reserveringen niet getoond. Moet dat vinkje er weer bij of kan dat eruit blijven?

ja mag eruit blijven lijkt me, (tenzij we ander bericht krijgen)
