### ISSUE TITLE
TrajectcoachSelectFilter houdt geen rekening met actief

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1262]

**Comment by barthuttinga** [comment]
Gaat om het toevoegen van een nieuw traject aan een deelnemer: daar moet het niet mogelijk zijn een inactieve trajectcoach te selecteren.

**Comment by barthuttinga** [comment]
Gerelateerde punten:
- dagbesteding => beheer => trajectcoaches: sorteren kolommen werkt niet
- dagbesteding => beheer => trajectcoaches: verwijderen werkt niet

**Comment by jtborger** [comment]
2.5.1
