### ISSUE TITLE
toevoegen in basisgegevens: voorkeurstaal en overige talen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1263]
toevoegen in basisgegevens: voorkeurstaal en overige talen

**Comment by dvleeuwen** [comment]
terugkoppeling: verzoek van Yahya en Annie

**Comment by dvleeuwen** [comment]
Ik denk dat open veld voldoende is, zou m niet koppelen aan nationaliteit

groet!
Daan

Op ma 12 dec. 2022 om 22:40 schreef JT Borger ***@***.***>:

**Comment by jtborger** [comment]
nee ik bedoel niet het te koppelen aan nationaliteit,
maar meer dat je een select menu krijgt waar je de taal kiest, ipv een
tekstveld waar je alles in kunt voeren.

stel dat je ooit wilt selecteren op spaans sprekende mensen, ik zeg maar
wat, dan is dat met een open veld niet handig, snap je?
(dan krijg je Spaans, spaanse, spans met een tikfout, en alle drie bedoelen
ze spaans ;))


Op di 13 dec. 2022 om 16:03 schreef dvleeuwen ***@***.***>:

**Comment by jtborger** [comment]
toch het verzoek te koppelen aan een lijst. heb in #1312 talen tabel toegevoegd. daarbij ook een kolom 'favoriet' toegevoegd. als het mogelijk i zou het fijn zijn om de TalenSelectFilterType zo te maken dat ie een groepering maakt (visueel dus) op basis van favoriet en dan op alfabet.

**Comment by jtborger** [comment]
NB ik weet niet wat de status is van het PR dat je hiervoor had ingediend maar die ik toen gereset heb...

**Comment by dvleeuwen** [comment]
was dit een vraag aan mij of aan Bart?
Ik snap m niet in elk geval ;)

Op wo 14 dec. 2022 om 14:32 schreef JT Borger ***@***.***>:
