### ISSUE TITLE
afsluitreden dossier Oekraine

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1289]
Als je een dossier wilt sluiten moet er een reden gekozen worden (verplicht veld) maar er zijn geen reden in te vullen

Kan hier of een beheer functie voor gemaakt worden, zodat medewerkers zelf rijtje reden kunnen invullen
of
dit rijtje ingevoegd worden:
- verhuisd naar zelfstandige woning
- verhuisd naar een andere opvang (niet van DRG)
- Verhuisd buiten nederland
- Terug naar land van herkomst
- overleden

**Comment by jtborger** [comment]
staat live in 2.5.1

**Comment by jtborger** [comment]
Heb bovenstaande redenen toegevoegd. Als dit zelfstandig gewijzigd moet kunnen worden, wil je dan een nieuw issue aanmaken met dit verzoek? tnx.
