### ISSUE TITLE
Overzicht klanten aanpassen (MW)

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1305]
Het overzicht en de query is nu nog gebaseerd op het mengelmoesje vanuit de historisch gegroeide samenhang met inloop klanten.
Dat mag eruit. Inmiddels zijn alle MW klanten ook MW klant dwz die hebben een dossier.
Het vinkje 'alleen zoeken in maatschappelijk werk' (links) mag er dan ook uit.

In het nieuwe overzicht mag de kolom 'aantal verslagen' eruit. en nieuwe kolom mag erbij als #1238 af is: Dat is 'Intake' en daarin, net als bij inloop, 'nieuwe intake nodig over 1 maand' in oranje, en in rood: intake verlopen, net als intake.
en evt in het groen de intake datum

en dan rechts een kolom met als actie: verslag toevoegen, zodat je rechtstreeks een verslag toevoegt voor die klant.

**Comment by barthuttinga** [comment]
> Het vinkje 'alleen zoeken in maatschappelijk werk' (links) mag er dan ook uit.
@jtborger Waar staat dat vinkje?

**Comment by barthuttinga** [comment]
@jtborger Is dit issue nog relevant?

**Comment by jtborger** [comment]
Nee, ik sluit hem.
