### ISSUE TITLE
management rapportage sneller maken

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1319]
Nakijken of management rapportage sneller gemaakt kan worden of opgeknipt.

**Comment by jtborger** [comment]
ik zou dit moloch graag willen opknippen in overzichtelijkere stukken en deze wellicht implementeren in de afdelingen Inloop en MW want daar gaat het feitelijk over.

Kijken hoe dat gedaan kan worden. Het duurt nu met prod data enkele minuten en dat is niet te doen.

**Comment by jtborger** [comment]
Met de juiste indexen is het van zo'n 8 minuten naar +/- 30 seconden gegaan.
Maar toch.

Volgende punten:
- verschillen in getallen afzonderlijk en de optelling, zie onder.
- MW en inloop scheiden
- MW locaties en inloop locaties maken
- Tmp tabellen anders inrichten/maken/mee werken/bekijken/herzien
- Views bekijken en herzien
- Purge van registraties tabel? hoe en wat

> Opmerkingen Hans:
> Ik zou nog even terugkomen op de optelling mannen uniek en vrouwen uniek en dan getal totaal uniek. Het verschil blijkt er al jaren in te zitten. Dus als je vrouwen uniek en mannen uniek bij elkaar optelt kom je net net aan het cijfer totaal uniek wat in de tabel van de management rapportage ernaast staat. Het zou kunnen zitten in afrondingsverschillen, omdat ie natuurlijk over heel veel cijfers een gemiddelde neemt.
> Maar na enig speurwerk kom ik op het volgende, ik geef hieronder even weer wat het verschil is als je mannen uniek en vrouwen uniek optelt. Het getal wat er per jaar staat is wat je tekort komt t.o.v. het totaal uniek;
> 
> 2011       -20
> 2012       -12
> 2013       -6
> 2019        -46
> 2020        -27
> 2021       - 24
> 2022       -26

**Comment by dvleeuwen** [comment]
opgelost
