### ISSUE TITLE
Maatschappelijkwerk rol binnen Oekraïne module voor verslagen

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1340]
Bepaalde verslagen moeten worden afgeschermd en alleen toegankelijk voor specifieke rol.

**Comment by jtborger** [comment]
Foutje bedankt verkeerd genoemd in PR en merge... Moet nog.

**Comment by jtborger** [comment]
Bij inloop en MW zijn verslagen gedeeld. Maar MW-ers kunnen verslagen maken die door Inloop niet gelezen kunnen worden. Zoiets moet hier ook gebeuren.
Er moet daarvoor een nieuwe rol komen: 'ECD Oekraine Maatschappelijk werk' die is al aangevraagd bij PCI.
De gebruikers in die groep moeten mogelijkheid hebben om verslagen alleen voor zichzelf inzichtelijk te maken, de anderen niet. En zij mogen dan dus ook alleen die verslagen lezen.

**Comment by dvleeuwen** [comment]
Jan even bellen voor overleg.
Rol MW_oek zou enkel voor de psychologen moeten zijn (liza en alina), anderen lijken m nu ook te hebben (irina bv) 
misschien hernoemen naar psychologen bij verslaglegging, nu onduidelijk
