### ISSUE TITLE
Loggable inzichtelijk maken.

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1359]
Gebruik maken van loggable als audiolog voor admins en/of managers om te kunnen zien wie wat wanneer gedaan heeft, met de duidelijk notie van de beperkingen (collections).
Liefst asynchroon per entiteit als een abstracte functie ergens injecteren als een entity loggable is.. of zoiets

**Comment by barthuttinga** [comment]
@jtborger Heb deze gedaan, nu als voorbeeld te zien bij inloopvrijwilliger-dossier en -memo. We moeten even kijken voor welke gebruikers en welke entiteiten dit relavant is, dan kunnen we daar de links gaan toevoegen.
