### ISSUE TITLE
Verwijzingen (door/naar) moeten veld "actief" krijgen.

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#136]
Hier /oek_verwijzingen_door/edit/73 moet actief in- of uitgeschakeld kunnen worden. Bij inschrijven/uitschrijven van een klant moeten alleen actieve verwijzingen als optie worden getoond.

**Comment by Evertt** [comment]
@barthuttinga deze kan volgens mij gesloten worden.
