### ISSUE TITLE
PFO-clienten koppelen werkt niet

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#1375]
Dit komt doordat koppeltabel `pfo_clienten_supportgroups` twee kolommen (`created`, `modified`) heeft die niet `null` mogen zijn.

Oplossing:
1. die twee kolommen verwijderen; of
2. many-to-many wijzigen met tussenliggende entiteit

**Comment by jtborger** [comment]
Ik denk dat ze ten onrechte ooit timestampable zijn gemaakt, waarschijnlijk door mij in het kader van het dichtzetten van ECD wat ik op basis van de aanwezigheid van de velden created modified doe in de heuristiek. maar op een m2m heeft dat weinig zin. Ik haal ze weg.

**Comment by jtborger** [comment]
nee dit gaat interfereren met het #1363 . ik laat deze open staan en denk dat ie daarmee is opgelost.
duplicate of #1363 ?

**Comment by barthuttinga** [comment]
@jtborger In mijn dev-db heeft `pfo_clienten_supportgroups` geen timestamps meer, dus ik denk dat dit al opgelost is. Kan jij bevestigen dat dit in de prod-db ook zo is?

**Comment by jtborger** [comment]
In prod ook niet idd.
