### ISSUE TITLE
foutmelding bij openen klantdossier

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1376]
Zodra je onderstaande klant aanklikt in bezoekerslijst krijg je foutmeldingspagina

https://ecd.deregenboog.org/oekraine/bezoekers/?bezoeker_filter%5BappKlant%5D%5Bid%5D=&bezoeker_filter%5BappKlant%5D%5Bvoornaam%5D=&bezoeker_filter%5BappKlant%5D%5Bachternaam%5D=Allisen&bezoeker_filter%5BappKlant%5D%5BgeboortedatumRange%5D%5Bstart%5D=&bezoeker_filter%5BappKlant%5D%5BgeboortedatumRange%5D%5Bend%5D=&bezoeker_filter%5Bwoonlocatie%5D=&bezoeker_filter%5BhuidigeStatus%5D=&bezoeker_filter%5Bfilter%5D=&bezoeker_filter%5B_token%5D=Ls5DaN6MUYhuSX5wQ_zpoPse-uRVmvS6DZ8U7yy3QKE

via Chloe/Belinniboat

**Comment by jtborger** [comment]
Dit kwam doordat deze persoon een partner had welke verwijderd is. Daardoor gaf hij een foutmelding.
