### ISSUE TITLE
Template Fallback mechanisme gaat soms fout

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1397]
Als bv een pad niet bestaat geeft hij een exceptie. Die is nu ondervangen in _getPath van EcdRoutingExtension, maar ergens zou dat misschien anders moeten? Tevens zijn er templates waarbij bv entity_name niet beschikbaar is.
Add en Edit zien er dan raar uit. Is er een heuristiek mogelijk om die dan alsnog te verkrijgen? Of moet er in een controller iets aangepast worden zodat entity_name alsnog geset wordt?

(Zie bv TW huuraanbod toevoegen).

**Comment by barthuttinga** [comment]
@jtborger

> Als bv een pad niet bestaat geeft hij een exceptie. Die is nu ondervangen in _getPath van EcdRoutingExtension, maar ergens zou dat misschien anders moeten?

Heb je een voorbeeld van een link die niet werkt? Wat is je voorstel voor hoe het anders moet?

> Tevens zijn er templates waarbij bv entity_name niet beschikbaar is. Add en Edit zien er dan raar uit. Is er een heuristiek mogelijk om die dan alsnog te verkrijgen? Of moet er in een controller iets aangepast worden zodat entity_name alsnog geset wordt?

In de huidige structuur zijn er twee opties: (1) oude template herstellen met hard-coded entity name, of (2) entity_name in controller toevoegen. We kunnen de templates ook strict maken; gebruik van een niet gedefinieerde var resulteert dan in een exception.

**Comment by jtborger** [comment]
@barthuttinga Het ging bv. fout bij aanmaken huuraanbod (TW-->Verhuurder-->aanmaken huuraanbod).
Omdat ik in twig geen exceptie kan afvangen en er geen hasPath() bestaat heb ik nu _getPath() zo gemaakt dat hij de test doet en de exceptie afvangt en dan false retourneert.
Op zich is dat wel misschien voldoende.

oude template herstellen kan natuurlijk maar dan doen we een deel van het werk teniet. Zonde. En ik weet niet bij welke templates het allemaal optreedt, want ik heb er wel een heel stel getest door te klikken maar niet stelselmatig (test coverage...)

strict templates weet ik niet zo goed. dat komt er alleen runtime uit he? dus lastig testen/debuggen ...

**Comment by barthuttinga** [comment]
@jtborger Ik begrijp niet waarom je deze exception zou willen afvangen: https://github.com/deregenboog/ecd/commit/2a9099ae88b29afcef15c0bdfb3c92007acb95f8#diff-0e2a40a9834ee54add81c3a58bfdc4a705ae51d8999b41b6103fffbb075b3fe0R72-R79. Misschien even overleggen?

**Comment by jtborger** [comment]
Ja dat kan ook. Er heeft ooit in een vorige SF versie een hasRoute in
gezeten maar die is er weer uitgehaald. Ik weet de redenatie niet meer maar
ik dacht iets met dat het eigenlijk controller logic zou moeten zijn (...).
Ik dacht in het kader daarvan: dan ga ik het niet terugbouwen...vandaar dat
ik het zo had opgelost (plus dat het een patch was die ik snel wilde
oplossen). Maar dit lijkt me de mooiste oplossing voor nu.

**Comment by jtborger** [comment]
opgelost in 2.5.8
