### ISSUE TITLE
inloop / Oekraïne bezoekers registratie : bij aanklikken klant geen duidelijke feedback dat klant is ingecheckt.

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1398]

**Comment by dvleeuwen** [comment]
Ja stel voor dit issue nu te sluiten 

Op ma 6 feb. 2023 om 11:16 schreef Jan Borger <[jborger@deregenboog.org](mailto:jborger@deregenboog.org)>:


Volgens mij heb je gelijk en is dat wat ze wilde,
de vraag is nog wel relevant of er betere feedback moet komen, alleen een stuk minder urgent...

Met vriendelijke groet,


Op ma 6 feb. 2023 om 11:14 schreef ECD De Regenboog Groep <[ecd@deregenboog.org](mailto:ecd@deregenboog.org)>:
Ha Jan,
als ik het vervolg vd mails goed lees lijkt het erop dat ze dossier wilde openen ipv inchecken en dat dus in het verkeerde scherm deed. Als dat inderdaad geval was kan dit issue direct weer dicht? Of speelt er nog iets anders volgens jou?

groet!
Daan
