### ISSUE TITLE
Consequenties vinkje "overleden" bepalen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#14]
Er is een vinkje in het dossier van cliënten om aan te geven dat deze persoon overleden is. Met deze info gebeurt nu nog niks. In welke overzichten moet de persoon wel terugkomen en waar niet? Dossier moet toegankelijk blijven, maar uiteraard niet in verzendlijsten terechtkomen.

**Comment by barthuttinga** [comment]
Geen "actieve" zaken, zoals registreren/schorsen etc.

**Comment by dvleeuwen** [comment]
nav ecdoverleg dec: als vinkje 'overleden'aan staat, moet automatisch 'geen post' aangevinkt worden

**Comment by dvleeuwen** [comment]
geldt voor heel ecd, dus haal label inloophuizen weg

**Comment by barthuttinga** [comment]
Postblokkade wordt nu automatisch ingesteld als "overleden" aangevinkt is.
