### ISSUE TITLE
managementrapportage geeft foutmelding

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1416]
via Janneke:
managementrapportage geeft foutmelding

**Comment by jtborger** [comment]
Hoi Daan,

dit ligt aan een instelling bij True. Ik heb daar een ticket aangemaakt en hou je op de hoogte...

**Comment by dvleeuwen** [comment]
ik heropen issue:

Hoi Daan,

De managementrapportage van inloop en MW zijn van elkaar gescheiden. Dat is fijn, want daardoor een stuk sneller. Maarrrrr... die van het MW geeft een foutmelding. Zou jij aan Jan willen vragen of hij daar even naar wil kijken? Dat ik de maandcijfers van mei kan aanleveren?

Dank alvast!
Met vriendelijke groet,

Janneke van Loo

**Comment by jtborger** [comment]
Probleem met het commenten van stukjes SQL in de management rapportage. Levert in dev geen foutmelding op, productie kan er niet mee dealen. Heb dat stuk code nu (wederom) weggehaald. Was door een merge weer teruggekomen...
Live gepatcht.
