### ISSUE TITLE
training is niet vindbaar als je via deelnemer wilt inschrijven

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1470]
nieuw toegevoegde training  [Workshop Zoeken Woning juni 2023] staat niet in het lijstje als je vanuit het dossier van een deelnemer iemand wilt toevoegen 
(https://ecd.deregenboog.org/oek/trainingen/?redirect=/oek/trainingen/)

voorbeeld:
https://ecd.deregenboog.org/oek/deelnames/add?deelnemer=626&redirect=/oek/deelnemers/626/view

**Comment by jtborger** [comment]
De training waar het over gaat heeft helaas een typfouten in de einddatum. (0203) Daardoor wordt ie niet meegenomen.

De trainingen die je kunt selecteren moeten allemaal en einddatum hebben die nog in de toekomst ligt. vandaar....

**Comment by jtborger** [comment]
ik heb de einddatum bewust niet aangepast, dan kunnen ze dat zelf even zien en doen, dat helpt voor het begrip (denk ik). niet dat ik het niet wil want dit typen kost meer tijd ;)
