### ISSUE TITLE
IZ verslagen op hulpaanbieding onmogelijk maken

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1473]
Nagaan of recente verslagen op hulpaanbod zijn gemaakte n zo ja die dan migreren naar de betreffende vrijwilliger.

**Comment by jtborger** [comment]
Overzicht gemaild naar Daan

**Comment by dvleeuwen** [comment]
Ha Jan,
dank!

dat zijn er toch meer dan ik verwacht had. Lijkt me voorbarig om dit er nu uit te slopen. Dus laten we m voorlopig maar gewoon zoals het is. 
Ik sluit issue Github voor nu,
