### ISSUE TITLE
Inloop dossier automatisch sluiten

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1504]
1 jaar na laatste registratie dossier automatisch sluiten cronjob.

Zoals afgesproken met Aukje en Bianca

**Comment by jtborger** [comment]
werkt nog niet helemaal goed.

**Comment by jtborger** [comment]
Seintje aan Willemijn als het werkt.

**Comment by barthuttinga** [comment]
@jtborger Wat werkt hier precies niet goed aan? Kan ik hier bij helpen? En zo ja: wat zijn in productie de mogelijke afsluitredenen in tabel `inloop_afsluiting_redenen`?

**Comment by jtborger** [comment]
Ik weet nu even niet wat er niet goed werkte eerlijk gezegd. Maar het werkte niet goed was mijn conclusie toen ik het uitprobeerde.
Dit zijn de huidige afsluitredenen, maar daar moet er denk ik 1 bij: Automatisch gesloten na 1 jaar geen bezoek. Die andere > 3 jaar moet maar blijven staan want die werd/word ook nog gebruikt..

 >3 jaar geen inloophuis bezocht
 Gerepatrieerd
 Overleden
 Overig

**Comment by jtborger** [comment]
Eindelijk gedaan. 6mnd is nu de termijn.
