### ISSUE TITLE
koppeling wordt niet gevonden als iemand meerdere hulpaanboden heeft open staan

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1543]
Uit verschil met testomgeving blijkt dat het in het koppelscherm misgaat als de vrijwilliger meerdere open hulpaanbiedingen heeft (+actieve koppeling?). Als je dan vanuit de hulpvraag van deelnemer zoekt, is dit hulpaanbod onvindbaar. Andersom werkt wel.

Nog in test omgeving te zien:
http://test-ecd.deregenboog.org/iz/klanten/22280/view?redirect=/iz/hulpvragen/51191/view#koppelingen
http://test-ecd.deregenboog.org/iz/vrijwilligers/17496/view?redirect=/iz/vrijwilligers/#koppelingen

**Comment by jtborger** [comment]
Ok, het lijkt erop dat het volgende aan de hand is:
- bij het opstellen van de lijst met matchende vrijwilligers wordt met van alles rekening gehouden
- daarbij ook of iemand in zijn hulpaanbod de hulpvraagsoort 'time out' heeft aangevinkt. deze heeft namelijk de speciale betekenis dat iemand (tijdelijk) geen koppeling wil.
- in deze casus is het zo dat in een van de twee open hulpaanbiedingen de hulpvraagsoort time out is aangevinkt.
- Zodra je die aanpast, verschijnt de VWer weer als match bij de deelnemer.

Vraag: is de betekenis van Time out wel goed bekend?

**Comment by jtborger** [comment]
Blijft een issue want houdt geen rekening met al afgesloten hulpaanbiedingen die dan timeout zijn. tevens moet hij rekening houden met de dat de timeout alleen geldt voor dat betreffende hulpaanbod en de types hulpvraagsoorten die daarin worden genoemd.

Zoek het in HulpaanbodDao:117

**Comment by jtborger** [comment]
Dat timeout verhaal moet echt beter, want ook afgesloten koppelingen waarin timeout in het hulpaanbod staat.
