### ISSUE TITLE
extra velden om contactgegevens van hulpverlening/netwerk van klant in te vullen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1571]
verzoek vanuit Oekraïne

actie Daan om na te vragen of dit ook op andere afdelingen een wens is

**Comment by dvleeuwen** [comment]
Is het mogelijk om in ECD een extra tabblad contactpersoon aan te maken? WIj willen graag de volgende gegevens daarin verwerken.

Gegevens contactpersoon(en)
Naam
Relatie
Telefoonnummer
email
Relatie met contactpersoon
Taal

verzoek Masha

**Comment by jtborger** [comment]
Daan navragen bij Kim
