### ISSUE TITLE
Mental Coach los van MW-er registreren op dossier

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1587]
Los van MW-ers moet er een aparte MCer kunnen worden gezet op een dossier.

**Comment by dvleeuwen** [comment]
+ mogelijkheid om hierop te filteren

(verzoek Yahya)

**Comment by jtborger** [comment]
Werkt niet goed. Zowel filter als formType goed nalopen. gaat iets niet goed, vermoedelijk met het filteren op rollen als configureerbare optie.

Tevens in het dossier de te selecteren medewerkers als mental coach filteren op rol

**Comment by jtborger** [comment]
heb nu een live patch gedaan om te zorgen dat het filteren op naam iig weer werkt.
(doordat er een null array terugkwam werd er altijd gefilterd op MCer ook als er geen was...)

**Comment by jtborger** [comment]
gaat mee met 2.7.0
