### ISSUE TITLE
Vrij zoekveld op woord die zoekt in verslagen bij open hulpvraag/aanbod

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1598]
Zodat er bv. in verslagen gezocht kan worden op 'schaken', en er zo mensen gevonden kunnen worden die daarop gematcht kunnen worden.

**Comment by jtborger** [comment]
@barthuttinga is dit iets voor jou?

**Comment by dvleeuwen** [comment]
@jtborger @barthuttinga 
uit welk veld worden de zoektermen nu gehaald? Ik ben er nu een tijdje mee aan het pielen, maar kom er niet uit....

**Comment by barthuttinga** [comment]
@dvleeuwen Er wordt gezocht in de tekst van verslagen die horen bij een hulpvraag/hulpaanbod. @jtborger Staat dit al live?

**Comment by dvleeuwen** [comment]
@barthuttinga zojuist met Jan besproken, het gaat om de verslagen vd deelnemer/vrijwilliger. En de zoekbalk zal dus ook in de tab deelnemers/vrijwilligers moeten komen ipv bij hulpaanbod
