### ISSUE TITLE
Opschonen klantenlijst

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#16]
Voorstel om iedereen waar drie jaar geen contact mee is geweest (geen MW, geen registratie, geen IZ, etc) te markeren als verwijderd en deze niet meer in de klantenlijst te laten zien. Bij invoeren van nieuwe klant moet er wel op gezocht worden (zoals nu gebeurt bij voorkomen dubbele invoer).

**Comment by barthuttinga** [comment]
Zie ook #51

**Comment by barthuttinga** [comment]
Aparte klantenlijst maken die alleen de inloophuisbezoekers toont. Ook inloopgegevens uit basisdossier verplaatsen naar apart inloopdossier.

**Comment by dvleeuwen** [comment]
@barthuttinga 

hoe denk jij over dit hele oude punt? 
Ik neig te zeggen 1,5jaar oud, niets meer over gehoord -> weg ermee.
akkoord?

**Comment by barthuttinga** [comment]
@dvleeuwen Ja, deels is het al gedaan. Inloopdossiers hebben aparte klantenlijst en kunnen afgesloten worden (en worden ook automatisch afgesloten na een bepaalde tijd). Algemene klantenlijst heeft inmiddels een andere rol. Ik sluit hem.
