### ISSUE TITLE
toegangsfout bij inchecken? 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1617]
Graziella:

XX heeft opeens ingecheckt kunnen worden in Amoc Zuid terwijl hij na zijn Re intake pas vanaf januari 2024 toegang mocht krijgen.
We begrijpen niet hoe dat kan, kan je alsjeblieft kijken?

https://ecd.deregenboog.org/inloop/klanten/5654224/view?redirect=/inloop/klanten/

**Comment by jtborger** [comment]
Eerste intake datum was al oud, dus vandaar... volgt precies de regels.
