### ISSUE TITLE
[OekBundle] wijziging medewerker link van klant wordt niet opgeslagen

### ISSUE THREAD

**Issue by Evertt** [deregenboog/ecd#162]
Bij `/oek/klanten/{id}/edit` en `/oek/klanten/{id}/open` wordt de opgegeven medewerker niet geslagen.

**Comment by barthuttinga** [comment]
@Evertt Je had deze aan mij toegewezen. Wil je graag dat ik hier naar kijk?

**Comment by Evertt** [comment]
Kan me niet herinneren dat ik dat gedaan heb. Ik wil er ook wel naar kijken vandaag. :-)

**Comment by barthuttinga** [comment]
@Evertt Ja, graag. Laat maar weten als ik er toch iets mee moet.
