### ISSUE TITLE
medewerker kan niet aangepast worden

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1694]
in klant overzicht zie je in kolom als "medewerker", hetgeen ingevuld is bij aanmelder, maar dit kan niet gewijzigd worden
https://ecd.deregenboog.org/uhk/deelnemers/149/view?redirect=/uhk/deelnemers/

ik vraag Evelien of Jan alle open dossiers sowieso kan omzetten Jelena-->Evelien
maar uiteindelijk moet het ook mogelijk zijn dit zelf te doen via medewerker wijzigen bij aanmelding

**Comment by jtborger** [comment]
duplicate #1703
