### ISSUE TITLE
Twee opslaan-buttons bij gebruik sub-forms

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#170]
Omdat de buttons nu ook in de formTypes zitten worden twee submit-buttons gerenderd als een subform gebruikt wordt. Zie bv /oek/klanten/add?klantId=21

Dit graag oplossen in de FormType van het hoogste niveau. Deze moet na includen van een subtype de submit button weghalen door zoiets als `$builder->get(IntakeType::class)->remove('submit')`

**Comment by Evertt** [comment]
Dat kan niet zomaar. Volgens [dit](http://stackoverflow.com/a/34543109/1498652) op SO moeten we dan de knop conditioneel *wel* laten verschijnen.

Nu lijkt het erop dat de submit-knoppen in de form types stoppen misschien toch niet zo'n goed idee was. Wil je het doen volgens dat SO antwoord? Of gewoon weer alle submit knoppen terug in de twig views stoppen?

**Comment by barthuttinga** [comment]
@Evertt Jawel hoor, dat kan gewoon en dat hoeft (moet) uiteraard niet in de controller te gebeuren. Conditioneel kan, maar ik stel voor juist het hoofdniveau verantwoordelijk te maken, niet de embedded forms. Dit is inderdaad een nadeeltje, maar daar staat tegenover dat de twig-templates aanzienlijk schoner zijn.

Zoals boven beschreven: bij het bouwen van de form wordt een subform toegevoegd, daarna doe je `$builder->get(SubformType::class)->remove('submit')` om de submit-button te verwijderen.

**Comment by barthuttinga** [comment]
@Evertt Zie commit c0572be2c9ba810beebb2a8756ea9de81527e143. Ik heb een BaseType gemaakt die recursief submit-buttons van child-forms verwijdert. Als je zorgt dat een form BaseType als parent heeft (direct of indirect) dan gaat het vanzelf goed. Om dit ticket op te lossen dus graag voor alle forms `getParent()` implementeren.

**Comment by barthuttinga** [comment]
@Evertt Graag ook in de Forms van de andere bundles.
