### ISSUE TITLE
nieuwe kolom toevoegen 'Training & ontwikkeling'

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1707]
Hoi Daan en Jan,

Wij zouden graag een kleine aanpassing aan het inloophuizentabblad willen: de kolom 'Training & ontwikkeling' toevoegen, met vinkboxjes. En dat de opbrengst daarvan dan terugkomt in de rapportagemodule. Is dat te doen?

Dank alvast!
Met vriendelijke groet,

Janneke van Loo

**Comment by barthuttinga** [comment]
Is hetzelfde als #1695. Ik sluit deze.
