### ISSUE TITLE
fout bij facturering 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1710]
Ha Daan,

Wij constateren een fout in ECD bij het verwerken van de binnenkomende betalingen op uitgestuurde facturen. ECD registreert betaling goed, maar openstaande saldo blijft openstaan.

Kunnen jullie er eens induiken wat hier niet goed gaat?
Zie klanten
Telegt
Heyouf
Kolf
Garcia
En iedereen die we verder betalingen voor invoeren.

We horen graag
Gr Sander

**Comment by jtborger** [comment]
Door een update werd het herberekenen van het saldo na invoeren van een betaling niet getriggered. 
Dat is hersteld. Tevens voor de betalingen die afgelopen week zijn gedaan zijn de saldi opnieuw berekend. Als het goed is staat alles weer zoals het zou moeten.
