### ISSUE TITLE
VOG en toestemmings formulier zijn niet meer te uploaden

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1729]
VOG en toestemmings formulier zijn niet meer te uploaden

zie oa mails Niek, Jacqueline en Mirjam

**Comment by barthuttinga** [comment]
@dvleeuwen Deze had ik opgelost in https://github.com/deregenboog/ecd/pull/1732. Kan deze gesloten worden?

**Comment by jtborger** [comment]
Ja
