### ISSUE TITLE
Training worden niet getoond bij groep

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#173]
Zie bv /oek/groepen/1/view

Ik voeg een nieuwe training toe maar deze verschijnt niet in de lijst. Elders zie ik dat deze training wel degelijk is opgeslagen en aan de betreffende groep gekoppeld is.

**Comment by Evertt** [comment]
Dat kan kloppen. Dat komt omdat in de code, die jij hebt geschreven, staat dat er in dat lijstje alleen maar trainingen moeten voorkomen die nog niet afgelopen zijn. Dat klinkt voor mij als zo'n specifiek filter dat dat vast niet per ongeluk zo gedaan is, dus ik neem aan dat dat zo moet blijven?

Of wil je daar toch alle trainingen hebben staan?

**Comment by barthuttinga** [comment]
@Evertt Ah ja, dat verklaar het. Inderdaad dit moet zo blijven. Ik heb daar bij het testen niet aan gedacht. Ik sluit dit ticket.
