### ISSUE TITLE
Inloopverslagen voor niet MW klanten mogelijk maken

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#1737]
Doordat er nu een MW dossier vereist is om een verslag te maken, lopen ze er bij inloop tegenaan dat dat dus niet altijd aanwezig is. De foutmelding is niet fijn, maar ook de oplossing nog niet onderweg.
Doordat verslagen in MW bepalend zijn voor de verantwoording, en een inloopverslag feitelijk eigenlijk MW werk is wat ook mee moet worden genomen in die verantwoording, is een open MW dossier nodig...

Even in overleg met Janneke wat we gaan doen.
Oplossingsrichting:
- Inloop medewerkers (dagco's?) mogen MW dossiers aanmaken, en dat kan dan evt impliciet gebeuren vanuit het aanmaken van het verslag
- De rapportage van MW wordt alleen gedaan op verslagtype = MW. Dus inloopverslagen tellen niet meer mee voor de verantwoording. Dit is een breuk met het verleden.
- het huidige verslagen model wordt uit elkaar getrokken, er komen twee tabellen, een voor inloop, een voor MW. MW verantwoord dan alleen op MW, inloop op inloop. Praktisch is dan dat er twee tabbladen komen in een inloop en mw dossier: voor elke verslagsoort een. Dat loopt dan chronologisch ook door elkaar. Al kan dat ook wel weer geïntegreerd worden. Dit is eigenlijk de meest zuivere oplossing omdat je dan binnen de domeinen blijft.
- Kern van de vraag is: is een verslag dat inloop maakt een inloop activiteit, of een MW activiteit, gedaan door een inloop medewerker.

**Comment by jtborger** [comment]
Verslagen werden altijd vanuit inloop en MW gemaakt.
Het punt tis dat verslagen een MW prestatie is en als zodanig voor de productie mee telt.
Om daar goede cijfers van te maken, is er een MW dossier nodig, zodat doorlooptijd etc berekend kan worden.

Omdat niet alle inkoopklanten automatisch een MW dossier hebben, maar er soms wel een verslag moet worden gemaakt, is de oplossing nu dat een dagco dan een MW dossier moet maken.
Dit wordt als te omslachtig te zien.

Wat er moet komen is dat wanneer er vanuit inloop een verslag gemaakt wordt, maar die klant geen MW dossier heeft, er 'onder water' een MW dossier gemaakt wordt, met daarin een aantal (evt nieuw te definiëren) default waardes ingegeven worden (zoals project, en wat er verder og in zit weet ik zo ff niet).

**Comment by jtborger** [comment]
Als dit is opgelost kan #1722 dicht.

**Comment by barthuttinga** [comment]
@jtborger Ik ben hiermee bezig geweest, maar moet even met je overleggen over hoe dit precies te doen.
