### ISSUE TITLE
ontbrekende namen bij Mijn Dagbesteding

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1738]
zie mails arno 8 maart

**Comment by jtborger** [comment]
Lijkt mij geen error, maar het ontbreken van het invullen van Project.
Ik kan niet terugvinden dat dit in een van de laatste releases gewijzigd is.
Het is wel zo dat bij sommige trajecten de werklocatie en projectlocatie hetzelfde is (DAM) en dat is verwarrend misschien...
Ik ben hierover met Arno aan het mailen, ik sluit nu dit ticket.
