### ISSUE TITLE
aanpassingen ivm Buitenhof

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1743]
scherm maken waarin zichtbaar is welke bewoner op welke kamer zit Buitenhof

+  

toegang voor dagco's TW, die ook verslagen kunnen toevoegen

+ 

verslagen gekoppeld aan MW/STED (vergelijkbaar met inloop-mw)

**Comment by dvleeuwen** [comment]
mail ter info:

Hi allen,zoals gister besproken: vandaag heb ik samen met Jan gezeten mbt Buitenhof-ECD, om hetgeen wij gisteren bespraken aan hem voor te leggen. Mijn idee was in eerste instantie er een aparte module voor te maken. Jan geeft echter de voorkeur om met een paar aanpassingen het in te bouwen in de bestaande Tijdelijk Wonen. 

De aanpassingen die hij hiervoor gaat doen:-de bug fixen dat er niet gefilterd kan worden op gekoppeld/niet gekoppeld-een overzichtsscherm waarin alle bewoners + kamers zichtbaar zijn van Buitenhof-toegangsrechten maken voor dagcoördinatoren zodat zij in module TW kunnen (klopt het dat dagcoordinatoren nieuwe collega's worden, of zijn dit collega's die nu werkzaam zijn in de inlopen?)-de verslagen die geschreven worden door STED/MW + TW + Dagco's allen te bundelen binnen het dossier vd bewoner. (hierbij voor MW optie toevoegen dat verslagen afgeschermd worden en enkel zichtbaar zijn voor MW)
Het is dus aan TW om alle beschikbare kamers in te voeren als "verhuurder", zodat ze gekoppeld kunnen worden aan persoon.

We hebben het streven bovenstaande af te maken voor eind april.Finetuning en extra wensen (bijvoorbeeld de besproken kleurcodes na 7,5 maanden) zullen dan in een later stadium aan bod komen.
Laat het vooral horen als jullie het gevoel hebben dat we iets over het hoofd zien met bovenstaande. 

groet!Daan

**Comment by jtborger** [comment]
Volgens mij is alles rondom buitenhof nu echt opgelost.
