### ISSUE TITLE
bug/foutmelding bij aanpassen project

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1754]
Ha Daan,

Anouk hier. Ik probeerde het label aan te passen bij projecten naar 'Buitenhof STED' maar het lukt mij net als Mirjam niet. Ik krijg het volgende te lezen:

Details: Expected argument of type "TwBundle\Entity\IntakeStatus", "null" given at property path "intakeStatus".

Neem contact op met Daan van Leeuwen ([ecd@deregenboog.org](mailto:ecd@deregenboog.org?subject=ECD%20foutmelding&body=Hi%21%0A%0AIk%20krijg%20deze%20foutmelding%3A%0D%0A%27Expected%20argument%20of%20type%20%22TwBundle%5CEntity%5CIntakeStatus%22%2C%20%22null%22%20given%20at%20property%20path%20%22intakeStatus%22.%27.%20%0D%0ADat%20gebeurt%20op%20deze%20pagina%3A%20%2Ftw%2Fklanten%2F239%2Fedit%20.)) als dit probleem zich blijft voordoen.

Zou jij hier even naar willen kijken?

Hartelijke groet,

Anouk Strandstra - Suzan Huppes - Joline van Driesten - Julia Tebbe
Tijdelijk Onder Dak

**Comment by dvleeuwen** [comment]
---------- Forwarded message ---------
Van: Mirjam Hasselt 
Date: do 28 mrt 2024 om 17:38
Subject: S. Joseph
To: Tijdelijk Onderdak <[tijdelijkonderdak@deregenboog.org](mailto:tijdelijkonderdak@deregenboog.org)>


Hola allen,

Ik mail even over de aanmelding van XX Ze is een cliënt van mij en gaat de NOIZ in. Ik wilde haar op de Buitenhof/STED lijst zetten - maar ik krijg een foutmelding. 

Zij hoeft dus niet gescreend te worden voor ToD. Kunnen jullie dat aanpassen?

Groetjes,
MNirjam

BETREFT DIT DOSSIER: https://ecd.deregenboog.org/tw/klanten/239/view?redirect=/tw/klanten/

**Comment by jtborger** [comment]
Bij het veranderen van de property project in bij de klant, geeft hij dus de  (/tw/klanten/42/edit?redirect=/tw/klanten/42/view)
Geeft hij in het dossier dat in productie is de melding dat intakteStatus niet nul kan zijn.
Dit dossier heeft de intake status 'Onbekend', maar die status is in de productieomgeving op inactief gezet.
En dan geeft hij dus een melding, terwijl in development de intake status wel leeg kan zijn in het formulier.

Hoe om te gaan met een property die activatable is, en dus inactief kan zijn, waarbij wanneer de entity bewerkt wordt, er dus iets mis kan gaan?
