### ISSUE TITLE
standaard "onbekend" ipv "niet gekoppeld"

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1802]
in het tab "verhuurders" in de kolom "gekoppeld" , staat nu als standaard "niet gekoppeld", dat moet aangepast worden naar  "onbekend" zoals het voorheen was.
In de praktijk zorgt dit voor problemen (mensen worden niet gevonden en/of dubbel ingevoerd)

(via Nezet)

**Comment by dvleeuwen** [comment]
staat nog steeds op "niet gekoppeld" als standaard

**Comment by jtborger** [comment]
Heb hem live gepatcht. Geen release.

**Comment by jtborger** [comment]
Hoi Daan,
Ik heb hem live gepatcht. Weet niet of je ook een mail krijgt van mijn
comment op het issue dus wellicht dubbelop.

Met vriendelijke groet,

Jan Borger
Ontwikkelaar ECD
***@***.***
(Ik reageer niet zo snel op mail. Voor spoed: via Daan van Leeuwen ben ik
telefonisch bereikbaar.)


Op wo 24 jul 2024 om 14:48 schreef dvleeuwen ***@***.***>:
