### ISSUE TITLE
aanmaken nieuw huuraanbod levert foutmelding op als er geen medewerker geselecteerd wordt

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1812]
aanmaken nieuw huuraanbod levert foutmelding op als er geen medewerker geselecteerd wordt

Er moet dus een sterretje bij medewerker geplaatst worden, want collega's raken hiervan in de war als ze foutmelding krijgen bij opslaan

https://ecd.deregenboog.org/tw/huuraanbiedingen/verhuurders/5720/huuraanbiedingen/add?redirect=/tw/verhuurders/5720/view

**Comment by jtborger** [comment]
Helder.
Nu is het zo dat de medewerker handmatig moet worden ingevuld. Is dat zoals het de bedoeling is, of is de medewerker ook altijd degene die het huuraanbod aanmaakt en kan ik hem al automatisch daarop laten instellen? (dan kan ie alsnog wel gewijzigd worden wanneer er soms een nadere medewerker ingevuld moet worden natuurlijk)
