### ISSUE TITLE
Oek-rapportages toevoegen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#183]
De volgende rapportages moeten worden toegevoegd:
- aantal trainingen per groep (verticaal) per stadsdeel (horizontaal)
- aantal deelnemers per training (verticaal) per stadsdeel (horizontaal) - aparte tabel per status (aangemeld, gestart, afgerond)
- totaal aantal deelnemers verwezen door (per verwijzing)
- totaal aantal deelnemers verwezen naar (per verwijzing)

Voor alle rapportages geldt dat ze over een op te geven datumbereik gaan. Zie IzBundle voor inspiratie over hoe de rapportages op te zetten. Iedere rapportage heeft een eigen class, welke als getagde service wordt gedefinieerd.

**Comment by barthuttinga** [comment]
Rapportages bij Iz worden nu alleen op het scherm getoond. Bij Oek graag optie toevoegen om als Excel te downloaden.

**Comment by barthuttinga** [comment]
@Evertt Kijk voor de downloptie ook even naar ticket #202 en/of commit a67f7497902e223de61ce98c284af4bde0247632 (headers op response-object).

**Comment by Evertt** [comment]
@barthuttinga deze kan naar **done** nadat je #204 gemerged hebt
