### ISSUE TITLE
heropen knop lijkt niet te werken

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#1831]
als je een dossier probeert te heropenen lijkt er niets te veranderen, en blijft de status op niet actief staan

zie bijvoorbeeld hier:
https://ecd.deregenboog.org/tw/verhuurders/4878/view?redirect=/tw/verhuurders/

verzoek vanuit Jacky

**Comment by dvleeuwen** [comment]
blijkt nog niet te werken, zie linkje hierboven
bij een ander dossier waarbij jan het probeerde leek het wel goed te gaan

**Comment by jtborger** [comment]
Vreemd verhaal. Lijkt alsof de release die file niet heeft meegenomen want ik zie de betreffende code niet live staan. Terwijl voor andere issues die zijn ereleased dat wel het geval is. 
Wordt vervolgd.

**Comment by jtborger** [comment]
Heb het nu live gepatcht.
