### ISSUE TITLE
Geen checkbox "activering" tonen bij ingecheckte Hi5-cliënten

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#19]
Hoge prioriteit. Een Hi5-er in traject (met begin en einddatum) mag in een inloophuis geen activering doen. De registratie-module moet zo aangepast worden dat bij een Hi5er geen activering meer aangevinkt kan worden. Verzoek is om geen checkbox “activering” te tonen bij personen die zijn ingecheckt in een inloophuis als deze al bij Hi5 zit.

**Comment by barthuttinga** [comment]
Gedaan, maar aanvullende vraag gemaild op 13-02-2017.

**Comment by barthuttinga** [comment]
On hold, tot er duidelijk is wat Hi5 met ECD gaat/wil doen.

**Comment by barthuttinga** [comment]
@dvleeuwen Kan jij nagaan wat hiermee moet gebeuren? Hi5 bestaat toch niet meer? Of in ieder geval wordt in ECD de module Hi5 niet meer gebruikt.

**Comment by dvleeuwen** [comment]
@barthuttinga 
Bas legt uit: de term Hi5 is idd verouderd. Gaat om mensen in dagbesteding. Als iemand actief dossier in dagbesteding heeft, moet het onmogelijk zijn deze persoon aan te vinken als activering in ECD 
kun je hier verder mee?

**Comment by barthuttinga** [comment]
@dvleeuwen Dank!

**Comment by barthuttinga** [comment]
Opgelost en live. Er wordt gekeken of iemand een actief dossier bij Dagbesteding heeft, niet of er een traject loopt.
