### ISSUE TITLE
Verbeteren overzicht documentenlijst

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#20]
Lage prio. Als er veel documenten bij een klant geupload worden, wordt de lijst onoverzichtelijk. Vraag is of dat beter kan.

**Comment by barthuttinga** [comment]
@Evertt Kan jij hier iets mee? MIsschien even telefonisch overleg als je hiermee bezig gaat.

**Comment by dvleeuwen** [comment]
Besloten in ECDoverleg dec: niet belangrijk (meer), afsluiten
