### ISSUE TITLE
VOG-vinkjes toevoegen bij vrijwilligers

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#33]
- Verklaring omtrend gedrag wel/niet aangevraagd
- Verklaring omtrend gedrag wel/niet aanwezig

**Comment by dvleeuwen** [comment]
Ik heropen ivm verzoek Miranda:

Gebleken is dat er door het administratie kantoor soms wordt vergeten te vinken wanneer een VOG of vrijwilligerscontract aanwezig is, deze vinkjes staan bij het basisdossier. 

Om die reden wil ik aan Bart vragen of het aanvink veld wilt verplaatsen naar het veld documenten. Misschien dat dat help en wordt het minder snel vergeten. 
Het vinkje staat op een onhandige plek, je moet steeds wisselen tussen Informele Zorg en het basisdossier.

**Comment by barthuttinga** [comment]
Ik heb het iets anders opgelost dan hierboven beschreven. In alle vrijwilligersdossiers (niet alleen IZ) staan links de basis- en contactgegevens. Daaronder staat nu een blokje "Overeenkomst" met deze vinkjes. Hier zijn ze ook direct te wijzigen, zonder eerst naar het basisdossier te gaan. Gaat vandaag live.
