### ISSUE TITLE
Vet en cursief kunnen gebruiken in PFO-verslagen, update: + MW

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#333]
Zie mail 02-10-2017.

Misschien markdown gebruiken? https://github.com/hectorguo/CKEditor-Markdown-Plugin

**Comment by dvleeuwen** [comment]
Dit lijkt (opnieuw) niet meer te werken?

Evelien:

Hoi Daan,
tot voor kort kon ik in het ECD ook schuine letters instellen, of dikke letters.
Dat is er opeens niet meer.
Is het mogelijk dat dat weer komt?
Als dan onderstrepen ook toegevoegd wordt ben ik helemaal gelukkig :-)
Groet!

**Comment by jtborger** [comment]
2.2.43

**Comment by dvleeuwen** [comment]
Verzoek vanuit MaatswchappelijkWerk of zij ook cursief en vet in tekst kunnen gebruiken (net als PFO)

**Comment by dvleeuwen** [comment]
hoge prio als het inderdaad klein klusje is, als het meer werk is mag 'hoge prio' eraf

**Comment by jtborger** [comment]
gaat mee met 2.3.5
