### ISSUE TITLE
Rapportages Onder de Pannen toevoegen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#474]
- Hoeveel huurders gestart na een bepaalde datum, met naam ed
- Hoeveel verhuurders gestart vanaf een bepaalde datum, met naam ed
- Hoeveel koppelingen gestart vanaf een bepaalde datum
- Hoeveel huuraanbiedingen vanaf een bepaalde datum
- Hoeveel huurverzoeken vanaf een bepaalde datum
- welke overeenkomst vormen tussen bepaalde data gesloten zijn

**Comment by dvleeuwen** [comment]
Besloten in ECDoverleg dec: niet belangrijk (meer), afsluiten
