### ISSUE TITLE
Voorkeur man/vrouw in matching meenemen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#479]

**Comment by dvleeuwen** [comment]
Ik heropen dit issue, want lijkt slechts 1 kant op te werken:

Voorbeeld
Vrouwelijke deelnemer geeft aan een vrouwelijke vrijwilliger gekoppeld te willen.
Als je vanuit dossier deelnemer zoekt gaat die goed (komen enkel vrouwelijke vrijwilligers naar voren).
Maar als je vanuit dossier mannelijke vrijwilliger gaat zoeken, komt haar naam ook naar voren als mogelijke match. Wat natuurlijk niet de bedoeling is.

**Comment by barthuttinga** [comment]
opgelost en live
