### ISSUE TITLE
Bij toevoegen verslag aangeven of het tussen-/eindevaluatie is

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#491]
Per koppeling is max 1 tussen- en 1 eindevaluatie mogelijk.

**Comment by dvleeuwen** [comment]
+ toevoegen verslagmacro's kennismaking/tussen-/eindevaluatie

**Comment by barthuttinga** [comment]
@dvleeuwen Nu is een tussen- of eindevaluatie hetzelfde als ieder ander verslag toch? Kan je aangeven hoe je dit zou willen? En is de opmerking van verslagmacro's nog relevant? (ik dacht dat daar vanaf gezien was)

**Comment by barthuttinga** [comment]
Lijkt me niet meer nodig nu #800 opgelost is.
