### ISSUE TITLE
Alle cache legen bij deployment

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#494]
Ook alle CakePHP cache. En APC.

**Comment by dvleeuwen** [comment]
bij ecdovereleg dec voor aanwezigen onduidelijk, navragen bij Bart en daarna prio toekennen

**Comment by dvleeuwen** [comment]
@barthuttinga 

voor mij onduidelijk, wat wordt hier bedoeld?
Is dit (nog) belangrijk?

**Comment by barthuttinga** [comment]
Nee, was al opgelost en is niet meer relevant sinds v2.0.0
