### ISSUE TITLE
Bij aanmaken hulpvraag/-aanbod zijn doelgroep, hulpvraaggebied en matchingscriteria verplicht

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#510]

**Comment by dvleeuwen** [comment]
Bij hulpvraag werkt dit goed,
bij hulpaanbod nog niet: daar kun je doelgroep en hulpvraagsoort nog leeg laten, terwijl er bij beiden minimaal 1 aangevinkt moet worden

**Comment by barthuttinga** [comment]
opgelost en live
