### ISSUE TITLE
Standaard alleen actieve dossiers tonen + filter toevoegen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#511]

**Comment by dvleeuwen** [comment]
Nav ecdoverleg dec: niet enkel voor dagbesteding, maar voor alle afdelingen (IZ heeft het al) vinkje actieve dossiers. Ik haal label dagbesteding eraf, want ecd breed.

**Comment by barthuttinga** [comment]
Op de meeste plekken doorgevoerd. Op verzoek kan ik het nog in andere overzichten toevoegen.
