### ISSUE TITLE
Kruimelpad uitbreiden met detailniveau

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#514]

**Comment by dvleeuwen** [comment]
@barthuttinga 

Bart: weet jij wat met dit oude issue bedoeld wordt?
Ik niet...

**Comment by barthuttinga** [comment]
@dvleeuwen Bovenin staat bv "ECD / Dagbesteding / Deelnemers", dat zou nog specifieker kunnen door een extra niveau weer te geven als je in het dossier van een deelnemer zit. Ik vind dit niet erg belangrijk. Sluit jij hem evt?

**Comment by dvleeuwen** [comment]
Ja ik sluit m af
