### ISSUE TITLE
Checkbox "ondersteuningsplan verwerkt" bij traject toevoegen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#518]
Zie #517

**Comment by barthuttinga** [comment]
Opgelost en live

**Comment by dvleeuwen** [comment]
Ha Bart,
de vraag komt terug of dit '1 scherm naar voren kan'

Dus of het hier zichtbaar kan zijn in lijst:
https://ecd.deregenboog.org/dagbesteding/deelnemers/116/view?redirect=/dagbesteding/deelnemers/
ipv hier:
https://ecd.deregenboog.org/dagbesteding/trajecten/440/view?redirect=/dagbesteding/deelnemers/116/view

Dat aanpassen op laatste pagina gebeurd is ok, maar heel graag dus al op
pagina daarvoor zichtbaar ja/nee

groet
Daan


Op ma 4 feb. 2019 om 16:12 schreef Bart Huttinga <notifications@github.com>:

**Comment by barthuttinga** [comment]
Ze hebben in het overzicht in "Mijn Dagbesteding" ook al een overzicht van alle trajecten zonder ondersteuningsplan (#518). Voldoet dat niet?

**Comment by dvleeuwen** [comment]
Ah top Bart,
de vraag kwam nog van voordat "Mijn dagbesteding" live was.
Ik check even, maar vermoed idd dat dit voldoende is.
Als je niets meer van me hoort is dit opgelost.


Op di 12 feb. 2019 om 16:38 schreef Bart Huttinga <notifications@github.com
