### ISSUE TITLE
Entiteit Persoon aanmaken

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#520]
Koppeling tussen klant en vrijwilliger kunnen maken, als het dezelfde persoon is. Gemeenschappelijke eigenschappen abstraheren om dubbeling te voorkomen.

**Comment by dvleeuwen** [comment]
Bas gaat navragen, daarna prio toekennen

**Comment by dvleeuwen** [comment]
niets meer teruggehoord, dus ik ga er vanuit niet (meer) wenselijk
