### ISSUE TITLE
Aanpassen telling managementrapportage

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#523]
- 2017 en eerder: tellen volgens telstrategie van project
- 2018: lopend + gestart meetellen
- 2019 en later: gestart tellen

**Comment by dvleeuwen** [comment]
Verzoek van Hans/Marit om telling 2019 toch zelfde als 2018 te doen: beginstand meenemen bij prestatie

**Comment by barthuttinga** [comment]
Aangepast en live
