### ISSUE TITLE
Bij sluiten verwijsbrief AMOC komt cliënt dubbel in systeem

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#578]

**Comment by barthuttinga** [comment]
@dvleeuwen Kan jij eens nagaan of dit nog relevant is?

**Comment by dvleeuwen** [comment]
5 feb

Ha Aukje,
hierbij een ouder issue, waarvan Bart benieuwd is of het nog speelt of vd lijst af kan.

Wil jij checken?

 "Bij sluiten verwijsbrief AMOC komt cliënt dubbel in systeem " 

dank!
Daan
---
Hoi Daan, 

Ik moet dit navragen bij MW.

**Comment by barthuttinga** [comment]
@dvleeuwen ik heb ticket aan jou toegewezen, graag weer aan mij toewijzen als ik er mee verder moet/kan

**Comment by dvleeuwen** [comment]
geen reactie meer ontvangen op vraag aan Aukje, dus ik sluit issue
