### ISSUE TITLE
Opties in keuzelijst "doorverwezen naar"

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#583]
"Kruispost" toevoegen en "Rehab" wijzigen in "Zorgtoeleiding"

**Comment by dvleeuwen** [comment]
Verzoek nav ecdoverleg dec: een beheer functie voor mw, zoals ook bij IZ bestaat, zodat medewerkers dergelijke aanpassingen zelf kunnen doen

**Comment by barthuttinga** [comment]
Opgelost en live
