### ISSUE TITLE
Tussenvoegsels verdwenen in klantenlijst bezoekersregistratie

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#584]

**Comment by barthuttinga** [comment]
Is nooit anders geweest. Meenemen in refactoring.

**Comment by dvleeuwen** [comment]
Ha alle3,

we gaan steeds verder terug in de berg van ECDverzoeken die er nog lagen vanuit 2018.

Zodoende kwam ik onderstaande tegen (juni 2018)
Tussenvoegsels verdwenen in klantenlijst bezoekersregistratie

Even check bij jullie:
is dit iets wat inderdaad aangepast moet worden (volgens Bart is het nooit zo geweest),
is het nu onhandig dat tussenvoegsels niet getoond worden, zorgt dit voor problemen?
Of werkt het (inmiddels?) prima zo en heeft niemand hier last van? (dan stel ik voor dit punt te schrappen) 

Hoor m graag terug, dank!

Daan

**Comment by dvleeuwen** [comment]
lijkt niet (meer) relevant

ik sluit af
