### ISSUE TITLE
Links moeten duidelijker (bv onderstrepen)

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#605]

**Comment by dvleeuwen** [comment]
bv namen in IZdossiers

**Comment by dvleeuwen** [comment]
nu zien/snappen collega's soms niet dat je simpelweg op naam kunt klikken om in dossier te komen. (bijvoorbeeld vanuit koppeling naar dossier vw'er/deelnemer)

**Comment by barthuttinga** [comment]
Heb je hier recentelijk nog klachten over gehad? Lijkt mij een kwestie van wennen. Ik sluit het issue.

**Comment by dvleeuwen** [comment]
ja, mee eens!

Op do 21 mrt. 2019 om 13:18 schreef Bart Huttinga <notifications@github.com
