### ISSUE TITLE
Velden vw-overeenkomsten toevoegen aan vw-download

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#640]

**Comment by dvleeuwen** [comment]
MIchelle zoekt uit, en antwoord:
Hoi Daan,
Ik heb het nagekeken. Bij de HS krijg je op de download niet te zien of er een VOG is (aangevraagd)
En het viel me op dat als je in homservice naar een doosier van een VW gaat er niets in staat over een VOG.
Als je naar vrijwilligers algemeen gaat (van de hele Regenboog) en je tikt de naam van een VW in, dan staat er wel iets bij over de VOG.
Maar; hun vraag; kan hetn op de download, nu stata het er dus niet, maar volgens mij komt dat omdat het uberhaupt niet in het HS dossier te vinden is.

Mijn reactie:
In de ECDissuelijst van Bart ging het om de VWovereenkomst, en niet over VOG.
Dit zijn natuurlijk 2 verschillende zaken. Zal ik bij Sander navragen wat er nu werkelijk bedoeld/gewenst wordt?

Ik vraag na bij Sander, daarna prio toekennen

**Comment by dvleeuwen** [comment]
En aanvullend nog een vraag:
klopt het dat jullie nog geen inzage hebben in welke vw'ers wel/niet VOG hebben, of is dit opgelost?

groet!
Daan

**Comment by barthuttinga** [comment]
@dvleeuwen Hier wacht jij ook nog op antwoord? Ik zet deze op jouw naam. Zet je hem weer op mij als ik er wat mee moet?

**Comment by dvleeuwen** [comment]
Ola,
er staat nog een punt bij ons open mbt VOG vrijwilligers.
Klopt het dat jullie nu weer gewoon bij basisdossiers van jullie vw'ers kunnen, en dan linksonder in beeld de VOG opties hebben?
Ik heb even getest, bij mij werkt het vanuit HS. Graag even bevestiging van jullie of het bij jullie ook werkt, dan kan dit ticket gesloten worden.

groet
Daan

**Comment by dvleeuwen** [comment]
Goedemorgen Daan,

Ja het klopt, ik kan nu bij vrijwilligers de VOG opties zien en aanvullen.

Gr Sander

kan dus gesloten worden
