### ISSUE TITLE
Diverse aanpassingen homeservice

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#641]
Uit mail 23-08-2018:

- [ ] ~Binnen de klus bij geregistreerde uren zou het fijn zijn als ik kan selecteren op naam en datum/tijd. Zeker bij grote klussen met veel gemaakte uren handig.~
- [x] Factuurdatum mag op laatste dag van de maand, als dat kan. Klussen die al op 1 augustus afgerond zijn krijgen nu als factuurdatum 1 augustus, terwijl ik de factuur op z'n vroegst pas eerste week september verstuur. Klanten raken daar van in de betalingsstress heb ik gemerkt.
- [x] Kan de omschrijving van declaratie ook op factuur kunnen komen?
- [x] Zou de achternaam van de klant in de omschrijving van de PDF factuur kunnen?
- [x] Zou het selectieveld van de activiteiten in het Klussen-veld op alfabet kunnen? Zijn er best veel, en nu komt de nieuwste onderaan te staan

**Comment by dvleeuwen** [comment]
navragen bij Sander hoe relevant dit nog is, daarna prio bepalen

**Comment by dvleeuwen** [comment]
allen nog actueel, dus ingedeeld bij V2.2

**Comment by barthuttinga** [comment]
Gaat vandaag live.

**Comment by barthuttinga** [comment]
@dvleeuwen 3e en 5e punt zijn nu ook gedaan en gaan vandaag live

**Comment by dvleeuwen** [comment]
Volgens Iris zijn punt 2 & 4 vandaag nog niet live/aangepast?

Bart: wil jij checken? Hoor m graag terug

**Comment by dvleeuwen** [comment]
Hoi daan, 

punt 4 is inmiddels live, maar Bart heeft het anders geinterpreteerd dan ik bedoelde :)

Achternaam staat nu achter factuurnummer op de factuur zelf. ik bedoelde: de achternaam in de naam van het PDF-bestand... Sorry, my bad! 

Groet Iris

**Comment by jtborger** [comment]
Vierde punt: Zou de achternaam van de klant in de omschrijving van de PDF factuur kunnen?, heb ik opgelost.

**Comment by jtborger** [comment]
punt 2 werkt bij mij lokaal goed. of het live staat weet ik niet.

**Comment by dvleeuwen** [comment]
opgelost maar nog niet live

**Comment by jtborger** [comment]
punt 4 staat nu live. overige zaken moet ik nog naar kijken

**Comment by dvleeuwen** [comment]
De rest was volgens mij al gedaan door Bart, dus ik sluit dit issue

**Comment by dvleeuwen** [comment]
vraag ligt bij Iris of eerste punt uit lijstje alsnog uitgevoerd moet worden (in april besloten dit niet te doen, maar ze vraagt er nu opnieuw naar) Ik wacht nog op def bevestiging.

**Comment by dvleeuwen** [comment]
Helderheid: 2tm5 is gedaan en werkt
Punt 1 svp nog aanpassen, lage prio

**Comment by jtborger** [comment]
Dit is lastig(er) te realiseren dan het lijkt; omdat het een 'sub-lijst' is, is deze niet, zoals andere lijsten, eenvoudig te filteren en sorteren. Dat vraagt om een nieuwe implementatie van deze sublijsten (die overal in ECD gebruikt worden). Ik ga even nadenken over een andere oplossing voor deze specifieke case.

**Comment by jtborger** [comment]
Ik heb het alsvolgt opgelost:
- in de klus zelf bij het tabblad Uren staat een link 'bekijk details'. Je komt dan in de uren lijst terecht gefilterd op deze klus. Daar kan je wel sorteren (en nu ook bewerken en verwijderen van uren). Het is niet ideaal want je bent uit de 'klus', maar goed dit is voor nu het hoogst haalbare. Ik maak van het onderliggende probleem een nieuw issue.
