### ISSUE TITLE
Ontdubbel-tool maken om dubbele dossiers samen te voegen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#649]
Ontdubbel-tool werkte niet goed tijdens migratie van Cake naar Symfony, dus uitgeschakeld. In Symfony moet deze functie herbouwd worden. Cake-code kan hiervoor niet zomaar hergebruikt worden.

**Comment by barthuttinga** [comment]
@dvleeuwen Zoals eerder besproken werkt dit nu, maar kan het een probleem opleveren als de twee samen te voegen dossier bv allebei een IZ-dossier hebben, want dat zou resulteren in één basisdossier met twee IZ-dossier, wat niet kan/mag, dus foutmelding. Wat denk jij? Is het de moeite waard voor alle afzonderlijke modules ook een samenvoegfunctie te maken? Of doe ik dat waar nodig handmatig en bekijken we eerst eens even hoe vaak dat nodig is? Wat het meeste voorkomt is - denk ik - dat er twee basisdossier voor dezelfde persoon zijn. Een met bv een IZ-dossier en een met een dagbesteding-dossier. In zo'n geval werkt het samenvoegen gewoon.

**Comment by dvleeuwen** [comment]
Zoals zojuist telefonisch besproken: we laten het zo, en wachten even af
hoeveel 'problemen' dit oplevert met mogelijke dubbele IZ dossiers etc

Op do 7 mrt. 2019 om 13:34 schreef Bart Huttinga <notifications@github.com>:

**Comment by barthuttinga** [comment]
Dus ik sluit deze af. Kan zonodig later weer heropend worden.

**Comment by dvleeuwen** [comment]
voor feedback zie mail Josje 30-07-2019
