### ISSUE TITLE
Datamodel voor OEK

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#66]
OekKlant: is het OEK-dossier voor een klant, bevat wat extra velden (aanmelding, afsluiting etc). Deze bestaat al.

OekTraining: dit zijn de trainingen die door een klant gevolgd kunnen worden. Een klant kan meerdere trainingen volgen. Training heeft startdatum en starttijd en een einddatum en een locatie (tekstveld). Iedere OekTraining hoort bij precies één OekGroep (zie onder).

OekGroep: trainingen vallen in een groep. OekKlanten kunnen aan een of meer OekGroepen gekoppeld worden.

Een OekKlant wordt aan een OekGroep gekoppeld om op de wachtlijst voor een bepaald type training te komen. Is er ruimte bij een training dan wordt een koppeling met OekTraining binnen die OekGroep gemaakt.

**Comment by Evertt** [comment]
Is goed, ga ik aan beginnen!

**Comment by Evertt** [comment]
@barthuttinga Zou je deze willen sluiten? Dat vind ik fijn voor het overzicht. :-)
