### ISSUE TITLE
Klussen en klanten ook vindbaar maken op straatnaam

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#661]

**Comment by dvleeuwen** [comment]
aanpassing nav ecdoverleg dec: niet op straatnaam, maar op werkgebied, volgens indeling die ook bij IZ gebruikt wordt

**Comment by dvleeuwen** [comment]
werkgebied kwam uit overleg naar voren, maar doen we vooralsnog niet
klanten zijn inmiddels vindbaar op straatnaam, ik vraag Sander of klussen ook nog moet

**Comment by dvleeuwen** [comment]
Ha Iris en Sander,
in een vorige mail stelde ik onderstaande vraag:
graag nog even antwoord, dan voeg ik m toe voor komend kwartaal, of haal ik m van de lijst:


En nog een vraag mbt 661:  Klussen en klanten ook vindbaar maken op straatnaam  , klanten zijn nu vindbaar via straatnaam, is verzoek nog geldig dit ook voor klussen zo in te richten, of hiermee voldoende?

dank!
Daan

**Comment by dvleeuwen** [comment]
niet meer nodig, antwoord Iris
