### ISSUE TITLE
Rapportages toevoegen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#666]
- Hoeveel huurders gestart na een bepaalde datum, met naam ed
- Hoeveel verhuurders gestart vanaf een bepaalde datum, met naam ed
- Hoeveel koppelingen gestart vanaf een bepaalde datum
- Hoeveel huuraanbiedingen vanaf een bepaalde datum
- Hoeveel huurverzoeken vanaf een bepaalde datum
- Welke overeenkomst vormen tussen bepaalde data gesloten zijn

**Comment by dvleeuwen** [comment]
Leek op eerder issue (welke?), dus afsluiten, besloten in ecd overleg dec
