### ISSUE TITLE
Verslagen linkt naar verkeerde tabblad

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#669]
Vanuit tab "Koppelingen" in VW-dossier gaat de link "Verslagen"  niet naar tab verslagen van Hulpaanbod, omdat er maar één #verslagen wordt overschreven door #koppelingen in die url.

**Comment by dvleeuwen** [comment]
Besloten in ECDoverleg dec: niet belangrijk (meer), afsluiten
