### ISSUE TITLE
CRUD-acties voor OekGroep

### ISSUE THREAD

**Issue by deregenboog** [deregenboog/ecd#67]
- [ ] index: overzicht van OekGroep, gepagineerd (20 per pagina), sorteerbaar op id en naam
- [ ] add: toevoegen op basis van naam
- [ ] edit: naam groep kunnen bewerken
- [ ] delete: alleen verwijderoptie aanbieden als de groep 0 trainingen bevat

Graag OekGroep::isDeletable() aanmaken, welke checkt of de groep trainingen bevat, zodat je deze zowel in de controller als de views kunt gebruiken.

**Comment by Evertt** [comment]
Zou je deze willen sluiten? Dat vind ik fijn voor het overzicht. :-)
