### ISSUE TITLE
werk/postcode gebied wordt niet ingevuld

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#677]
postcode juist ingevuld, maar werk en postcodegebied blijft leeg

https://beta-ecd.deregenboog.org/iz/klanten/15846/view?redirect=/iz/klanten/

https://ecd.deregenboog.org/iz/klanten/15780/view

**Comment by barthuttinga** [comment]
ECD gebruikt de postcodes van https://data.amsterdam.nl/, als de postcode daar niet te vinden is (zoals twee bovenstaande voorbeelden) wordt hij in ECD ook niet gevonden. Ik sluit deze.

**Comment by barthuttinga** [comment]
Handmatig kunnen toevoegen

**Comment by barthuttinga** [comment]
Opgelost en live. Onder "Beheer" in hoofdmenu kan je nu postcodes toevoegen.
