### ISSUE TITLE
inzichtelijk maken welke personen gereserveerd staan voor koppeling

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#678]
bijvoorbeeld door kleur aan te geven?
wens is dat in alle overzichten/lijsten direct te zien is als vrijwilliger/deelnemer op dit moment gereserveerd staat

**Comment by dvleeuwen** [comment]
+ overzicht kunnen maken van alle reserveringen (deelnemers en vrijwilligers)

**Comment by barthuttinga** [comment]
opgelost en live
gereserveerde hulpvragen/hulpaanbiedingen zijn nu rood in overzichten
