### ISSUE TITLE
Koppelingen filteren datum op datumbereik

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#682]
In ECD via Informele Zorg, Koppelingen kunnen we een export doen van alle koppelingen per deelnemer/vrijwilliger. Je kunt hier filteren op een specifieke datum maar is het ook mogelijk om te filteren op een datumbereik? Dus bijvoorbeeld alle koppelingen met een einddatum tussen 01-01-2017 t/m 30-06-2017.

**Comment by dvleeuwen** [comment]
Besloten in ECDoverleg dec: niet belangrijk (meer), afsluiten

**Comment by barthuttinga** [comment]
Toch nodig ivm controle accountant, dus ik heropen issue.
