### ISSUE TITLE
Datum TBC kan niet gewijzigd worden bij nieuwe intake

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#684]
Maar dat moet wel kunnen

**Comment by dvleeuwen** [comment]
oud punt, maar aansluitend recente mail mbt zelfde:

Hi Daan,
Today I couldn't fill in the information about the TBC-check. Before it was by "Wijzigen" on the line right under the name of the client. If i click on it now there just an empty page saying only "Klant wijzigen". Could you please look into it?
Best,
Ira

**Comment by barthuttinga** [comment]
Opgelost en live.
