### ISSUE TITLE
Rapportagemogelijkheden toevoegen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#686]
- Hoeveel huurders gestart na een bepaalde datum, met naam ed
- Hoeveel verhuurders gestart vanaf een bepaalde datum, met naam ed
- Hoeveel koppelingen gestart vanaf een bepaalde datum
- Hoeveel huuraanbiedingen vanaf een bepaalde datum
- Hoeveel huurverzoeken vanaf een bepaalde datum
- Welke overeenkomstvormen tussen bepaalde data gesloten zijn

**Comment by dvleeuwen** [comment]
Ha Juul,
vraagje op de stapel ecd verzoeken uit vorige jaar kwam is deze nog tegen:

Rapportages kunnen maken van:
Hoeveel huurders gestart na een bepaalde datum, met naam ed
Hoeveel verhuurders gestart vanaf een bepaalde datum, met naam ed
Hoeveel koppelingen gestart vanaf een bepaalde datum
Hoeveel huuraanbiedingen vanaf een bepaalde datum
Hoeveel huurverzoeken vanaf een bepaalde datum
Welke overeenkomstvormen tussen bepaalde data gesloten zijn

Klopt bovenstaande nog steeds, of moet daar iets bij/af?
Dan zetten we m voor dit kwartaal in de planning om aan te passen.

groet!
Daan

**Comment by barthuttinga** [comment]
@dvleeuwen Ik assign deze aan jou tot je reactie van Juul hebt. Zet je hem dan weer op mijn naam?

**Comment by dvleeuwen** [comment]
Ha Juul,
als er op onderstaande nog acties nodig zijn hoor ik het graag terug, anders sluiten we ticket.

groet!
Daan

**Comment by dvleeuwen** [comment]
blijft stil,
dus ik sluit deze af

**Comment by dvleeuwen** [comment]
reactie Juul:
Dat zijn inderdaad rapportages die we graag nog zouden willen kunnen draaien.

Het zou ook fijn zijn als we bij rapportages net als datum ook nog allemaal of per gemeente een rapportage kunnen uitdraaien? Is het ook mogelijk om ergens bij de koppeling een optie gemeente toe te kunnen voegen?
We hebben nu Zaanstad, Amsterdam, Haarlem, Velsen en Haarlemmermeer. 
Het zou handig zijn als we zelf hier Gemeente aan kunnen toevoegen wanneer er meer aansluiten.

Ik heropen

**Comment by jtborger** [comment]
Het rapportage gedeelte is even nieuw voor mij.
Even kijken of ik het goed snap:

1. Hoeveel huurders gestart na een bepaalde datum, met naam ed
Daarmee wordt bedoeld: WELKE huurders zijn gestart in een bepaalde periode, en tel het aantal even op. Denk ik? Gezien ze de naam erbij willen?

2. Hoeveel verhuurders gestart vanaf een bepaalde datum, met naam ed
Idem?
3. Hoeveel koppelingen gestart vanaf een bepaalde datum
Bestaat deze niet al? Je kunt nu koppeligen selecteren vanaf een bepaalde datum en dan zie je van alles qua koppelingen?
4. Hoeveel huuraanbiedingen vanaf een bepaalde datum
Valt dit niet ook al te zien via Verhuurders?
5. Hoeveel huurverzoeken vanaf een bepaalde datum
Idem?
6. Welke overeenkomstvormen tussen bepaalde data gesloten zijn
Staat er toch ook al in? Zie ik iets over het hoofd?

**Comment by jtborger** [comment]
Anders geformuleerd; - Wat moet er anders aan de huidige rapportages? 
ZIjn dat alleen die eerste twee punten eigenlijk?
Of bedoelen ze toch heel iets anders?

**Comment by dvleeuwen** [comment]
Ha Jan,
lastige in deze (en alle Onder de Panne punten) is dat de projectleider
(Juul) uitgevallen is.
Nieuwe collega's nemen dit nu over, maar zullen waarschijnlijk nog niet
alles kunnen beantwoorden.
Ik ga even uitzoeken bij wie ik deze vraag nu het beste neer kan leggen, en
kom er op terug zodra er antwoord/duidelijkheid is.
Tot die tijd dit issue maar even laten rusten.

groet
Daan



Op di 27 aug. 2019 om 15:18 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Ik leg de vraag neer bij Lisanne vd Ronden (nieuwe collega ODP) en wacht antwoord af

**Comment by dvleeuwen** [comment]
Lijkt niet om rapportages te gaan, maar om selecties. 
Ik ga na wat er uit lijstje al wel/niet mogelijk is. En pas dit issue later aan.

**Comment by jtborger** [comment]
enige update?

**Comment by dvleeuwen** [comment]
Ik heb het idee dat alle bovenstaande data (inmiddels?) eigenlijk te genereren is. Bovendien is het een issue van bijna een jaar terug. En is hier in recent OdP-ECD overleg niets over gezegd/gevraagd. Ik sluit issue. Mocht er later toch een wens liggen heropen ik.
