### ISSUE TITLE
Mutaties in ECD doormailen naar admin

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#687]
Niet elke wijziging in een dossier moet een mail opleveren, want dan worden er zoveel mails gestuurd dat het niet meer te behappen is. Het moet dus alleen om relevante wijzigingen gaan. Zie mailwisseling februari 2018.

**Comment by dvleeuwen** [comment]
Besloten in ECDoverleg dec: niet belangrijk (meer), afsluiten
