### ISSUE TITLE
uitdraai kunnen maken van afsluitreden koppeling 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#689]

**Comment by barthuttinga** [comment]
Dit kan al door een download van koppelingen te maken.

**Comment by dvleeuwen** [comment]
Dit is inderdaad slecht verwoord zie ik nu:
Gaat niet om de afsluitreden, maar om de succesindicatoren die aangevinkt
worden na afsluiting.
Deze zijn niet terug te vinden in de download.
Ik heropen.

groet!
Daan

Op do 21 mrt. 2019 om 10:27 schreef Bart Huttinga <notifications@github.com

**Comment by barthuttinga** [comment]
Succesindicatoren aan download koppelingen toegevoegd. Staat live.
