### ISSUE TITLE
CRUD-acties voor OekTraining

### ISSUE THREAD

**Issue by deregenboog** [deregenboog/ecd#69]
- [x] index: overzicht van OekTraining, gepagineerd (20 per pagina), sorteerbaar op id, naam, startdatum, einddatum
- [x] add
- [x] edit
- [x] delete: alleen verwijderoptie aanbieden als OekTraining 0 deelnemers heeft

Graag OekTraining::isDeletable() aanmaken, welke checkt of de training deelnemers heeft, zodat je deze zowel in de controller als de views kunt gebruiken.

**Comment by Evertt** [comment]
@barthuttinga Zou je deze willen sluiten? Dat vind ik fijn voor het overzicht. :-)
