### ISSUE TITLE
toevoegen dagbestedingsplekken

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#698]
-Claverhuis
-veegploeg Claverhuis

**Comment by barthuttinga** [comment]
@dvleeuwen Moet "Claverhuis" als locatie en "Veegploeg Claverhuis" als project worden toegevoegd?

**Comment by dvleeuwen** [comment]
Ha Bart,
ik heb het even na moeten vragen:
"Claverhuis" is locatie.
En "Claverhuis" & "Veegploeg Claverhuis" zijn beiden projecten.

Dus 1x locatie toevoegen, en 2x project.

Dank!
Daan

Coördinator Informele Zorg

Werkdagen: maandag, dinsdag, donderdag en vrijdag
Tel: 020 - 5317 600 of 06 - 14 86 66 15
dvleeuwen@deregenboog.org

Bezoekadres: Oranje Nassaulaan 51-2, 1075 AK, Amsterdam
www.deregenboog.org

aanmelden deelnemer: www.hulpvanderegenboog.org





Op ma 17 dec. 2018 om 12:12 schreef Bart Huttinga <notifications@github.com
