### ISSUE TITLE
CRUD-acties voor OekKlant

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#70]
- [x] index: overzicht van OekKlanten, gepagineerd (20 per pagina), sorteerbaar op id, naam, aanmelddatum, afsluitdatum
- [x] add: "aanmelddatum" (verplicht) en "verwezen door" (optioneel) weergeven
- [x] edit
- [x] afsluiten: "afsluitdatum" (verplicht) en "verwezen naar" (optioneel) weergeven

Delete voorlopig niet implementeren.

**Comment by Evertt** [comment]
@barthuttinga Zou je deze willen sluiten? Dat vind ik fijn voor het overzicht. :-)
