### ISSUE TITLE
Beheerfunctie afsluit reden koppeling werkt niet

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#700]
zowel in beta als in regulier ECD; als je via beheer redenen op niet actief zet, blijven deze toch zichtbaar in het rijtje staan van afsluit redenen koppeling
https://ecd.deregenboog.org/iz/admin/afsluitredenenkoppeling/?redirect=/iz/koppelingen/28474/close

**Comment by barthuttinga** [comment]
opgelost en live
