### ISSUE TITLE
bij klantgegevens wijzigen kan BSNnummer niet (meer) aangepast worden

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#702]
Het gaat om het volgende;

Voorheen kon je na het potloodje rechts het bsn nr wijzigen, deze optie is verdwenen.

https://ecd.deregenboog.org/klanten/view/5629721

Dank alvast!

Groetjes,
Bianca

**Comment by barthuttinga** [comment]
@dvleeuwen Wat is hier precies het probleem? BSN is gewoon aan te passen.

**Comment by barthuttinga** [comment]
Vanuit Inloop deed klant wijzigen het niet, ik neem aan dat dat hier bedoeld werd. Ik heb het opgelost. Gaat vandaag live.
