### ISSUE TITLE
foutmelding: als ik op een intervisiegroep klik, kom ik op foutmeldingspagina terecht

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#705]
zowel in beta als in regulier

**Comment by dvleeuwen** [comment]
niet bij alle intervisiegroepen, zie bijvoorbeeld groep 61 en 78

https://ecd.deregenboog.org/iz/intervisiegroepen/?redirect=/iz/intervisiegroepen/74/view

**Comment by barthuttinga** [comment]
opgelost en live

**Comment by dvleeuwen** [comment]
Werkt nog niet helemaal; zie bv  intervisiegroep #61
blijf foutmelding krijgen als ik er op klik

**Comment by barthuttinga** [comment]
opgelost en live
