### ISSUE TITLE
velden bij maatschappelijk werk mogen ook leeg blijven

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#706]
verzoek eva westerneng:

punt is dat als ik de 'extra'  gegevens van maatschappelijk werk wil wijzigen, en bijvoorbeeld een bewindvoerder wil noemen, ik dat niet op kan slaan zonder alle andere vakken in te vullen, over bv woningnet regisratie en inkomen. Kan jij regelen dat er in dat stuk ook velden leeg kunnen blijven?

**Comment by barthuttinga** [comment]
@dvleeuwen Is dit nog relevant? Volgens mij is geen van de velden verplicht.

**Comment by dvleeuwen** [comment]
Ha Eva,
zie de mail die hieronder hangt, vraag 2 was doorgeschoven naar volgende kwartaal, daar zijn we nu mee bezig. 
Vraag is of deze nog relevant is, volgens Bart zijn er geen verplicht in te vullen velden (meer?)

Wil jij eens checken, hoor graag terug of we er nog iets mee moeten, of dat hij gesloten kan worden.

groet!
Daan

**Comment by dvleeuwen** [comment]
Het probleem is inderdaad verholpen, ticket kan gesloten...

Met vriendelijke groet, 

Eva Westerneng
