### ISSUE TITLE
inzichtelijk maken bezoeken inloophuis geschiedenis

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#707]
nu zijn enkel de laatste 40 bezoeken terug te zien, verzoek is of volledige history weer getoond kan worden

**Comment by dvleeuwen** [comment]
is opgelost, aangepast door Bart. Nu laatste 250 zichtbaar.

**Comment by barthuttinga** [comment]
Ik laat nu alle registraties t/m de drie voorgaande jaren zien. Onbeperkt ben ik geen voorstander van.

**Comment by dvleeuwen** [comment]
Ok prima,
mocht er meer nodig zijn horen we het wel.

Op do 21 feb. 2019 om 11:31 schreef Bart Huttinga <notifications@github.com
