### ISSUE TITLE
in ECD Homeservice moet er vaak meerdere keren geklikt worden voor volgende pagina

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#722]
opmerking Sander:

Ik zie nu dat als ik onder 'stadsdeel', 'startdatum' of 'einddatum' klik in de klus dat de klus geopend wordt. Klik ik onder kopje 'activiteit' of 'Status' dan opent ECD de klus niet.
Lijkt erop dat twee velden dus niet meer doorklikbaar zijn.

**Comment by barthuttinga** [comment]
Opgelost, staat live.

**Comment by dvleeuwen** [comment]
Krijg terug te horen van Sander, dat er helaas nog steeds problemen zijn met dit issue:

"Via Homeservice, tabblad 'Klussen' en dan klikken we altijd een klus open onder kolom 'Activiteit', of 'Status'. Deze zijn beide niet doorklikbaar."

**Comment by barthuttinga** [comment]
@dvleeuwen Ondervind jij zijn probleem ook? Ik kan gewoon doorklikken.

**Comment by barthuttinga** [comment]
@dvleeuwen Ik weet niet goed wat ik hiermee moet. In zowel Chrome als Firefox werkt het bij mij gewoon. Even bellen vandaag?

**Comment by dvleeuwen** [comment]
prima Bart,
voor jou ok rond 3 uur even bellen?

groet!
Daan

Op do 7 feb. 2019 om 09:19 schreef Bart Huttinga <notifications@github.com>:

**Comment by dvleeuwen** [comment]
vraag voor Sander:
kun jij even checken of jij in klussenoverzicht nog steeds niet door kan klikken onder 'activiteit' en 'status'?
Dit kan bij mij nu wel, waar het eerder niet werkte. Wil even zeker weten of het bij jou nu ook werkt, dan kan deze gesloten worden.

**Comment by dvleeuwen** [comment]
nog geen antwoord Sander, maar ga er vanuit dat bij hem nu ook werkt. Sluit issue. Mocht ik terughoren van Sander dat het niet werkt heropen ik.
