### ISSUE TITLE
'nu binnen' 1 pagina ipv meerdere pagina's

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#725]
verzoek vanuit inloophuizen:

We zouden het liefst op 1 pagina alle namen willen zien van de mensen die nu binnen zijn. Dat maakt alles wat overzichtelijker en gaat het tellen van hoeveel mensen we op een dag binnen hebben gehad wat makkelijker.
 (dit is bij het kopje 'nu binnen')

**Comment by barthuttinga** [comment]
opgelost en live
