### ISSUE TITLE
foutmelding bij toevoegen vrijwilliger aan intervisiegroep 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#726]
Als ik vanuit ecd intervisie groepen iemand wil toevoegen geeft die een foutmelding. 

https://ecd.deregenboog.org/iz/intervisiegroepen/21/view?redirect=/iz/intervisiegroepen/

Het lukt wel als ik het vanuit de vrijwilliger doe.

**Comment by barthuttinga** [comment]
opgelost en live
