### ISSUE TITLE
nieuwe zoekfuncties homeservice

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#728]
verzoek Sander

Nieuw is dat wij graag onder de tabbladen Klant, Dienstverlener en Vrijwilliger willen kunnen zoeken op Hulpverlener, Telefoonnummer en adres.

**Comment by barthuttinga** [comment]
Opgelost en live. Ik heb aangenomen dat adres/telefoon op de klant/dienstverlener/vrijwilliger sloegen en niet op de hulpverlener.

**Comment by dvleeuwen** [comment]
@barthuttinga 
telefoon lijkt nog te ontbreken, kan die toegevoegd worden

**Comment by barthuttinga** [comment]
Werd al gebruikt in zoekcriteria, maar nu ook in lijst toegevoegd.
