### ISSUE TITLE
verslagen worden niet chronologisch weergegeven 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#733]
zie hier:

https://ecd.deregenboog.org/dagbesteding/deelnemers/300/view?redirect=/dagbesteding/deelnemers/#verslagen

**Comment by barthuttinga** [comment]
Bij deelnemers werden in één lijst eerste de verslagen van de deelnemer en daarna de verslagen van de trajecten weergegeven. Die splitsing heb ik nu met kopjes duidelijker gemaakt. Binnen een deelnemer/traject worden de verslagen wel anti-chronologisch gesorteerd.
