### ISSUE TITLE
intakeoverzicht bezoeker klopt niet

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#735]
bericht Bianca:
Maar het gaat dus nu om het intake overzicht wat weg is, bij sommige zie je daarboven een ZRM overzicht maar ook niet bij alle.  Als ik dan op intake overzicht klik kom ik een lijst met alle bezoekers zonder zoekbalk..
Kunnen we het overzicht van de oude intakes nog terug krijgen zodat we deze volledig kunnen bekijken.

https://ecd.deregenboog.org/inloop/klanten/5629721/view?redirect=/inloop/klanten/

https://ecd.deregenboog.org/inloop/intakes/?klant=5629721&redirect=/inloop/klanten/5629721/view

Bedoeling is dus bij intakeoverzicht de intakes vd betreffende persoon te zien

**Comment by barthuttinga** [comment]
Opgelost en live
