### ISSUE TITLE
verslag

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#737]

**Comment by dvleeuwen** [comment]
verzoek vanuit zowel IZ als MW:
als je een verslag aan het tikken bent is nergens te zien in welk dossier je zit. Als het hectisch is zorgt dit soms voor verwarring. Kan in beeld staan welk dossier je op dat moment werkt?

**Comment by dvleeuwen** [comment]
dus naam deelnemer/vrijwilliger intake, of koppel

**Comment by barthuttinga** [comment]
Bij IZ en MW aangepast. Staat live.
