### ISSUE TITLE
bij afsluiten dossier maatschappelijk werk, reden afsluiting duidelijk zichtbaar

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#738]
Michael:
- Wanneer een dossier wordt afgesloten is het handig als de reden van afsluiting duidelijk en makkelijk kan worden gezien (zodat bijvoorbeeld EU burgers bij een nieuwe intake eerst naar Amoc worden gestuurd).

waar?
Graag in de klantenlijst de afsluiting en reden van afsluiting vermelden.

Het is dan wel van belang dat een afgesloten dossier niet meer geopend kan worden. Of dat dan de reden van afsluiting verschijnt.

**Comment by barthuttinga** [comment]
In de module MW is er geen mogelijkheid om een dossier af te sluiten toch? Bedoel je dat de status van het inloopdossier weergegeven moet worden? Dat heb ik nu gedaan, gaat zo live. Ik sluit het ticket. Heropen hem als het toch anders moet zijn.
