### ISSUE TITLE
overzicht alle contacten in klantenlijst 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#739]
Michael:
in de klantenlijst zijn alleen de face2face contacten van het maatschappelijk werk te zien. Graag alle contacten vermelden (zonder de rapportages).

**Comment by barthuttinga** [comment]
@dvleeuwen Ik snap deze niet.

**Comment by dvleeuwen** [comment]
Poe ik ook niet... ;)

Ga ik navragen!

Op ma 25 mrt. 2019 om 15:53 schreef Bart Huttinga <notifications@github.com

**Comment by dvleeuwen** [comment]
Daarbij kwam deze vraag van jou naar boven: 
in de klantenlijst zijn alleen de face2face contacten van het maatschappelijk werk te zien. Graag alle contacten vermelden (zonder de rapportages). 

Bart (en ik) hebben hier wat toelichting op nodig, kun je specificeren wat er precies gewenst wordt? (wat voor contacten?)

dank!
Daan

**Comment by dvleeuwen** [comment]
toelichting ontvangen en aan Bart verstuurd

**Comment by barthuttinga** [comment]
@dvleeuwen Ik snap het nog steeds niet, heb gereageerd op je mail van toen.

**Comment by dvleeuwen** [comment]
Bart:
Hoi Daan, ik snap het nog steeds niet. Volgens mij worden de contactmomenten van MW uberhaupt niet getoond bij Inloop. En het face-to-face-contact van 13-9 zie ik ook nergens. Kan jij eens meekijken?


Daan -> Michael

Ha Michael,
helaas was onderstaande nog altijd niet duidelijk genoeg voor Bart, zie onderstaande mails.
Waar zie jij laatste contact 13-9 staan? 
En volgens Bart is bij inloop laatste contact MW sowieso niet te zien.
Ongelukkig genoeg is Bart nu weg, en wachten wij op opvolger. Dus alles vertraagt weer :(
Maar hopelijk kunnen we met opvolger verder aan dit punt. Kun jij nog eens naar onderstaande kijken, en checken of Barts opmerking correct is?

**Comment by dvleeuwen** [comment]
zie mailwisseling EWA/MICHAEL/WILLEMIJN 3-5-2019

ik sluit issue (voorlopig?)
