### ISSUE TITLE
trajecten zelfstandig kunnen verwijderen of aanpassen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#740]
Medewerkers willen zelf trajecten kunnen wijzigen of verwijderen (na foutieve invoer)

**Comment by barthuttinga** [comment]
Wijzigen kon al. Verwijderen kan nu ook, maar alleen als:
- er geen documenten zijn; en
- er geen verslagen zijn; en
- er geen uren zijn ingevuld; en
- de rapportages geen documenten hebben.

**Comment by barthuttinga** [comment]
Gaat vandaag live.

**Comment by barthuttinga** [comment]
Live zetten komt volgende week, tegelijk met ander werk.
