### ISSUE TITLE
niet rechthebbende moeten ook toegang kunnen krijgen in Amoc Nachtopvang

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#742]
Ha Aukje en Henner,
het probleem is inmiddels duidelijk (dat is stap 1 ;)
ECD heeft 2 klantenlijsten: inclusief mensen niet-rechthebbend en minder dan 6 maanden in ons systeem, en zonder niet rechthebbende minder dan 6 maanden in ons systeem. 
1ste lijst is enkel toegankelijk voor Amoc, 2de lijst voor alle inlopen.
Nu maakt nachtopvang Amoc foutief gebruik vd 2de lijst. Dit gaan we met spoed aanpassen, verwacht dat dit volgende week aangepast is.

groet!
Daan

**Comment by barthuttinga** [comment]
De toegangsregels van AMOC gelden nu ook voor nachtopvang en AMOC gebruikersruimte.
