### ISSUE TITLE
registratie tijdstip bezoekers Ondro Bong vervroegen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#748]
verzoek Willemijn

Kan het tijdstip waarop we Ondro Bong bezoekers kunnen registreren in het ECD vervroegd worden naar 10 uur? (Valentijn is verhuisd naar Ondro Bong en we starten al om 10.00 uur met deelnemers en meewerkend bezoekers, vandaar)

**Comment by barthuttinga** [comment]
Hoi Daan, dit kan via de interface. Inloophuizen => Beheer => Locaties => Bekijken => dan zijn de openingstijden per dag te wijzigen

**Comment by dvleeuwen** [comment]
aangepast en afgesloten
