### ISSUE TITLE
Bezoekers apart toegang tot Ondro Bong geven

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#749]
Ik heb nog iets: we gaan vanaf morgen sommige clienten die hier korter dan 6 maanden zijn toegang verlenen tot Ondro Bong. Nu hebben we in ECD alleen de keuze AMOC/ of alle andere lokaties. 
Kan je het ECD zo aanpassen dat we ook clienten alleen toegang tot AMOC en Ondro Bong kunnen verlenen?

**Comment by dvleeuwen** [comment]
= verzoek Aukje

**Comment by barthuttinga** [comment]
Boven "Startdatum toegang overigen" veld "Startdatum Ondro Bong" toevoegen.

**Comment by barthuttinga** [comment]
Opgelost zoals besproken en staat (bijna) live.
