### ISSUE TITLE
OekKlanten-lijst moet te filteren zijn op OekGroep

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#75]
Een OekKlant die een associatie met een OekGroep heeft staat in feite op de wachtlijst voor een OekTraining uit de betreffende OekGroep. Er moet een wachtlijst getoond kunnen worden voor een bepaalde OekGroep, zodat deze mensen nagebeld kunnen worden om te vragen of ze aan een bepaalde training willen meedoen. In feite betekent dit dus: klantenlijst filteren op groep, zodat je alle klanten te zien krijgt die van die groep "lid" zijn.

**Comment by Evertt** [comment]
@barthuttinga Zou je deze willen sluiten? Dat vind ik fijn voor het overzicht. :-)
