### ISSUE TITLE
aangevinkte buttons uitschakelen bij herintake

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#750]
Willemijn:
Hoi Daan,

ik kwam er gisteren per toeval achter dat als je een intake toevoegt, deze automatisch de vinkjes uit de oude intake overneemt in het gedeelte' ondersteuning'. Denk dat het gemakkelijker is als deze buttons leeg zijn bij een nieuwe intake?

**Comment by barthuttinga** [comment]
Opgelost, gaat vandaag live.
