### ISSUE TITLE
download eropuit kalender enkel de 'wel verzenden'

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#751]
Bij download is nu de hele lijst (wel & niet verzenden). Voor medewerkers een onnodige tussenstap om vervolgens te sorteren en verwijderen.
Graag dus enkel de gegevens van mensen die wel eropuit willen in de download, zodat ie direct bruikbaar is als verzendlijst.

**Comment by barthuttinga** [comment]
@dvleeuwen Volgens mij worden de kalenders zowel per post als per e-mail verzonden, dus filtering zal altijd nog moeten plaatsvinden. Dit ticket lijkt me dan ook niet relevant. Bovendien wordt de download wellicht ook voor andere doeleinden dan verzending gebruikt. Ik sluit hem, open hem maar weer als er toch iets moet gebeuren.

**Comment by dvleeuwen** [comment]
Goed punt mbt mail/post Bart.
Voor nu gaat ie alleen per post naar deelnemers, en deze lijst wordt enkel
daarvoor gebruikt.
Ik check voor zekerheid even bij aanvragers van dit punt. En kom bij je
terug mocht er toch wat mee moeten.

Bas/Elina:
graag jullie input mbt de download Eropuit in ECD.
Jullie verzoek was hierin enkel te tonen mensen die m wel willen ontvangen.
Maar Bart wijst er terecht op dat er 2 categorien zijn: post en email. Wat
willen we hiermee?

groet!
Daan

Op do 21 mrt. 2019 om 13:17 schreef Bart Huttinga <notifications@github.com
