### ISSUE TITLE
Toegang tot gebruikersruimte vervalt als > 2 maanden niet geweest

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#752]

**Comment by dvleeuwen** [comment]
Bart even check voor zekerheid:
je noemt in dit issue 'inloophuis', maar als ik mail Janneke goed begrijp
gaat het hierbij enkel om gebruikersruimte, had je dat zo toegepast?

groet
Daan

Op di 12 feb. 2019 om 09:14 schreef Bart Huttinga <notifications@github.com

**Comment by barthuttinga** [comment]
@dvleeuwen Je hebt gelijk, titel van issue klopte niet.
