### ISSUE TITLE
'opmerkingen' hoger plaatsen in dossier

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#753]
zodat er niet naar beneden gescrold hoeft te worden, maar direct zichtbaar

**Comment by dvleeuwen** [comment]
zet deze na overleg in kwartaal 1 ipv 2, blijkt dat hierdoor echt dingen mis gaan / over het hoofd gezien worden bij maatschappelijkwerk.

**Comment by dvleeuwen** [comment]
aanvullend verzoek: ook 'schorsingen' omhoog op paging, zodat t direct zichtbaar is zonder naar beneden te scrollen

**Comment by barthuttinga** [comment]
opgelost en live
