### ISSUE TITLE
checken welke dossiers er nog op 'Bart Huttinga' staan

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#755]
als het er weinig zijn: Daan zoekt handmatig per dossier welke naam medewerker logisch zou zijn
als het er veel (20+) zijn: overleg wat hier mee te doen

**Comment by barthuttinga** [comment]
Het zijn er 3000+. In het verleden was medewerker niet verplicht, dat is wel verplicht geworden en daarbij zijn ze standaard op mijn naam gekomen. Laten we even overleggen. Handigst is denk ik om medewerker bij nieuwe dossiers wel verplicht te maken, maar ze op niks te zetten waar ze nu op mijn naam staan.

**Comment by dvleeuwen** [comment]
ja, mee eens!

Op do 7 mrt. 2019 om 13:55 schreef Bart Huttinga <notifications@github.com>:

**Comment by barthuttinga** [comment]
opgelost
