### ISSUE TITLE
bij deelnemers en vrijwilligers overzicht in IZ nieuwe kolom 'medewerker aanmelding' 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#756]

**Comment by barthuttinga** [comment]
@dvleeuwen Dat veld is er nu niet, bij de aanmelding wordt geen medewerker opgegeven. Je bedoelt dus niet alleen een kolom toevoegen aan het overzicht, maar ook een medewerker-veld toevoegen aan de aanmelding zelf?

**Comment by dvleeuwen** [comment]
ja!

Op do 7 mrt. 2019 om 14:29 schreef Bart Huttinga <notifications@github.com>:

**Comment by barthuttinga** [comment]
Toegevoegd en gaat deze ochtend live.
