### ISSUE TITLE
Bij koppelen klant aan training moet de koppeling met betreffende groep vervallen

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#76]
Lidmaatschap van een OekGroep betekent dat je op de wachtlijst staat van dat type training. Op het moment dat een OekKlant gekoppeld wordt aan een OekTraining moet de koppeling met de betreffende OekGroep vervallen. Dit is business logic dus graag in de modellen regelen en niet in de controllers.

**Comment by Evertt** [comment]
@barthuttinga Zou je deze willen sluiten? Dat vind ik fijn voor het overzicht. :-)
