### ISSUE TITLE
mijn dagbesteding linkt door naar 'trajecten' ipv 'personen' 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#760]
hierdoor onstaat verwarring, als je in dit scherm bijvoorbeeld een document toevoegt hangt het niet in het deelnemerdossier, maar aan traject vast

**Comment by barthuttinga** [comment]
Het zijn lijsten van trajecten. Dan lijkt het me logisch dat je bij klikken in het traject terecht komt.

**Comment by dvleeuwen** [comment]
Het is uiteindelijk een lijst deelnemers toch?
Met andere woorden: een deelnemer met meerdere trajecten staat niet
meerdere keren in deze lijst.

Ik neem dit punt even mee om met Bas te bespreken (wat zij willen). Kom ik
op terug, tot die tijd hoef je er niets mee te doen.

groet!
Daan

Op ma 25 feb. 2019 om 15:30 schreef Bart Huttinga <notifications@github.com

**Comment by barthuttinga** [comment]
Nee, het is een lijst met trajecten. Een persoon met meerdere trajecten staat dus meerdere keren in de lijst.
