### ISSUE TITLE
foutmelding bij toevoegen document onder trajecten

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#761]
als je hier document toevoegt kom je op foutmeldingspagina terecht,
echter blijkt document daarna wel gewoon toegevoegd

**Comment by barthuttinga** [comment]
Ik krijg geen foutmelding. Heb je meer informatie? (per mail)

**Comment by barthuttinga** [comment]
Foutmelding is bij verwijderen, niet bij toevoegen.

**Comment by barthuttinga** [comment]
Opgelost en live
