### ISSUE TITLE
beheer projecten: niet actief wordt alsnog getoond

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#762]
via beheer projecten op niet actief gezet, maar deze worden alsnog getoond bij projecten
zie Zero Wastlab

https://ecd.deregenboog.org/dagbesteding/admin/projecten/?url=dagbesteding/admin/projecten/&redirect=/dagbesteding/trajecten/212/view&sort=project.naam&direction=asc&page=3

https://ecd.deregenboog.org/dagbesteding/trajecten/161/edit?redirect=/dagbesteding/trajecten/161/view

**Comment by barthuttinga** [comment]
opgelost en live
