### ISSUE TITLE
foutmelding bij aanmaken nieuwe klus 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#767]
bericht Sander

Ik maak zojuist een nieuwe klus aan in ECD en krijg op deze pagina:
https://ecd.deregenboog.org/hs/klussen/add?klant=984&redirect=/hs/klanten/984/view#klussen
Deze melding:

image.png
Klus kan ik wel gewoon aanmaken en slaat ECD goed op.

**Comment by dvleeuwen** [comment]
afbeelding vd foutmelding gemaild naar Bart

**Comment by barthuttinga** [comment]
opgelost in commit f8f00547bd55242c0e5d59a56769bb8a4bc03c23, staat al live
