### ISSUE TITLE
klantentabblad terugwijzigen naar standaard 'niet actief' ipv 'actief'

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#768]
bericht Sander,

In ECD staat het tabblad klanten sinds de laatste update nu altijd gesorteerd op ' ACTIEF',  graag weer terug wijzigen naar 'LEEG'  (dus alle klanten tonen met of zonder klus):
https://ecd.deregenboog.org/hs/klanten/?redirect=/hs/klussen/add

**Comment by barthuttinga** [comment]
opgelost, gaat straks live

**Comment by dvleeuwen** [comment]
Iris wijst me erop dat dit opnieuw omgedraaid lijkt te zijn. Jan snap jij hoe dit kan gebeuren.
Graag weer instellen dat de lijst dus standaard op niet-actief ipv actief staat.

**Comment by jtborger** [comment]
Op niet-actief of op leeg?
Ik heb hem nu op leeg gezet.
Waarom het veranderd is: geen idee. Kan ik niet helemaal volgen, heb gekeken maar kan de reden niet achterhalen. Wel dat het gebeurd is. Maar waarom....
2.2.47
