### ISSUE TITLE
nog niet actieve deelnemers kunnen filteren/tonen per coordinator

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#771]
ferdgie:
Waar staat de open hulpvraag deelnemer? Dit zijn deelnemers die we alvast invoeren in ECD verslaglegging over doen en vermoedelijk in traject komen maar voorlopig dus nog niet gekoppeld zijn aan een traject waardoor ze niet in je caseload overzicht staan. Het is voor ons belangrijk om deze op het netvlies te houden.

**Comment by barthuttinga** [comment]
opgelost en live
