### ISSUE TITLE
uitzoeken welke bezoekers getoond worden in Ladis rapportage

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#774]
datavelden lijken niet te werken, alle bezoekers worden getoond?

**Comment by barthuttinga** [comment]
@dvleeuwen Klopt, nu worden alle klanten getoond. Voor zover ik dat kan beoordelen is dat altijd zo geweest. Hoe moeten de datumvelden gebruikt worden om te filteren?

**Comment by dvleeuwen** [comment]
Ha Bart,
Zie hieronder antwoord van Hans, op de vraag welke bezoekers nu eigenlijk getoond moeten worden in de Ladis rapportage.

Ik kan me voorstellen dat excelbestand het makkelijkste is (minste werk?). Wat denk jij als je onderstaande leest?

groet
Daan



---------- Forwarded message ---------
From: Hans Wijnands <hwijnands@deregenboog.org>
Date: di 5 mrt. 2019 om 17:35
Subject: Re: Ladis
To: ECD De Regenboog Groep <ecd@deregenboog.org>


Dag

heb daar vrijdag met Ton Mol onderzoeker van Ladis over gesproken en de wens is als volgt;
Alle bezoekers laten zien van de afgelopen 10 jaar is hun wens, daarbij dan datum eerste bezoek en datum laatste bezoek. Voor hen geldt dat als iemand 6 maanden niet is geweest er sprake is van een uitschrijving op de laatste bezoekdag. Als iemand na 6 maanden weer terugkomt is er sprake van herintake op de eerste bezoekdag. 
Nu weet ik niet of daar een goeie rapportage van te maken is. Het kan ook zo zijn dat het zichtbaar wordt in een excell sheet en dat zij dan gaan vogelen met het bestand om dat soort gegevens eruit te halen. Laat maar weten wat er wel en niet kan. Dan kan ik dat weer even overleggen met Ladis.  
Met vriendelijke groet,

**Comment by barthuttinga** [comment]
Aangepast en live gezet
