### ISSUE TITLE
fout met pop-up en opmerkingen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#776]
zie bijvoorbeeld dossier 5612812

-Als deze bezoeker ingecheckt wordt, wordt pop-up niet getoond

-In lijst 'nu binnen' staat vermeld 4 opmerkingen, waar dit 2 zou moeten zijn (2 staan als opgelost aangevinkt)

**Comment by barthuttinga** [comment]
@dvleeuwen Er werd alleen gekeken naar de laatste opmerking: was deze ongezien/onopgelost dan werd een pop-up getoond bij inchecken, anders niet. Oudere opmerkingen deden er niet toe. Ik heb het nu zo aangepast dat alle ongeziene/onopgeloste opmerkingen in de pop-up getoond worden.

**Comment by barthuttinga** [comment]
Gaat zo live
