### ISSUE TITLE
probleem met intakes wijzigen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#777]
Arend belt:

In dit dossier 
https://ecd.deregenboog.org/inloop/klanten/5611195/view?redirect=/inloop/klanten/
mist Arend de knop "wijzigen" onder "laatste intake" 
(hij heeft intake dezelfde ochtend aangemaakt, en wilde aanvullen)

via deze weg is er wel een knop "wijzigen" zichtbaar, maar krijgt hij foutmelding ("neem contact op met Daan) zodra hij er op klikt
https://ecd.deregenboog.org/inloop/intakes/27669/view?redirect=/inloop/intakes/

**Comment by barthuttinga** [comment]
Probleem niet terug te vinden, ook niet als ik namens hem inlog.
