### ISSUE TITLE
na herintake zijn bezoekers onvindbaar in tab inloophuizen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#778]
Ha Bart,
als het je lukt OndroBong registratie te corrigeren, en je hebt nog tijd. Kijk svp even naar onderstaande. Hier lijkt opnieuw iets mis te gaan bij herintakes bezoekers.

Onderstaande namen zijn te vinden via tab klanten (waar ook te zien is dat ze al meerdere intakes/ZRMs hebbben).
Maar zoek je via inloophuizen/bezoekers of registratie komen ze niet naar boven.

Fijn als je tijd hebt om hier vandaag naar te kijken! (ik maak ook direct Github aan)

dank!
Daan

---------- Forwarded message ---------
From: Aki Herlyn <aherlyn@deregenboog.org>
Date: ma 4 mrt. 2019 om 16:48
Subject: niet kunnen registreren
To: ECD De Regenboog Groep <ecd@deregenboog.org>

Dag allen,
oude clienten, die een niewue intake krijgen, kunnen niet worden geregistreerd,
**5623473
925
5632647
(ivm privacy namen vervangen door nummers DvL)**

en ik denk nog meer, we raken daardoor veel gegevens kwijt.
Groet aki

**Comment by barthuttinga** [comment]
@dvleeuwen Volgens mij heeft het niet met de herintakes te maken. Het zijn afgesloten dossiers, dus niet in te checken in de inloophuizen. Ze zijn onder Inloop => Klanten wel te vinden, maar alleen als je ook de niet-actieve dossiers toont. Het is nu niet erg duidelijk dat een dossier afgesloten is en een intake zou helemaal niet mogelijk moeten zijn op afgesloten dossier. Dat ga ik aanpassen.

**Comment by barthuttinga** [comment]
Opgelost en live. De inloopdossiers die een intake na afsluiting hadden heb ik heropend (10 stuks).
