### ISSUE TITLE
bij intake worden oude intakeformulier en ZRM gebruikt 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#779]
bericht Arend:
als hij nieuwe intake invoert blijkt dat opeens een oud intakeformulier en de het oude format ZRM gebruikt worden

**Comment by barthuttinga** [comment]
Wat bedoel je met oud intakeformulier? Waar blijkt dat uit? Als ik een nieuwe intake maak zie ik in ieder geval gewoon de nieuwe ZRM.

**Comment by dvleeuwen** [comment]
Een oudintake formulier, waar volgens Arend in verleden mee gewerkt werd.
Hierbij werd veel meer gevraagd over druggebruik, begreep ik van hem.

De oude ZRM kun je herkennen aan het feit dat er maar naar 1 soort ADL
gevraagd wordt, in de nieuwe wordt gevraagd naar Basale- en Instrumentele
ADL.


Op di 5 mrt. 2019 om 12:20 schreef Bart Huttinga <notifications@github.com>:

**Comment by barthuttinga** [comment]
Kan jij dit bevestigen dan? Ik zie gewoon de nieuwe ZRM bv.

**Comment by barthuttinga** [comment]
Bij nieuwe intake vult hij de oude antwoorden alvast in, misschien dat daardoor ook de oude versie genomen wordt. Heb je een klantnr voor me?

**Comment by barthuttinga** [comment]
Ik zie dat [dit](https://github.com/deregenboog/ecd/issues/779#issuecomment-469668510) inderdaad aan de hand is. Ik zal het oplossen.

**Comment by barthuttinga** [comment]
Opgelost en live
