### ISSUE TITLE
Tab Buurtboerderij maken, met registratie vrijwilligers

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#780]

**Comment by barthuttinga** [comment]
@dvleeuwen Voeg je hier nog specificaties aan toe?

**Comment by barthuttinga** [comment]
@dvleeuwen Welke rollen moeten hiertoe toegang hebben?

**Comment by barthuttinga** [comment]
@dvleeuwen Tab Buurtboerderij is toegevoegd. Als er dingen anders moeten kan je aparte tickets openen. Laat je nog even weten welke rollen nodig zijn om bij tab Buurtboerderij te kunnen? Nu kan iedereen erbij die ook bij de algemene vrijwillers kan komen.
