### ISSUE TITLE
maatschappelijkwerk kan geen intakes meer toevoegen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#781]
zie bijvoorbeeld dit dossier:
https://ecd.deregenboog.org/mw/klanten/5633137/view?redirect=/mw/klanten/

vraag van Agnieszka

**Comment by barthuttinga** [comment]
Die mogelijkheid had ik in #778 uitgeschakeld: alleen bij actieve inloopdossiers kunnen intakes toegevoegd worden. Maar MW maakt impliciet inloopdossiers aan door een intake toe te voegen, dus nu heb ik het zo gedaan: "Intake toevoegen" is zichtbaar bij actief inloopdossier of bij geen inloopdossier; bij afgesloten inloopdossier is de link niet zichtbaar.
