### ISSUE TITLE
foutmelding bij afsluiting VWdossier 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#786]
Bij afsluiten vw binnen IZ met reden 'foutieve invoer' kom je op foutmeldingspagina terecht,
zie hier:
https://ecd.deregenboog.org/iz/vrijwilligers/16006/view

dossier wordt echter wel gewoon gesloten en verwijderd

**Comment by barthuttinga** [comment]
Opgelost en live
