### ISSUE TITLE
afgeschermde versie PFO

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#788]
Voor Janneke, Hans, Michael mogen de verslagen van PFO niet meer getoond worden

**Comment by dvleeuwen** [comment]
Daan zet vraag voor nieuwe rol uit bij Tineke, als die er is kan Bart verder

**Comment by dvleeuwen** [comment]
Ha Michael,
deze ligt al heeeel lang bij Toltech (die moeten deze rechtenrollen aanmaken).
Er waren 6 van dit soort aanvragen de afgelopen maanden, de helft is gedaan door Toltech, de andere helft niet.
Tineke heeft er flink achteraan gezeten, en Hans ook. Maar vooralsnog zonder resultaat :(

Heb hier vorige week Hans nog over gemaild. Hierbij nogmaals ter info voor jou Hans. Hoop dat jij er iets mee kunt.
(Gaat dus over de juiste PFOrechten ivm privacy, verzoek is in maart richting Toltech gegaan)

**Comment by dvleeuwen** [comment]
On hold, wachten op bericht Janneke of Michael.

**Comment by dvleeuwen** [comment]
role pfobeperkt moet ingericht worden: toegang tot PFO in ECD, maar NIET tot de verslagen.

**Comment by dvleeuwen** [comment]
actie Daan:
rol checken bij Tineke (Janneke)

**Comment by dvleeuwen** [comment]
Staat niet in dit overzicht, maar is wel aangemaakt door toltech?
Tineke zoekt uit

https://ecd.deregenboog.org/medewerkers/?redirect=/inloop/rapportages/

**Comment by jtborger** [comment]
deze rol heeft alles wat PFO ook heeft behalve dat ze de verslagen niet mogen zien.[

**Comment by jtborger** [comment]
OK. Mensen met de rol PFO_BEPERKT krijgen geen verslagen te zien.
Tab documenten nog wel, kon ik niks over terugvinden.

**Comment by jtborger** [comment]
OK blijkt dus niet helemaal te werken nog althans, de rol staat wel in LDAP maar niet in ECD. ROllen worden niet gesynchroniseerd. Daarom heropend.

**Comment by jtborger** [comment]
Ik wacht op toegang tot de ActiveDirectory servers zodat ik beter kan zien wat er misgaat.

**Comment by jtborger** [comment]
Anders gezegd: in ECD staan geen mensen met de rol PFO Beperkt.
Ik vermoed dus dat ze in de ActiveDirectory ook nog niet zo staan. Als dat wel het geval is, dan gaat er iets mis maar dan kan ik daar gerichter op zoeken.

**Comment by jtborger** [comment]
Hm. ik zie wel dat hans PFO Beperkt heeft. Even kijken of hij opnieuw kan in en uitloggen in ecd om te kijken of het gaat werken?
Raar dit

**Comment by jtborger** [comment]
Nog een keer goed naar gekeken. Vond een typo...
Ik denk dat dat het probleem was :(
Even kijken of Janneke, Hans etc nu de rol PFO Beperkt krijgen wanneer ze opnieuw inloggen

**Comment by dvleeuwen** [comment]
Ik vraag Hans en Janneke om bevestiging dat dit nu zo werkt

**Comment by dvleeuwen** [comment]
Ha Jan,
ik heb het nagevraagd bij Janneke, maar zij is hele tab PFO kwijt.
Gaat dus helaas nog iets mis.
Ik heropen issue

groet!
Daan

Op di 29 okt. 2019 om 11:14 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
het lijkt erop dat janneke geen PFO rol heeft.
Dat is wel nodig anders ziet ze de tab inderdaad niet.
Kan dat zo zijn? Moet even in de active directory worden nagekeken.

Andere medewerkers die wel PFO rol hebben zijn Evelien, Herman en Michael.
Als het goed is zien zij de PFO tab wel? Zou je dat willen nagaan en als
zij dat idd zien even kunnen nagaan bij TARQ ofdat Janneke in de groep ECD
PFO zit in de AD?


Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op vr 1 nov. 2019 om 13:25 schreef dvleeuwen <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Janneke geeft aan dat zij PFO een paar weken geleden is "kwijt" geraakt. Heeft dus niet met de laatste wijzigingen mbt PFObeperkt te maken.

Ik vraag na bij Hans of hij inderdaad (dit dacht Janneke) PFO nu ook helemaal kwijt is

**Comment by jtborger** [comment]
Even opgezocht:
wanneer de rol PFO niet aanwezig is dan wordt de PFO tab inderdaad niet weergegeven.
Daarom moet een gebruiker PFO + PFO beperkt hebben en niet enkel pfo beperkt

**Comment by dvleeuwen** [comment]
ik vraag bij TARQ role_PFO aan voor Janneke, en role_PFO_beperkt voor Michael.
Dan zou het compleet moeten zijn.

**Comment by dvleeuwen** [comment]
nog geen antwoord TARQ, ik vraag opnieuw.
aanvulling Janneke: Michael moet wel volledige toegang hebben! Geen role_beperkt voor hem dus.

Beperkt: Janneke & Hans
Geheel: Herman, Evelien, Michael

**Comment by dvleeuwen** [comment]
Goedemorgen Daan,

 

Zojuist Janneke van Loo toegevoegd aan de groep: ECD PFO. Wellicht dat Janneke, eerst uit en in moet loggen, zodat de aanpassing wordt doorgevoerd
Om in de toekomst dit soort verwarringen te voorkomen, ga ik aan Jan Borger een overzicht overhandigen, wie toegang heeft tot welke ECD groepen.

---
Lijkt opgelost, ik vraag Janneke om bevestiging en dan kan deze dicht.

**Comment by jtborger** [comment]
Janneke heeft nu rol PFO + PFO beperkt. lijkt mij goed gegaan.
Jij mag hem dicht doen als je reactie hebt van Janneke.

**Comment by jtborger** [comment]
@dvleeuwen any update van Janneke?

**Comment by dvleeuwen** [comment]
ah sorry, vergeten af te sluiten, werkt naar behoren!
