### ISSUE TITLE
gegevens vrijwilligers niet meer te zien/wijzigen bij Homeservice

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#791]
Sander geeft aan dat hij gegevens vrijwilligers niet meer kan wijzigen (komt dan op foutmeldingspagina)

Iris geeft aan dat ze ze niet kan bekijken (komt dan op foutmeldingspagina)

**Comment by barthuttinga** [comment]
@dvleeuwen Heb je een voorbeeld?

**Comment by barthuttinga** [comment]
opgelost en live
