### ISSUE TITLE
wens om koppelingen te kunnen verwijderen bij Homeservice

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#792]
soms gaan koppelingen vanuit andere registraties niet goed: nu kan ik die verkeerde koppeling niet verwijderen, en staan sommige dienstverleners er vervolgens dubbel in.

**Comment by barthuttinga** [comment]
@dvleeuwen Het is mij niet helemaal duidelijk wat hier bedoeld wordt.

**Comment by dvleeuwen** [comment]
zoeken naar concrete casus

**Comment by jtborger** [comment]
Is die al gevonden? Anders heropenen vanaf dat er een nieuwe casus is?

**Comment by dvleeuwen** [comment]
Yup, mee eens Jan,
denk dat we sowieso al onevenredig veel tijd/aandacht aan Homeservice
besteden recentelijk. Dus sluit dit punt af, tot ze er zelf op terug komen
met concreet voorbeeld.

groet
Daan

Op di 27 aug. 2019 om 15:20 schreef JT Borger <notifications@github.com>:
