### ISSUE TITLE
probleem facturen Homeservice

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#793]
- Aantal facturen die wel al helemaal betaald zijn, komen nog bovendrijven als niet betaald (bijvoorbeeld klanten: mail ik Bart) Denk dat deelbetalingen niet helemaal lekker verwerkt worden.

**Comment by barthuttinga** [comment]
@dvleeuwen Ik zie het probleem niet. De eerste twee namen uit je mail staan op saldo 0, dus dat klopt dat toch? De derde heeft minder betaald dan dat er gefactureerd is, dus dat lijkt ook te kloppen.

**Comment by dvleeuwen** [comment]
als er in voorbeeld 2 gevinkt wordt op "Met openstaande bedrag" komt er opeens 1 naar boven met openstaand bedrag

**Comment by barthuttinga** [comment]
opgelost en live
