### ISSUE TITLE
sorteer optie facturen Homeservice

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#795]
in het tabje facturen kan ik niet sorteren van hoog naar laag bij openstaand bedrag

Sander

**Comment by barthuttinga** [comment]
Hebben we het al eerder over gehad, die waarde wordt berekend op het moment dat het weergegeven wordt. Het is niet een waarde die in de database opgeslagen is, daarom kan er niet op gesorteerd worden.

**Comment by dvleeuwen** [comment]
ok koppel ik terug!



Op ma 25 mrt. 2019 om 15:58 schreef Bart Huttinga <notifications@github.com
