### ISSUE TITLE
Bij koppelingen extra opties naast 'verslag toevoegen', met tekstkopjes in veld

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#800]
Naast de optie verslag toevoegen bij koppeling ook: 'tussenevaluatie toevoegen' en 'eindevaluatie toevoegen' 

Er wordt dan veld geopend met de volgende tekst:

Verslag tussentijdse evaluatie
- Terugblik; hoe hebben de deelnemer en de vrijwilliger het contact ervaren
- Hoe vaak zien zij elkaar
- Hoe gaat het met de deelnemer?
- Indien van toepassing: is er gewerkt aan de gestelde doelen, wat is de stand van zaken
- is er iets veranderd in de situatie van de vrijwilliger wat gevolgen kan hebben voor het contact?
- waar komt in de komende periode het accent op te liggen?

Verslag eindevaluatie (aan het einde van ieder half jaar)
- Terugblik; hoe hebben de deelnemer en de vrijwilliger het contact ervaren
-  was de deelnemer tevreden over hoe het maatje hem / haar benaderde en met hem / haar omging? 
- Heeft het contact aan de verwachtingen voldaan? Waarom wel / niet?
- Hoe gaat het nu met de deelnemer.
- Wat was het doel van het contact en welke effecten ervaart de deelnemer? (*)
- Is er voor de deelnemer (nog iets anders) veranderd in positieve zin door het contact met de vrijwilliger. Wat?
- Hoe gaat het nu met de deelnemer; is vervolgondersteuning nodig? 
- Welk cijfer geeft de deelnemer het contact met je laatste maatje? Graag een toelichting.
- Ben je tevreden over het contact met de coördinator?
- Vragen specifiek aan de vrijwilliger; met wel cijfer beoordeel je je vrijwilligerswerk bij ons? Wat maakt dat je ons dat cijfer geeft?

Als tussen/eindevaluatie ingevuld is verander optie 'evaluatie toevoegen' in 'evaluatie tonen'

**Comment by barthuttinga** [comment]
opgelost, gaat vandaag live
