### ISSUE TITLE
probleem met aanmaken dossier vanuit MW

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#801]
vraag Janneke:

Hoi Daan,

Sinds afgelopen week is er iets veranderd in het ECD, waardoor ik geen nieuwe klant meer kan aanmaken. Wel als ik dat doe vanuit de inloophuizen, maar niet vanuit het maatschappelijk werk. En het is niet passend om eerst een inloopklant aan te maken, en die dan over te nemen bij het MW. Het gaat namelijk om aan,meldingen vanaf de site, specifiek voor het MW, van mensen die geen bezoeker van de inloop zijn. Weet jij raad?
Met vriendelijke groet,

Janneke van Loo, Regiomanager Centrum / Noord / Oost

**Comment by barthuttinga** [comment]
opgelost en live

**Comment by dvleeuwen** [comment]
opmerking Janneke, ik heropen:

Het is bijna helemaal goed. Het enige is dat nu het veld 'geboortedatum' verplicht moet worden ingevuld, terwijl dat op de aanmelding via de site niet wordt gevraagd. Die info heb ik dus niet. Heb nu een fake datum ingevuld. Kan dat een facultatief veld worden?

**Comment by barthuttinga** [comment]
Geboortedatum is nu optioneel, gaat straks live.
