### ISSUE TITLE
foutmelding bij afsluiting vrijwilliger

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#803]
Als je vwer afsluit krijg je melding dat dit niet kan omdat er nog een groep actief zou zijn, wat niet het geval lijkt te zijn.
Zie bijvoorbeeld hier:
https://ecd.deregenboog.org/ga/vrijwilligerdossiers/8886/view/afsluiting?redirect=/ga/vrijwilligerdossiers/8886/view/groepen

vraag elllina

**Comment by barthuttinga** [comment]
Opgelost, gaat straks live.
