### ISSUE TITLE
bij activiteit kunnen geen vrijwilligers toegevoegd worden

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#804]
zie bijvoorbeeld hier:
https://ecd.deregenboog.org/ga/activiteiten/644/view?redirect=/ga/activiteiten/#vrijwilligers

bij toevoegen kom je op foutmeldingspagina terecht

vraag ellina

**Comment by barthuttinga** [comment]
Opgelost, gaat straks live.
