### ISSUE TITLE
uren invoeren werkt niet meer

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#806]
Iris:

ik kan geen uren meer invoeren. Na eindeloos "connecten" krijg ik bijgevoegde melding...
(Bart: ik mail je de bijbehorende afbeelding)

**Comment by dvleeuwen** [comment]
Ha,
vraag van Bart mbt onderstaande: lopen jullie er alleen bij deze specifieke klus tegen aan, of in alle gevallen.
Bart heeft geprobeerd in te loggen als jullie, en toen leek het te werken. Speelt dit probleem nog steeds bij jullie?

groet!
Daan

**Comment by dvleeuwen** [comment]
specifieke casus is doorgemaild naar Bart

**Comment by barthuttinga** [comment]
Ik kon het probleem lokaal niet reproduceren, maar zag wel dat wat meer geheugen gebruikt werd dan nodig. Dat is nu opgelost, daarmee hoop ik dat het probleem voor hen ook verholpen is. Gaat vandaag live.

**Comment by barthuttinga** [comment]
Ik kan het probleem niet reproduceren, maar Iris geeft aan dat het nog niet is opgelost. Ik heb om meer info gevraagd.

**Comment by barthuttinga** [comment]
opgelost en live
