### ISSUE TITLE
foutmelding bij wijzigen intake

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#808]
Bianca:

Hi hi,

heb zojuist een her-intake gedaan en ik wil nog iets wijzigen.
Krijg de volgende foutmelding!
gaat om deze;

https://ecd.deregenboog.org/inloop/intakes/27967/view 

dank alvast!

**Comment by barthuttinga** [comment]
@dvleeuwen Heb jij dit zelf ook geprobeerd? Ik zie niks geks.

**Comment by dvleeuwen** [comment]
Ze stuurde mij in bijlage screenshot vd foutmeldingspagina, dus het gaat wel echt fout.

Ik kan nu wel wijzigen, maar dat heeft waarschijnlijk met rechten te maken (aangezien dit eigenlijk niet zou moeten kunnen toch, aangezien ik intake niet aangemaakt heb?)

**Comment by dvleeuwen** [comment]
Ze stuurde mij in bijlage screenshot vd foutmeldingspagina, dus het gaat
wel echt fout.

Ik kan nu wel wijzigen, maar dat heeft waarschijnlijk met rechten te maken
(aangezien dit eigenlijk niet zou moeten kunnen toch, aangezien ik intake
niet aangemaakt heb?)

groet
Daan

Op do 18 apr. 2019 om 10:27 schreef Bart Huttinga <notifications@github.com

**Comment by barthuttinga** [comment]
@dvleeuwen Ik kan geen probleem vinden, ook niet als ik als Bianca inlog en een nieuwe intake aanmaak en deze daarna probeer te wijzigen.

**Comment by dvleeuwen** [comment]
bart: Ik kan geen probleem vinden, ook niet als ik als Bianca inlog en een nieuwe intake aanmaak en deze daarna probeer te wijzigen.

Ik vraag Bianca of zij het naast dit ene geval vaker meemaakt

**Comment by dvleeuwen** [comment]
onduidelijk wat probleem was, maar speelt niet meer, dus sluit af
