### ISSUE TITLE
collega's IZ kunnen er op uit kalender niet afsluiten

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#809]
Zelf kan ik het wel, maar collega's komen op foutmeldingspagina terecht zodra ze vanuit IZ dossier een eropuitkalender proberen af te sluiten. 
Foutmelding als ze in dossier onder 'diensten' op eropuit klikken

**Comment by barthuttinga** [comment]
@dvleeuwen Dit is een toegangsrecht dat die mensen niet hebben. Moet iedereen met rol IZ ook toegang hebben tot ErOpUit?

**Comment by dvleeuwen** [comment]
ja graag!

**Comment by dvleeuwen** [comment]
ja graag!

Op do 18 apr. 2019 om 10:24 schreef Bart Huttinga <notifications@github.com

**Comment by barthuttinga** [comment]
is aangepast
