### ISSUE TITLE
ivm naamswijziging  'Ondro Bong' wijzigen in 'Zeeburg' 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#811]
Waar het kon heb ik (DvL) het aangepast, maar komt op meer plaatsen voor, bijvoorbeeld:

Locatiekeuze
Intakelocatie
AMOC
Toegang inloophuis
Ja
Einddatum toegang AMOC
Startdatum toegang Ondro Bong
09-04-2019
Startdatum toegang overigen
Toegang gebruikersruimte

**Comment by barthuttinga** [comment]
gedaan, gaat vandaag live
