### ISSUE TITLE
herintake wordt als nieuwe aanmelding gezien Amoc

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#812]
Wendy:
Hi Daan,

ik zag vandaag dat wanneer Amoc een herintake gedaan heeft, er staat: nieuwe aanmelding. Als dit bij Amoc gebeurt, dan moeten ze normaal gesproken weer eerst 6 maanden geregistreerd zijn. Het blijkt dus te gaan om een nieuwe intake. Zou dit misschien weer op de oude manier in het ECD gezet kunnen worden? Dan hoeven we niet steeds te bellen,,

alvast bedankt en groetjes

**Comment by dvleeuwen** [comment]
4 april
Ha Bart,
zie onderstaande, begrijp jij dan wat er met oude manier bedoeld wordt?

Als ik het goed begrijp lijkt het nu na een herintake alsof mensen opnieuw 6 maanden enkel toegang tot Amoc hebben, wat niet wenselijk is.

groet!
Daan

**Comment by dvleeuwen** [comment]
zie ook mail Aki 16mei

**Comment by dvleeuwen** [comment]
nog wat voorbeelden:
Aki: https://ecd.deregenboog.org/inloop/klanten/5621866/view?redirect=/inloop/klanten/
Raph: https://ecd.deregenboog.org/inloop/klanten/5632506/view?redirect=/inloop/klanten/

**Comment by dvleeuwen** [comment]
Ik kwam deze nog tegen in geschiedenis:
#802

Zelfde punt?

**Comment by jtborger** [comment]
Ik kom hier niet goed uit want ik begrijp niet wat het probleem is. Heb iets meer tekst en uitleg nodig.

**Comment by jtborger** [comment]
Dus:
- Niet rechthebbende klanten moeten eerst een half jaar na eerste aanmelding naar AMOC en mogen niet naar andere inloophuizen.
- Na 6mnd mogen ze ook andere inloophuizen bezoeken
- Klanten krijgen regelmatig herintakes.
- Het lijkt nu dat bij een herintake sommige klanten (naw: niet rechthebbend en/of ooit via AMOC intake gehad) weer die 6mnd periode in gaan.

**Comment by jtborger** [comment]
OK, een heel gepuzzel al met al (...)

Het is vrij complex qua implementatie gemaakt, maar uiteindelijk komt het hierop neer:
Er wordt bij het opslaan van een (nieuwe) intake elke keer ingesteld tot welke inloophuizen iemand toegang heeft.
Daar zijn verschillende strategieen voor beschikbaar:
- gebruikersruimte
- Amoc
- Ondrobongo
- Verblijfsstatus.

Deze verschillende strategieen zijn gekoppeld aan bepaalde locaties. Per locatie wordt gekeken of de klant aan de 'drempel' die de strategie opwerpt, voldoet.

Een van deze drempels/strategieen is de 'verblijfsstatus' drempel.
Wanneer deze drempels niet worden gehaald, krijgt iemand alleen toegang tot AMOC + nachtopvang.
Wanneer iemand de drempels wel haalt, mag hij ook in andere ruimtes.

De drempels voor verblijffstatus zijn:

Verblijffstatus = niet rechthebbend bij de laatste intake
OF
verblijffstatus is niet ingesteld (zou mi niet moeten kunnen)
OF
de eerste intakedatum was voor 1 juni 2017 EN bij de laatste intake is ingesteld dat de startdatum overige in het verleden of vandaag is.
OF
eerste intakedatum was na 1 juni 2017 EN eerste intakedatum wel een half jaar voor vandaag EN toegang overige inloophuizen is ingesteld voor vandaag.

Dit laatste veld, toegang overige inloophuizen, moet dus worden ingesteld, anders gaat het mis.
Dat is ook wat ik kan hercreeeren: als ik hem hier instel dan gaat het goed, stel ik hem niet in (leeg) of in de toekomst, dan krijgt iemand enkel toegang tot Amoc/nachtopvang.

Is dit gewenst of moet dat hele Toegang overige eruit? Waar is dat eigenlijk voor?

**Comment by jtborger** [comment]
Als niet duidelijk dan even bellen of donderdag bespreken.

**Comment by dvleeuwen** [comment]
Ok Jan,
lijkt me goede om vanmiddag even gezamenlijk naar te kijken.

groet!

Op di 16 jul. 2019 om 13:53 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Hier nog 1 recent  voorbeeld:
https://ecd.deregenboog.org/inloop/klanten/5632598/view?redirect=/inloop/klanten/

**Comment by jtborger** [comment]
Laten we er inderdaad naar kijken vanmiddag. Al heeft ook die laatste klant
geen ingevulde datum bij 'Toegang overige inloophuizen'.

Laten we dat even bekijken, en waarom dat wel of niet ingevuld wordt - en
of die voorwaarde uberhaupt meegenomen dient te worden. Daar is in het
verleden blijkbaar voor gekozen?



Op do 18 jul. 2019 om 12:21 schreef dvleeuwen <notifications@github.com>:

**Comment by jtborger** [comment]
Vooralsnog bij herintake geen beperking op andere locaties.

**Comment by jtborger** [comment]
In overleg met Janneke.
