### ISSUE TITLE
foutmelding bij aanmaken declaratie in klus

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#814]
Na klus/declaratie toevoegen en dan gegevens invullen -> foutmelding

**Comment by jtborger** [comment]
Hoi Daan, lokaal kan ik dit niet reproduceren; bij mij slaat ie gewoon op. (voor de zekerheid: gaat om homeservice/klussen --> klus openen --> declaraties --> declaratie toevoegen, toch?)

**Comment by dvleeuwen** [comment]
Ha Jan,
Kun jij zien of dat ook zo is als je ingelogt bent als Iris de Lau?

groet!
Daan

Op ma 20 mei 2019 om 17:53 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
+ mail Janneke R 17 mei

**Comment by jtborger** [comment]
Ik moet even zien te achterhalen hoe ik in kan loggen als een andere medewerker zodat ik vanuit hun rechten kan bekijken hoe of wat

**Comment by dvleeuwen** [comment]
ah ja dat is wel handig, Bart deed het regelmatig, dus misschien even bij
hem checken?

groet!
Daan

Op di 28 mei 2019 om 09:16 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Ik weet nu hoe dat moet, ik heb alleen nog geen toegang tot de live ECD geloof ik.
Wordt aan gewerkt, wanneer ik dat kan ga ik kijken

**Comment by jtborger** [comment]
Ik kon dit reproduceren; wanneer er eerst uren waren ingesteld op de klus ging het goed, bij eerst een declaratie niet omdat er op dat moment nog geen conceptfactuur aanwezig was.
Ik heb dit nu aangepast, er vanuit gaande dat er soms ook klussen met alleen declaraties kunnen zijn en zonder uren. Als dat niet het juiste proces is, dan kan ik ook kiezen voor een melding: eerst uren registreren voor declaratie.

Vooralsnog opgelost, graag even feedback. Gaat mee in volgende release.
@ @

**Comment by dvleeuwen** [comment]
Ha Sander/Iris,
Jan ontdekt dat een vd bugs (foutmelding bij aanmaken declaratie in klus) veroorzaakt wordt doordat het nu onmogelijk is declaraties aan te maken voor klussen waar nog geen uren bij staan. Er moeten dus altijd eerst uren geregistreerd worden, en dan pas declaraties.
Is dit bewust zo ingebouwd/wenselijk, of niet?
We kunnen het aanpassen dat je ipv een foutmelding een waarschuwing krijgt 'eerst uren registreren alvorens declaratie aan te maken' ofzo.
Of we schrappen het geheel, waardoor het gewoon mogelijk wordt declaraties te maken voor klussen zonder uren. Wat willen jullie?

**Comment by dvleeuwen** [comment]
Antwoord Iris:
Hoi Daan, 

lijkt me prima, is niet bewust gedaan volgens mij, en volgens mij is dat dan iets wat later is toegevoegd.. Schrap het geheel maar!

Groet Iris

**Comment by jtborger** [comment]
Helder. Dan laten we het zoals het nu is dus.
