### ISSUE TITLE
geen automatisch vinkje actieve koppelingen meer

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#815]
verzoek Juul:

tevens zou het fijn zijn als het ECD niet standaard op actief staat. Maar als we zoeken dat we binnen de hele poel kunnen zoeken en zelf de actieve aan kunnen vinken wanneer we een lijst uit willen draaien o.i.d.
Dit gaat dan over alle tabjes.

**Comment by jtborger** [comment]
Ik heb dit lokaal gefixt maar heb nog geen toegang tot de github repository. Dat moet allemaal nog geregeld worden.

**Comment by dvleeuwen** [comment]
opgelost maar nog niet live

**Comment by jtborger** [comment]
Ik heb het nu net live gezet - maar lees ook nu net pas de laatste zin: alle tabjes.
Ik had alleen naar de eerste gekeken. Deze is dus nog niet live (behalve de eerste). ga ik morgen mee verder.
