### ISSUE TITLE
niet alle koppelingen worden getoond?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#816]
-mail Juul
 als ik bij koppelingen kijk, krijg ik er nooit meer dan 54. Ook niet als ik de begin data of actieve filter uit zet. terwijl we er in totaal 124 hebben gehad. Zouden jullie hiernaar kunnen kijken waarom deze koppelingen niet terug naar boven komen? 

-
Ha Juul,
nog even aanvullend op onderstaande. Heb je voor mij een paar namen van koppelingen die niet terugkomen in dit overzicht van 54? Dat maakt het zoeken/puzzelen waarschijnlijk makkelijker. 

groet!
Daan

**Comment by jtborger** [comment]
Dag Daan. Ik heb even gekeken, maar wat ik mijn lokale development database zien kan zijn er maar 50 rijen in de database tabel voor huurovereenkomsten.
Ik weet niet of dat de data die ik heb in aantal hetzelfde zijn als er in de productieomgeving staan, of dat dit niet per se zo hoeft te zijn. Ik heb nog geen toegang tot productie en dus kan ik daar verder niet naar kijken.
Als er een concrete naam is inderdaad is het sowieso makkelijker zoeken.

**Comment by dvleeuwen** [comment]
Ha Juul,
Jan heeft toch heel graag een naam van een koppel die volgens jullie niet terugkomt in het overzicht vd koppelingen. 
Hier zie ik er idd 54 staan
https://ecd.deregenboog.org/odp/huurovereenkomsten/?huurovereenkomst_filter%5Bfilter%5D=&huurovereenkomst_filter%5Bid%5D=&huurovereenkomst_filter%5Bhuurder%5D%5Bklant%5D%5Bnaam%5D=&huurovereenkomst_filter%5BverhuurderKlant%5D%5Bnaam%5D=&huurovereenkomst_filter%5Bmedewerker%5D=&huurovereenkomst_filter%5Bstartdatum%5D%5Bstart%5D=&huurovereenkomst_filter%5Bstartdatum%5D%5Bend%5D=&huurovereenkomst_filter%5Bopzegdatum%5D%5Bstart%5D=&huurovereenkomst_filter%5Bopzegdatum%5D%5Bend%5D=&huurovereenkomst_filter%5Beinddatum%5D%5Bstart%5D=&huurovereenkomst_filter%5Beinddatum%5D%5Bend%5D=&huurovereenkomst_filter%5Bafsluitdatum%5D%5Bstart%5D=&huurovereenkomst_filter%5Bafsluitdatum%5D%5Bend%5D=&huurovereenkomst_filter%5BverhuurderKlant%5D%5Bplaats%5D=&huurovereenkomst_filter%5Bvorm%5D=&huurovereenkomst_filter%5Bhuurder%5D%5BautomatischeIncasso%5D= 

En bij rapportage 124.
Is deze 124 juist volgens jullie?

Heel fijn als het jullie dan lukt een naam te bedenken/terug te vinden die niet in de 54 koppelingen staan die nu in ecd getoond worden.
Dan kan Jan verder puzzelen.

dank!
Daan

**Comment by jtborger** [comment]
- Als een huurder / kldeelnemerant geblokkeerd of verwijderd is dan wordt de koppeling hier niet getoond
- Als een verhuurder / klant geblokkeerd of verwijderd is, ook niet
- wanneer de afsluitreden is ingesteld om niet in de lijst te tonen ook niet

Dat is wat ik nu kan vinden op basis van de database vraag (query) die er gesteld wordt.

Als ik de query die ik lokaal heb draai in de productiedatase krijg ik inderdaad 126 (er zijn er 2 bijgekomen sinds melding) rijen. Ik draai met een nieuwere versie dan productie.
Ik wil dus even kijken of di tis opgelost. Zo ja, dan komt dit doordat ik iets heb aangepast dat te maken heeft met het actief vinkje.
Zo niet, dan moet ik verder kijken. Ik kan dit nu niet verder oppakken.

**Comment by dvleeuwen** [comment]
opgelost, ik check even bij Juul en sluit af
