### ISSUE TITLE
herinrichting vrijwilligers inlopen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#817]
Hoi Daan,

Hierbij gaat de hernieuwde opdracht voor de rubriek Inloophuizen - Vrijwilliger.
De eerdere opdracht van vorig jaar april/mei is slechts gedeeltelijk
uitgevoerd, Bart kreeg nl. van hogerhand andere prioriteiten op zijn
bord. De rubriek is toen nog niet in gebruik genomen omdat er nog geen
mogelijkheid was om een dossier af te sluiten (hoewel er al gegevens
waren ingevoerd). Inmiddels is er door Bart overigens wel een
afsluitoptie toegevoegd.

Ik heb nu in overleg met Lieke en met input van Kathleen een
uitgebreidere opzet gemaakt, zowel voor het dossier als de kolommen in
de download. Dit vervangt dus de oude opdracht.

Hoewel het onzeker is wanneer Barts opvolger aan de slag gaat houdt de
klus naar ik aanneem dezelfde plek op de prioriteitenlijst! Voor
vragen of verduidelijking ben ik uiteraard beschikbaar.

Groet,

Josje

Ik heb documenten ter verduidelijking, later met Jan bespreken

**Comment by dvleeuwen** [comment]
zie bijlage in mail + aanvulling

Op 18 april heb ik een opzet gemaild voor het afmaken van het dossier + de download Inloopvrijwilliger. Hierop heb ik nog een paar aanvullingen, wil jij zorgen dat die worden toegevoegd aan de opdracht?

Het zijn deze punten:
- onder de tab Afsluiting graag de mogelijkheid Heropenen toevoegen (zoals bij IZ)
- lijst vrijwilligers: toevoegen vinkje 'alleen open dossiers'; NB dit vinkje moet standaard UIT staan
- lijst vrijwilligers: mogelijkheid toevoegen om de sorteren op Locatie
- download vrijwilligers: kolom 'Locatie' toevoegen, na kolom E-mailvoorkeur

**Comment by dvleeuwen** [comment]
mail Josje na gesprek Jan 28nov

Hoi Jan,

Nog even een bevestiging van de aanpassing t.a.v. trainingen in de rubriek Vrijwilligers Inloophuizen:
- in het dossier komt een tab Trainingen met daaronder een scrollmenu met de 2 verplichte trainingen + een blanco invoerveld (zie bij bijlage Scrollmenu's). Als aanvulling: het handigst lijkt me om onder de tab de tekst '+ training toevoegen' te zetten, met een doorklik naar het scrollmenu. Na invoer moet je opnieuw een training kunnen toevoegen (dus het scrollmenu wordt dan opnieuw opgeroepen). 
- aan de download wordt een kolom Trainingen toegevoegd (laatste kolom) waarin de trainingen uit het dossier zichtbaar worden, op 1 regel gescheiden door komma's.

De overige aanpassingen aan het dossier heb je zelf al genoteerd.

Als er nog vragen mochten opkomen weet je me te vinden.

Groet,

Josje

**Comment by jtborger** [comment]
2.2.35
1 openstaand issue besproken met Josje.

**Comment by dvleeuwen** [comment]
nog wat aanvullingen Josje, dus ik heropen issue:
------
Josje:
Correctie bij punt 2: ik zie nu dat in het IZ-dossier de verslagdatum niet achteraf aanpasbaar is. Het pluspunt is daar wel dat de opgeslagen datum grafisch duidelijk afwijkt van een invulveld. 

Ik zou bij de inloopvw dan toch kiezen voor een datum zoals bij het IZ-verslag, dus een automatisch gegenereerde datum die grafisch opvallend is na opslaan (groene letters), en niet aanpasbaar. Het is weliswaar te voorzien dat juist die startnotitie later wordt aangevuld, maar het is dan niet wenselijk om de oorspronkelijke datum te wijzigen. De gebruiker kan in dat geval in de bestaande notitie desgewenst handmatig een datum toevoegen aan de update van de informatie.




---------- Forwarded message ---------
Van: Josje Leene <jleene@deregenboog.org>
Date: ma 27 jan. 2020 om 11:56
Subject: inloop vw getest
To: ECD De Regenboog Groep <ecd@deregenboog.org>


Hoi Jan,

Ik heb de release van de inloopvw-rubriek bekeken en het ziet er heel goed uit. Ook de download. Nog twee kleine puntjes zou ik graag aangepast zien tbv de gebruikersvriendelijkheid:
- vraagteken verwijderen bij invulbox 'Alleen actieve vrijwilligers' op de schermlijst
- notitiedatum onder tab Aanmelding: bij het aanmaken of wijzigen van de aanmeldgegevens komt de notitiedatum vlak boven de startdatum te staan, dat is wat verwarrend (merkte ik bij het invullen van een startdatum). Zou je die notitiedatum kunnen aanpassen zoals in het IZ-dossier, nl. een automatisch aangemaakte datum die pas verschijnt bij opslag van de notitie (en evt. wel aangepast kan worden)?

Als je dit nog zou kunnen aanpassen op korte termijn zou het mooi zijn.

Dank & groet,

Josje

**Comment by jtborger** [comment]
Punten doorgevoerd. Ik heb de tekst niet groen, maar blauw gemaakt. Meer conform de rest van ECD geloof ik.
2.2.38
