### ISSUE TITLE
nieuwe rapportage 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#819]
Nieuwe rapportage:
-verticaal: hulpvraagsoort deelnemer
-horizontaal: doelgroep deelnemer

**Comment by jtborger** [comment]
Hoi Daan,

Als ik het goed begrijp gaat het om het aantal deelnemers per doelgroep per hulpvraagsoor?
Wil je dat van alle dossier, ooit ever,
alleen gestartte dossiers
alleen afsgeloten dossier
alleen afsgeloten dossier die succesvol zijn afgesloten
?

**Comment by jtborger** [comment]
Heb voor de voortgang even gekozen voor 'afgesloten' dossiers. Als dit anders moet is dat eenvoudig door mij aan te passen.

**Comment by dvleeuwen** [comment]
open-gekoppeld-afgesloten
tel contact voor toelichting

**Comment by jtborger** [comment]
gaat alleen om dit jaar gestartte koppelingen.

**Comment by jtborger** [comment]
Gaat zo mee in release. 2.2.18
