### ISSUE TITLE
toekennen juiste rechten aan nieuwe groepen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#822]
meer info volgt via Tineke

**Comment by dvleeuwen** [comment]
Deze groepen zijn aangemaakt:

ECD SCIP
ECD SKIP Beheer
ECD Eropuit

En deze wel aangevraagd, maar niet aangemaakt:

ECD PFO Beperkt (=#788)
ECD Buurtboerderij
ECD Secretariaat

**Comment by dvleeuwen** [comment]
Hallo Tineke,

De volgende security groepen zijn aangemaakt :
ECD PFO Beperkt
ECD Buurtboerderij
ECD Secretariaat

Met vriendelijke groet,
Robert

**Comment by jtborger** [comment]
BB en secretariaat gemist.

**Comment by jtborger** [comment]
Secretariaat 

Klanten en VRijwilligers alleen toegankelijk maken voor secretariaat, josje, en admin.

**Comment by jtborger** [comment]
Note to self: Klanten en vrijwilligers worden door alle andere modules ook gebruikt bv bij wijzigen van bepaalde stamgegevens. Dat loopt over die controller. Ze moeten eigenlijk enkel uit het menu verdwijnen.

**Comment by jtborger** [comment]
Klanten + VW tabs: alleen voor:
secretariaat, josje, admin en management (even kijken), teamleiders.

**Comment by dvleeuwen** [comment]
onduidelijkheid of deze al (deels?) live gezet is. zie mail van vandaag mbt Bas

**Comment by jtborger** [comment]
lijst rollen in medewerker filter is niet up to date : ROLE_SECRETARIAAT staat daar niet bij??

**Comment by jtborger** [comment]
Meer gevolgen want niet alle mensen in de managementlaag onder directie zit in rol Teamleiders.

**Comment by dvleeuwen** [comment]
definitieve lijstje van mensen die toegang willen houden tot tab klanten/vrijwilligers:
-sec: Lia, Loes, Anita
-management: Hans, Marit, Brigit, Janneke (van Loo)
-laag onder management: Lennaert, Bas, Dini, Michael
+ Willemijn & Josje

**Comment by jtborger** [comment]
- er is geen rol voor management. Hans, Brigit,Marit en Janneke hebben geen gemeenschappelijke rol die uniek is voor hun rol in de organisatie. Het zou handig zijn dit wel te maken misschien, wat denk jij?
- Hetzelfde geldt voor de groep daaronder met Lennaert, Bas, Dini en Michael.
Dan heb je nog Willemijn en Josje.
Die kunnen evt de rol secretariaat krijgen omdat ze ook secretariele taken doen in de organisatie dus letterlijk die rol ook hebben denk ik.

Zie jij dit ook zo? Zo ja dan ga ik twee groepen aan laten maken bij TARQ:

* Management
* Afdelingsleiders? Beter term?

**Comment by dvleeuwen** [comment]
Ja top, gedaan!

Rollen "Management" en "Programma Coördinator" aan laten maken bij TARQ

Op ma 6 jan. 2020 om 13:33 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Programma Coördinator

Kan je die laten veranderen in
ECD Programma Coordinator
zonder trema?

Ik weet niet hoe hij daarmee omgaat. misschien gaat het goed maar dit soort
dingen zijn soms nog een beetje prehistorisch..

Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op vr 10 jan. 2020 om 16:22 schreef dvleeuwen <notifications@github.com>:

**Comment by jtborger** [comment]
Ik zie dat ie er nu instaat met trema. geen idee of dat goed gaat, laten we maar eens kijken...

**Comment by jtborger** [comment]
2.2.39

**Comment by dvleeuwen** [comment]
Ik heropen, iedereen heeft nog steeds de tabs klanten en vrijwilliges

**Comment by jtborger** [comment]
Ik kan het hier lokaal niet reproduceren. Toch even volgende week kijken.

**Comment by dvleeuwen** [comment]
Bij collega's is TAB klanten/deelnemers nu weg.
Echter bij Bas de Groot ook? (+andere problemen, zie hieronder)
Daan + Jan bespreken!

Hi Daan,

Het ECD is altijd in beweging en dat is een mooi ding. Maar. Soms beweegt het ECD de verkeerde kant op. Vandaag logde ik in en ik kan echt alleen nog maar Dagbesteding, ErOpUit en Groepsactiviteiten zien. Los van het gegeven dat ik ook over OEK ga, heb ik ook geen zich meer op het totale klantenbestand van de regenboog. Hoe moeten we in vredesnaam voorkomen dat we dubbele registraties e.d. krijgen als we niet kunnen zien wie er al in staat?
Misschien is het alleen bij mij zo, maar ik vind het in ieder geval vreselijk onhandig dat ik niet kan zien of iemand al klant is en waar.

Voorbeeld. Recentelijk kreeg ik vragen van de gemeente over iemand waarvan werd beweerd dat deze niet in de stad verbleef. In ECD kon ik zien dat dat wel het geval was. Dat zou ik nu niet meer kunnen. Niet handig.

Is dat op te lossen.

Groet,

**Comment by dvleeuwen** [comment]
zie ook mail 17feb (met  #822 in tekst)

**Comment by dvleeuwen** [comment]
managementoverleg: terug draaien besluit klanten/vw tab afsluiten voor iedereen?

Overleg: Jan + Daan
