### ISSUE TITLE
urenregistratie springt automatisch naar laatste dag vd maand

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#824]
Iris:

Hoi Daan, 

Weer een voor het lijstje: nu schiet bij somige klanten de urenregistratie automatisch op 31 mei....

---
Sterker nog: alle uren schieten op de laatste dag van de maand!

**Comment by jtborger** [comment]
Ik kan dit niet reproduceren.

Ik doe: 
Homeservice -> Klant die actief is -> Klus die in behandeling is -> Uren toevoegen -> krijgt in het formulier automatisch de datum van vandaag -> opslaan -> blijft zo, tevens op factuur.

Zijn dit ook de stappen die Iris doet?

**Comment by dvleeuwen** [comment]
Ha Jan,
ja dan zou het heel handig zijn als jij ook in kunt loggen als Iris, om het
dubbel te checken (vraag jij dit na bij Bart?)

@Iris:
Ha Iris,
de nieuwe programmeur (=Jan) probeert jouw probleem met data
urenregistratie te achterhalen, en op te lossen. Maar bij hem gebeurt het
niet. Zie zijn mail hieronder, zijn dit de stappen die jij ook doorloopt,
of gaat het om een andere plek in ECD?

*Homeservice -> Klant die actief is -> Klus die in behandeling is -> Uren
toevoegen -> krijgt in het formulier automatisch de datum van vandaag ->
opslaan -> blijft zo, tevens op factuur.*

We horen graag terug, dank!

Daan

Op di 28 mei 2019 om 12:11 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Hoi Jan,

welkom! Iedere eerste urenregistratie die ik doe binnen een klus springt op
de laaste dag van de maand. Bij e volgende gaat het wel ged, daarna kan ik
de eerste aanpassen. Wel weer een extra handeling...

[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

Zie onderste regel...



Met vriendelijke groeten,
Homeservice
020 626 0969
www.deregenboog.org

geopend: maandag t/m donderdag van 09:00-15:00 uur





Op di 28 mei 2019 om 12:37 schreef ECD De Regenboog Groep <
ecd@deregenboog.org>:

**Comment by jtborger** [comment]
Hoi Daan, ik kan de plaatjes niet bekijken. Misschien staat daar net wat extra info in die ik kan gebruiken. Zou je die kunnen iploaden?
Dank!

**Comment by dvleeuwen** [comment]
Ha Jan,
ivm privacywetgeving mogen er nooit naam of gegevens van deelnemers in
Github komen te staan. Dus ook geen screenshots.
Ik stuur de mail met afbeelding aan je door!

groet
Daan

Op di 28 mei 2019 om 13:17 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Daan, heb nogmaals alles bekeken incl de plaatjes en zo goed mogelijk geprobeerd te reproduceren hier lokaal, zonder resultaat. 
Ook in de code kan ik niets vinden dat dit zou doen; het enige dat er eerder in zat, en ik al gefixt heb, is dat de factuurdatum naar de laatste dag van de maand ging. Ik weet niet precies of ik dit probleem heb opgelost toen ik dat ook oploste, misschien wel.
Ik wil dit even parkeren en dan kijken hoe of wat alsi k straks in productie erbij kan.

**Comment by dvleeuwen** [comment]
prima,
ik vraag nog even na of zij het probleem nog ondervinden

Op ma 3 jun. 2019 om 09:45 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Nou ik heb het nog niet gereleased dus dat moeten we even doen wanneer dat
gebeurd is.


Op ma 3 jun. 2019 om 09:58 schreef dvleeuwen <notifications@github.com>:

**Comment by jtborger** [comment]
Nogmaals naar gekeken nu ook in productie. Probleem duidelijk, het lijkt erop dat Bart dit bewust zo heeft gemaakt, is geintroduceerd met issue #641 . Maar dat ging volgens mij om de factuurdatum op de laatste dag van de maand, niet de interne registraties of declaraties.
Heb dit nu uitgezet. Er worden dus van registraties en declaraties geen invoer meer op de laatste dag van de maand gezezt.
Als dit niet in orde is kan deze opnieuw wordne geopend.

**Comment by dvleeuwen** [comment]
opmerking Iris mbt urenregistratie:
- urenregistratie lijkt nu goed te gaan, maar daardoor gaat het ergens anders weer mis lijkt het: bij klant XX krijg ik per urenregistratie een factuur... Ben ik niet eerder tegengekomen en lijkt random, want bij andere kanten gaat het wel goed

Deze klant:
https://ecd.deregenboog.org/hs/klanten/2069/view?redirect=/hs/klanten/

**Comment by jtborger** [comment]
Raar, dit is de enige klant waarbij dat is.
Wellicht een side effect van iets dat ik niet helemaal goed geimplementeerd had.
Even in de gaten houden.
Kan een van deze twee facturen eruit? Dan doe ik dat in de database.
Als dit vandaag of na vandaag nog een keer voorkomt moet ik verder kijken. Vooralsnog beschouw ik het even als een eenmalig iets. Kan het lokaal ook niet reproduceren.

**Comment by jtborger** [comment]
verder opgelost.
