### ISSUE TITLE
toevoeging bij openstaande vraag CLIP

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#825]
Beste Bart,

Graag zouden we nog een toevoeging zien in ons ECD, namelijk een symbooltje, bolletje of iets dergelijks bij de openstaande vragen, om aan te geven of iemand zelf danwel iedereen met een vraag aan de slag kan. Iets dat we zelf aan/uit kunnen zetten.
Dit zou misschien geplaatst kunnen worden achter het vraagnummer.
We hopen dat dit mogelijk is, i.i.g. hartelijk dank,

Giuseppe, Clip

**Comment by jtborger** [comment]
Daan, het is mij niet geheel duidelijk wat ze willen. Misschien voor jou wel en zou je het anders willen vragen?
- Als er een vraag binnenkomt van een client, dan wordt die door een medewerker geregistreerd. Is het de bedoeling dat er dan daarbij wordt aangegeven dat die medewerker die invoert deze vraag zelf gaat behandelen, en zo niet, dat deze dus door iedereen opgepakt kan worden?

Waar ik aan denk is dat een vraag wordt gekoppeld aan een medewerker, zodat duidelijk is dat hij/zij ermee aan de slag is. Als er geen medewerker aan gekoppeld zit (ondanks dat iemand de vraag heeft ingevoerd) dan kan een andere medewerker ermee aan de slag en die moet hem dan ook aan zichzelf 'toekennen'. Net zoiets als in Github als het ware :)

Dekt dat de lading denk je?

**Comment by dvleeuwen** [comment]
Ha Jan,
Jouw voorstel klinkt mij logisch.
Ik leg het voor aan de aanvrager, en koppel terug zodra er antwoord binnen
is.



Op di 4 jun. 2019 om 08:59 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Beste Daan,

De 'toegekende' naam is dus variabel, en staat open als deze niet door iemand wordt behandeld. 
Als het goed zichtbaar is voor iedereen, lijkt me dat een goede oplossing.

Alvast bedankt!
Giuseppe

**Comment by jtborger** [comment]
Ik begrijp het nog niet helemaal hoe het nu is ingericht. Wanneer is een vraag openstaand en wanneer afgesloten? En nu zit aan een vraag ook een medewerker gekoppeld. Dat is de medewerker die de vraag initieel heeft opgenomen denk ik? Maar dus niet perse degene die hem ook gaat behandelen? Is dat het idee, dat er dus een extra medewerker aan gekoppeld wordt? Of, wat ook kan, is dat de medewerker (welke als 'behandelaar' staat aangegeven volgens mij) niet wordt ingevuld bij het aanmaken van de vraag. 
dan verlies je weliswaar zicht op wie hem heeft ingediend, maar wat is de toegevoegde waarde van die informatie? Wordt dat gebruikt?
We zouden dat ook kunnen opslaan in een contactmoment, namelijk een initieel contactmoment waarbij dan die medewerker staat.

Ik vind dat een vraag 1 eigenaar moet hebben, en dus in principe gekoppeld moet zijn aan 1 medewerker. En niet perse de aanmaker. De aanmaker moet worden vastgelegd in een logboek (contactmoment)  denk ik. 
Dan hou je het zuiverder. Ook als je later wisselt van behandelaar/medewerker bv. zou je dat in zo'n contactmoment kunnen registreren.

Is dit een idee om het te implementeren?

**Comment by dvleeuwen** [comment]
Ik ga maandag bij CLIP op bezoek om een aantal ECD zaken te bespreken, deze
vraag/opzet neem ik dan mee!

groet
Daan

Op do 26 sep. 2019 om 10:05 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Aangezien deze al een tijdje open staat heb ik het volgende gemaakt en hoop maar dat het naar wens is:
een vraag krijgt geen behandelaar (medewerker) initieel. wel wordt het eerste contactmoment ingevuld met de medewerker die de vraag invoert.

nu zie je dus vrij snel of een vraag een medewerker heeft of niet.
dat lijkt mij vrij duidelijk. de medewerker die de vraag gaat behandelen kan hem aan zichzelf toekennen door de vraag te wijzigen en dan bij behandelaar zijn/haar eigen naam in te voeren (dat selecteert ie als het goed is automatisch).
dekt dit de lading zo?
(2.2.33)

**Comment by dvleeuwen** [comment]
Na aanpassen gaan er nu twee zaken fout:
-lijst openstaande vragen blijft leeg
-medewerker kan wel ingevuld worden, maar blijft in overzicht leeg, lijkt niet opgeslagen te worden

Tevens een laatste toevoeging/wens:
bij open vragen vinkboxje "hulp van collega gezocht". Als deze aangevinkt is de vraag een kleur geven in het overzicht

**Comment by jtborger** [comment]
2.2.35
straks online.

**Comment by dvleeuwen** [comment]
Gaat nog steeds iets mis bij het opslaan/tonen van medewerker. Pas na opnieuw wijzigen lijkt deze opgeslagen te worden:

De medewerker aan een vraag echter wordt niet direct weergeven in het overzicht (het lijstje met #, Cliënt, Hulp nodig?, Medewerker, Startdatum etc.), ook niet bij de openstaande vragenlijst.

Pas als je de vraag wijzigt komt de naam van de medewerker er wel in. (wijzigen-Vraag wijzigen-Behandeling-Medewerker-opslaan). Werkt dus wel, maar pas in tweeën. Mogelijk is het te verhelpen?


Alvast dank,
Giuseppe, medewerker Clip

**Comment by dvleeuwen** [comment]
Werkt nog steeds niet naar wens, naam mederwerker wordt niet altijd getoond in overzicht.

Zie in overzicht:
https://ecd.deregenboog.org/clip/vragen/?redirect=/clip/openstaandevragen/

Als je hier een vraag aanklikt waar geen medewerker vermeld staat, zie je dat er in feite wel een medewerker is. Wordt dus niet goed getoond in overzicht? Even bellen morgenochtend voor overleg

**Comment by dvleeuwen** [comment]
Ha Giuseppe
Jan zojuist gesproken: we gaan het nu aanpassen dat degene die eerste contactmoment heeft ook automatisch getoond wordt in het overzicht bij medewerker. Ik begrijp ook waar de verwarring vandaan komt bij Jan; want in een eerdere communicatie ging het er juist over dat dit veld ook open moest kunnen blijven. Anyways onduidelijkheid nu verholpen .

Wel nog een aanvullende vraag, om de puntjes op de i te zetten:Medewerker wordt nu dus automatisch degene die eerste contactmoment heeft, naam medewerker kan altijd handmatig aangepast worden. Als iemand later contact heeft mbt dezelfde vraag (dus nieuw contactmoment): moet naam medewerker in overzicht dan veranderen naar persoon van laatste contactmoment? Of blijven staan op oorspronkelijke medewerker?

Als we antwoord op deze vraag hebben kan Jan het vrijwel direct aanpassen/oplossen. (als niet duidelijk: bel me even)
groet!
Daan

**Comment by dvleeuwen** [comment]
Hoi Daan,

We kiezen ervoor de medewerker die het eerste contact heeft dan in het overzicht te laten staan.
Alvast dank!

Giuseppe

**Comment by jtborger** [comment]
2.2.48
