### ISSUE TITLE
aanpassingen OEK

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#826]
Hoi ECD'er,

Wij hebben nog een aantal vragen, wensen mbt  de Op EIgen Kracht module. 

We willen graag:
- een deelnemer kunnen verwijderen uit een lijst van een training = # 826

- een vrijwilliger afsluiten, zonder  dat de historie verdwijnt. nu kunnen we alleen verwijderen = #882
- bij het afronden van een training bij een deelnemer een veld verwezen naar = #886
- een deelnemer kunnen koppelen aan de groep EropUit-kalender. = #887
Met vriendelijke groet,

Jacqueline Wielaart,

**Comment by dvleeuwen** [comment]
liefst alle deelnemers automatsich EropUit-Kalender

**Comment by jtborger** [comment]
1. Deelnemer verwijderen van een training heb ik opgelost door een nieuwe status: Verwijderd. Dan blijft de geschiedenis zichtbaar. Als dit niet wenselijk is kan het ook anders.

**Comment by dvleeuwen** [comment]
Lijkt toch nog iets mis te gaan met verwijderen uit training, zie hier:
https://ecd.deregenboog.org/oek/deelnames/513/delete?redirect=/oek/trainingen/52/view

foutmelding zodra je op klikt

**Comment by dvleeuwen** [comment]
Ik splits dit issue op per punt. 
Dit draadje gaat nu enkel nog over 1ste punt, voor de overige maak ik nieuwe issues aan. Houdt het overzichtelijker.

**Comment by jtborger** [comment]
OK top.
Dit zou nu toch echt moeten werken (...)
