### ISSUE TITLE
foutmelding bij bekijken wachtlijst OEK

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#827]
Wij krijgen een foutmelding als we naar de  wachtlijst willen gaan. Hopelijk kan dit opgelost?

**Comment by jtborger** [comment]
Ik denk dat ik dit heb opgelost, ik krijg echter 0 resultaten als ik op wachtlijst klik nu - eerst een foutmelding, die heb ik dus getackled maar of er nu het juiste resultaat staat...

Wanneer ik kan gaan deployen en ook live kan meekijken kan ik dit beter bekijken. Vooralsnog denk ik dat ie gefixt is.

**Comment by dvleeuwen** [comment]
Ha Hille en Jacqueline,
de nieuwe programmeur denkt dat probleem is opgelost. Willen jullie voor zekerheid even checken of het idd naar behoren werkt nu?

groet!
Daan

**Comment by dvleeuwen** [comment]
opgelost maar nog niet live

**Comment by dvleeuwen** [comment]
werkt!
