### ISSUE TITLE
vraag: krijgt iedereen binnen SCIP automatisch eropuitkalender?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#829]
Hai Daan 

ik heb nog wel een vraag, als je bij de contactgegevens deze aan hebt staan;
Postvoorkeur              wel post
Email voorkeur           wel e-mail

krijg je dan de automatisch de EropUit kalender en de Meeleven?

Kabul

**Comment by dvleeuwen** [comment]
bij IZ automatisch eropuit module, onduidelijk hoe dit bij anderen zit

**Comment by jtborger** [comment]
Bij SCIP niet.
Moet dat wel?

**Comment by dvleeuwen** [comment]
Maandag zit ik met Dini, deze vraag neem ik dan ook mee!

Op do 26 sep. 2019 om 10:10 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
@dvleeuwen  Wat gaat het worden?

**Comment by dvleeuwen** [comment]
Ja goeie...
daar wilden ze toen nog even over nadenken/overleggen. Maar nooit meer
teruggehoord.
Heb zojuist vm Dini ingesproken met deze vraag.

Op di 14 jan. 2020 om 12:45 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Ha Dini,ik sprak vorige week je vm in, niet zeker of je die gehoord hebt?Anyways: wij (programmeur Jan en ik) hebben al enige tijd het punt "alle SCIPers de ErOpUitKalender" met een vraagteken op onze lijst staan.Kun jij de knoop doorhakken? Is het inderdaad wenselijk dat alle SCIPers deze ontvangen? Dan passen we dat aan in ECD.
Ik hoor het graag!groetDaan

**Comment by dvleeuwen** [comment]
Dini:

Ja! Dat willen we!

**Comment by jtborger** [comment]
OK dit zou nu moeten werken voor nieuwe deelnemers bij Scip.
Die worden als deelnemer bij de ErOpUit module toegevoegd.
Lijkt me dat dat de bedoeling is toch? Heb het gekopieerd van de Iz module.
2.2.36 (nog niet live dus)
