### ISSUE TITLE
knop "vrijwilligers toevoegen" verwijderen uit tab "vrijwilligers" algemeen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#831]

**Comment by jtborger** [comment]
Had je nog gecheckt of dit inderdaad echt niet gebruikt wordt? Dan haal ik het definitief weg.

**Comment by dvleeuwen** [comment]
Ja had ik gevraagd, wordt niet gebruikt: mag weg!

Op di 28 mei 2019 om 09:13 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
OK check.

**Comment by dvleeuwen** [comment]
opgelost maar nog niet live

**Comment by jtborger** [comment]
live
