### ISSUE TITLE
checken of ontdubbelfunctie nu goed werkt, en bepaalde mensen hier weer toegang toe geven

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#832]
https://ecd.deregenboog.org/admin/klanten/duplicates?redirect=/klanten/

**Comment by dvleeuwen** [comment]
Ha Jan,
het punt is dat deze optie voor anderen niet meer beschikbaar is. (zij krijgen foutmelding zodra ze 'beheer/dubbele invoer' klikken meen ik) Hier is voor gekozen omdat deze functie niet optimaal meer werkte na omzetten Cake  --> Symfonie , toen is het uitgeschakeld voor collega's. 
Zie stukje voorgeschiedenis: #649

Mijn voorstel: deze functie weer toegankelijk te maken voor iedereen (ik vermoed dat er maar 2 of 3 collega's zijn die hier daadwerkelijk gebruik van maken), en dan afwachten of men tegen problemen/fouten aanloopt. 

Mee eens? In dat geval dus graag zorgen dat klanten/beheer/dubbele invoer niet enkel meer voor admin toegankelijk is, maar voor iedereen.

**Comment by dvleeuwen** [comment]
Hoi Daan,

Helder. Ik kan het ook alleen toegankelijk maken voor de beheerders van de
verschillende afdelingen. Dat lijkt me verstandiger dan voor iedereen?

En dan kijken we inderdaad wel waar men tegenaan loopt.
Ik zal voor die tijd een sanity check doen of het niet meteen heel erg mis
gaat ;) en zal dat issue waarnaar je refereert even checken.

Wordt vervolgd

**Comment by dvleeuwen** [comment]
Mij lukt dit nog niet: ECD lijkt vast te lopen zodra je naar dubbele dossiers zoekt. Database te groot??

**Comment by jtborger** [comment]
Hij is inderdaad erg langzaam maar hij komt uiteindelijk wel boven bij mij.
Zeker die functie achternamen op elkaar lijken.
Wellicht eens op de schop doen.

#823 dubbel.
