### ISSUE TITLE
nieuwe rapportage maatschappelijk werk

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#833]
Hoi Daan,

voor de verantwoording van de repats bij de gemeente wil ik graag een uitdraai kunnen maken van de afgesloten Dossiers. Daarbij ik volgende info nodig:

Hoeveelheid Repats
Land van herkomst van geraptrieerde
Land van vertrek van de gerepatrieerde
Datum van vertrek.

Deze info is in ECD ingevoerd maar ik zie niet waar ik de rapportage ervan kan vinden. Kan ECD worden aangepast om deze info eruit te halen?

Groet,
Michael

**Comment by dvleeuwen** [comment]
Ha Michael,

Mocht je Daan nog niet gesproken hebben over die rapportagemodule voor de repatriëringen: er bestaat er inderdaad eentje. Alleen staat die op de verkeerde plek, namelijk  onder Inloophuizen. Daar kan je een rapportage selecteren, en in dat rijtje staat ie. Het een uitgeklede versie, waar alleen landen van terug keer en aantal per land in staan. Geen totaal, geen vertrekdatum, geen nationaliteit. Dat laatste hoeft trouwens misschien niet eens, maar datum en totaalaantal wel. En wat doen we dan in plaats van een naam, alleen een klantnummer? Iets om het dossier terug te kunnen vinden is denk ik toch wel handig. Ik heb in de bijlage een pdf gedaan van hoe het er nu uitziet.

**Comment by dvleeuwen** [comment]
rapportage staat nu onder inloophuis -> moet naar mw

Land van herkomst van gerepatrieerde
Land van vertrek van de gerepatrieerde
Datum van vertrek
Dossiernummers

**Comment by dvleeuwen** [comment]
Wordt een beetje warrig issue zo, maar bovenstaande is dus een aanvulling op bestaande rapportage. Die nu nog op verkeerde plek staat in ECD: 
Rapport "Repatriëringen per land van bestemming"

https://ecd.deregenboog.org/inloop/rapportages/?rapportage%5Bstartdatum%5D=01-01-2019&rapportage%5Beinddatum%5D=25-07-2019&rapportage%5Brapport%5D=InloopBundle%5CReport%5CRepatrieringenPerLand&rapportage%5Bshow%5D=

**Comment by jtborger** [comment]
Ik heb een rapportage gemaakt. Deze heet 'Repatriering per klant'.
Die uit Inloop (per land) staat nu ook in MW, dat is meer een samenvatting.
Deze per klant omdat men vraagt om land van herkomst, vertrek en dossiernummers.
Lijkt mij dus om een lijst te gaan in plaats van een aggregatie.
Als dit anders moet hoor ik het wel.

Ik heb nu het dossiernummer, land van herkomst en vertrek en de datum van vertrek - hoewel dit laatste niet wordt geregistreerd. Die datum is dus de datum waarop het inloopdossier gesloten werd.
