### ISSUE TITLE
nieuwe popup bij inchecken

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#834]
Hoi Daan,

Er is een nieuw TBC protocol waar we graag in ECD een registratie van willen:

Nieuwe bezoekers uit Romenie, Bulgarije, Estland, Letland en Litouwen moeten zich laten screenen bij de GGD. 

Wat we nodig hebben:

Bij de intake wordt het land van herkomst ingevoerd in ECD. Vanaf dat moment moet er bij de bezoekers uit bovengenoemde landen bij elke check in een pop up verschijnen, dat deze persoon naar de GGD moet

Deze pop up moet op gegeven moment ( wanneer de persoon bij de GGD geweest) door de coördinator kunnen worden verwijderd.

Kan Jan zo iets instellen?

Groet,
Michael

**Comment by dvleeuwen** [comment]
zelfde verzoek komt nu binnen via Janneke en Aukje, met als boodschap dat er haast bij is, ivm TBCbesmetting

Ha Daan, 

Er is een ander TBC beleid. 

De jaarlijkse controle TBC (pop-up) kan er uit voor alle bezoekers. 

Er moet een nieuwe pop-up komen voor nieuwe intakes uit Roemenie, Bulgarije, Estland, Letland en Litouwen . Deze moeten namelijk een eerste TBC screening doen bij de GGD. 
Dus:  als er een nieuwe bezoeker uit een van deze landen komt moet er een TBC pop-up verschijnen elke keer dat hij binnenkomt. Deze pop-up moet de dagco weg kunnen halen als de bezoeker bij de GGD is geweest.

**Comment by jtborger** [comment]
OK. Ik heb nog niet goed helder wat er moet komen.
Als ik het goed begrijp is er op dit moment een TBC check voor alle klanten van inloophuizen. Deze staan opgeslagen in het inloopdossier.
Iemand kan een inloopdossier hebben, maar nog geen intake, of een verlopen intake.
In de intake wordt niks gevraagd over TBC op dit moment.

Als ik het goed begrijp, moet er bij de intake van klanten uit die landen, een extra melding gedaan worden dat deze een TBC screening moeten doen.

Wanneer een bezoeker geregistreerd wordt bij een bezoek aan een inloophuis, moet er gekeken worden: komt klant uit risicoland? zo ja, laatste TBC check recent (hoe lang?) --> OK of melding niet ok.

Wanneer deze is bij GGD geweest is, kan de dagco dit (is dit qua rechten OK?) wijzigen dmv het instellen van de laatste TBC check in het inloopdossier van die klant.

Klopt dit zo?
En betekent dit ook dat de algemene TBC check eruit kan?
De huidige TBC check wordt alleen gecontroleerd (voor zover ik zie) als een bezoeker zich registreert bij een gebruikersruimte. Niet bij inloophuizen zonder gebruikersruimte.
Klopt dit ook voor de nieuwe werking van de TBC check?

**Comment by jtborger** [comment]
Zie mail Janneke

**Comment by jtborger** [comment]
Wat ik nu heb gemaakt is het volgende:
- Er bestond al iets voor tbc controle. Dat heb ik deels hergebruikt want tbc controle hoeft voor niemand meer, behalve:
- voor bezoekers uit risicolanden.
- wanneer een bezoeker uit een risicoland zich meld bij portier om in te checken krijgt portier melding dat de tbc controle langer dan 6 mnd geleden is en deze persoon uit een risicoland komt met de vraag: toch inchecken?
- wanneer een bezoeker uit risicoland komt, moet deze een ggd verklaring laten zien. Wanneer klant die heeft kan via klant --> wijzigen de datum laatste tbc controle worden ingesteld.

**Comment by jtborger** [comment]
Even voor de volledigheid de laatste emailzaken:
Ik heb zojuist een nieuwe versie klaargezet waarin ik deze functie in heb verwerkt. Hopelijk op de goede manier, maar het kan best zijn dat ik toch zaken door elkaar heb gehaald of ze anders werken dan jullie wensen.

Het volgende zou moeten werken:

Wanneer bij Inloophuizen er een nieuwe klant wordt aangemaakt komt er een popup zodra deze uit een risicoland komt. Er verschijnt dan een datumveld (TBC-check?) wat fungeert als 'het vinkje'. Die datum heeft men vast niet wanneer ze voor het eerst aanmelden, maar dan is het iig duidelijk dat de klant erop gewezen moet worden. Er veschijnt bij opslaan ook een extra melding bovenaan.
Wanneer een klant wordt gewijzigd die uit een risicoland komt en deze heeft geen TBC check datum, dan komt er een melding. 
Wanneer een klant komt met bewijs van de TBC controle kan dit dus worden ingevoerd via Klant wijzigen en dan in het veld TBC check de datum invullen. Als het goed is komt er dan geen popup meer.
Wanneer er een intake gedaan wordt, en klant komt uit risicoland EN heeft geen TBC check gedaan (datum veld leeg) dan popup. Intake kan gewoon worden afgemaakt en opgeslagen maar is dus een reminder om te melden aan klant
Wanneer klant zich meld bij portier en heeft geen datum en komt wel uit risicoland: melding aan portier met vraag: wel of niet inchecken.
Wanneer een inloopdossier heropend wordt, wordt er ook een melding gegeven wanneer klant uit risicoland en tbc check datum niet gevuld.

Ik hoor graag of het zo naar wens is of dat er nog zaken anders moeten.

Laatste vraag:
Voorheen werden er dus voor sommige klanten die datum laatste tbc controle vastgelegd. Mogen die allemaal worden gewist? Want ik gebruik dat veld nu voor de nieuwe TBC check.

**Comment by jtborger** [comment]
Er was nog iets niet goed: bestaande klanten kregen allemaal die melding (de portier). Dat was niet de bedoeling: alleen nieuwe klanten.
In overleg met Aukje heb ik alle bestaande klanten die bekend zijn en zich ooit hebben aangemeld tot 2 weken terug een 'fake' TBC controledatum gegeven.
Klanten met aanmeldingen vanaf 01 juli hebben geen tbc datum en dus krijgen de popup (zowel bij intake als registratie).
