### ISSUE TITLE
toegang ip-adres Vellance

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#835]
Hoi Bart,

Onze nieuwe IT supplier, TARQ-PCI, kan niet bij https://ecd.deregenboog.org vanuit hun datacenter. 

Het uitgaande IP-adres van het datacenter is: 91.234.17.1

Kan jij ervoor zorgen dat dit ip-adres toegang krijgt tot de website bij Vellance?

Vriendelijke groet,
Bastiaan Mathot

**Comment by jtborger** [comment]
In een call gezet bij Sentia / SIS. Nog geen response...

**Comment by jtborger** [comment]
IP adres zou toegevoegd moeten zijn.
