### ISSUE TITLE
fout in code bij dagbesteding

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#836]
mail Daan:
Voor zover mij bekend krijgen nieuwe medewerkers een inlog en ECDrechten via Tineke, en zijn dan ook automatisch terug te vinden in ECD als medewerker vd betreffende afdeling (zodat caseload op hun naam gezet kan worden etc, en ze een "Mijn IZ" pagina hebben). 
Nu blijkt dit bij een nieuwe collega bij dagbesteding niet automatisch te gaan (zie ook mails hieronder). Onder dagbesteding/beheer heb ik wel de mogelijkheid "trajectbegeleider toevoegen", wat klinkt als een mogelijke oplossing, maar deze lijkt niet te werken: Hier staan vreemd genoeg geen trajectbegeleiders onder, maar redenen van afsluiting.

antwoord Bart:
Wat betreft je vraag: bij dagbesteding werkt het anders dan op veel andere plekken in ECD. Het lijstje met trajectbegeleiders is niet hetzelfde als een lijstje medewerkers. Hierin kunnen ook namen van externen staan (die niks met ECD te maken hebben). Via de link die jij probeerde zou je normaal gesproken een medewerker aan het lijstje toevoegen. Maar ik zie in de code een foutje staan waardoor je iets anders te zien krijgt. @Jan hier moet TrajectafsluitingDao gewijzigd worden in TrajectbegeleiderDao.

**Comment by jan** [comment]
@dvleeuwen hejsa hopsa!

**Comment by dvleeuwen** [comment]
Ai Arno, 
heel wonderlijk, en vervelend.
Het is mij eigenlijk een raadsel hoe het kan dit dit vrijdag wel mogelijk was. 
Ik speel het direct door naar onze programmeur, hopelijk is het hem wel duidelijk. En bovenal: hopelijk lukt het hem dit op te lossen, zodat jij gewoon onder eigen naam aan de slag kan in ECD.

@Jan:
zie berichten hieronder, betreft #836
Nieuwe medewerker bij dagbesteding staat dus niet automatisch in ECD. Door een fout in code kan hij ook via beheer niet toegevoegd worden (zie eerdere mail Bart). Nu leek het om raadselachtige wijze eind vorige week opgelost te zijn, maar vandaag weer niet mogelijk...
Hopelijk kun jij hier verder mee?

dank & succes!
Daan

**Comment by dvleeuwen** [comment]
ah ik snap nu ook waarom die Duitse Jan hier eerder op reageerde, komt door mijn gebruik van @... Jan
;)
Zal hierop letten in toekomst

**Comment by jtborger** [comment]
@dvleeuwen dan moet je @jtborger  gebruiken :)

**Comment by jtborger** [comment]
nb hij staat nu wel in github maar nog niet live. hij closed ze automatisch als ik ze noem in mijn commentaar bij publish naar github.
