### ISSUE TITLE
verplaatsen documenten

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#841]
Gisteren mailde ik je ivm de vraag of er een verwijderoptie moet komen voor de documenten linksonder in het vw-dossier. Het lijkt wel alsof ik het erom doe, maar vandaag stuit ik op een testcase... Ik ben bezig met het opschonen van vw-dossiers IZ zonder intakedatum (in overleg met Miranda Dijks). Een dossier op de lijst is dat van Janneke de Jongh. Het blijkt nu dat in dit dossier per ongeluk de VOG en vw-overeenkomst geupload zijn van Jolien de Jongh. 
Bij deze dus de vraag aan Jan Borger om deze documenten van het dossier van Janneke de Jongh (inmiddels afgesloten, 13732) te verplaatsen naar dat van Jolien de Jongh (14413). 

Alvast dank!

Groet,

Josje

**Comment by jtborger** [comment]
Ik kom er nog niet helemaal uit, ga bart mailen. De koppeling tussen documenten en vrijwiliigers is wat schimmig en ondoorzichtig vind ik.
Ik heb de documenten bij janneke 13732 weggehaald en op jolien gezet 14413, maar ik zie ze daar nog niet verschijnen en dat snap ik niet.

**Comment by jtborger** [comment]
Gelukt.
