### ISSUE TITLE
toevoegen projecten / doelgroep bij aanmaken hulpvraag en hulpaanbod

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#842]
Bij aanmaken nieuw hulpaanbod en nieuwe hulpvraag toevoeging bij projecten:

DV uitlaat
DV langdurig

Bij doelgroepen toevoegen:
huisdier

in augustus nodig

**Comment by jtborger** [comment]
Hoi Daan,
ik snap dit niet helemaal... Ben niet goed thuis in IZ. Kunnen we even bellen?

**Comment by dvleeuwen** [comment]
gedaan + bij projecten Dier en Vriend aangemaakt

zijn nog niet terug te zien in rapportages, maar dit is vermoedelijk omdat score overal nog 0 is
