### ISSUE TITLE
Bij het aanmaken van nieuw dossier dagbesteding lijkt de check of deelnemer al in ecd staat niet altijd te werken

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#843]
ivm het niet mogen noemen van namen via Github stuur ik Jan een mail met meer info.
Het lijkt erop dat sommige deelnemers wel, en andere niet, herkent worden als al bestaand in het systeem.

**Comment by dvleeuwen** [comment]
Het lijkt om verschil in weergave te gaan, zie te vergelijking Informele Zorg, graag op deze wijze

**Comment by jtborger** [comment]
Gaat mee in 2.2.19
