### ISSUE TITLE
Homeservice: vrijwilliger die is disabled/verwijderd wel/niet laten zien in dossier

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#844]
@dvleeuwen Wanneer een vrijwilliger verwijderd danwel disabled is, wordt deze niet laten zien in de klus.
Is dit inderdaad de bedoeling?

**Comment by dvleeuwen** [comment]
deze snap ik niet, waar komt verzoek/opmerking vandaan?
Donderdag even tel contact

Op ma 1 jul. 2019 om 11:53 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
na overleg: lijkt ok nu
