### ISSUE TITLE
handmatig aangemaakte facturen zijn niet meer te wijzigen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#845]
Iris:
Ik kan handmatige aangemaakte facturen niet meer wijzigen of verwijderen, ook niet als ze nog niet definitief zijn.

**Comment by jtborger** [comment]
Kon dit wel? En zo ja, tot wanneer kon dit?

**Comment by jtborger** [comment]
Voor zover ik zien kan heeft dit nooit gekunt. Klopt dat?
Ik heb het nu wel zo gemaakt, maar is even de vraag waarom het er nooit in heeft gezeten dan, als dat in elk geval zo is.
In de code kan ik het zo gauw niet terugvinden.
Gaat vanmiddag live

**Comment by dvleeuwen** [comment]
Ha Iris,
nog een vraag van Jan aan jullie: bij dit issue (zie onderwerp): dat kon in verleden wel? En if so: weet jij sinds wanneer (ongeveer) dit niet meer lijkt te werken?

dank & groet
Daan

**Comment by dvleeuwen** [comment]
antwoord Iris:
Ja, dit kon wel, ik denk dat het rondom de jaarwisseling veranderd is. Toen wij terugkwamen van vakantie werkte een heleboel dingen opeens anders :)   

Viel mij in ieder geval voor het eerst op rond 07-02-2019, toen ik een handmatige factuur voor klant Fer heb aangemaakt.

**Comment by dvleeuwen** [comment]
werkt volgens Iris nog steeds niet, op haar verzoek heropen ik issue

- ik kan handmatige facturen niet meer wijzigen of verwijderen, zelfs als ze nog niet definitief zijn. Dat kon eerder wel (Zie bijvoorbeeld XXX 
https://ecd.deregenboog.org/hs/klanten/?klant_filter%5Bfilter%5D=&klant_filter%5Bid%5D=&klant_filter%5Bnaam%5D=schopman&klant_filter%5Bhulpverlener%5D=&klant_filter%5Badres%5D=&klant_filter%5Bstadsdeel%5D=&klant_filter%5BafwijkendFactuuradres%5D=&klant_filter%5Bstatus%5D=

**Comment by jtborger** [comment]
Iris gebeld; het werkte wel, maar ze konden niet verwijderd worden. Wel op 0.
Nu dan ook verwijderen toegevoegd.
