### ISSUE TITLE
verdwenen info uit ecd?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#846]
Ferdgie heeft vaker het idee dat er info van zijn clienten uit ECD verdwijnt. 
Hierbij concreet voorbeeld: 06nummer is verdwenen, waar dat er voorheen echt stond. 
https://ecd.deregenboog.org/dagbesteding/deelnemers/151/view?redirect=/dagbesteding/deelnemers/

Hopelijk lukt het Jan om in de geschiedenis terug te vinden wanneer (en door wie?) dit verwijderd is.

**Comment by jtborger** [comment]
Het is wel raar, want in de database staat dat de klantinfo voor het laatst gewijzigd is in januari.
Dus niet recent. Uit de recente logbestanden vind ik niks.

Als hij weer denkt dat het zo is moet ie het maar melden dan kunnen we er weer naar kijken.
Kan niet uitsluiten dat er niks mee is gebeurd, hoewel de datum in de database er niet op wijst.

**Comment by dvleeuwen** [comment]
Ok Jan, thanks!
En dat kan best kloppen hoor, geen idee hoe intensief dat contact is.
Wellicht 1x per half jaar evaluatie, en dan zou het dus prima kunnen dat
het er in januari nog in stond, en dat Ferdgie nu pas merkt dat het
aangepast is.
Je kon niet toevallig nog achterhalen wie er als laatste iets in dat
dossier gewijzigd heeft?

groet
Daan

Op do 4 jul. 2019 om 10:48 schreef JT Borger <notifications@github.com>:
