### ISSUE TITLE
overzicht inloopbezoekers van bepaalde postcode

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#847]
Jan: kun jij een uitdraai maken van bezoekers inloophuizen die wonen in postcode 1093?

mail Sander:
Hoi Daan,

Voor een pilot van het verbond van 100 in oost wil ik graag filteren op postcode in ECD. Is het mogelijk om uit het klantensysteem van DRG (van de inloop) te filteren op postcode 1093? Ik hoor het graag!   
Met vriendelijke groet,

 

Sander Verweij

**Comment by jtborger** [comment]
Hoi Daan/ Sander,
Ik heb een query gemaakt die alle bezoekers aan inloophuizen uit 1093 vanaf 01-01-2019 laat zien en ook een van altijd.

Ik mail het resultaat even naar Daan. Als de tijdsspanne anders moet hoor ik het wel.

Groet,
Jan

**Comment by jtborger** [comment]
SELECT CONCAT_WS(' ', klant.voornaam, klant.tussenvoegsel, klant.achternaam) AS naam, klant.roepnaam, klant.geboortedatum, COUNT(registratie.id) AS aantal FROM klanten AS klant INNER JOIN registraties AS registratie ON registratie.klant_id = klant.id WHERE  klant.postcode LIKE '1093%' AND DATE(registratie.binnen) BETWEEN '2019-01-01' AND '2019-07-31' GROUP BY klant.id ORDER BY klant.achternaam
