### ISSUE TITLE
mogelijkheid voor medewerkers om geuploade documenten te verwijderen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#849]
Op veel plaatsen kan dit al, maar nog niet overal:

-bij IZ toestemmingsformulier deelnemer
-bij IZ VOG & overeenkomst vrijwilliger
-bij Maatschappelijk werk toestemmingsformulier
-bij maatschappelijk werk overige documenten

**Comment by dvleeuwen** [comment]
+ waarschuwing "weet je het zeker?"

**Comment by jtborger** [comment]
Het lijkt erop dat bij deelnemers (=klant) er een algemene weergave wordt gebruikt die in heel ECD zit. Daardoor betekent een wijziging hier, een wijziging voor iedereen. Met andere woorden, mag iedereen ook in andere modules het toestemmingsformulier verwijderen?
Dat geldt naw ook voor de andere soorten documenten die je vraagt.

**Comment by dvleeuwen** [comment]
Ideale oplossing zou zijn alleen mogelijkheid om documenten te verwijderen
die jezelf hebt toegevoegd. Is dat realiseerbaar, of te ingewikkeld?


Op do 26 sep. 2019 om 11:11 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Gaat mee in volgende release. Alleen documenten die door de medewerker zelf zijn geupload kunnen verwijderd worden. 
mensen met ROLE_ADMIN (jij en ik en hans geloof ik) kunnen sowieso documenten verwijderen.
Dit werkt nu voor alle basis documenten aan een klant en vrijwillilger.
MW overige documenten maak ik een nieuw issue aan. Staat los van het globale ding.
