### ISSUE TITLE
aanpassen managementrapportage IZ

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#850]
mail 4 april (net voordat duidelijk werd dat Bart zou stoppen)

Ha Bart,
bij IZ is behoefte aan een nieuwe (management)rapportage.
Hieronder de wensen zoals in overleg vanmiddag besproken.

Wil jij alvast kijken:
-of onderstaande duidelijk is voor jou
-of je inschatting kunt maken of/wanneer je dit kunt aanpassen

Dan bellen we er volgende week over.
Dank alvast!

Nieuwe rapportage:
-verticaal: hulpvraagsoort deelnemer
-horizontaal: doelgroep deelnemer

In management rapportage:
In 1 overzicht cijfers per hulpvraagsoort: gestart + nieuw en succesvol afgesloten
In 1 overzicht cijfers per doelgroep: gestart + nieuw en succesvol afgesloten
En bovenstaande cijfers uitgesplitst per stadsdeel (zoals in huidige managementrapportage nu per project staat, projecten verdwijnen dus in geheel uit de managementrapportage)

**Comment by jtborger** [comment]
Als ik het goed begrijp vervang ik de gegevens die nu per proejct staan in de gegevens per doelgroep, per stadsdeel.

en moet er dan ook per hulpvraagsoort een overzicht komen en da took weer per stadsdeel?


Wat doen we met overzicht per team?

**Comment by dvleeuwen** [comment]
Poe, tricky met die oude issues is dat het verleden soms alweer ingehaald
wordt door heden... (zeg je dat zo?)
Beperk je svp voor nu tot eerste verzoek:
Nieuwe rapportage:
-verticaal: hulpvraagsoort deelnemer
-horizontaal: doelgroep deelnemer

Aanpassing managementrapportage wil ik even dubbelchecken, want ik vermoed
dat daar nu alweer iets anders mee moet.
Kom ik op terug!



Op ma 4 nov. 2019 om 11:46 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Ha Marit & Lennaert,Jan is bezig met een oudere issue (van de periode dat Bart ons verliet)Daarin vragen wij om alle oude IZprojectnamen definitief te verwijderen uit ECD. Is dit inderdaad wat wij (nu) willen?
Volgens mij worden deze nog steeds gebruikt voor verantwoordingen en cijfertjes, toch?Of kunnen we deze inderdaad doorzetten en verder gaan met een ECD zonder oude projectnamen?
Graag jullie reactie.
dank!Daan

**Comment by dvleeuwen** [comment]
Marit:
hi,

ja het lijkt nog steeds goed om ze erin te houden..

een deel omdat de fondsen graag projecten financieren. en dan kun je beter alle projectnamen ng even erin houden? 

Daan:
Ja precies,
ik meende ook dat dit nog altijd nuttige info was voor ons.
Dan schrap ik dit oude issue.

Hoor ik wel graag nog terug van jullie of er nog andere wensen zijn mbt rapportagemogelijkheden. Of dat we nu up-to-date zijn, en alles werkt en vindbaar is zoals jullie willen.
(zie ook eerdere mails)

dank!
Daan
