### ISSUE TITLE
vinkje bij intake deelnemers inloophuizen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#851]
verzoek Janneke:

bij intake vwers moet vinkboxje komen 'geinformeerd over opslaan gegevens'

tevens moet het mogelijk zijn een uitdraai te maken van de personen waarbij dit niet is aangevinkt

**Comment by jtborger** [comment]
Gedaan, echter de vraag voor een uitdraai cq download: die mogelijkheid is er op dit moment niet bij de algemene tab klanten en vrijwilligers.
daar is een reden voor (je wilt eigenlijk niet in 1 keer alle klanten of vwers downloaden, systeembelasting maar ook: teveel gegevens te makkelijk toegankelijk, lijkt mij)

Waar / vanuit welke module wil Janneke die VW uitdraai hebben?

**Comment by dvleeuwen** [comment]
Gaat hier allen over module inloophuizen

Op ma 4 nov. 2019 om 12:06 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Zit in de download als je inloop -> vrijwilligers -> download kiest in het overzicht.
2.2.33

**Comment by dvleeuwen** [comment]
Arg, miscommunicatie:
Vinkje blijkt nu nodig bij clienten inloophuizen ipv vrijwilligers

**Comment by jtborger** [comment]
Moet hij weg bij Inloop VW?

**Comment by jtborger** [comment]
Heb het weggehaald bij VW en ingevoegd bij klanten. als het anders moet hoor ik het wel.

2.2.36

**Comment by dvleeuwen** [comment]
perfect, dank!

Op do 23 jan. 2020 om 17:07 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Ik zie nu dat dit ook bij deelnemers IZ is geimplementeerd, moest alleen bij inloophuizen.
Of kan dat niet omdat het nu bij basisgegevens staat?

**Comment by jtborger** [comment]
Inderdaad, basisgegevens. Ik denk overigens dat je ivm AVG dit voor alle
clienten zou moeten toch?
Ik weet het niet zeker, maar goed.
Kan deze weer dicht?

**Comment by dvleeuwen** [comment]
Ah nee,
net iets lastiger:
Elke afdeling doet dit op zn eigen manier. Bij ons (IZ) worden hiervoor de
toestemmingsformulieren gebruikt en geupload. En zorgt dit vinkje bij
intake dus eerder voor verwarring.
Is het een kleine ingreep om het enkel bij inloopdossiers bij te houden?
Dus niet basisgegevens?
Zo niet, zal ik even verder moeten denken/overleggen wat we hier mee
willen.

groet!
Daan

Op di 28 jan. 2020 om 16:31 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
OK dan moet ik het even om gaan bouwen... wordt vervolgd :)

>

**Comment by jtborger** [comment]
2.2.38

**Comment by dvleeuwen** [comment]
Met excuses voor de verwarrende communicatie:
moet bij deelnemers Inloop en Maatschappelijk Werk
Staat nu (volgens Janneke?) alleen bij MW.

**Comment by jtborger** [comment]
Dag Daan,

Het wordt wat rommelig zo. Ik zie het gewoon bij Inloop klanten staan.
Het staat feitelijk overal behalve bij Iz. Het behoort tot de basis klant gegevens weergave die zoveel mogelijk wordt hergebruikt. Ik heb het zo gemaakt dat Iz de uitzondering is.

Maar het zal me niks verbazen als er een beetje langs elkaar heen wordt gecommuniceerd.
Even bespreken dus.

**Comment by dvleeuwen** [comment]
Als ik een nieuwe klant toevoeg via inloop zie ik het vinkje nergens?

maar we bellen hier vanmiddag even over!

**Comment by dvleeuwen** [comment]
zoals telefonisch besproken:
vinkje moet zichtbaar zijn in scherm waar je nieuwe deelnemer/klant aanmaakt voor inloop en mw.

**Comment by dvleeuwen** [comment]
aanvullend verzoek Janneke:

Hoi Daan,

Nog even over dat suffe AVG-vinkje bij de intake van inloophuizen en MW: zou Jan daar een verplichtend vinkje van willen maken? Dat je niet kunt opslaan zonder dat je dat vinkje hebt aangezet? 

Dank alvast & fijn weekend!
Met vriendelijke groet,

**Comment by jtborger** [comment]
Gedaan,
maar:

als een nieuwe klant wordt aangemaakt wordt alleen het hoognodige gevraagd.
Adresgegevens, postvoorkeur etc zit op een ander 'blad' en daar staat dat
vinkje ook.
maw: het is dus in de huidige manie rvan werken prima mogelijk een klant
aan te maken (weliswaar zonder adresgegevens) omdat dat vinkje niet voorbij
komt.

is dit de bedoeling?
Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op ma 24 feb. 2020 om 15:57 schreef dvleeuwen <notifications@github.com>:

**Comment by dvleeuwen** [comment]
verplaatsen naar intake,
ik check nog bij Michael of het wel/niet ok is als dit bij elke herintake opnieuw langs komt

**Comment by jtborger** [comment]
2.2.40
