### ISSUE TITLE
foutmelding bij invoer nieuwe deelnemer

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#852]
Ha Jan,
heb jij iets veranderd bij aanmelding nieuwe deelnemer?

Je komt daar altijd eerst op een pagina terecht waar gekeken wordt of de persoon al in het systeem staat. Als je nu een naam intypt die nog niet bekend is, kom je op een foutmeldingspagina terecht, waardoor je niet door kunt met invoeren.

Kun je hier naar kijken?

https://ecd.deregenboog.org/iz/klanten/add?redirect=/iz/klanten/ 
https://ecd.deregenboog.org/iz/klanten/add?klant=new 

(ik maak ook een github aan)  

Dank!
Daan

**Comment by dvleeuwen** [comment]
Ha Jan,
aanvullend: ik dacht via een omweg voorlopig wel nieuwe deelnemers in te kunnen voeren. Namelijk een bestaande naam intypen, en dan in het volgende scherm te kiezen voor "nieuwe deelnemer", maar ook dan kom ik op de foutmeldingspagina. Kortom: het is nu geheel onmogelijk nieuwe deelnemers in te voeren, en dat is erg lastig.
Hopelijk begrijp jij wat hier de oorzaak van is, en kunt het spoedig terugdraaien?

https://ecd.deregenboog.org/iz/klanten/add?klant_filter%5Bid%5D=&klant_filter%5Bnaam%5D=klaas&klant_filter%5Bbsn%5D=&klant_filter%5Bgeboortedatum%5D=&klant_filter%5Bfilter%5D= 
https://ecd.deregenboog.org/iz/klanten/add?klant=new&redirect=/iz/klanten/add 

groet!
Daan

**Comment by jtborger** [comment]
kwam door aanpassingen ivm #831 
opgelost.
