### ISSUE TITLE
foutief ingevoerde ZRM verwijderen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#853]
Hey, 

Ik heb per ongeluk bij Nataliya Il'yina ZRM klant erin gezet. 
Ik heb dat hersteld naar een Maatschappelijk werk ZRM. 
Kun je die van -klant- eruit halen? 
Dankjewel!
Met vriendelijke groet,

Camilla Franken

**Comment by jtborger** [comment]
gedaan
