### ISSUE TITLE
rapportage PFO op stadsdeelniveau

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#854]
Hoi Daan,

Het is weer zo ver: ik heb cijfers nodig voor de verantwoording van PFO in stadsdeel Centrum. Kun jij me weer (laten) helpen aan het aantal mensen dat door PFO is gezien in de periode 01-01-2019 tot en met 30-06-2019, uit stadsdeel Centrum?

Dank alvast!
Met vriendelijke groet,

Janneke van Loo, Regiomanager Centrum / Noord / Oost

----

**Comment by dvleeuwen** [comment]
dit is een terugkerend verzoek, dus wellicht rapportage aanpassen zodat medewerkers deze info zelf uit kunnen draaien?

**Comment by dvleeuwen** [comment]
Na overleg: ja wens is hier aparte rapportage voor aan te maken, zie #855

Ik laat deze (854) open staan, gaat dus puur om de uitdraai van bovenstaande. Kan me voorstellen dat dit sneller/eerder gedaan is dan nieuwe rapportage, dus vandaar 2 losse issues

**Comment by jtborger** [comment]
Ik doe dat met deze query:
SELECT DISTINCT MAX(DATE(v.modified)) AS laatste_contact, COUNT(cv.id) AS num_contact, c.roepnaam, c.tussenvoegsel,c.achternaam,c.postcode,g.naam AS groep FROM pfo_clienten_verslagen AS cv INNER JOIN pfo_clienten AS c ON c.id = cv.pfo_client_id 
INNER JOIN pfo_verslagen AS v ON v.id = cv.pfo_verslag_id
INNER JOIN pfo_groepen AS g ON g.id = c.groep
WHERE
(
    c.postcode LIKE ('1011%')
    OR
    c.postcode LIKE ('1012%')
    OR
    c.postcode LIKE ('1013%')
    OR
    c.postcode LIKE ('1014%')
    OR
    c.postcode LIKE ('1015%')
    OR
    c.postcode LIKE ('1016%')
    OR
    c.postcode LIKE ('1017%')
    OR
    c.postcode LIKE ('1018%')
)
AND
v.modified BETWEEN DATE("2019-01-01") AND DATE("2019-06-30")
GROUP BY cv.pfo_client_id DESC
ORDER BY v.modified DESC

**Comment by jtborger** [comment]
Kan ook zo:
SELECT DISTINCT MAX(DATE(v.modified)) AS laatste_contact, COUNT(cv.id) AS num_contact, c.roepnaam, c.tussenvoegsel,c.achternaam,c.postcode,g.naam AS groep FROM pfo_clienten_verslagen AS cv INNER JOIN pfo_clienten AS c ON c.id = cv.pfo_client_id
INNER JOIN pfo_verslagen AS v ON v.id = cv.pfo_verslag_id
INNER JOIN pfo_groepen AS g ON g.id = c.groep
INNER JOIN postcodes AS pc ON pc.postcode = c.postcode
WHERE
(
pc.stadsdeel = 'Centrum'
)
AND
v.modified BETWEEN DATE("2019-01-01") AND DATE("2019-06-30")
GROUP BY cv.pfo_client_id DESC
ORDER BY v.modified DESC

MAAARRRRR
dan zit 1018 er niet bij, gek genoeg?
