### ISSUE TITLE
Rapportage mogelijkheden PFO op stadsdeel en postcodegebied

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#855]

**Comment by jtborger** [comment]
Voor PFO clienten gelden andere regels dan gewone klanten. Ze worden enkel bij PFO geregistreerd en dus niet alles wat voor normale klanten werkt, werkt voor PFO klanten.
Zoals stadsdeel/postcodegebied, dat wordt niet geregistreerd. Natuurlijk kan dit gemaakt worden, maar de vraag is dan of het niet beter zou zijn om PFO klanten gelijk te stellen aan andere klanten van DRG. Dan gaan ze ook mee in eventuele rapportages etc, zonder allerlei kunstgrepen te moeten doen.
Er is vast bewust een keuze gemaakt PFO klanten erbuiten te houden. Maar ik weet niet waarom.

**Comment by dvleeuwen** [comment]
Hans geeft aan dat het ivm privacy een bewuste keuze is de PFOklanten niet te koppelen aan algemene klantenlijst.
Ik vraag Janneke met deze info hoe belangrijk dit issue is. Wacht op antwoord.

**Comment by dvleeuwen** [comment]
Antwoord Janneke:
ze heeft 2x per jaar deze cijfers nodig. 
Aan ons wat wenselijk is: ombouwen/nieuwe rapportage of 2x per jaar op verzoek door Jan uit laten draaien
Jan: wat heeft jouw voorkeur?

**Comment by jtborger** [comment]
Dat weet ik nog niet. Even over nadenken wat de implicaties zijn en hoeveel tijd het kost zoiets te bouwen.

**Comment by jtborger** [comment]
Welke cijfers wil Janneke hebben uitgesplitst per stadsdeel dan? Dan kan ik even kijken hoe of wat.

**Comment by jtborger** [comment]
Ik heb lig nu gemaakt dat stadsdeel en werkgebied wordt opgeslagen voor de cliënten van PFO dus dan is het een kwestie van rapportage bouwen.

**Comment by dvleeuwen** [comment]
Het aantal klanten per stadsdeel

Op di 14 jan. 2020 om 13:28 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
deze rapportage zit er nu in als het goed is. als het anders moet hoor ik graag welke gegevens. de stadsdeel en ggw gebieden worden nu bijgehouden en gekoppeld aan postcode wanneer nieuwe cliënten worden aangemaakt. voor oude cliënten heb ik het opnieuw laten koppelen. dus de rapportage was een kleine moeite nu.
2.2.36
