### ISSUE TITLE
na aanpassen postcode naar buiten Amsterdam blijft stadsdeel en werkgebied op oude gegevens staan

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#856]
Hoi Daan,

Ik merkte dat bij wijzigen van een Amsterdams adres in een adres buiten Amsterdamten het eerder ingevoerde Amsterdamse postcodegebied ten onrechte blijft staan. 
In mijn sent items zie ik dat ik eind 2017 hier met Bart over heb gemaild (toen ging het specifiek over Amstelveen/Diemen), zie zijn reactie:

Op 20 december 2017 om 13:55 schreef Bart Huttinga <bhuttinga@deregenboog.org>:
Hoi Josje,

Diemen en Amstelveen krijgen inderdaad geen postcodegebied, zou dus leeg moeten zijn. Dat het oude postcodegebied blijft staan is uiteraard niet de bedoeling, dat zal ik aanpassen.

Met vriendelijke groet,
Bart Huttinga
 
Blijkbaar werkt het toch niet helemaal op dit moment. Zie dit dossier van XXX, vw IZ: https://ecd.deregenboog.org/iz/vrijwilligers/13317/view?redirect=/iz/vrijwilligers/
Kan dit (weer) op de lijst? Alvast dank.

Groet,

Josje

**Comment by jtborger** [comment]
Opgelost. 2.2.24
