### ISSUE TITLE
Kolom Maatschappelijkwerker toevoegen in klantenoverzicht

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#859]
Deze schijnt er in verleden geweest te zijn, maar (onterecht?) verwijderd.

Graag hier weer kolom maatschappelijkwerker toevoegen. 

https://ecd.deregenboog.org/mw/klanten/

**Comment by dvleeuwen** [comment]
Ha Jan,als jij deze week nog een keer 10 minuten over hebt: zou je een blik op #859 willen werpen? Dit is iets waar ze erg blij van worden (wordt regelmatig naar status gevraagd) ik heb het echter nooit prio willen geven, en had gehoopt dat het inmiddels ongeveer wel aan de beurt was. Maar doordat er steeds andere prios tussendoor komen, is dat er nog niet van gekomen.Omdat het lijkt te gaan om een functie die er voorheen was, maar nu niet meer: zou je eens kunnen kijken of dit simpel weer in te voeren is (kolom maatschappelijkwerkers).Als dit een kleine klus is: wil je m uitvoeren? Als het toch meer werk is, laten we hem gewoon staan waar ie nu staat.
dank!Daan

**Comment by jtborger** [comment]
Ik ga er even naar kijken.
Is dat het veld 'case manager'?
of trajectbegeleider?

**Comment by dvleeuwen** [comment]
Ha Jan,
ik vermoed het veld "medewerker"
Zie hier een voorbeeld dossier, in overzicht van klanten zou deze dus in
kolom medewerker Eva moeten tonen volgens mij.
https://ecd.deregenboog.org/mw/klanten/5627080/view?redirect=/mw/klanten/

Ik zie zelf 'case manager' en 'trajectbegeleider' niet terug in
maatschappelijkwerkdossiers?

groet!
Daan

Op di 19 nov. 2019 om 09:47 schreef JT Borger <notifications@github.com>:

**Comment by jtborger** [comment]
Ok!
Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op di 19 nov. 2019 om 11:04 schreef dvleeuwen <notifications@github.com>:

**Comment by jtborger** [comment]
gaat mee in release

**Comment by dvleeuwen** [comment]
Toch nog een aanpassing nodig:
moet gaan om medewerker(s) die verslagen toegevoegd hebben bij maatschappelijkwerk, niet om medewerker basisgegevens.

**Comment by jtborger** [comment]
Zie bv OEK: https://ecd.deregenboog.org/oek/deelnemers/
trainingen per deelnemer

**Comment by jtborger** [comment]
Ook IZ: https://ecd.deregenboog.org/iz/klanten/?redirect=/iz/mijn/koppelingen

**Comment by jtborger** [comment]
Veld medewerkers in overzicht is nu een opsomming van medewerkers die een verslag hebben gemaakt voor de klant. Hij laat alleen de eerste 3 zien. Zijn er meer medewerkers die verslagen hebben gemaakt dan zie je (...) erbij in de lijst.
2.2.33 (later vandaag of morgen)
