### ISSUE TITLE
Veranderen term "werkgebied" in "stadsdeel"

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#863]
Overal in de verschillende lijsten

**Comment by jtborger** [comment]
Heb volgens mij alles vervangen.
Voor deelnemer weergave gebruiken we de generieke algemene weergave. daar heb ik werkgebied vervangen in stadsdeel/werkgebied; dit soort dingen moeten eigenlijk geharmoniseerd worden in heel ECD / DRG.
2.2.37
