### ISSUE TITLE
bug bij wijziging urenregistratie, telkens nieuwe factuur

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#865]
Bij klant XX wordt er voor iedere urenregistratie een nieuwe factuur aangemaakt.  

https://ecd.deregenboog.org/hs/klanten/2069/view?redirect=/hs/klanten/#klussen

**Comment by dvleeuwen** [comment]
Ik heb nu ook bij andere klanten een probleem bij het voeren van uren:

Ook bij XXX en XXX gaat dat nu mis. Het lijkt erop dat er problemen ontstaan wanneer ik in een nieuwe maand uren invul van de maand ervoor: de factuurdatum staat ook op 31 augustus. Ik ga voor deze klanten nu een handmatige factuur aanmaken, maar zou fijn zijn als het snel wordt opgelost: prio wat mij betreft!

Groet Iris 

https://ecd.deregenboog.org/hs/klanten/1333/view?redirect=/hs/klanten/
https://ecd.deregenboog.org/hs/klanten/1361/view?redirect=/hs/klanten/

**Comment by dvleeuwen** [comment]
nog een aanvulling van Iris:

Daarbij nog een aanvulling: ook al voer ik de uren in de ieuwe maand in, dan moet de factuurdatum wel op de laatste van de betreffende maand komen te staan... Dat geldt ook voor handmatige facturen, daarbij kan ik de datum niet handmatig invoeren...

**Comment by jtborger** [comment]
Zijn eigenlijk twee punten. Heb nieuw issue aangemaakt voor factuurdatum.
NIeuwe facftuur per setje uren ga ik bekijken. Heel vreemd. Is niet bij alle genoemde zaken het geval.

**Comment by jtborger** [comment]
Wat er fout ging is wanneer een declaratie of registratie gebeurde in een andere maand dan huidig
hij de mist in ging bij het bepalen van de factuurdatum. Die werd altijd laatste dag van huidige maand gezet.
Wanneer hij dan ene registratie doet maakt hij conceptfactuur aan, als er nog geen bestaat.
Hij zoekt daarbij binnen een datum range. Die datum range is de range van de registratie of declaratie.
Aangezien dat een andere maand is, vond hij geen factuur, maakte nieuwe, die kreeg foute datum, enzovoorts enzoverder.
de updateDatum functie was sowieso oud en beetje lelijk dus heb hem nu iets beter gemaakt denk ik.
Belangrijkste is dat hij niet meer kijkt naar huidige datum maar gewoon de meest grote datum pakt uit registratie of declaratie en daarvan de laatste dag van die maand pakt.
