### ISSUE TITLE
aanpassing veld opmerkingen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#866]
Josje:

Hoi Daan,

Ik heb een verzoek m.b.t het veld Opmerkingen in het basisdeel van het klant/vw-dossier. Dit veld is bedoeld voor 'dienstmededelingen' voor gebruikers van het dossier over bereikbaarheid, postadres e.d. (al wordt het ten onrechte soms ook voor aanmeldgegevens gebruikt). Het probleem is dat een nieuwe opmerking direct achter de vorige wordt geplakt, dus niet op een nieuwe regel. Hierdoor kan het bij meerdere opmerkingen een visuele brij worden. Graag zou ik willen dat je door een Enter te gebruiken in dit veld een nieuwe regel kunt creëren.

**Comment by dvleeuwen** [comment]
Josje dacht dit probleem nog steeds te hebben, terwijl Jan en ik het niet kunnen reproduceren.
Zij gaat checken en laat me weten.

**Comment by dvleeuwen** [comment]
Josje heeft t probleem idd nog wel, anderen ook.
Zal wellicht met browser te maken hebben?
Ik zoek verder uit

**Comment by dvleeuwen** [comment]
Hoi Daan,

Iedereen gebruikt Google Chrome als standaardbrowser.
Ik heb even gekeken naar de instellingen maar word daar niet wijzer van. Misschien heb ik ooit wel eens iets aangepast, maar dit niet. De door de organisatie beheerde instellingen zouden voor iedereen gelijk moeten zijn, denk ik? Of zou bijv. de hardware nog mee kunnen spelen?
Misschien geen echte ECD-kwestie maar een oplossing is welkom.

Groet,

Josje
--

wonderlijk,
ik weet t dan ook niet (gebruik hier ook Chrome, waarmee het prima werkt)
Maar zal kijken of Jan er verder mee komt.

**Comment by jtborger** [comment]
Ik gebruik ook chrome hier. Ik denk dat we misschien wel iets anders bedoelen. Ik parkeer dit wel totdat ik een keer op droogbak ben en mee kan kijken... dat is misschien het handigst?

**Comment by dvleeuwen** [comment]
Ja lijkt me prima, geen haast mee.
Ze heeft het op mijn verzoek nogmaals geprobeerd en screenshot gemaakt,
lijkt echt zo te zijn (dat enters wegvallen). Was bij haar in de kamer op
dat moment nog 1 persoon waarbij dat gebeurde. Bij een ander (net als bij
ons) niet.
Raadselachtig... maar goed idee dit te laten rusten tot je weer een keer
hier bent.



Op ma 3 feb. 2020 om 10:12 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
aanvullende info Josje, 
het werkt (bij haar?) wel als je in algemene klanten/vw dossier werkt, maar niet als je vanuit andere tab werkt

Hoi Daan/Jan,

Toevallig ontdekte ik iets dat misschien informatief is voor de oplossing van de in sommige gevallen niet werkende Enter-functie in het veld Opmerkingen. Die werkt nl. op mijn computer niet binnen een afdelingsdossier, maar wel in de algemene klanten- of vrijwilligerslijst. 
Als bijlagen een IZ-testdossier na opslaan van het veld Opmerking + hetzelfde dossier in de Vrijwilligerslijst (nr. 14830).
Dit mag dus toegevoegd worden aan het ticket.

Groet,

Josje

----

Ik probeer deze nu te reproduceren Josje, maar snap het nog niet helemaal.
Waar wijzig je opmerkingen in een afdelingsdossier? Heb je een linkje voor mij?
Overal waar ik kijk ga je dan automatisch naar algemene klanten/vw lijst. Ik zie geen andere plek waar ik opmerkingen kan wijzigen?

dank!
Daan

**Comment by dvleeuwen** [comment]
Hoi Daan,

Ja, dat klopt, bij openen van de klant- cq vrijwilligersgegevens kom je automatisch in de klanten- cq vrijwilligerslijst terecht.
Het punt is dat na opslaan van de invoer in het veld Opmerkingen - op mijn computer dus - de gegevens in het afdelingsdossier achter elkaar worden geplakt zonder enter, terwijl als je datzelfde dossier in de klanten-/vrijwilligerslijst bekijkt de enter wel werkt en je dus na een ingevoerde enter een nieuwe regel krijgt.
Waar dat aan ligt lijkt me lastig, het verschilt dus kennelijk per computer of account. Als Jan er is hou ik me aanbevolen om mee te kijken.

Groet,

Josje
---
Ja mysterie...
lijkt me goede om volgende week even samen met Jan naar te kijken!

groet
Daan

**Comment by jtborger** [comment]
Helder.
Opgelost in 2.2.40 of 41
