### ISSUE TITLE
role_scip: mogelijkheid geven persoonsgegevens te wijzigen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#867]
verzoek Sonh

**Comment by jtborger** [comment]
2.2.37

**Comment by dvleeuwen** [comment]
ivm privacy problemen:
verzoek deze terug te draaien naar oude situatie

**Comment by dvleeuwen** [comment]
Of #822 werkt nog niet goed?
Probleem is dat alle SCIPers nu tab Klanten hebben, wat ivm privacy niet de bedoeling is.
Maar volgens mij zou deze tab sinds live zetten #822 niet meer zichtbaar moeten zijn, behalve voor de daar gespecificeerde personen, toch? 
Even overleggen bij volgende contact.

**Comment by dvleeuwen** [comment]
Ik sluit deze weer, als 822 goed werkt is dit probleem (privacy) ook verholpen, en dit issue verder naar tevredenheid
