### ISSUE TITLE
role_scip_beheer mogelijkheid geven projecten te verwijderen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#868]
verzoek Sonh

**Comment by dvleeuwen** [comment]
"role_scip_beheer mogelijkeheid geven projecten toe te voegen en wijzigen #868"

Dit schijnt er toch al te zijn, alleen nog niet om ze ook weer te verwijderen.
Ik pas titel vh issue aan

**Comment by jtborger** [comment]
ze kunnen op inactief worden gezet.
dat lijkt me ook de lading te dekken? je wilt geen historie verliezen door projecten te verwijderen.
incidenteel verkeerd aangemaakte projecten kan ik evt in de database verwijderen.

er zijn veel plekken in ECD waar we werken met inactief ipv verwijderen.
