### ISSUE TITLE
Huurverzoek aanmaken vanuit dossier huurder

### ISSUE THREAD

**Issue by barthuttinga** [deregenboog/ecd#87]
Vanuit een huurder (/odp_huurders/view/<id>) moet je een huurverzoek kunnen aanmaken.

**Comment by Evertt** [comment]
@barthuttinga ik neem aan dat mijn nieuwe branch voor deze feature dan gebaseerd moet zijn op de branch genaamd `feature/78-odp-bundle` ?

**Comment by Evertt** [comment]
@barthuttinga Ik heb deze PR gemaakt voor zover dat mogelijk is met het huidige data-model. Moet de entity voor huurverzoek nog uitgebreider worden? Zo ja, dan wil ik dat ook wel maken.

**Comment by barthuttinga** [comment]
@Evertt Deze PR is van voor ons telefonisch overleg toch? Nog zonder forms enzo. Dan negeer ik hem nu gewoon even.

**Comment by barthuttinga** [comment]
@Evertt Je hebt het over "deze PR", maar ik zie nu eigenlijk geen PR open staan...

**Comment by Evertt** [comment]
Yes precies

Op wo 25 jan. 2017 15:02 schreef Bart Huttinga <notifications@github.com>:

**Comment by Evertt** [comment]
Yes dat klopt ook, was een beetje vroeg met het een "PR" noemen. PR komt
later wel.

Op wo 25 jan. 2017 om 15:05 schreef Bart Huttinga <notifications@github.com
