### ISSUE TITLE
Evaluatiemomenten toevoegen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#870]
Bij vrijwilligers evaluatiemomenten toe kunnen voegen (datum)
En deze tonen in overzichten. Als datum verstreken is oranje kleuren

**Comment by jtborger** [comment]
een moment, of meerdere? en moet daar dan nog wat mee? Als in: moet er dan ook iets worden opgeslagen, of is het puur een reminder?
(en als dat het is, hoort dat dan wel in ECD thuis)

**Comment by dvleeuwen** [comment]
een moment: een datum invoeren dat het tijd is voor evaluatie + waarschuwingscode/kleur als deze verstrijkt. De medewerker zal dan evaluatie doen en verslag toevoegen.
Vergelijkbaar met waarschuw evaluaties in IZ module. 
Is dit zo helder?

**Comment by jtborger** [comment]
Enkel een veld met evaluatiedatum. Wanneer een verslag wordt gemaakt daarvan kunnen aangeven dat dit een evaluatie betreft. Als die wordt opgeslagen en de datum ligt na de evaluatiedatum, evaluatiedatum leegmaken.

**Comment by jtborger** [comment]
2.2.37
heb het nu zo gemaakt dat in het algemene deelnemers/vrijwilligersoverzicht een rij rood kleurt wanneer het evaluatiemoment vandaag of verstreken is, en geel kleurt wanneer het binnen een week verstrijkt.
Ook in het bekijken van het profiel zie je de datum verkleuren op die manier.
wanneer een verslag wordt opgeslagen waarbij aangevinkt dat deze een evaluatie betreft dan kijkt hij naar de datum. wanneer de verslagdatum meer dan een week VOOR de evaluatiedatum ligt, doet hij niks, ook al zegt men 'het is een evaluatieverslag'. Dan geeft hij wel een melding (verslagdatum ligt meer dan een week voor evaluatiedatum).
Als deze termijnen anders moeten dan hoor ik het wel. Er kan overigens altijd handmatig een evaluatiedatum worden leeggemaakt.
