### ISSUE TITLE
nieuwe bezoekers amoc zijn niet te registreren

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#871]
2 nieuwe intakes van vandaag komen niet terug in registratie tab:

https://ecd.deregenboog.org/inloop/klanten/5650826/view?redirect=/inloop/klanten/
https://ecd.deregenboog.org/inloop/klanten/5650825/view?redirect=/inloop/klanten/

Toegang locatie staat aangevinkt, ik zie alleen geen einddatum toegang amoc staan, meen dat deze automatisch op 6 maanden later komt normaal gesproken?

**Comment by dvleeuwen** [comment]
startdatum overigen bedoel ik hierboven (ipv einddatum Amoc)

**Comment by dvleeuwen** [comment]
excuus, ik begrijp dat die datum wel handmatig ingevoerd moet worden?
vraag blijft waarom deze nieuwe bezoekers nu niet welkom zijn in Amoc

**Comment by jtborger** [comment]
Opgelost... domme fout van mijn kant.

**Comment by jtborger** [comment]
NB einddatum amoc is niet nodig voor zover ik zien kan
