### ISSUE TITLE
foutmelding bij verwijderen uren

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#873]
En bij een poging uren te verwijderen bij klant XXX krijg ik bijgevoegde melding... 

https://ecd.deregenboog.org/hs/registraties/3265/delete?redirect=/hs/klussen/797/view

**Comment by jtborger** [comment]
Ik kreeg een foutmelding ook bij het opvragen van de klus (797)
Ook iris kon die dus niet meer openen.
Wat er precies fout is gegaan bij het verwijderen van de uren kan ik niet achterhalen, het enige dat ik kan zien is dat er een extra urenregistratie stond die niet aan enige factuur gekoppeld was (technisch, ook niet aan een concept factuur). Daar kwam bij mij de foutmelding vandaan. Maar naw was dat nog niet het geval toen die uren verwijderd werden of geprobeerd werd ze te verwijderen.

Ik kan er nu helaas niks mee. Uren toevoegen en verwijderen op dit dossier lukt mij gewoon nu... Als ik iets niet goed zie hoor ik het wel.
