### ISSUE TITLE
wijziging rapportage maatschappelijk werk

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#879]
Ha Daan,

Nog een kleinigheidje: er staan nog wat locaties in de rapportages die niet meer bestaan. Mogen die eruit, zonder dat de oude data verloren gaan? Het gaat om Westerpark, Vrouwen nachtopvang en de Eik.

Dank alvast!

**Comment by dvleeuwen** [comment]
opgelost

**Comment by dvleeuwen** [comment]
heropent:
was opgelost binnen rapportage mw, maar nog niet bij managementrapportage.
Hier mag verwijderd worden:
-eik
-noorderpark
-pi
-politie
-vrouwennachtopvan
-westerpark

**Comment by jtborger** [comment]
Ik heb het nu zo gemaakt dat alleen locaties die open waren in de periode dat er gerapporteerd wordt, meegenomen worden. 

2.2.38
