### ISSUE TITLE
toevoegen deelnemers OEK trainig op alfabet

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#881]
Verzoek Ellina:

bij deelnemers toevoegen aan training staan namen nu niet op alfabet, is erg onhandig

**Comment by jtborger** [comment]
De namen stonden wel alfabetsch, maar op voornaam, achternaam ipv andersom.
Heb dat nu aangepast, leek me ook handiger.

**Comment by dvleeuwen** [comment]
Ha Ellina,
het toevoegen van deelnemers training OEK is nu op alfabet.
Alleen lijkt het mij (en Jan) nog steeds niet ideaal; vergelijkbaar met het punt wat jij aandroeg over toevoegen deelnemer bij activiteiten bij  Groepsactiviteiten. (lastig typen in zoekbalk, en geen mogelijk onderscheid voornaam/achternaam)

Dit willen Jan en ik dus later nog verbeteren.

groet!
Daan

zie #884
