### ISSUE TITLE
mogelijkheid om dossier te sluiten bij OEK

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#882]
Nu lijkt het alleen mogelijk te verwijderen, waardoor data verloren gaat

**Comment by jtborger** [comment]
Gaat zo mee met de commit en straks live.

**Comment by dvleeuwen** [comment]
Werkt volgens Ellina nog niet, dus ik heropen.
Samen even naar kijken? (Jan + Daan)

**Comment by jtborger** [comment]
Ik weet niet waarom het niet werkte maar ik heb het gefixt ... als het goed is ;) 
gaat vanmiddag mee.

**Comment by jtborger** [comment]
Deze en #889 staan nu direct ook live.

Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op vr 6 sep. 2019 om 13:00 schreef dvleeuwen <notifications@github.com>:

**Comment by dvleeuwen** [comment]
👍

Op ma 9 sep. 2019 om 10:10 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Ha Ellina,
weer even overleg gehad met Jan:
Om de een of andere reden is het vrijwilligersveld bij OEK geheel anders vormgegeven dan bij de andere modules in ECD. Dat maakt het lastiger/tijdrovender om aan te passen.
De knop "vrijwilliger verwijderen" wordt aangepast naar "vrijwilliger inactief maken". (=dus dossier sluiten) 
Dit werkt nu al (alleen moet de term verwijderen dus nog aangepast worden). In het overzicht van vrijwilligers zie je nu ook de kolom met status actief, waar je op kunt selecteren.

Ben je er dan? Of moet het geheel toch omgebouwd worden? 
Jullie doen geen intakes/verslagen met vrijwilligers, correct?

groet!
Daan

zie ook #890

**Comment by jtborger** [comment]
Ik weet overigens niet waar of er vrijwilligers gebruikt worden binnen Oek? Wordne die gekoppeld aan trainingen of deelnemers?
Want dan moeten inactieve eruit gefilterd worden natuurlijk...
Dat is volgens mij nog niet gebouwd. Enkel 'het vinkje' actief/inactief...
Dat heeft natuurlijk geen betekenis/waarde als er verderop niks mee gebeurd maar dat kon ik uit de vraag niet opmaken (en ik was zelf niet slim genoeg er eerder naar te vragen).

**Comment by dvleeuwen** [comment]
Ha Ellina,
nog een aanvullende vraag van Jan:
klopt het dat jullie verder niets van vwers registreren. Dus geen mogelijkheid voor intake en dat er ook niet geregistreerd wordt bij welke training ze helpen etc?

groet!
Daan
