### ISSUE TITLE
diverse wijzigingen groepsactiviteiten

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#885]
samen met Jan een keer voor zitten, nav overzicht Ellina

**Comment by jtborger** [comment]
hoe staat het hiermee? :)

**Comment by dvleeuwen** [comment]
Daan moet met Ellina overleggen

**Comment by dvleeuwen** [comment]
Daan checkt bij Bas met wie dit nu besproken moet worden (Ellina of nieuwe collega's)
Of dat dit issue gesloten kan worden

**Comment by dvleeuwen** [comment]
nav met Bas:
we sluiten deze. Mochten de nieuwe collega's tegen dingen aan lopen hoor ik het van bas.
