### ISSUE TITLE
opties bij afronding training

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#886]
Bij afronding van een training:
1. vinkjes bij de namen van wachtlijst/deelnemers kunnen geven 'afgerond'
2. en veld met 'doorverwezen naar':
3. als deelnemers niet afgerond worden aangevinkt na afloop weer terug naar wachtlijst

**Comment by jtborger** [comment]
het eerste punt snap ik niet zo goed: een deelname aan een training kan al worden gemarkeerd als afgerond. wat wordt er bedoeld met vinkjes bij de namen?
en bij punt 3:
wanneer is na afloop? afloop van wat?

**Comment by jtborger** [comment]
Ik heb punt 2 gebouwd als volgt:
- wanneer een deelname status wordt gezet op 'Afgerond' verschijnt het veld 'Doorverwijzen naar'. Dit veld is niet verplicht.
OP een profiel van een deelnemer staat bij de trainingen wanneer Afgerond daarachter de inhoud van het veld doorverwezen naar.
2.2.37

**Comment by dvleeuwen** [comment]
Ellina kan helaas 27feb niet. Maar schuift graag volgende keer dat Jan weer op DB is aan om dit uit te werken en af te sluiten. Geen haast.

**Comment by jtborger** [comment]
Ellina gaat zelf aanpassen en op inactief zetten.
