### ISSUE TITLE
foutmelding bij verwijderen medewerker

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#891]
Er moeten 3 medewerkers verwijderd worden (Rosa, Lot en Mary)
Maar zodra je hier op verwijderen klikt kom je op foutmelding terecht.

https://ecd.deregenboog.org/clip/admin/behandelaars/?redirect=/clip/clienten/

**Comment by jtborger** [comment]
Heeft dit ooit gewerkt? Hij geeft een melding dat ie de gekoppelde gegevens (zoals contactmomenten) niet kan verwijderen. Dat is logisch als je het dossier wilt behouden.
Verwijderen moet eigenlijk niet kunnen als je dossiers wilt houden; men moet op 'inactief' komen ofzo. Net als bij vrijwilligers van OEK.

Het verbaast me daarom dat dit nu (pas) mis gaat, of dat het er wel ooit ingezeten heeft? Ik ga het even onderzoeken en aanpassen cq bouwen.

**Comment by jtborger** [comment]
Gaat straks live.

**Comment by jtborger** [comment]
ik ga dit nu niet live zetten; hopelijk morgen of vanavond.
heeft meer impact omdat ik het generieker heb gemaakt maar daardoor de impact nog niet goed kan overzien. wil dat eerst even goed nagaan, kost meer tijd.

**Comment by dvleeuwen** [comment]
prima!

Op ma 9 sep. 2019 om 14:42 schreef JT Borger <notifications@github.com>:
