### ISSUE TITLE
toevoegen van nieuwe regio's

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#893]
Aan lijst stadsdelen toevoegen:
Toevoegen Zaanstad-Haarlem-Haarlemmermeer-Beverwijk 

Dit ook zichtbaar maken in rapportage 
Amsterdam (alle ingevulde stadsdelen) - Zaanstad-Haarlem-Haarlemmermeer-Beverwijk 

wacht nog op info Marit/Lisanne of Zaanstad verder opgesplitst moet worden

**Comment by dvleeuwen** [comment]
Amstelveen
Diemen
Amsterdam - Centrum
Amsterdam - Oost
Amsterdam - West
Amsterdam - NieuwWest
Amsterdam -Zuid
Amsterdam - Noord
Amsterdam - ZuidOost
Zaanstad - Krommenie
Zaanstad - Assendelft
Zaanstad - WestZaan
Zaanstad - Nieuw-West
Zaanstad- Westerkoog
Zaanstad- Rooswijk
Zaanstad- Oud Zaandijk
Zaanstad- Oud Koog aan de Zaan
Zaanstad- Peldersveld
Zaanstad- Hoornseveld
Zaanstad- Poelenburg
Zaanstad- Wormerveer
Zaanstad- Zaandam Noord
Zaanstad- Zaandam West
Zaanstad- Zaandam Zuid
Zaanstad- Kogerveld
Zaanstad- Oudehaven 
Zaanstad- Rosmolenwijk

**Comment by dvleeuwen** [comment]
Overleg met Jan hoe we dit gaan organiseren: automatisch met postcode of handmatig invoeren

**Comment by dvleeuwen** [comment]
- Haarlem
- Beverwijk
- Bloemendaal
- Purmerend
- Overig

**Comment by jtborger** [comment]
#912

**Comment by jtborger** [comment]
Let op: ook postcodes en postcodegebieden checken.

**Comment by jtborger** [comment]
@dvleeuwen Ik heb de werkgebieden gekoppeld aan de postcodes op basis van de gegevens vanuit het Rijk. Echter, de verschillende wijken die het rijk heeft voor de postcodes correspondeert niet 100% (wel bijna) met het lijstje hierboven. Ik hou die van het rijk aan zodat we altijd kunnen updaten wanneer nodig.

**Comment by dvleeuwen** [comment]
Info aangeleverd vanuit OdP

•	Amsterdam – Centrum -> 1011-1018
•	Amsterdam – Oost -> 1019, 1086-1099, 1114
•	Amsterdam – Zuid -> 1070-1083
•	Amsterdam – Noord -> 1020-1039
•	Amsterdam – Zuid Oost -> 1100-1108
•	Amsterdam – West -> 1050-1059
•	Amsterdam – Nieuw West -> 1060-1069
•	Amsterdam – Westpoort -> 1040-1049
•	Zaanstad – Krommenie 1561
•	Zaanstad – Assendelft 1566- 1567
•	Zaanstad – Westzaan -> 1551
•	Zaanstad - Nieuw-West -> 1507
•	Zaanstad- Westerkoog -> 1541
•	Zaanstad- Rooswijk
•	Zaanstad- Oud Zaandijk -> 1544
•	Zaanstad- Oud Koog aan de Zaan -> 1541
•	Zaanstad- Peldersveld -> 1503 AA t/m 1503 
•	Zaanstad- Hoornseveld
•	Zaanstad- Poelenburg
•	Zaanstad- Wormerveer
•	Zaanstad- Zaandam Noord
•	Zaanstad- Zaandam West
•	Zaanstad- Zaandam Zuid
•	Zaanstad- Kogerveld
•	Zaanstad- Oudehaven 
•	Zaanstad- Rosmolenwijk
•	Haarlem - Oost 
•	Haarlem – Noord
•	Haarlem – Centrum / Rozenprieel
•	Haarlem - Zuid-West
•	Haarlem – Schalkwijk

https://postcode.site/nl/noord-holland/gemeente/zaanstad

**Comment by dvleeuwen** [comment]
postcodes van Zaanstad en Haarlem volgen
