### ISSUE TITLE
wachtlijst OEK geeft foutmelding

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#894]
Ellina:

https://ecd.deregenboog.org/oek/wachtlijst/?redirect=/oek/deelnemers/  hier zou een complete wachtlijst moeten verschijnen. Nu staat er neem contact op met daan

**Comment by jtborger** [comment]
Gaat zo mee in release.

**Comment by jtborger** [comment]
(was een functie waar ik aan had gewerkt en die niet afgemaakt was --> daardoor foutmelding). Ondergesneeuwd vanwege bugjes afgelopen week. Teruggedraaid, pak ik later weer op.

**Comment by dvleeuwen** [comment]
Hoi Daan,

Het lukt niet meer om de wachtlijst (en) van OEK te downloaden. Wat heel jammer  is.

Kun jij aan Jan vragen of hij dit kan oplossen?

Alvast bedankt!

-- 
Hartelijke groet,

Ellina van der Boon

**Comment by jtborger** [comment]
gaat mee in release
