### ISSUE TITLE
deelnemers trainingen zijn niet meer zichtbaar

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#895]
In het overzicht staat wel aantal deelnemers, wat klopt.
Echter als je op de betreffende training klikt zie je de namen niet

https://ecd.deregenboog.org/oek/trainingen/?url=oek/trainingen/&redirect=/oek/deelnemers/&sort=training.startdatum&direction=asc&page=3

**Comment by jtborger** [comment]
gaat zo mee in release.
Naweeen van eerder complex issue dat ik wat fundamenter opgelost had. Maar dat ging in deze casus dus niet goed.
