### ISSUE TITLE
document verwijderen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#899]
Hoi Jan/Daan,

In het vrijwilligersdossier van XX( https://ecd.deregenboog.org/vrijwilligers/7732/view?redirect=/vrijwilligers/ ) is per ongeluk de VOG van vrijwilliger XX geupload.
Zou je dit document willen verwijderen? 

Alvast dank. 

Groet,

Josje

**Comment by jtborger** [comment]
Dit kan vanaf 2.2.19 zelf, of door jou als admin, of door de betreffende medewerker.
Mocht het toch niet lukken, dan is er iets fout.

Ik doe het bewust niet zelf nu om meteen te checken of het werkt ;)

**Comment by dvleeuwen** [comment]
Ha Jan,
ik heb deze nu inderdaad kunnen verwijderen. Werkt dus goed.

Nog 1 detail: er verschijnt na verwijderen van (in dit geval) VOG de tekst: VrijwilligersController is verwijderd.in beeld. Dat klinkt mij wat vreemd (ik weet niet wat vrijwilligersController is?) kun je dit nog aanpassen?

Ik open oude Github nog even voor dit puntje op de i

groet!
Daan

**Comment by jtborger** [comment]
2.2.20
