### ISSUE TITLE
wijziging in schorsingsformulier 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#900]
aanpassing in het formulier dat gebruikt wordt bij schorsingen lander dan 2 weken. Zie mails 24sept voor details

**Comment by jtborger** [comment]
Check. Ik heb ze naast elkaar gelegd, volgens mij ging het alleen omde gegevens van Lina Berger.
Het is handiger als Janneke alleen de wijziging doorgeeft, dan hoef ik het niet handmatig na te gaan en maak ik evt minder fout (zie ik de verschillen niet over het hoofd)
