### ISSUE TITLE
foutmelding declaratie homeservice

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#906]
Ha Daan, 
er gaat weer iets mis, bij klant XX Heb een declaratie ingevoerd en na een poging de datum aan te passen ging het mis: bedrag staat er nu wel, maar komt nu niet naar voren bij overzicht. Uren invoeren lukt nu ook niet meer. Help!

https://ecd.deregenboog.org/hs/klanten/2429/view?redirect=/hs/klanten/

**Comment by dvleeuwen** [comment]
ik stuur Jan de mail door, daarin staan screenshots

**Comment by jtborger** [comment]
De fout van het niet meer kunnen openen van de klus enzo had te maken met een foutieve invoer van de declaratie;
waardoor dat veroorzaakt is begrijp ik niet goed. Als ik zelf de datum van die declaratie aanpas gaat het gewoon goed. 
Kan jij nagaan wat Iris heeft gedaan? Welke datum was het eerst en welke datum heeft ze daarna ingevoerd?
Ook zie ik - dat staat er los van - dat er een aparte declaratie categorie is aangemaakt die eigenlijk maar over 1 factuur gaat. lijkt me niet handig die categorie zo specifiek te doen. dan beter een categorie noemen 'betalingsverschil' of 'administratief onderhoud' of weet ik veel. Maar dat is niet helemaal an mij ;)

**Comment by dvleeuwen** [comment]
Ik speel het terug aan Iris!

Op di 8 okt. 2019 om 09:37 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Antwoord Iris:
---Hoi Jan, Daan!
Datum in oktober was eerst, daarna datum in september. Ik snap ook niet zo goed wat er nou mis gaat :(
En hele goede suggestie, dank je Jan! Soms zie ik door de bomen het bos niet meer...
 ---

Wat denk jij Jan: dit issue nu maar sluiten ivm onduidelijkheid?
groet
Daan

**Comment by jtborger** [comment]
Heel fijn deze feedback. Ik kan het probleem nu reproduceren door de datum ind e vorige maand te zetten. Ik ga ermee verder.

**Comment by jtborger** [comment]
Fout opgelost.
Ergens die in de code gebeurde iets vreemds waardoor bij een factuur in een andere maand dan de eerste declaratie niet goed werd aangemaakt. Daardoor raakte de declaratie zijn binding met de factuur kwijt en dat gaat dan niet goed.
2.2.21

**Comment by dvleeuwen** [comment]
Iris geeft aan dat er toch nog iets niet helemaal goed gaat in deze
in dit dossier blijft nu een lege factuur staan in overzicht, zie: https://ecd.deregenboog.org/hs/klanten/2429/view?redirect=/hs/klanten/#facturen
ik heropen

**Comment by jtborger** [comment]
Ah. Ja. 
Bij effect.

**Comment by jtborger** [comment]
Ik ben er wederom ingedoken. Het heeft helaas veel tijd gekost want het is complexe materie.
Het hele facturatieverhaal bij HS heeft allerlei haken en ogen. Zo dit ook.
Wanneer een declaratie of registratie aangepast wordt en daarmee in een ander tijdvak valt, dan gaat het niet goed.
Dit heeft te maken met een eerder gemaakte keuze hoe een en ander geprogrammeerd is. Ik heb geprobeerd daarmee/daaromheen te werken maar levert dan verderop toch weer problemen op zoals we zien.
Het heeft dus meer voeten in aarde dit recht te zetten omdat het over een andere boeg moet.
Ik zal hiermee verder gaan, maar het is dus nog niet klaar...
Vooralsnog zitten er even wat haken en ogen aan het aanpassen van declaraties en registraties. Ik kan niet helemaal inschatten wat op dit moment precies wel en niet werkt.
Wordt vervolgd.

**Comment by jtborger** [comment]
Ik heb dit deels herbouwd. Als het goed is (klop klop) werkt het nu.
Ik heb verschillende scenario's getest met declaraties en facturen die al definitief waren, die niet definitief waren, registraties wel op die maand, declaratie naar vorige maand: het lijkt hier bij mij allemaal goed te gaan.

de fout waardoor er eerder 'vage' problemen optraden was vrij 'low level' en ging daardoor niet op een heel logische manier mis: enkel in sommige gevallen. Dat is nu verholpen en het zou dan ook weer 'logisch' moeten werken nu.
Zo niet dan hoor ik het graag want dan heb ik wat over het hoofd gezien ben ik bang.
