### ISSUE TITLE
problemen registratie sinds overgang naar TARQ

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#907]
Beste Daan,

Sinds de overstap naar TARQ hebben we ook met het ECD een aantal problemen gekregen die er voorheen niet waren. Ik weet niet of alle locaties hier last van hebben, maar dat zal wel?

1.- Als je een bezoeker eenmaal hebt uitgecheckt dan kun je hem niet meer aanklikken zodra hij weer binnenkomt via de tab "Recent uitgecheckt" maar moet je hem weer opnieuw opzoeken. Dit is erg onhandig en extra werk! 
2.- De tijden doen het niet meer in het ECD, waardoor je niet meer kun zien hoe lang een bezoeker buiten is geweest. Op deze manier wordt de 1 -uurs regel erg lastig te handhaven.

Zou je hier z.s.m. naar kunnen kijken? 

-- 
Met vriendelijke groet,

Daphne van Zetten

**Comment by jtborger** [comment]
Hoi Daan, 
Ik heb dit eerst lokaal gecheckt en gaf geen problemen. Ik vermoedde dat het eventueel een Internet Explorer probleem was waar we de eerste dag na TARQ ook mee te maken hadden met het registreren van bezoekers. De oorzaak van toen leek nu niet meer aanwezig.
Heb op remote desktop ingelogd dus dezelfde omgeving als jullie (in principe) en zowel in Chrome als IE gaat het bij mij goed...
Dat geldt overigens voor recent uitgecheckt als de melding van 1 uur en het zien van de tijden dat men binnen is geweest. 
Anders gezegd: het is voor mij erg lastig dit punt op te lossen.
Zou het kunnen zijn dat Daphne een andere browser/omgeving gebruikt ofzo? 
Het is lastig voor haar, maar ook voor mij, om dit op afstand op te lossen. Welke locatie zit zij? Misschien dat ze even met TARQ kan bellen en dat zij kunnen meedenken wat het is, met misschien deze achtergrond info?

Een dubbele check: hebben andere collega's van inloophuizen hier ook last van? En zo niet, werken die op een andere of dezelfde locatie als Daphne?

**Comment by dvleeuwen** [comment]
Dank Jan,
ik speel deze vraag door naar Daphne en collega's!

Wij bellen over een uurtje he?

groet
Daan

Op di 8 okt. 2019 om 08:10 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Blijkt op alle locaties te zijn:

Ja maar dit is erg omslachtig. Normaal kun je gewoon bij recent uitgecheckt " her " inchecken door een simpele klik op de naam.. 

met vriendelijke groet,

Daphne van Zetten 

Op do 10 okt. 2019 11:23 schreef Willemijn Los <wlos@deregenboog.org>:
Even gecheckt:

uitgecheckten kunnen inderdaad niet meer direct via de ''uitgecheckt''  pagina opnieuw worden ingecheckt. Je moet ze als gewone bezoeker inchecken. Wel verschijnt dan een pop- up dat ze minder dan een uur geleden zijn uitgecheckt mocht dat zo zijn. En ook verschijnt er een pop-up als ze net van een andere locatie vandaan komen of daar nog staan ingecheckt.
Handhaving van de 1-uurs regeling zou dus geen probleem hoeven te zijn?

**Comment by jtborger** [comment]
Helder.
Die heb ik nu gefixt.

1 uurs regeling was dus wel OK?

Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op do 10 okt. 2019 om 12:27 schreef dvleeuwen <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Werkt helaas nog niet naar wens:

Daphne:
Iets te enthousiast, er staat nu wel een uitcheck pijltje en als je me muis er over haalt komt daar in checken te staan, maar als je er op klikt gebeurd er niks helaas!

**Comment by jtborger** [comment]
Is helder, ik moet het nog releasen

Met vriendelijke groet,

Jan Borger
(Extern) Ontwikkelaar ECD
jborger@deregenboog.org
(Ik reageer niet zo snel op mail. Werk beperkte tijd aan ECD. Voor spoed:
via Daan van Leeuwen ben ik telefonisch bereikbaar.)


Op do 10 okt. 2019 om 13:54 schreef dvleeuwen <notifications@github.com>:

**Comment by jtborger** [comment]
2.2.21
