### ISSUE TITLE
Extra criteria bij huurderprofielen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#908]
zie mail met aanvullende info

**Comment by jtborger** [comment]
OK
Twee vragen:
1) bij Woco's splitsen, is dat een kwestie van gewoon de nieuwe toevoegen? Of moeten er ook gegevens van oude gesplitst worden naar nieuwe? En zo ja, op basis van welke criteria? Zo nee, als het dus slechts een toevoeging is van nieuwe + aanpassing van de naam van de huidige/oude, dan kan men cq de beheerder dat zelf.
2) Splitsing per gebied: waar geldt dit voor? Is mij niet helemaal duidelijk.
3) criteria lijkt me helder.
Splitsen in meerdere issues als duidelijk wat punt 1en punt 2z ijn.

**Comment by jtborger** [comment]
@dvleeuwen 
Men vraagt of het mogelijk is later deelgebieden aan te leveren voor Haarlem en Beverwijk.
Dat kan wel, maar heeft de consequentie dat alle dossiers die tot die tijd op Haarlem of Beverwijk worden gezet, enkel handmatig per stuk omgezet zouden moeten wordne naar een nadere specificatie (deelgebied). Dat heeft dus eigenlijk niet de voorkeur, tenzij het er echt enkelen zijn.
Tevens de vraag of men dan ook de betreffende postcode lijst zou kunnen opvragen. Het kost mijr elatief veel tijd dit op te zoeken
(er is voor zover ik heb kunnen vinden geen centraal punt vanuit de overheid. Sommige gemeentes publiceren het (Zaanstad) via een data platform, andere niet).

**Comment by dvleeuwen** [comment]
Ha Lisanne,
zie svp hieronder reactie van Jan.Later toevoegen deelgebieden kan dus problemen opleveren. En als jullie dit willen: verzoek van Jan of jullie de betreffende postcodes kunnen aanleveren. Ecd voegt automatisch de juiste gebieden in bij het aanmaken van een dossier op basis vd postcode. Dat is erg handig (minder werk + geen menselijke fouten), maar voor nieuwe gebieden moeten dan dus wel eerst de juiste postcodes verzameld worden. Jan wil/kan dit begrijpelijkerwijs niet doen. Jullie wel?
groet!
Daan

**Comment by jtborger** [comment]
Ik heb de criteria toegevoegd behalve leeftijd en geslacht aangezien die al in klantprofiel staan voor zover ik weet.
Deelgebieden is ook #912 dus ik sluit deze.
Gaat mee in 2.2.21
