### ISSUE TITLE
Dagbestedings aanwezigheid projecten sync maken

### ISSUE THREAD

**Issue by jtborger** [deregenboog/ecd#910]
rechts bij deelnemer staat overzicht aanwezigheid
maar ook afgesloten projecten blijven erin staan, dat moet niet.

**Comment by dvleeuwen** [comment]
Ook Niek loopt tegen hetzelfde probleem aan:

Hoi,

Ik heb een vraag over de module Dagbesteding. 

Bij client XXX (https://ecd.deregenboog.org/dagbesteding/trajecten/872/view) staan twee projecten, nl. Diaconie en Boekbinderij. Deze client is nog actief bij alleen de Diaconie dus ik wil graag de Boekbinderij onzichtbaar maken. Volgens mij zou ik dat moeten kunnen doen door hier het vinkje bij Boekbinderij weg te halen maar ik zie geen vinkje om weg te halen. Wat moet ik doen?

**Comment by jtborger** [comment]
Projecten mogen niet verwijderd worden ivm de gegevens die bewaard moeten blijven
wel op inactief.

inactieve projecten ook niet tonen bij aanwezigheid.

**Comment by dvleeuwen** [comment]
besproken: niet meer relevant, ik sluit af
