### ISSUE TITLE
toevoegen "diensten" bij algemene VWdossiers

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#914]
Hoi Daan en Jan,

Graag wil ik hierbij verzoeken om in dossiers van vrijwilligers een soortgelijk blokje Diensten op te nemen als bij klanten/deelnemers. Dit omdat het met enige regelmaat voorkomt dat vrijwilligers bij verschillende afdelingen actief zijn of zijn geweest.
Het is handig dat medewerkers van een afdeling en administratieve krachten kunnen zien dat iemand elders actief is geweest/een intake heeft gehad. Dit ook met het oog op muteren van gegevens in de relatiedatabase (nu Charibase).

Dubbele dossiers komen trouwens ook voor bij vrijwilligers, maar wel veel minder dan bij deelnemers. Als ik die tegenkom voeg ik dossiers handmatig samen. Een dienstenblokje zou hierbij ook een goed hulpmiddel zijn, je kunt dan snel controleren welke afdelingsdossiers van een vrijwilliger onder een bepaald basisdossier/ECD-nummer hangen.

Josje

---
Ha Josje,
welke diensten denk je dan precies aan bij vwers? Iz, inloophuizen etc?
groet
Daan
---

Hoi Daan,

Terechte vraag, mijn verzoek was wat te kort door de bocht.

In elk geval zou ik graag de volgende groepen vrijwilligers zien in het dienstenblokje:
- Informele Zorg
- Inloophuizen
- Groepsactiviteiten
- Op Eigen Kracht

**Comment by dvleeuwen** [comment]
zie ook #978 (dubbel)

**Comment by barthuttinga** [comment]
@dvleeuwen Ik heb dit toegevoegd @jtborger Wil jij reviewen?
