### ISSUE TITLE
probleem bij rapportage inloophuizen "infobalie" + naamswijziging

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#915]
voor screenshot bijlage: zie mail

Hoi Daan,

De infobalie-rapportage is ergens onderweg gehandicapt geraakt. Zie bijgaand printscreen: hij geeft geen inzicht meer in aantal bezoeken, aantal unieke bezoekers en aantal verslagen van het MW. Zou jij Jan willen vragen om daarnaar te kijken? En als het hier dan toch over gaat: de naam mag veranderd worden in rapportage EU-burgers.

Dank alvast!
Met vriendelijke groet,

Janneke van Loo

**Comment by jtborger** [comment]
Ik heb deze gefixt (denk ik) en release hem nu.

Wanneer er voor 'alle locaties' werd gekozen, werd er feitelijk geen informatie verzameld. Waarom dat nu zo is en niet zo was weet ik niet.
Het is nu zo als je 'alle locaties' kiest, je ook daadwerkelijk gegevens van alle locaties krijgt.
Voor zover ik de melding begrijp zou dit het probleem moeten verhelpen - of ik begrijp de melding dus niet goed :)

2.2.22
