### ISSUE TITLE
Uit het Krijt (nieuwe module) aanmaken

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#918]
stap 1: deelnemers kunnen toevoegen: naw gegevens + (intake)verslagen

**Comment by jtborger** [comment]
Deze moest voor het eind van het jaar toch? Of zsm?

**Comment by dvleeuwen** [comment]
+ datum aanmelding & naam aanmelder
+ naam van contactpersoon "nazorg"

**Comment by jtborger** [comment]
Is klaar, donderdag even nalopen.
