### ISSUE TITLE
toevoegen locatie bij doorverwijzing inloophuizen --> dagbesteding

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#919]
Hoi!

Daan, ik krijg dit soort mails als een klant aangeeft interesse te hebben in dagbesteding. Het wordt in de intake in het inloophuis gevraagd. 
Er staat de naam van de interne verwijzer in. Er waren tijden dat ik precies wist welke medewerker vanuit welk inloophuis actief was, en kon ik de mail heel gericht doorsturen aan de betreffende trajectbegeleider die aan dat inloophuis verbonden is. Maar nu weet ik dat helaas lang niet altijd meer. 

is het mogelijk hier ook de locatie die het betreft toe te voegen?

Ik hoor het graag!

Hartelijke groet,

Brigit Nieuwburg

**Comment by dvleeuwen** [comment]
Niet alleen locatie toevoegen, maar ook naar ander mailadres in toekomst: 
niet meer naar bnieuwburg@dereXXXboog.org, maar naar bdgroot@dereXXXboog.org
Ivm vertrek van Brigit nu hoge prio.

#1046 is soortgelijk issue: dus kan wellicht in 1 moeite meegepakt worden?

**Comment by jtborger** [comment]
mailadres is gewijzigd.

**Comment by jtborger** [comment]
2.2.48
