### ISSUE TITLE
nieuwe rapportage mogelijkheid Op Eigen Kracht

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#920]
Rapportage van vrijwilligers actief in bepaalde periode

+ bij alle rapportages (vrijwilliger & deelnemer) svp ook de stadsdelen toevoegen

**Comment by jtborger** [comment]
Minimaal: deelnemers per stadsdeel
evt ook bij de andere rapportages meenemen per stadsdeel.
