### ISSUE TITLE
aanpassing facturen HS

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#922]
Hoi Jan en daan, 

wij hebben sinds vandaag een nieuw rekeningnummer bij HS. Dat moet dus worden aangepast op de facturen. Vond de tekst sowieso wat stroef, dus kun je de tekstregel aanpassen zoals hieronder? En dan ook zonder punt graag :) Lukt dat nog voor volgende week woensdag? Dan wil ik namelijk de facturen versturen. Hoe eerder hoe beter!

Uw betaling graag overmaken o.v.v. factuurnummer op bankrekeningnummer NL44 RABO 0331 1944 14 ten name van Stichting De Regenboog Groep

**Comment by jtborger** [comment]
Gaat (ik hoop vandaag) mee met 2.2.24
Kan ze morgen even checken of het goed gaat zo niet even bellen dan kan ik het voor woensdag zeker klaar hebben. Maar lijkt me dat dit wel goed gaat was iets kleins

**Comment by dvleeuwen** [comment]
Ik heropen dit issue, want:

Hoi allen,

Als je in ECD een betalingsherinnering genereert staat er in de brief nog het ING banknummer, dit moet het RABO nummer zijn wat onder aan de herinnering staat!
Hoe kan dit gewijzigd worden?
Dank!
Groet Emma

Emma Ricketts
Projectondersteuner Homeservice

**Comment by jtborger** [comment]
Er stond inderdaad nog ergens op een tweede plek een definitie van de opmaak van een herinnering...
Verwarrend.
Ook aangepast nu. Excuses.
2.2.29
