### ISSUE TITLE
in deelnemersoverzicht download ook kolom toestemmingsverklaring aanwezig met datum

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#923]
vergelijkbaar met kolom VOG aanwezig bij vw'ers

mail Miranda
Hoi Daan,

Niek en ik hebben geprobeerd om uit ECD een uitdraai te maken van de toestemmingsformulieren. Helaas lukt het ons niet. Lukt het jou wel?
Mocht dit niet mogelijk zijn, zou deze mogelijkheid wel gemaakt kunnen worden? Dan kan ik net als de de VOG en de contracten checken of het binnen is, en het aan de coördinatoren doorgeven. 

Met vriendelijke groet,

Miranda B

**Comment by jtborger** [comment]
gaat mee in 2.2.24
