### ISSUE TITLE
persoon is niet te vinden onder inloop

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#924]
Goedemorgen,
Ik wil graag een dossier van klant nr 5633127, XXXX sluiten maar maar ik kan hem niet in de Klanten/ Inloophuis vinden. Kun je het alsjeblieft voor me nakijken?
Groet,
Agnieszka

-- 
Met vriendelijke groet,

Agnieszka Franczak

----
https://ecd.deregenboog.org/mw/klanten/5633127/view?redirect=/mw/klanten/
niet vindbaar bij inloophuizen, hoe kan dit?

**Comment by jtborger** [comment]
Ik weet niet waarom of wat of hoe, maar hij is nooit aangemeld geweest voor een inloop huis voor zover ik kan zien.
Hij heeft geen 'dossierstatus' in het systeem. Daarom komt ie niet tevoorschijn in de zoekresultaten bij inloop.

Organistatorische/procesmatige vraag is dus: kan het zijn dat klanten wel onder MW vallen maar nooit worden geregistreerd/ als klant worden aangemeld bij inloop? 

Dat lijkt hier het geval te zijn namelijk.

**Comment by jtborger** [comment]
Is dus geen 'technisch' issue, dus ik gooi hem dicht.
