### ISSUE TITLE
2x fout bij wijzigen persoonsgegevens

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#925]
Hoi Daan/Jan,

Bij twee dossiers lukt het mij niet om contactgegevens te wijzigen, ik krijg de melding 'er is een fout opgetreden'. Opnieuw inloggen helpt niet. Bij andere dossiers krijg ik overigens geen foutmelding.
Het gaat om: 
- XXXX, huurder Onder de Pannen - plaatsnaam Zaandam toevoegen lukt niet https://ecd.deregenboog.org/odp/huurders/319/view
- XXXXX vrijwilliger IZ - opmerking van adresveld verplaatsen naar veld Opmerkingen lukt niet.
https://ecd.deregenboog.org/vrijwilligers/14739/view?redirect=/vrijwilligers/

Kennelijk zit ergens een bug, wil Jan hier naar kijken?
Alvast dank.

Groet,

Josje

**Comment by jtborger** [comment]
Werd door zelfde probleem veroorzaakt.
Werkgebieden werden opgeslagen bij de klant met een maximum van 20 tekens.
Echter, sinds Zaandam zijn dat er meer geworden. Doordat hij het werkgebied niet kon koppelen, ging het fout.
Nu rechtgezet.
