### ISSUE TITLE
verschil tussen handmatige lijst en ECDrapportage repratriering 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#926]
Janneke:

Hoi Daan,

Hierbij zoals net besproken de twee lijsten: één van Ewa, handmatig gemaakt en één uitdraai van de nieuwe rapportagemodule. In de ideale wereld levert dat dezelfde lijst op, maar de wereld is nog niet ideaal: 243 - 228 is net een te groot verschil. Ik kan de lijsten niet met elkaar vergelijken, omdat de ene op dossiernummer is, zonder naam en de ander op naam, zonder nummer. Het zou al mooi zijn als ik twee vergelijkbare lijsten zou kunnen krijgen, zodat we kunnen gaan kijken waar het verschil vandaan komt. En nog mooier als Jan en jij dat ook al zouden kunnen vinden. Ik vermoed een registratiefoutje bij de medewerkers, waardoor het systeem een repatriëring niet registreert en Ewa wel. Vinkje vergeten ofzo?

Dank voor de moeite alvast!
Met vriendelijke groet,

Janneke van Loo

(zie mail voor bijlage Ewa)

**Comment by dvleeuwen** [comment]
Ewa gevraagd hoe zij tot haar lijst komt, antwoord:

We hebben een aparte map met alle tickets die gekocht zijn en deze map valt buiten ECD. Op basis van deze map maak ik een lijst en sluit ik onmiddellijk dossiers die niet zijn afgesloten.
Groet, Ewa

(op basis van bus/trein/vliegtickets dus)

**Comment by jtborger** [comment]
zie mail
