### ISSUE TITLE
reservering mogelijkheid

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#930]
Reservering duo
Binnen huuraanbiedingen/huurverzoeken kunnen we niet zien wie een potentiele duo zijn (die dus een duo aanmeldformulier hebben ingevuld).  Kan dit aangepast worden? Toevoegen: Reservering + link naar naam 

Zichtbaar in tabel verzoeken aanbiedingen

**Comment by dvleeuwen** [comment]
Aanvullend:
op verzoek van Marit hoge prio gegeven

vergelijkbaar met IZ reserveringen

**Comment by jtborger** [comment]
Kan dit niet op een andere manier, door bv een huurovereenkomst te gebruiken die bv. nog niet 100% zeker is?
of krijgen we dan andere problemen?

**Comment by dvleeuwen** [comment]
vergelijkbaar met IZ
Daan vraagt na of er ook automatische einddatum bij moet en welke info (naam medewerker?)

**Comment by dvleeuwen** [comment]
mail Daan aan team ODP:

Bij IZ wordt bij het aanmaken van reservering automatisch een einddatum ingevuld. Idee hierachter is dat als een reservering niet doorgaat, maar medewerker vergeet deze ongedaan te maken, de reservering automatisch na bepaalde tijd ongedaan gemaakt wordt (zodat ze weer beschikbaar zijn, anders blijven ze onterecht tot in eeuwigheid op gereserveerd staan)
Willen jullie iets soortgelijks inbouwen? En zo ja: na hoeveel tijd moet reservering dan automatisch ongedaan gemaakt worden?
-bij IZ staat bij elke reservering ook genoteerd welke medewerker de reservering gemaakt heeft. Is dit voor jullie ook handig/wenselijk?

**Comment by dvleeuwen** [comment]
antwoord Marit:
-graag standaard op 2 maanden laten staan
-ook naam medewerker reservering tonen

**Comment by jtborger** [comment]
Koppeling kan aangevinkt worden als 'reservering'.
einddatum niet verplicht.
In lijstjes: huurverzoek en huuraanbieding zichtbaar met kleurtje. wel evt filterbaar.
in koppelingenstandaard niet zichtbaar wel aan te vinken.
reserveringen niet meetellen in rapportages.

koppeling/resersvering moet ongedaan gemaakt kunnen worden. en dan even vastleggen in verslag.

**Comment by jtborger** [comment]
Gaat mee in 2.2.46
Heb gemaakt wat ik besproken heb met Juul.
Reserveringen loopt via koppelingen.
Koppeling kan dus gemarkeerd worden als reservering.
Reserveringen worden roze/rood gekleurd in de overzichten. Bij verzoek en aanbod staan ze standaard 'aan', bij Koppelingen standaard uit.
