### ISSUE TITLE
doorlinken tussen ODPverslagen en maatschappelijkwerk

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#931]
Khadija’s account aanpassen
Nu moet Khadija (hulpverleners OdP) tweemaal een verslag maken, in de Onder de Pannen map en dan ook binnen maatschappelijk werk Onder de Pannen.  Kan dit gelinkt worden zodat ze alle verslagen een keer hoeft op te schrijven?

**Comment by jtborger** [comment]
Nee dat kan niet. Het zijn twee verschillende entiteiten in ECD: een MW verslag en een Odp verslag.
Kopieren is nooit wenselijk, dus we moeten even een andere mogelijkheid verzinnen. Kan dit besproken worden als ik er weer ben? En moet dat dan met Khadija of moet Arnoud of Juul?
Waar in de organisatie speelt dit meer? Lijkt me dat er meer terugkoppeling tussen afdelingen plaatsvindt, en hoe is dat dan opgelost?

**Comment by dvleeuwen** [comment]
Zie ook #944

Op di 7 jul. 2020 om 10:33 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
zie #944

**Comment by dvleeuwen** [comment]
Herstel: zie ook #994

Op do 22 okt. 2020 om 12:31 schreef ECD De Regenboog Groep <
ecd@deregenboog.org>:

**Comment by dvleeuwen** [comment]
En aanvullend,er hangt al enige tijd een soortgelijk verzoek met als label "wacht op info": het wederzijds zichtbaar maken van alle info uit modules "tijdelijk wonen" en "maatschappelijk werk".Willen we dit nu ook doorvoeren? Dan wederom aan jullie om via Leo/Monique de rechten uit te breiden vd betreffende medewerkers.Laat svp even weten of jullie dit wel/niet willen, dan sluit ik het issue en koppel terug aan aanvragers.
groet!Daan
