### ISSUE TITLE
er kan na invoeren aanmelding nu hulpvraag aangemaakt worden als er nog geen intake gedaan is, en dit geeft foutmelding

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#937]
De waarschuwing "er is nog geen hulpvraag aangemaakt"verschijnt nu direct na aanmelding. Je kunt daarop klikken en hulpaanbod maken, maar dit geeft later foutmelding, omdat er dan nog geen intake bestaat.

**Comment by dvleeuwen** [comment]
als je daarna intakeverslag invoert en opslaat kom je opnieuw op foutmeldingspagina terecht (terwijl het wel opgeslagen wordt)

**Comment by jtborger** [comment]
Kan niet reproduceren lokaal. 
Hierin is trouwens niks aangepast de laatste tijd toch?

**Comment by jtborger** [comment]
melding 'nieuwe hulpvraag/aanbod' alleen laten zien als intake bestaat.

**Comment by jtborger** [comment]
2.2.29
