### ISSUE TITLE
mogelijkheid om maatschappelijkwerkdossier af te sluiten + klantrapportage, op zelfde wijze als bij inloophuizen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#938]
Dus als je in het dossier vd klant zit: linksboven de optie maatschappelijkwerk dossier sluiten + klantrapportage
(zelfde als je dossier vanuit inloophuizen benaderd)

**Comment by dvleeuwen** [comment]
bij afsluiten van maatschappelijkwerk dossier de volgende afsluitreden in dropdown menu toevoegen:

- Begeleiding afgerond
- Begeleiding overgedragen
- Client langer dan 1 jaar niet geweest 
- Client gerepatrieerd
- Client overleden
- Overig

**Comment by dvleeuwen** [comment]
bij afsluiten maatschappelijkwerk dossier de volgende resultaten toevoegen (vinkboxjes, meerdere opties mogelijk)

- Overdracht naar buurteam
- Postadres geregeld
- Inkomen op orde
- Administratie op orde
- Toeleiding schuldhulpverlening  
- Werk gevonden/behouden
- Herstel woningnet  
- Huisvesting eigen netwerk  binnen Amsterdam
- Huisvesting eigen netwerk buiten Amsterdam
- huisvesting zelfstandig binnen Amsterdam
- Huisvesting zelfstandig buiten Amsterdam
- Huisvesting via Onder de pannen
- Plaatsing Passantenpenion
- Plaatsing MO/BW
- Verwijzing GGD
- Verwijzing GGZ
- Organiseren somatische zorg
- Jippie, het gaat weer helemaal top!

+rapportage waarin deze resultaten geteld worden per locatie en totaal

**Comment by dvleeuwen** [comment]
Na overleg krijgt dit punt prio toegekend.

**Comment by jtborger** [comment]
2.2.48
-- rapportage is ng in de making.

**Comment by jtborger** [comment]
rapportage krijgt nieuw issue. stel ik uit.

**Comment by dvleeuwen** [comment]
Komt bij nader inzicht nog kleine aanpassing/toevoeging op afsluitreden & resultaten:

Afsluitreden
"Cliënt langer dan 1 jaar niet geweest" veranderen in "Client uit beeld"

Resultaten
"Huisvesting via Onder de pannen" veranderen in "Huisvesting via Onder de panne/Parentshouse/200woningen"
toevoegen: "Urgentie toegekend"

**Comment by jtborger** [comment]
gedaan.

**Comment by dvleeuwen** [comment]
Resultaten is nu verplicht iets in te vullen, dit is niet de bedoeling, moet ook mogelijk zijn om niks aan te vinken.

**Comment by jtborger** [comment]
check. 2.2.51

**Comment by jtborger** [comment]
@dvleeuwen deze is live gepatched zojuist, doe deze week geen release meer.
