### ISSUE TITLE
rapportage onder maatschappelijkwerk niet toegangelijk voor maatschappelijkwerkers

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#940]
De rapportage "repratiering" onder maatschappelijkwerk is niet toegankelijk voor mwers. Staat wel in lijstje, maar kunnen er niet op klikken.
Komt wellicht doordat het is overgeplaatst vanuit Inloop?

**Comment by jtborger** [comment]
kan niet reproduceren

**Comment by dvleeuwen** [comment]
kan niet gereproduceerd worden, na overleg met Janneke: afsluiten.
Mocht het probleem zich opnieuw voordoen: graag de betreffende naam doorgeven dan openen we dit issue opnieuw
