### ISSUE TITLE
rapportage Inventarisatie verwijderen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#941]
Rapportage "inventarisatie" onder mw mag verwijderd worden

**Comment by jtborger** [comment]
@dvleeuwen Als de rapportage eruit mag, mag dan alles wat met inventarisaties te maken heeft weg? Ik heb dat in mijn tijd dat ik aan ECD werk volgens mij nog geen een keer bij de hand gehad... 
dus volgens mij is het oud en kan het weg maar kan jij dat checken bij Janneke?
