### ISSUE TITLE
aanpassing afsluitreden inloop

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#943]
Bij de opties na dossier sluiten vanuit inloop:

toevoegen: 
-foutieve invoer (en dan laten verdwijnen, zoals bij IZ)
-bezoeker heeft de inloop niet meer nodig

wijzigen:
3 jaar geen inloop bezocht  ---> 2 jaar geen inloop bezocht

**Comment by dvleeuwen** [comment]
on hold, wacht op info Janneke

**Comment by dvleeuwen** [comment]
Het rijtje toevoegingen vervalt.

Blijft staan de wijziging:

wijzigen:
3 jaar geen inloop bezocht ---> 2 jaar geen inloop bezocht

Deze moet tevens geselecteerd worden na automatische afsluiting, zie #944

**Comment by jtborger** [comment]
Duplicate van #1127
