### ISSUE TITLE
managementrapportage: resultaat is 0 als je slechts 1 dag selecteert?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#949]
Hoi Daan,

Voor de GGD hebben we in alle inloophuizen gisteren geteld hoeveel mensen er aangaven dat ze buiten hebben geslapen. Dat is gerapporteerd door 'kledingomruil' aan te vinken. Nu wil ik daar vandaag een overzicht van uitdraaien, staan alle tabellen op 0 als ik een managementrapportage maak voor alleen 26 november. Nu weet ik bijna zeker dat vorig jaar precies hetzelfde aan de hand was. En dat jij dat zo gefixt had. Kun je dat nog een keer misschien? Of doe ik gewoon iets sufs, waardoor het niet werkt?
Met vriendelijke groet,

Janneke van Loo, manager Inloophuizen & Hulpverlening

**Comment by jtborger** [comment]
2.2.28
