### ISSUE TITLE
bug Homeservice 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#951]
mail 19 nov Iris

Klant XXX: saldo klopt niet meer na aanpassen uren

https://ecd.deregenboog.org/hs/klanten/1333/view?redirect=/hs/klanten/#facturen

**Comment by jtborger** [comment]
Kan niet reproduceren: saldo staat op 0, uren lijken te kloppen met gefactureerde uren.
denk dat dit, zoals ookb esproken met iris, nog een na-wee was van de tijd dat eea niet goed werkte.
ik sluit hem en mail iris wel even
