### ISSUE TITLE
automatisch toegang na 6 maanden overige locaties lijkt niet goed te gaan

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#953]
via Aki/Shane:

2 niet-rechthebbende bezoekers die langer dan 6 maanden in Amoc komen, hebben nog geen toegang tot overige locaties:

https://ecd.deregenboog.org/inloop/klanten/5633267/view?redirect=/inloop/klanten/

https://ecd.deregenboog.org/inloop/klanten/5650344/view?redirect=/inloop/klanten/

**Comment by dvleeuwen** [comment]
Ha Jan,ik heb bevestiging van Janneke:
-de datum waar naar gekeken dient te worden bij niet rechthebbende is eerste intakedatum Amoc
-als de 6 maanden verstreken zijn, is er een herintake nodig (op Amoc) alvorens mensen toegang kunnen krijgen op de overige locaties.
Als ik jou zojuist goed begreep lijkt bovenstaande dus correct in de code te staan?En zal mijn antwoord aan de melders van Lloyd en Medard zijn dat deze mensen langs Amoc moeten voor herintake, en dat ze daarna op andere locaties welkom zijn. 
Correct?
groet!Daan

**Comment by jtborger** [comment]
Na wat hickups voor AMOC gaat ie zo nogmaals mee in 2.2.31

Er zitten wat eigenaardigheden in de hele implementatie. En er is geen test voor geschreven (wat dus wel zou moeten om dit soort gedoe te voorkomen)

**Comment by dvleeuwen** [comment]
Beste allen,
zoals jullie gemerkt hebben waren er vorige week problemen met de toegang tot inloop (vooral bij  Amoc)Er bleek iets niets te kloppen in de code. Jan (onze programmeur) is hier druk mee geweest, en meent het nu opgelost te hebben.  Mochten jullie desondanks toch nog tegen problemen aanlopen: hoor ik het graag (altijd met naam vd betreffende bezoeker svp!)

En verder:
misschien goed om de juiste werkwijze mbt niet-rechthebbende na een half jaar Amocbezoek hier nogmaals te noemen: de afspraak is dat bezoekers pas toegang krijgen tot andere locaties als ze na een half jaar een herintake gehad hebben bij Amoc. Zo is het nu ook ingericht in ECD.Mocht er dus iemand aan de deur staan van een andere inloop, en je ziet dat ie al langer dan een half jaar bij Amoc komt, maar je kunt hem/haar toch niet registreren in jouw inloop: --->  eerst naar Amoc doorverwijzen voor herintake.Ik weet niet zeker of deze werkwijze nu bij iedereen bekend is? Janneke: wil jij dit nogmaals onder aandacht brengen van alle inloopmedewerkers? Dank!
Hopelijk hebben we dit issue nu voor eens en altijd goed opgelost.
Mocht het niet zo zijn: weet mij te vinden ;)
groet!
Daan
