### ISSUE TITLE
foutmelding zodra maatschappelijkwerk een verslag wil toevoegen aan dossier

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#956]
sinds de nieuwe release, melding via Maria

**Comment by jtborger** [comment]
opgelost
sorry!
slordigheid....

**Comment by dvleeuwen** [comment]
Fijn dat ie zo snel herstelt kon worden!

thanks

Op di 3 dec. 2019 om 12:52 schreef JT Borger <notifications@github.com>:
