### ISSUE TITLE
foutmelding bij invoerer vw'er buurtboerderij

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#966]
Hoi Daan,

Ik wilde zojuist gegevens aanvullen in ECD Buurtboerderij (laatst al onze vrijwilligers kunnen invoeren) maar daar heb ik opeens geen rechten voor.
Kan jij dat verhelpen?
Alvast bedankt,

Met vriendelijke groet,

Kim
 
Kim Dudink
Beheerder Buurtboerderij

T:  020 337 6820
M: 06 14866593
E: kim@buurtboerderij.nl

---
Ai, wat vervelend en raar...
Begrijp ik goed dat dit tijdelijk wel werkte, en nu niet meer?
Kom je helemaal niet meer in de module Buurtboerderij, of kun je enkel geen vw'ers meer toevoegen?
Waar gaat het precies mis?

groet!
Daan
---

Als ik gegevens van vrijwilligers wil toevoegen; ik kom wel in de boerderij module maar kan niks meer toevoegen

**Comment by jtborger** [comment]
Ik kan dit niet reproduceren. Ik ben ingelogd als gebruiker kdudink en kan gewoon VW toevoegen enzo...
Is wat lastig op te lossen zo :)

**Comment by dvleeuwen** [comment]
Ha Kim,de programmeur komt er niet uit: als hij inlogt met jouw gegevens kan hij wel gewoon vrijwilligers toevoegen zoals gebruikelijk.Is dit bij jou nu inmiddels ook gewoon weer het geval? Of gaat er nog steeds iets mis?
groet!Daan

**Comment by jtborger** [comment]
Geen toegang tot wijzigen basisdossier VW.Moet wel.

**Comment by dvleeuwen** [comment]
bericht Kim:
Hoi,

Happy New Year!

Nee het lukt nog steeds niet..
Als ik bijvoorbeeld XXX haar geb datum wil toevoegen dan heb ik daar geen rechten toe.
Dus dat...:)

Met vriendelijke groet,

Kim

**Comment by jtborger** [comment]
Helder. Buurtboerderij had geen toegang om VWers te bewerken inderdaad. Ik heb dat aangepast (live)
