### ISSUE TITLE
bezoeker is niet meer terug te vinden onder module inloop

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#969]
https://ecd.deregenboog.org/inloop/klanten/5652092/view

momenteel enkel te vinden via algemene klantenlijst.
vermoeden Jan: bij oorspronkelijke intake is geen inloop ingevuld?

**Comment by jtborger** [comment]
Het is opgelost.
Er zat een fout in de database regel van deze klant. Hij linkte niet goed naar zijn laatste dossier status.
Daarom kon de 'toegangs updater' hem niet vinden en werd zijn toegang dus niet geüpdatet.
waarom die vier locaties daar niet op reageren is mij een raadsel maar staat los van deze zaak.
Ik heb handmatig de koppeling van laatste dossier status weer gelegd en daarmee is klant weer vindbaar in klanten lijst. heb tevens toegang opnieuw gerund.

zoiets kan voorkomen door een incident  maar zou natuurlijk eigenlijk niet mogen gebeuren.
ik zal even kijken of ik kan kijken van welke klanten er wel een dossier status is maar die niet in de basis klant staan. als dat er veel zijn gaat er ergens structureel iets mis ben ik bang....

Voor nu opgelost.

**Comment by dvleeuwen** [comment]
👍

Op di 24 dec. 2019 om 14:08 schreef JT Borger <notifications@github.com>:
