### ISSUE TITLE
niet mogelijk om nieuwe deelnemer toe te voegen OdP

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#970]
Hoi Jan,

Na het aanpassen van de filteroptie bij het invoeren van nieuwe huurders/verhuurders van Onder de Pannen blijkt het niet meer mogelijk te zijn een nieuwe (verhuurder) in te voeren. Daar kwam collega Arnaud van OdP achter. Het filteren (incl. ophalen uit de klantenlijst) lukt dus wel, maar als de persoon niet in de klantenlijst staat kun je geen nieuwe (ver)huurder toevoegen

Wil je deze bug met prioriteit verhelpen? 

Alvast dank!

Groet,

Josje

**Comment by jtborger** [comment]
Opgelost live gepatched.

**Comment by dvleeuwen** [comment]
Ha Josje,
ja ik zie wat je bedoelt, dat is nog niet optimaal. Je gaat dan met de "+nieuwe huurder" opnieuw naar het zoekscherm ipv veld voor nieuwe huurder.

Ik geef het door aan Jan!

groet
Daan

Hoi Daan/Jan,

Dank tot zover. Ik heb het even getest. Als het filteren geen hits oplevert kom je automatisch op het invoerscherm voor nieuwe (ver)huurder terecht. Dat is top!

Maar als het filteren wel hits oplevert, maar de juiste persoon zit daar niet bij, dan moet je opnieuw filteren voor je een nieuwe (ver)huurder kunt toevoegen. Voorbeeld (authentiek): je zoekt Ad Klaverblad; de zoekterm 'klaver' levert een aantal hits op, maar de gezochte persoon zit daar niet bij. Nu moet je opnieuw zoeken, uiteindelijk kun je wel een nieuw dossier aanmaken. Het zou handiger zijn je na de eerste zoekactie vanaf het scherm met hits kunt kiezen tussen opnieuw zoeken óf gelijk een nieuwe (ver)huurder aanmaken zonder nieuwe zoekactie. Kan dat zo aangepast worden?

Groet,

Josje

**Comment by jtborger** [comment]
Helder. Gaat mee in volgende release
2.2.33

**Comment by jtborger** [comment]
NB dit kan zijn dat het op meer plekken niet helemaal goed gaat. staat op mn lijstje dit na te lopen.
Heeft te maken met het 'generieker' maken van bepaalde functionaliteit (zoals het toevoegen van <dingen> via een zoekscherm. tot op heden stond dit per <ding> (huurder, verhuurder, vrijwilliger, whatever) benoemd en gedefinieerd, wat resulteerde in 10x bijna dezelfde code met alleen een andere 'naam' (en verwijzing). door dit iets generieker te maken wordt de code simpeler en eenduidiger, alleen moet op alle plekken waar bv naar 'huurder' werd verwezen nu worden verwezen naar een generiekere variant ('entity'). vandaar dus...
