### ISSUE TITLE
niet alle rollen zijn zichtbaar in uitklapmenu

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#971]
bij "medewerkers"als je zoekt in de tab "rollen"zijn niet alle bestaande rollen te vinden. 
Zo is role_secretariaat niet vindbaar in die lijst, terwijl er wel medewerkers met die rol zijn. (Lia bijvoorbeeld)

**Comment by jtborger** [comment]
gaat mee in 2.2.33
