### ISSUE TITLE
onduidelijkheid mbt kleurcode IZ

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#972]
als je bij deelnemers bepaalde zoekopdracht geeft, krijgen sommige deelnemers onterecht kleurcode (=geen hulpvraag of koppeling

zien bijvoorbeeld hier:
https://ecd.deregenboog.org/iz/klanten/?url=iz/klanten/&iz_klant_filter%5Bfilter%5D=&iz_klant_filter%5Bklant%5D%5Bid%5D=&iz_klant_filter%5Bklant%5D%5Bvoornaam%5D=&iz_klant_filter%5Bklant%5D%5Bachternaam%5D=&iz_klant_filter%5Bklant%5D%5BgeboortedatumRange%5D%5Bstart%5D=&iz_klant_filter%5Bklant%5D%5BgeboortedatumRange%5D%5Bend%5D=&iz_klant_filter%5Bklant%5D%5Bstadsdeel%5D=&iz_klant_filter%5BaanmeldingMedewerker%5D=&iz_klant_filter%5BintakeMedewerker%5D=20620&iz_klant_filter%5Bactief%5D=ooit&iz_klant_filter%5Bproject%5D=61&iz_klant_filter%5BhulpvraagMedewerker%5D=&iz_klant_filter%5BafsluitDatum%5D%5Bstart%5D=&iz_klant_filter%5BafsluitDatum%5D%5Bend%5D=&sort=klant.achternaam&direction=asc&page=1&redirect=/iz/klanten/

Ben & Pieter

**Comment by jtborger** [comment]
Het gele kleurtje geeft aan dat een dossier/klant afgesloten kan worden. Dat doet hij dus soms blijkbaar onterecht gezien bovenstaande resultaat. Waarom dat zo is snap ik niet zo goed. Ik heb iets aangepast en wellicht dat dit het probleem oplost maar dat is een beetje op basis van een aanname. Even bespreken als dit fout blijft gaan.
2.3.6
