### ISSUE TITLE
problemen met verslagen PFO

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#973]
Herman had vorige week problemen dat verslagveld eerst niet meer aanwezig was, en later heel klein. Een kwartier later leek dit euvel zich vanzelf opgelost te hebben.

Vandaag belde Evelien, zij had hetzelfde probleem (klein verslag veld). Bij haar werkte het vorige week nog prima. Ook kan ze sinds vandaag niet meer cursief en dik gedrukt typen in verslagen.

Als ik zelf kijk heb ik helemaal geen verslagen veld.

**Comment by jtborger** [comment]
Ik denk opgelost, hier lokaal wel.
Onder water was de teksteditor ge-update maar niet 100% goed gegaan.
Wil je even kijken of het werkt?
