### ISSUE TITLE
onduidelijkheid (factuur)lijst HomeService 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#975]
Beste mensen,
Mijnheer X heb ik zelf in ECD gezet een tijd terug en sindsdien staat hij om een of andere, voor mij, onverklaarbare reden bovenaan boven de eerste klant die vanzelfsprekend met een A begint (alfabetische volgorde dus). Ik heb er toen niks mee gedaan maar zie bij uitdraaien van factuur van Mijnheer X dat zijn naam niet mee komt uit ECD?
Hoor graag hoe op te lossen.
Dank en groet Emma

-- 
Met vriendelijke groet,

Emma Ricketts

gaat om:
https://ecd.deregenboog.org/hs/klanten/2599/view?redirect=/hs/klanten/

zie hem hier bovenaan alfabetische lijst staan:
ecd.deregenboog.org/hs/klanten/?redirect=/hs/klanten

**Comment by jtborger** [comment]
De reden dat klant X bovenaan stond was omdat de achternaam niet was ingevuld, enkel de voornaam. (Terwijl dat achternaam is).
Het sorteren gaat op achternaam. En 'leeg' gaat voor 'A' :)

Dit is ook de reden voor de lege naam op de factuur.
