### ISSUE TITLE
foutmelding bij uitdraai

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#976]
Niek:

Hi Daan, als ik in ECD een export wil doen dan krijg ik steeds onderstaande foutmelding. Ik krijg deze melding als ik via https://ecd.deregenboog.org/iz/vrijwilligers/?redirect=/iz/vrijwilligers/ een vrijwilligersoverzicht wil downloaden en ook als ik via https://ecd.deregenboog.org/dagbesteding/dagdelen/?redirect=/dagbesteding/mijn/trajecten de dagdelen wil downloaden.

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@ecd.deregenboog.org to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

-- 
Josje ondervindt zelfde probleem

**Comment by dvleeuwen** [comment]
update: Janneke geeft aan dat het op veel plaatsen (weer?) goed werkt, maar bij managementrapportage nog niet

**Comment by jtborger** [comment]
Ligt bij Sentia - heeft te maken met de update in de server omgeving.
Lange commando's (zoals rapportages) lopen nog niet helemaal goed, waardoor er intern binnen de server soms de verbinding wordt verloren als er lang op resultaat (uit bv. de database) moet worden gewacht.
Het is even afwachten hoe een en ander nu loopt en afgesteld moet worden.
Ik verwacht dit vandaag wel op te lossen.

**Comment by jtborger** [comment]
Hoe staat het hier nu mee?
Dagbesteding ben ik mee bezig met die dagdelen. Hij geeft niet eens een error maar alleen een wit scherm als ik alle dagdelen (zonder filter) wil downloaden. Lijkt me ook dat dit niet nodig is- gaat toch per jaar neem ik aan?

Dit is een wat dieperliggend ding wat over geheugen gaat bij het aanmaken van rapportages en downloads. Dat kan anders maar los ik pas in 2.3.5. op naw.
Voor nu is het het beste om selectief te filteren. Als het niet werkbaar is hoor ik het graag.

**Comment by dvleeuwen** [comment]
ik vraag na bij melders of rapportages nu weer goed gaan, sluit issue voorlopig. 
Mocht het nodig zijn heropen ik.

**Comment by dvleeuwen** [comment]
blijkt idd ok te zijn!
