### ISSUE TITLE
foutmelding bij toevoegen nieuwe personen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#977]
Arnaud:
Hoi Daan,

Ik heb even nog een ECD vraag.  Onder de Pannen proberen (Cindy en ik dan) mensen toe te voegen in ECD, maar dat lukt helaas niet.  Wij krijgen een melding Er is een fout opgetreden.
Dit krijg ik nadat ik verhuurder/huurder toevoegen aanklik, de gegevens van de huurver/verhuurder invul en als ik dan op opslaan klik...dan krijg ik de melding.

Volgens mij lukt het Josje het wel, dus ik was benieuwd of het een Onder de Pannen probleem is?

Hartelijke groet,

Arnaud de Korver
Project Medewerker Onder de Pannen

**Comment by jtborger** [comment]
opgelost in 2.2.34

**Comment by jtborger** [comment]
live gepatched; zou nu moeten werken
