### ISSUE TITLE
bij klantenlijst als je ooit actief + naam coordinator filtert lijken alleen open dossiers getoond te worden ipv alle

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#980]

**Comment by jtborger** [comment]
ooit actief werkt alleen bij project.
moet dat anders?

**Comment by dvleeuwen** [comment]
Ja zou fijn zijn,
zie antwoord bij #1074

groet
Daan

Op vr 12 mrt. 2021 om 14:07 schreef JT Borger ***@***.***>:

**Comment by barthuttinga** [comment]
@dvleeuwen Deze staat klaar (PR #1750), @jtborger Wil jij reviewen?
