### ISSUE TITLE
Onderscheid aanmaken tussen huurder-verhuurderkoppelingen, en mensen die op andere wijze onderdak krijgen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#981]
Er komen steeds meer varianten van hoe mensen ondergebracht worden, steeds vaker ook niet bij een verhuurder (persoon), maar andere constructies (leegstaande panden etc).
Deze andere plekken worden nu nog aangemaakt als zijnde verhuurders (personen), maar er kan nu geen onderscheid gemaakt worden in overzichten/cijfers om het om daadwerkelijke koppelingen gaat of anders.
Optie: een vinkje bij het huuraanbod "betreft geen persoon" ? 
Andere manier?

**Comment by jtborger** [comment]
Ja je zou met huuraanbodtypes kunnen gaan werken. misschien werkt dat? Daar kan je dan evt meerdere soorten toevoegen. ik weet niet of het voorzienbaar is dat er meerdere varianten zijn waarop je wilt rapporteren, als dat zo is kan je dmv die types differentiëren op een meer fijnmazige manier dan alleen 'is geen persoon'.

**Comment by jtborger** [comment]
Besproken. Doen zoals hierboven staat.

**Comment by jtborger** [comment]
Moet er nog iets aan de rapportages worden aangepast voor Odp? Moeten bv. koppelingen die niet tussen personen zijn worden benoemd?

**Comment by jtborger** [comment]
Heb koppeling per huurtype toegevoegd aan rapportages.

gaat mee in 2.2.46
