### ISSUE TITLE
fout bij rapportage OEK

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#982]
Bij rapportages lijken onterecht deelnemers niet meegenomen te worden in verschillende tabs download.

VB zie de rapportage Deelnemers/ DN per naam training en groep

en deze training:
https://ecd.deregenboog.org/oek/trainingen/69/view?redirect=/oek/trainingen/

De afgeronde personen worden niet weergegeven in overzicht

**Comment by jtborger** [comment]
Besproken met Ellina en opgelost.
