### ISSUE TITLE
foutmelding bij download IZvrijwilligers

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#986]
Niek:

Hi, elke maand download ik de gegevens van IZ vrijwlliger naar excel om daar verdere selecties op te maken. Nu krijg ik onderstaande melding wanneer ik de vrijwilligers IZ wil downloaden via deze link. 

https://ecd.deregenboog.org/iz/vrijwilligers/?redirect=/iz/vrijwilligers/

**Comment by jtborger** [comment]
Heb ik bij Sentia aangekaart.

**Comment by jtborger** [comment]
live gepatched.
