### ISSUE TITLE
datum oud verslag springt automatisch op vandaag

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#987]
Volgens mij een issue wat we eerder aan de hand gehad hebben, maar kan het niet terugvinden in Github.
In dit dossier springt het onderste oude verslag ("bart huttinga") automatisch op datum van vandaag zodra je verslagen bekijkt. 

https://ecd.deregenboog.org/iz/vrijwilligers/7685/view?redirect=/iz/vrijwilligers/#verslagen

**Comment by jtborger** [comment]
Er spelen twee dingen, dit hangt overigens samen met het andere issue waarbij de datum ook steeds versprong van het onderste verslag.
Er zijn verslagen (ruim 2400) met Bart als medewerker. Veel hiervan hebben ook geen datum. Vermoedelijk is dit een eerste omzetting geweest waarbij niet alle gegevens aanwezig waren.
Wanneer er geen datum was, liet hij de datum van nu zien. Dat heb ik aangepast zodat je nu gewoon geen datum meer ziet. Dat is minder verwarrend.

Willen we evt de verslagen die op nam van Bart staan nog toekennen aan een 'Onbekende gebruiker' of zo?
Of maar gewoon zo laten?

**Comment by jtborger** [comment]
2.3.6

**Comment by dvleeuwen** [comment]
nee prima, mag op naam Bart blijven staan

Op vr 12 mrt. 2021 om 12:56 schreef JT Borger ***@***.***>:
