### ISSUE TITLE
foutmelding bij wijzigingen OdP 

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#988]
Josje:

Hoi Daan/Jan,

Het lukt sinds kort niet meer om vanuit een OdP huurders- of verhuurdersdossier iets te wijzigen in het basisdossier van de persoon. Er verschijnt dan een foutmelding.
Heeft geen hoge prio, omdat ik zelf nu het meeste invoerwerk doe en dit kan omzeilen door rechtstreeks naar de klantenlijst te gaan. Maar de OdP-collega's kunnen dat niet.
Dus deze mag ook op de lijst.

Groet,

Josje

**Comment by jtborger** [comment]
Rechtenkwestie...
2.2.38

**Comment by dvleeuwen** [comment]
Ha Jan,
is jouw duidelijk wat hier aangepast moet worden qua rechten? Mij niet :(

Welke role moet er toebedeeld worden etc? Hoor het graag, dan ga ik er weer
mee richting TarQ...

dank!
Daan

Op ma 3 feb. 2020 om 10:15 schreef JT Borger <notifications@github.com>:

**Comment by dvleeuwen** [comment]
Josje:
Ik zie echter 1 item bij de closed items in GitHub staan dat nog niet werkt, nl. wijzigen basisgegevens (ver)huurder vanuit het OdP-dossier (#988). Deze moet dus heropend worden en aangezien het een bug is zou ik hem graag willen aanbevelen voor de volgende release.
Collega's die geen toegang tot de klantenlijst hebben kunnen nu het basisdossier niet wijzigen, dat is niet wenselijk.
Dank voor het werk tot zover,

groet,

Josje

**Comment by jtborger** [comment]
Ik heb dit net getest maar volgens mij had ik de rol ODP ook toegang gegeven tot klanten en vrijwilligers.. ik zal het zo met Josje nog even doorlopen.

**Comment by jtborger** [comment]
Ik heb dit net getest maar volgens mij had ik de rol ODP ook toegang gegeven tot klanten en vrijwilligers.. ik zal het zo met Josje nog even doorlopen.

**Comment by jtborger** [comment]
Dit zou opgelost moeten zijn al enige tijd.
@Josje: zo niet hoor ik het graag, dan snap ik het niet meer :)
