### ISSUE TITLE
fout bij rapportage EUburgers inloophuizen?

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#992]
Hoi Daan,

Zou jij (of zou Jan) willen kijken naar de rapportagemodule die onder Inloophuizen hangt? Hij registreert wel goed (denk ik) het aantal nieuwe bezoekers, maar het aantal unieke bezoekers uit alle EU-landen kan onmogelijk kloppen (393 ofzo. Veel en veel te weinig). Ik heb de info nodig voor het inhoudelijke jaarverslag. Dank voor de moeite alvast!
Met vriendelijke groet,

Janneke van Loo, manager Inloophuizen & Hulpverlening

--

Ha Jan,
zou jij even mee kunnen kijken naar onderstaande?

Gaat om deze:
https://ecd.deregenboog.org/inloop/rapportages/?rapportage%5Blocatie%5D=&rapportage%5Bstartdatum%5D=01-01-2019&rapportage%5Beinddatum%5D=31-12-2019&rapportage%5Bgeslacht%5D=&rapportage%5Breferentieperiode%5D=0&rapportage%5Bamoc_landen%5D%5B%5D=5010&rapportage%5Bamoc_landen%5D%5B%5D=7024&rapportage%5Bamoc_landen%5D%5B%5D=5040&rapportage%5Bamoc_landen%5D%5B%5D=5015&rapportage%5Bamoc_landen%5D%5B%5D=6029&rapportage%5Bamoc_landen%5D%5B%5D=7065&rapportage%5Bamoc_landen%5D%5B%5D=6002&rapportage%5Bamoc_landen%5D%5B%5D=5002&rapportage%5Bamoc_landen%5D%5B%5D=6003&rapportage%5Bamoc_landen%5D%5B%5D=6039&rapportage%5Bamoc_landen%5D%5B%5D=5017&rapportage%5Bamoc_landen%5D%5B%5D=6007&rapportage%5Bamoc_landen%5D%5B%5D=7044&rapportage%5Bamoc_landen%5D%5B%5D=7064&rapportage%5Bamoc_landen%5D%5B%5D=7066&rapportage%5Bamoc_landen%5D%5B%5D=6018&rapportage%5Bamoc_landen%5D%5B%5D=5009&rapportage%5Bamoc_landen%5D%5B%5D=7028&rapportage%5Bamoc_landen%5D%5B%5D=7050&rapportage%5Bamoc_landen%5D%5B%5D=7047&rapportage%5Bamoc_landen%5D%5B%5D=5049&rapportage%5Bamoc_landen%5D%5B%5D=6067&rapportage%5Bamoc_landen%5D%5B%5D=6037&rapportage%5Bamoc_landen%5D%5B%5D=6066&rapportage%5Bamoc_landen%5D%5B%5D=5039&rapportage%5Brapport%5D=InloopBundle%5CReport%5CInfobalie&rapportage%5Bshow%5D= 

Waarbij Janneke aangeeft dat unieke bezoekers veel hoger zou moeten zijn. (wat mij ook logisch klinkt, als je ziet dat er bijna 1000 nieuwe klanten zijn, kan unieke bezoekers totaal nooit 393 zijn)
Tevens klopt volgens haar het aantal verslagenMW ook niet (zouden er veeeeel meer moeten zijn volgens haar).
Kun jij hier induiken en kijken waar ECD de cijfers vandaan haalt, en wat hier mist?

Liefst zsm ivm jaarverslag waar ze nu mee bezig zijn.

Ik maak voor volledigheid ook github aan.

dank!
Daan

**Comment by dvleeuwen** [comment]
aanvullend: groot-brittannie mag uit dit rijtje verwijderd worden, nu het geen EU meer is ;)

**Comment by jtborger** [comment]
haha :)
er ging iets technisch fout met de query, dat heb ik opgelost. Ik weet niet of de cijfers dan nu 100% kloppen want de optelsom van bezoekers uit landen uit de management rapportage komt nog niet overeen met wat ik hier zie. Maar dat heb ik nu uitstaan per mail.
Vooralsnog sluit ik deze.
Live gepatched.
