### ISSUE TITLE
fout in management rapportage

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#996]
Hoi Daan,

Er is iets misgegaan met de managementrapportage: alle inloophuizen behalve Zeeburg zijn eruit verdwenen. Zowel bij de bezoekersaantallen inloophuizen als bij het aantal contacten en klanten van het maatschappelijk werk. Zou je Jan willen vragen om wat herstelwerkzaamheden uit te voeren? Dank alvast!
Met vriendelijke groet,

Janneke van Loo, manager Inloophuizen & Hulpverlening

**Comment by dvleeuwen** [comment]
aanvulling Janneke:
Ook Claverhuis en de Huizen van de wijk in Noord zijn kwijt :)

**Comment by jtborger** [comment]
Ik denk dat het nu goed moet zijn. Excuses.
Ik had alle niet-open locaties er automatisch uit gehaald, er geen rekening mee houdend dat sommige locaties 'eeuwig' open zijn, dwz geen 'datum tot' hebben.
Die locaties sloot hij vervolgens ook uit.
