### ISSUE TITLE
opmerking inloop werkt niet goed

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#997]
Hoi Daan

Wanneer wij een opmerking in het ECD afvinken, blijft de  'vink' niet plakken.
Het is ook een periode zo geweest dat het op de ene computer wel kon en de andere niet.
Dit is erg vervelend werken met een groot team,en wanneer een bezoeker weer tegen wordt gehouden omdat er nog een opmerking od open staat.
Kun jij hier iets aan doen?

Groet,
Mirjam Ras

**Comment by jtborger** [comment]
Kan jij even namen en rugnummers verzamelen voor wanneer ik hiermee aan de slag ga?
Dit is te vaag voor mij ben ik bang.

is het altijd op dezelfde computer/locatie dat het gebeurt? dezelfde medewerker?
etc.

**Comment by dvleeuwen** [comment]
Ha Mirjam,de programmeur is hiermee bezig geweest, maar kan het probleem niet vinden.Heb jij/jullie voor mij meer info: wanneer gebeurde dit, bij welke medewerker, en welke opmerking (linkje of screenshot). Dan kan hij verder zoeken.
dank!Daan

**Comment by jtborger** [comment]
is dit nog relevant?

**Comment by dvleeuwen** [comment]
antwoord was dat ze het bij volgende geval direct aan mij zouden mailen (met alle info)
Daarna bleef het stil, dus ik sluit voor nu.
Mocht er een nieuw geval zijn in toekomst heropen ik.
