### ISSUE TITLE
nieuwe rapportage onder maatschappelijk werk

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#998]
Naam rapportage: 
economisch daklozen

Hierin vd volgende locaties:
post oost
gravestein
de meeuw
claverhuis
't blommetje
havelaar

de volgende info:
unieke cliënten , per locatie  & totaal)
aantal contacten (=verslagen) , per locatie & totaal

**Comment by jtborger** [comment]
gaat mee in 2.2.40
