### ISSUE TITLE
extra optie bij klant toevoegen

### ISSUE THREAD

**Issue by dvleeuwen** [deregenboog/ecd#999]
bij het scherm klant toevoegen
https://ecd.deregenboog.org/mw/klanten/add?klant=new

nieuw veld: "binnengekomen via"
met volgende dropdown
- Madi/buurtteams
- DRG maatschappelijk werk
- GGD
- WPI
- Gemeente
- Zelfmelders
- Straatjurist/Ombudsvrouw
- LVB instellingen
- Inloophuizen
- Huis van de Wijk
- Tijdelijk Wonen DRG
- Woningbouwcorporaties
- Overig

**Comment by jtborger** [comment]
Is dat niet deze lijst?
https://ecd.deregenboog.org/inloop/admin/binnenvia/?redirect=/inloop/registraties/

**Comment by jtborger** [comment]
laat maar, dit is voor VWers...

**Comment by dvleeuwen** [comment]
Ha Michael,weet jij of dit veld in de praktijk benut wordt door MW?
https://ecd.deregenboog.org/mw/klanten/5655820/info?redirect=/mw/klanten/5655820/view 
dit is het veld als je in klantdossier zit links halverwege pagina:  Maatschappelijk werk Info wijzigen 

We vragen ons af of dit de juiste/logische plek is om de "binnengekomen via" aan toe te voegen, en in toekomst wellicht ook de BSN (als die niet openbaar mag voor alle afdelingen).Ben nu als eerste benieuwd of dit gedeelte van MW-ECD überhaupt benut wordt op dit moment? 
dank!Daan

**Comment by jtborger** [comment]
Gaat mee met 2.3.5.
